package mavencoord

import (
	"archive/zip"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

// writeJAR writes a zip (JAR) with the given entries into dir/name.
func writeJAR(t *testing.T, dir, name string, entries map[string]string) {
	t.Helper()
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	zw := zip.NewWriter(f)
	for n, content := range entries {
		w, err := zw.Create(n)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
}

func pomProps(group, artifact, version string) string {
	return "#Generated by Maven\ngroupId=" + group + "\nartifactId=" + artifact + "\nversion=" + version + "\n"
}

func TestResolveCorrectsMisDerivedGroup(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "grpc-core-1.62.2.jar", map[string]string{
		"META-INF/maven/io.grpc/grpc-core/pom.properties": pomProps("io.grpc", "grpc-core", "1.62.2"),
		"io/grpc/internal/Foo.class":                      "x",
	})
	comps := []sbom.Component{
		// syft mis-derived the group from the io.grpc.internal class namespace.
		{Name: "grpc-core", Version: "1.62.2", PURL: "pkg:maven/io.grpc.internal/grpc-core@1.62.2"},
	}
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("corrected = %d, want 1", n)
	}
	if got, want := comps[0].PURL, "pkg:maven/io.grpc/grpc-core@1.62.2"; got != want {
		t.Fatalf("PURL = %q, want %q", got, want)
	}
}

func TestResolveLeavesCorrectAndNonMavenUntouched(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "asm-9.6.jar", map[string]string{
		"META-INF/maven/org.ow2.asm/asm/pom.properties": pomProps("org.ow2.asm", "asm", "9.6"),
	})
	comps := []sbom.Component{
		{Name: "asm", Version: "9.6", PURL: "pkg:maven/org.ow2.asm/asm@9.6"}, // already correct → untouched
		{Name: "left-pad", Version: "1.0.0", PURL: "pkg:npm/left-pad@1.0.0"}, // non-maven → untouched
		{Name: "ghost", Version: "1.0.0", PURL: "pkg:maven/x.y/ghost@1.0.0"}, // no JAR → untouched
	}
	before := []string{comps[0].PURL, comps[1].PURL, comps[2].PURL}
	if n := New().Resolve(context.Background(), dir, comps); n != 0 {
		t.Fatalf("corrected = %d, want 0", n)
	}
	for i := range comps {
		if comps[i].PURL != before[i] {
			t.Errorf("comp %d PURL changed: %q -> %q", i, before[i], comps[i].PURL)
		}
	}
}

func TestResolveSkipsAmbiguousArtifactVersion(t *testing.T) {
	dir := t.TempDir()
	// Two JARs declare the same artifact@version under different groups → never guess.
	writeJAR(t, dir, "utils-a.jar", map[string]string{
		"META-INF/maven/com.a/utils/pom.properties": pomProps("com.a", "utils", "1.0.0"),
	})
	writeJAR(t, dir, "utils-b.jar", map[string]string{
		"META-INF/maven/com.b/utils/pom.properties": pomProps("com.b", "utils", "1.0.0"),
	})
	comps := []sbom.Component{{Name: "utils", Version: "1.0.0", PURL: "pkg:maven/wrong/utils@1.0.0"}}
	if n := New().Resolve(context.Background(), dir, comps); n != 0 {
		t.Fatalf("ambiguous artifact must not be corrected, got %d", n)
	}
	if comps[0].PURL != "pkg:maven/wrong/utils@1.0.0" {
		t.Fatalf("ambiguous PURL changed: %q", comps[0].PURL)
	}
}

func TestResolveNestedSpringBootJAR(t *testing.T) {
	dir := t.TempDir()
	// Build a nested dependency JAR in memory, then embed it in a fat JAR under BOOT-INF/lib.
	var nested bytes.Buffer
	nz := zip.NewWriter(&nested)
	w, _ := nz.Create("META-INF/maven/org.jetbrains/annotations/pom.properties")
	_, _ = w.Write([]byte(pomProps("org.jetbrains", "annotations", "26.0.1")))
	_ = nz.Close()

	f, err := os.Create(filepath.Join(dir, "app-1.0.0.jar"))
	if err != nil {
		t.Fatal(err)
	}
	fz := zip.NewWriter(f)
	lw, _ := fz.Create("BOOT-INF/lib/annotations-26.0.1.jar")
	_, _ = lw.Write(nested.Bytes())
	_ = fz.Close()
	_ = f.Close()

	comps := []sbom.Component{{Name: "annotations", Version: "26.0.1", PURL: "pkg:maven/annotations/annotations@26.0.1"}}
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("nested-jar corrected = %d, want 1", n)
	}
	if got, want := comps[0].PURL, "pkg:maven/org.jetbrains/annotations@26.0.1"; got != want {
		t.Fatalf("PURL = %q, want %q", got, want)
	}
}
