# C# language-pack rule specs, batch 2 (#189). Clean-room, line-detectable — TLS/ASP.NET security,
# reflection/deserialization, and modern-idiom / BCL-misuse smells. Same clean-room policy as batch 1.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- security: TLS / transport / ASP.NET ----
    r(id="cs-ssl3-tls10-protocol", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="Obsolete SSL/TLS protocol selected",
      desc="SecurityProtocol / SslProtocols is set to Ssl3, Tls (1.0), or Tls11.",
      rationale="SSL 3.0 and TLS 1.0/1.1 are broken/deprecated (CWE-327). Require TLS 1.2+.",
      remediation="Use SslProtocols.Tls12 | Tls13 (or leave the OS default).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(SecurityProtocolType|SslProtocols)\.(Ssl3|Tls|Tls11)\b',
      nc='ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;',
      c='ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;'),
    r(id="cs-cookie-not-secure", type="hotspot", qual="sec", sev="medium", cwe="CWE-614",
      title="Cookie Secure flag disabled",
      desc="A cookie sets Secure = false, so it can be sent over plaintext HTTP.",
      rationale="A non-Secure cookie can leak over HTTP (CWE-614). Set Secure = true.",
      remediation="Set the cookie's Secure property to true.",
      source="https://cwe.mitre.org/data/definitions/614.html",
      re=r'\.Secure\s*=\s*false',
      nc='cookie.Secure = false;',
      c='cookie.Secure = true;'),
    r(id="cs-cookie-not-httponly", type="hotspot", qual="sec", sev="medium", cwe="CWE-1004",
      title="Cookie HttpOnly flag disabled",
      desc="A cookie sets HttpOnly = false, exposing it to client-side script.",
      rationale="A non-HttpOnly cookie is readable by JavaScript, aiding XSS token theft (CWE-1004).",
      remediation="Set HttpOnly = true for session/auth cookies.",
      source="https://cwe.mitre.org/data/definitions/1004.html",
      re=r'\.HttpOnly\s*=\s*false',
      nc='cookie.HttpOnly = false;',
      c='cookie.HttpOnly = true;'),
    r(id="cs-validaterequest-false", type="vuln", qual="sec", sev="high", cwe="CWE-79",
      title="ASP.NET request validation disabled",
      desc="validateRequest=\"false\" or [ValidateInput(false)] turns off built-in input validation.",
      rationale="Disabling request validation removes a layer of XSS protection (CWE-79).",
      remediation="Keep request validation on and encode output explicitly.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'(validateRequest\s*=\s*"false"|ValidateInput\(\s*false\s*\))',
      nc='[ValidateInput(false)]',
      c='[ValidateInput(true)]'),
    r(id="cs-html-raw", type="hotspot", qual="sec", sev="medium", cwe="CWE-79",
      title="Html.Raw with a variable (possible XSS)",
      desc="Razor's Html.Raw outputs a non-literal value without encoding.",
      rationale="Html.Raw bypasses output encoding; rendering untrusted input injects script (CWE-79).",
      remediation="Render via @model (auto-encoded) or sanitize before Html.Raw.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'Html\.Raw\(\s*[a-z_]\w*',
      nc='@Html.Raw(comment)',
      c='@Model.Comment'),
    r(id="cs-assembly-loadfrom", type="hotspot", qual="sec", sev="high", cwe="CWE-494",
      title="Assembly.LoadFrom / LoadFile loads code from a path",
      desc="Assembly.LoadFrom / LoadFile loads an assembly from a file path at runtime.",
      rationale="Loading an assembly from a path executes its code; if the path is attacker-influenced this is arbitrary code execution (CWE-494). Verify the source.",
      remediation="Load only verified, signed assemblies from trusted locations (prefer Assembly.Load by name).",
      source="https://cwe.mitre.org/data/definitions/494.html",
      re=r'Assembly\.(LoadFrom|LoadFile)\(',
      nc='var asm = Assembly.LoadFrom(pluginPath);',
      c='var asm = Assembly.Load(new AssemblyName("Trusted.Plugin"));'),
    r(id="cs-activator-createinstance-var", type="hotspot", qual="sec", sev="medium", cwe="CWE-470",
      title="Activator.CreateInstance from a type name",
      desc="Activator.CreateInstance is called with a runtime type name string.",
      rationale="Instantiating a type named by input enables unsafe reflection (CWE-470).",
      remediation="Map input to a fixed allow-list of types instead of naming types dynamically.",
      source="https://cwe.mitre.org/data/definitions/470.html",
      re=r'Activator\.CreateInstance\(\s*(Type\.GetType\(|[a-z_]\w*\s*[,)])',
      nc='var o = Activator.CreateInstance(Type.GetType(typeName));',
      c='var o = Activator.CreateInstance<Widget>();'),
    r(id="cs-xslt-enable-script", type="vuln", qual="sec", sev="high", cwe="CWE-94",
      title="XSLT scripting enabled",
      desc="XsltSettings.EnableScript / TrustedXslt allows embedded script during transform.",
      rationale="Enabling XSLT script executes embedded code (CWE-94).",
      remediation="Use XsltSettings.Default (script disabled) and a null resolver.",
      source="https://cwe.mitre.org/data/definitions/94.html",
      re=r'(EnableScript\s*=\s*true|XsltSettings\.TrustedXslt)',
      nc='var s = new XsltSettings { EnableScript = true };',
      c='var s = XsltSettings.Default;'),
    r(id="cs-regex-from-input", type="hotspot", qual="sec", sev="medium", cwe="CWE-1333",
      title="Regex compiled from a variable (ReDoS risk)",
      desc="A Regex is constructed from a non-literal pattern, risking catastrophic backtracking.",
      rationale="A user-supplied or dynamic pattern can be crafted for ReDoS (CWE-1333); also set a timeout.",
      remediation="Use a fixed pattern, validate the input pattern, and pass a matchTimeout.",
      source="https://cwe.mitre.org/data/definitions/1333.html",
      re=r'new\s+Regex\(\s*[a-z_]\w*\s*[,)]',
      nc='var re = new Regex(userPattern);',
      c='var re = new Regex(@"^\\d{4}$", RegexOptions.None, TimeSpan.FromSeconds(1));'),
    r(id="cs-xmldocument-load", type="hotspot", qual="sec", sev="medium", cwe="CWE-611",
      title="XmlDocument.LoadXml with default resolver",
      desc="XmlDocument parses input with the default XmlResolver (external entities allowed pre-4.5.2).",
      rationale="A default XmlResolver can resolve external entities (CWE-611); set XmlResolver = null.",
      remediation="Set doc.XmlResolver = null before loading untrusted XML.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r'\bnew\s+XmlDocument\s*\(\s*\)',
      nc='var doc = new XmlDocument();',
      c='var doc = new XmlDocument { XmlResolver = null };'),
    # ---- modern-idiom / correctness smells ----
    r(id="cs-null-equality", type="smell", qual="maint", sev="low", cwe="",
      title="== null / != null instead of pattern match",
      desc="A reference is compared with == null or != null.",
      rationale="`is null` / `is not null` cannot be fooled by an overloaded == operator and is the modern idiom.",
      remediation="Use `x is null` / `x is not null`.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns",
      re=r'(==|!=)\s*null\b',
      nc='if (user != null) { Save(user); }',
      c='if (user is not null) { Save(user); }'),
    r(id="cs-count-vs-any", type="smell", qual="maint", sev="low", cwe="",
      title=".Count() compared to 0 instead of Any()",
      desc="LINQ .Count() is compared to 0 to test emptiness, enumerating the whole sequence.",
      rationale=".Count() == 0 / > 0 walks the entire sequence; .Any() short-circuits (CA1827).",
      remediation="Use !collection.Any() / collection.Any().",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1827",
      re=r'\.Count\(\)\s*(==|!=|>|<=)\s*0\b',
      nc='if (items.Count() > 0) { Process(); }',
      c='if (items.Any()) { Process(); }'),
    r(id="cs-datetime-now-utc", type="smell", qual="maint", sev="low", cwe="",
      title="DateTime.Now for stored/compared timestamps",
      desc="DateTime.Now returns local time, which is ambiguous across time zones and DST.",
      rationale="Local time is not comparable across zones and shifts with DST; use UtcNow for stored/compared instants.",
      remediation="Use DateTime.UtcNow (or DateTimeOffset.UtcNow).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305",
      re=r'\bDateTime\.Now\b',
      nc='var created = DateTime.Now;',
      c='var created = DateTime.UtcNow;'),
    r(id="cs-tolower-compare", type="smell", qual="maint", sev="low", cwe="",
      title="ToLower()/ToUpper() for case-insensitive compare",
      desc="Strings are lowercased to compare case-insensitively, allocating and being culture-sensitive.",
      rationale="ToLower()== allocates and depends on culture; use a StringComparison overload (CA1862).",
      remediation="Use string.Equals(a, b, StringComparison.OrdinalIgnoreCase).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1862",
      re=r'\.ToLower\(\)\s*==',
      nc='if (name.ToLower() == "admin") Grant();',
      c='if (string.Equals(name, "admin", StringComparison.OrdinalIgnoreCase)) Grant();'),
    r(id="cs-string-empty-literal", type="smell", qual="maint", sev="info", cwe="",
      title='Comparison to String.Empty via ==',
      desc='A string is compared to String.Empty with ==.',
      rationale="Comparing to String.Empty is clearer and null-safer as string.IsNullOrEmpty.",
      remediation="Use string.IsNullOrEmpty(s).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820",
      re=r'==\s*(String|string)\.Empty\b|(String|string)\.Empty\s*==',
      nc='if (input == String.Empty) return;',
      c='if (string.IsNullOrEmpty(input)) return;'),
    r(id="cs-first-without-check", type="smell", qual="maint", sev="low", cwe="",
      title=".First() / .Single() without a guard",
      desc="LINQ .First()/.Single() throws if the sequence is empty (or not singular).",
      rationale=".First()/.Single() throw on empty input; prefer FirstOrDefault/SingleOrDefault with a null check when emptiness is possible.",
      remediation="Use FirstOrDefault/SingleOrDefault and handle the null/absent case.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first",
      re=r'\.(First|Single)\(\s*\)',
      nc='var head = items.First();',
      c='var head = items.FirstOrDefault();'),
    r(id="cs-nan-compare", type="bug", qual="rel", sev="medium", cwe="",
      title="Comparison to double.NaN / float.NaN",
      desc="A value is compared with == or != to NaN, which is always false / true.",
      rationale="NaN compares unequal to everything including itself; == NaN never matches. Use double.IsNaN.",
      remediation="Use double.IsNaN(x).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.double.isnan",
      re=r'(==|!=)\s*(double|float)\.NaN\b',
      nc='if (rate == double.NaN) return;',
      c='if (double.IsNaN(rate)) return;'),
    r(id="cs-empty-general-catch-brace", type="smell", qual="maint", sev="low", cwe="",
      title="catch without an exception type",
      desc="A bare `catch {` catches everything, including non-CLS exceptions.",
      rationale="A typeless catch is even broader than catch(Exception) and hides all failures.",
      remediation="Catch a specific exception type.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031",
      re=r'\bcatch\s*\{',
      nc='try { Do(); } catch { }',
      c='try { Do(); } catch (IOException e) { Log(e); }'),
    r(id="cs-region", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="#region used to fold code",
      desc="A #region directive is present, often hiding overly long files.",
      rationale="Regions frequently mask classes that are too large; prefer smaller types over folding.",
      remediation="Split the type instead of hiding sections behind regions.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives",
      re=r'^\s*#region\b',
      nc='#region Helpers',
      c='// Helpers'),
    r(id="cs-magic-number", type="smell", qual="maint", sev="info", cwe="",
      title="Magic number literal in a comparison",
      desc="An unexplained numeric literal (>1 digit) is compared against directly.",
      rationale="Unnamed numeric constants obscure intent; name them (ISO/IEC 25010 maintainability).",
      remediation="Extract the value into a named const with a meaningful name.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'[<>]=?\s*\d{4,}\b',
      nc='if (retries > 8640) Abort();',
      c='if (retries > MaxRetriesPerDay) Abort();'),
    r(id="cs-thread-sleep", type="smell", qual="maint", sev="low", cwe="",
      title="Thread.Sleep in async or server code",
      desc="Thread.Sleep blocks the thread; in async code it should be await Task.Delay.",
      rationale="Blocking a pooled thread with Thread.Sleep harms scalability; await Task.Delay yields it.",
      remediation="Use await Task.Delay(...) in async methods.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep",
      re=r'\bThread\.Sleep\s*\(',
      nc='Thread.Sleep(1000);',
      c='await Task.Delay(1000);'),
    r(id="cs-obsolete-arraylist", type="smell", qual="maint", sev="low", cwe="",
      title="Non-generic ArrayList/Hashtable used",
      desc="Legacy non-generic collections (ArrayList, Hashtable) are used.",
      rationale="Non-generic collections box values and lose type safety; use generic List<T>/Dictionary<K,V> (CA1050-era guidance).",
      remediation="Use the generic System.Collections.Generic types.",
      source="https://learn.microsoft.com/en-us/dotnet/standard/collections/",
      re=r'\bnew\s+(ArrayList|Hashtable)\s*\(',
      nc='var items = new ArrayList();',
      c='var items = new List<string>();'),
    r(id="cs-out-param-many", type="smell", qual="maint", sev="low", cwe="",
      title="Method using multiple out parameters",
      desc="A signature declares several out parameters, a design smell.",
      rationale="Multiple out parameters signal a method doing too much; return a tuple or a type.",
      remediation="Return a tuple or a dedicated result type.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1021",
      re=r'\bout\s+\w+[^,)]*,\s*out\s+\w+',
      nc='void Parse(string s, out int x, out int y) { }',
      c='(int X, int Y) Parse(string s) { }'),
    r(id="cs-interpolated-log", type="smell", qual="maint", sev="low", cwe="",
      title="Interpolated string in a structured log call",
      desc="ILogger is called with an interpolated string instead of a message template.",
      rationale="Interpolation defeats structured logging (no named fields) and always formats; use the template + args (CA2254).",
      remediation='Use a message template: logger.LogInformation("user {Id}", id).',
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254",
      re=r'\.Log(Information|Warning|Error|Debug|Critical|Trace)\(\s*\$"',
      nc='logger.LogInformation($"user {id} logged in");',
      c='logger.LogInformation("user {Id} logged in", id);'),
    r(id="cs-explicit-finalizer", type="smell", qual="maint", sev="low", cwe="",
      title="Finalizer declared without unmanaged resources",
      desc="A destructor (~Type) is declared; finalizers are rarely needed and hurt GC.",
      rationale="Finalizers add GC overhead and are only for unmanaged resources; use IDisposable/SafeHandle (CA1821).",
      remediation="Remove the finalizer; implement IDisposable (or use SafeHandle).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1821",
      re=r'^\s*~\w+\s*\(\s*\)',
      nc='    ~Cache() { }',
      c='    public void Dispose() { _handle.Dispose(); }'),
    r(id="cs-boxing-in-string-concat", type="smell", qual="maint", sev="info", cwe="",
      title="Value type concatenated to a string (boxing)",
      desc="A struct/enum is concatenated with + to a string literal, boxing it.",
      rationale="Concatenation boxes value types; interpolation or ToString avoids the allocation.",
      remediation="Use string interpolation or an explicit ToString with a format.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305",
      re=r'"\s*\+\s*\w+\s*\+\s*"',
      nc='var s = "count=" + count + " items";',
      c='var s = $"count={count} items";'),
    r(id="cs-public-const-string", type="smell", qual="maint", sev="low", cwe="",
      title="public const in a library (binary-compat hazard)",
      desc="A public const is exposed; its value is baked into callers at compile time.",
      rationale="Changing a public const does not update already-compiled consumers; use static readonly for library values (CA2211-adjacent).",
      remediation="Expose public static readonly instead of public const for cross-assembly values.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/const",
      re=r'^\s*public\s+const\s+\w',
      nc='    public const int Version = 3;',
      c='    public static readonly int Version = 3;'),
    r(id="cs-mutable-static-field", type="smell", qual="maint", sev="medium", cwe="CWE-362",
      title="Public mutable static field",
      desc="A public static non-readonly field is shared, unsynchronized global state.",
      rationale="Public mutable statics are global state prone to races and hidden coupling (CWE-362, CA2211).",
      remediation="Make it static readonly, or encapsulate behind a synchronized accessor.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2211",
      re=r'^\s*public\s+static\s+(?:[\w<>\[\].]+)\s+\w+\s*(=|;)',
      nc='    public static int Counter;',
      c='    public static readonly int Counter = 0;'),
    r(id="cs-empty-constructor", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant empty public constructor",
      desc="An explicit empty public constructor duplicates the implicit default.",
      rationale="An empty default constructor is redundant noise (IDE0060-adjacent).",
      remediation="Remove the redundant constructor.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors",
      re=r'\bpublic\s+(\w+)\s*\(\s*\)\s*\{\s*\}',
      nc='    public Service() {}',
      c='    // implicit default constructor'),
    r(id="cs-linq-where-count", type="smell", qual="maint", sev="low", cwe="",
      title=".Where(...).Count() instead of .Count(predicate)",
      desc="A filtered count uses Where(...).Count() rather than Count(predicate).",
      rationale="Count(predicate) is the direct, allocation-free form (CA1826-adjacent).",
      remediation="Use collection.Count(predicate).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count",
      re=r'\.Where\([^)]*\)\.Count\(\s*\)',
      nc='var n = users.Where(u => u.Active).Count();',
      c='var n = users.Count(u => u.Active);'),
    r(id="cs-tostring-in-log-arg", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant .ToString() on a logged argument",
      desc="An argument passed to a formatting call has an unnecessary .ToString().",
      rationale="Formatting already calls ToString; the explicit call is redundant (IDE0071-adjacent).",
      remediation="Pass the value directly.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated",
      re=r'\{\s*\w+\.ToString\(\)\s*\}',
      nc='var s = $"id={id.ToString()}";',
      c='var s = $"id={id}";'),
]
