# C language-pack rule specs, batch 1 (#198). Clean-room, line-detectable — banned/dangerous libc
# functions (CWE-120/676), format-string sinks (CWE-134), weak RNG, command injection, non-reentrant APIs.
# Concept origins cited (CWE, SEI CERT C); all wording/examples first-party.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "c")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "c"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # --- unbounded string operations: classic buffer overflow (CWE-120) ---
    r(id="c-gets", type="vuln", qual="sec", sev="critical", cwe="CWE-242",
      title="Use of gets()",
      desc="gets() reads a line with no bound on the destination buffer.",
      rationale="gets() cannot know the buffer size and always risks overflow; it was removed in C11 (CWE-242/120).",
      remediation="Use fgets() with an explicit size.",
      source="https://cwe.mitre.org/data/definitions/242.html",
      re=r'\bgets\s*\(',
      nc='gets(buffer);',
      c='fgets(buffer, sizeof(buffer), stdin);'),
    r(id="c-strcpy", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of strcpy()",
      desc="strcpy() copies until a NUL with no destination bound.",
      rationale="If the source is longer than the destination, strcpy overflows the buffer (CWE-120).",
      remediation="Use strlcpy()/snprintf(), or bound the copy and NUL-terminate.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bstrcpy\s*\(',
      nc='strcpy(dst, src);',
      c='snprintf(dst, sizeof(dst), "%s", src);'),
    r(id="c-strcat", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of strcat()",
      desc="strcat() appends with no bound on the destination buffer.",
      rationale="strcat cannot know the remaining space and overflows when the result exceeds the buffer (CWE-120).",
      remediation="Use strlcat()/snprintf() with an explicit size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bstrcat\s*\(',
      nc='strcat(path, suffix);',
      c='strlcat(path, suffix, sizeof(path));'),
    r(id="c-sprintf", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of sprintf()",
      desc="sprintf() writes formatted output with no destination bound.",
      rationale="A wide field or long %s can write past the buffer (CWE-120).",
      remediation="Use snprintf() with the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bsprintf\s*\(',
      nc='sprintf(buf, "%s", name);',
      c='snprintf(buf, sizeof(buf), "%s", name);'),
    r(id="c-vsprintf", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of vsprintf()",
      desc="vsprintf() writes formatted output from a va_list with no destination bound.",
      rationale="Like sprintf, vsprintf can overflow the destination (CWE-120).",
      remediation="Use vsnprintf() with the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bvsprintf\s*\(',
      nc='vsprintf(buf, fmt, args);',
      c='vsnprintf(buf, sizeof(buf), fmt, args);'),
    r(id="c-scanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="scanf(\"%s\") without a field width",
      desc="A scanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token into the buffer, overflowing it (CWE-120).",
      remediation="Add a field width, e.g. %63s for a 64-byte buffer.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bscanf\s*\(\s*"[^"]*%s',
      nc='scanf("%s", name);',
      c='scanf("%63s", name);'),
    r(id="c-sscanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="sscanf(\"%s\") without a field width",
      desc="An sscanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token into the buffer, overflowing it (CWE-120).",
      remediation="Add a field width matching the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bsscanf\s*\([^)]*"[^"]*%s',
      nc='sscanf(line, "%s", token);',
      c='sscanf(line, "%63s", token);'),
    r(id="c-getwd", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of getwd()",
      desc="getwd() writes the working directory into a buffer with no size argument.",
      rationale="getwd cannot bound the write and can overflow (CWE-120); it is obsolete.",
      remediation="Use getcwd() with an explicit buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bgetwd\s*\(',
      nc='getwd(path);',
      c='getcwd(path, sizeof(path));'),
    # --- footgun bounded functions (truncation / off-by-one) ---
    r(id="c-strncpy", type="bug", qual="rel", sev="medium", cwe="CWE-170",
      title="Use of strncpy()",
      desc="strncpy() does not NUL-terminate when the source fills the buffer.",
      rationale="A non-terminated string leads to over-reads in later string operations (CWE-170).",
      remediation="Use strlcpy(), or explicitly NUL-terminate after strncpy.",
      source="https://cwe.mitre.org/data/definitions/170.html",
      re=r'\bstrncpy\s*\(',
      nc='strncpy(dst, src, sizeof(dst));',
      c='strlcpy(dst, src, sizeof(dst));'),
    r(id="c-strncat", type="bug", qual="rel", sev="medium", cwe="CWE-787",
      title="Use of strncat()",
      desc="strncat()'s size argument is the remaining space, not the buffer size.",
      rationale="Passing the total buffer size (a common mistake) overflows the destination (CWE-787).",
      remediation="Use strlcat(), or pass the true remaining space.",
      source="https://cwe.mitre.org/data/definitions/787.html",
      re=r'\bstrncat\s*\(',
      nc='strncat(dst, src, sizeof(dst));',
      c='strlcat(dst, src, sizeof(dst));'),
    # --- format string injection (CWE-134) ---
    r(id="c-printf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="printf() with a non-literal format",
      desc="printf() is called with a single variable as the format string.",
      rationale="If the format string is attacker-controlled, %n/%s conversions can read/write memory (CWE-134).",
      remediation="Use a literal format: printf(\"%s\", value).",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bprintf\s*\(\s*[a-zA-Z_]\w*\s*\)',
      nc='printf(msg);',
      c='printf("%s", msg);'),
    r(id="c-fprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="fprintf() with a non-literal format",
      desc="fprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bfprintf\s*\([^,)]*,\s*[a-zA-Z_]\w*\s*\)',
      nc='fprintf(stderr, msg);',
      c='fprintf(stderr, "%s", msg);'),
    r(id="c-snprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="snprintf() with a non-literal format",
      desc="snprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bsnprintf\s*\([^,]*,[^,]*,\s*[a-zA-Z_]\w*\s*\)',
      nc='snprintf(buf, sizeof(buf), fmt);',
      c='snprintf(buf, sizeof(buf), "%s", fmt);'),
    r(id="c-syslog-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="syslog() with a non-literal format",
      desc="syslog() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bsyslog\s*\([^,)]*,\s*[a-zA-Z_]\w*\s*\)',
      nc='syslog(LOG_ERR, msg);',
      c='syslog(LOG_ERR, "%s", msg);'),
    # --- command / process execution (CWE-78 / CWE-426) ---
    r(id="c-system", type="vuln", qual="sec", sev="high", cwe="CWE-78",
      title="Use of system()",
      desc="system() runs a command through the shell.",
      rationale="Any input in the command string can be shell-injected (CWE-78).",
      remediation="Use exec-family calls with an argv array and no shell.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'\bsystem\s*\(',
      nc='system(cmd);',
      c='execv("/bin/prog", argv);'),
    r(id="c-popen", type="vuln", qual="sec", sev="high", cwe="CWE-78",
      title="Use of popen()",
      desc="popen() runs a command through the shell.",
      rationale="Input in the command string can be shell-injected (CWE-78).",
      remediation="Use pipe()+fork()+execv() with an argv array.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'\bpopen\s*\(',
      nc='FILE *f = popen(cmd, "r");',
      c='/* build a pipe with execv and no shell */',
      skip=CC),
    r(id="c-execlp", type="vuln", qual="sec", sev="medium", cwe="CWE-426",
      title="Use of execlp()",
      desc="execlp() resolves the program via the PATH environment variable.",
      rationale="A PATH-based lookup can execute an attacker-planted binary (CWE-426).",
      remediation="Use execv() with an absolute path.",
      source="https://cwe.mitre.org/data/definitions/426.html",
      re=r'\bexeclp\s*\(',
      nc='execlp("prog", "prog", NULL);',
      c='execv("/usr/bin/prog", argv);'),
    r(id="c-execvp", type="vuln", qual="sec", sev="medium", cwe="CWE-426",
      title="Use of execvp()",
      desc="execvp() resolves the program via the PATH environment variable.",
      rationale="A PATH-based lookup can execute an attacker-planted binary (CWE-426).",
      remediation="Use execv() with an absolute path.",
      source="https://cwe.mitre.org/data/definitions/426.html",
      re=r'\bexecvp\s*\(',
      nc='execvp("prog", argv);',
      c='execv("/usr/bin/prog", argv);'),
    # --- predictable temp files (CWE-377) ---
    r(id="c-tmpnam", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of tmpnam()",
      desc="tmpnam() returns a temp filename that is created later, opening a TOCTOU race.",
      rationale="Between naming and opening, an attacker can create/symlink the path (CWE-377).",
      remediation="Use mkstemp() which atomically creates and opens the file.",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\btmpnam\s*\(',
      nc='char *p = tmpnam(NULL);',
      c='int fd = mkstemp(template);'),
    r(id="c-tempnam", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of tempnam()",
      desc="tempnam() returns a temp filename subject to a TOCTOU race.",
      rationale="The named file is created later, allowing a race/symlink attack (CWE-377).",
      remediation="Use mkstemp().",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\btempnam\s*\(',
      nc='char *p = tempnam(dir, "app");',
      c='int fd = mkstemp(template);'),
    r(id="c-mktemp", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of mktemp()",
      desc="mktemp() only generates a name; the file is created separately.",
      rationale="The gap between naming and creating enables a TOCTOU race (CWE-377).",
      remediation="Use mkstemp() which creates and opens atomically.",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\bmktemp\s*\(',
      nc='mktemp(template);',
      c='int fd = mkstemp(template);'),
    # --- weak randomness (CWE-338 / CWE-337) ---
    r(id="c-rand", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="Use of rand() for security-sensitive values",
      desc="rand() is a non-cryptographic pseudo-random generator.",
      rationale="rand() output is predictable and unsuitable for tokens/keys/nonces (CWE-338); review the use.",
      remediation="Use a CSPRNG (getrandom/arc4random) for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\brand\s*\(\s*\)',
      nc='int token = rand();',
      c='getrandom(&token, sizeof(token), 0);'),
    r(id="c-srand-time", type="hotspot", qual="sec", sev="medium", cwe="CWE-337",
      title="srand() seeded with time()",
      desc="The PRNG is seeded with the current time.",
      rationale="A time-based seed is guessable, making the sequence predictable (CWE-337).",
      remediation="Seed from a CSPRNG, or use a CSPRNG directly for security values.",
      source="https://cwe.mitre.org/data/definitions/337.html",
      re=r'\bsrand\s*\(\s*time\s*\(',
      nc='srand(time(NULL));',
      c='getrandom(&seed, sizeof(seed), 0);'),
    # --- integer overflow in allocation (CWE-190) ---
    r(id="c-malloc-multiply", type="bug", qual="rel", sev="high", cwe="CWE-190",
      title="malloc() with a multiplication size",
      desc="An allocation size is computed by multiplying two values.",
      rationale="The product can overflow size_t, allocating a too-small buffer that later overflows (CWE-190).",
      remediation="Use calloc(count, size), or check for overflow before multiplying.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\bmalloc\s*\(\s*\w+\s*\*',
      nc='int *a = malloc(n * sizeof(int));',
      c='int *a = calloc(n, sizeof(int));'),
    r(id="c-alloca", type="bug", qual="rel", sev="medium", cwe="CWE-770",
      title="Use of alloca()",
      desc="alloca() allocates on the stack with no failure path.",
      rationale="A large or attacker-influenced size silently overflows the stack (CWE-770).",
      remediation="Use a fixed-size buffer or heap allocation with a size check.",
      source="https://cwe.mitre.org/data/definitions/770.html",
      re=r'\balloca\s*\(',
      nc='char *buf = alloca(n);',
      c='char *buf = malloc(n); if (!buf) return -1;'),
    # --- number parsing without error detection (CWE-190/CWE-20) ---
    r(id="c-atoi", type="bug", qual="rel", sev="low", cwe="CWE-190",
      title="Use of atoi()",
      desc="atoi() reports no error and has undefined behavior on overflow.",
      rationale="Invalid or out-of-range input silently yields 0 or UB (CWE-190).",
      remediation="Use strtol() and check errno/endptr.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\batoi\s*\(',
      nc='int n = atoi(arg);',
      c='long n = strtol(arg, &end, 10);'),
    r(id="c-atol", type="bug", qual="rel", sev="low", cwe="CWE-190",
      title="Use of atol()",
      desc="atol() reports no error and has undefined behavior on overflow.",
      rationale="Invalid or out-of-range input silently yields 0 or UB (CWE-190).",
      remediation="Use strtol() and check errno/endptr.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\batol\s*\(',
      nc='long n = atol(arg);',
      c='long n = strtol(arg, &end, 10);'),
    r(id="c-atoll", type="bug", qual="rel", sev="low", cwe="CWE-190",
      title="Use of atoll()",
      desc="atoll() reports no error and has undefined behavior on overflow.",
      rationale="Invalid or out-of-range input silently yields 0 or UB (CWE-190).",
      remediation="Use strtoll() and check errno/endptr.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\batoll\s*\(',
      nc='long long n = atoll(arg);',
      c='long long n = strtoll(arg, &end, 10);'),
    r(id="c-atof", type="bug", qual="rel", sev="low", cwe="CWE-20",
      title="Use of atof()",
      desc="atof() reports no error on malformed input.",
      rationale="Invalid input silently yields 0.0 with no way to detect it (CWE-20).",
      remediation="Use strtod() and check endptr.",
      source="https://cwe.mitre.org/data/definitions/20.html",
      re=r'\batof\s*\(',
      nc='double d = atof(arg);',
      c='double d = strtod(arg, &end);'),
    # --- non-reentrant / thread-unsafe APIs (CWE-676) ---
    r(id="c-strtok", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of strtok()",
      desc="strtok() keeps hidden static state and mutates its input.",
      rationale="It is not reentrant or thread-safe and corrupts state when nested (CWE-676).",
      remediation="Use strtok_r() (or strsep()).",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bstrtok\s*\(',
      nc='char *t = strtok(line, ",");',
      c='char *t = strtok_r(line, ",", &save);'),
    r(id="c-gethostbyname", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of gethostbyname()",
      desc="gethostbyname() is obsolete, IPv4-only, and not reentrant.",
      rationale="It returns a static buffer and cannot handle IPv6 (CWE-676).",
      remediation="Use getaddrinfo().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bgethostbyname\s*\(',
      nc='struct hostent *h = gethostbyname(name);',
      c='getaddrinfo(name, port, &hints, &res);'),
    r(id="c-localtime", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of localtime()",
      desc="localtime() returns a pointer to shared static storage.",
      rationale="Concurrent or nested calls overwrite the result; it is not thread-safe (CWE-676).",
      remediation="Use localtime_r().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\blocaltime\s*\(',
      nc='struct tm *t = localtime(&now);',
      c='struct tm t; localtime_r(&now, &t);'),
    r(id="c-gmtime", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of gmtime()",
      desc="gmtime() returns a pointer to shared static storage.",
      rationale="Concurrent or nested calls overwrite the result; it is not thread-safe (CWE-676).",
      remediation="Use gmtime_r().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bgmtime\s*\(',
      nc='struct tm *t = gmtime(&now);',
      c='struct tm t; gmtime_r(&now, &t);'),
    r(id="c-ctime", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of ctime()",
      desc="ctime() returns a pointer to shared static storage.",
      rationale="Concurrent or nested calls overwrite the result; it is not thread-safe (CWE-676).",
      remediation="Use ctime_r() or strftime().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bctime\s*\(',
      nc='char *s = ctime(&now);',
      c='char s[26]; ctime_r(&now, s);'),
    r(id="c-asctime", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of asctime()",
      desc="asctime() returns a pointer to shared static storage and can overflow.",
      rationale="It is not thread-safe and has a fixed 26-byte buffer (CWE-676).",
      remediation="Use strftime() with an explicit buffer.",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\basctime\s*\(',
      nc='char *s = asctime(tm);',
      c='char s[64]; strftime(s, sizeof(s), "%c", tm);'),
    r(id="c-strerror", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of strerror()",
      desc="strerror() returns a pointer to a shared static string.",
      rationale="Concurrent calls can race on the shared buffer; it is not thread-safe (CWE-676).",
      remediation="Use strerror_r().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bstrerror\s*\(',
      nc='log_error(strerror(errno));',
      c='char b[128]; strerror_r(errno, b, sizeof(b));'),
    r(id="c-vfork", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of vfork()",
      desc="vfork() shares the parent's address space until exec/exit.",
      rationale="Any write in the child before exec is undefined behavior; vfork is error-prone and largely obsolete (CWE-676).",
      remediation="Use fork() (or posix_spawn()).",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bvfork\s*\(',
      nc='pid_t p = vfork();',
      c='pid_t p = fork();'),
    r(id="c-longjmp", type="smell", qual="maint", sev="low", cwe="",
      title="Use of longjmp()",
      desc="longjmp() performs a non-local jump that skips normal control flow.",
      rationale="It bypasses cleanup and destructor-like teardown, making resource management error-prone.",
      remediation="Use structured error returns and goto-cleanup within a function.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/MSC22-C.+Use+the+setjmp%28%29+macro+and+longjmp%28%29+function+securely",
      re=r'\blongjmp\s*\(',
      nc='longjmp(env, 1);',
      c='return ERR_PARSE;'),
    # --- housekeeping marker ---
    r(id="c-todo-comment", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="TODO/FIXME marker in C code",
      desc="A TODO or FIXME marker flags unfinished work.",
      rationale="Tracked markers highlight incomplete or known-broken code paths that should be resolved.",
      remediation="Resolve the item or track it in an issue.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/",
      re=r'/[/*].*\b(TODO|FIXME)\b',
      nc='/* TODO: validate the length here */',
      c='/* validated above */'),
]
