# C++ language-pack rule specs, batch 4 (#199). Clean-room, line-detectable — non-reentrant/obsolete C
# APIs and weak-crypto/RNG variants relevant in .cpp, plus C++-specific lambda/idiom rules. Origins cited.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cpp")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "cpp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


def reent(id_, fn, rfn, type_="bug", qual="rel"):
    return r(id=id_, type=type_, qual=qual, sev="low", cwe="CWE-676",
             title=f"Use of {fn}()",
             desc=f"{fn}() returns a pointer to shared static storage.",
             rationale=f"Concurrent calls overwrite the shared result; {fn} is not thread-safe (CWE-676).",
             remediation=f"Use {rfn}().",
             source="https://cwe.mitre.org/data/definitions/676.html",
             re=rf'\b{fn}\s*\(',
             nc=f'auto* p = {fn}(&arg);',
             c=f'{rfn}(&arg, &out);')


def csprng(id_, fn, re_, nc, cwe="CWE-338", why="predictable"):
    return r(id=id_, type="hotspot", qual="sec", sev="medium", cwe=cwe,
             title=f"Use of {fn} for security values",
             desc=f"{fn} is a non-cryptographic pseudo-random source.",
             rationale=f"Its output is {why} and unsuitable for tokens/keys ({cwe}).",
             remediation="Use std::random_device / a CSPRNG for security values.",
             source=f"https://cwe.mitre.org/data/definitions/{cwe.split('-')[1]}.html",
             re=re_,
             nc=nc,
             c='auto v = secure_rng();')


def perm777(id_, fn, re_):
    return r(id=id_, type="vuln", qual="sec", sev="medium", cwe="CWE-732",
             title=f"{fn}() with mode 0777",
             desc=f"{fn}() creates a world-accessible filesystem object.",
             rationale="Mode 0777 lets any local user modify the object (CWE-732).",
             remediation="Use a restrictive mode (e.g. 0600/0700).",
             source="https://cwe.mitre.org/data/definitions/732.html",
             re=re_,
             nc=f'{fn}(path, 0777);',
             c=f'{fn}(path, 0600);')


RULES = [
    reent("cpp-localtime", "localtime", "localtime_r"),
    reent("cpp-gmtime", "gmtime", "gmtime_r"),
    reent("cpp-ctime", "ctime", "ctime_r"),
    reent("cpp-asctime", "asctime", "asctime_r"),
    reent("cpp-strerror", "strerror", "strerror_r"),
    reent("cpp-gethostbyname", "gethostbyname", "getaddrinfo", "smell", "maint"),
    reent("cpp-getpwuid", "getpwuid", "getpwuid_r", "smell", "maint"),
    reent("cpp-getpwnam", "getpwnam", "getpwnam_r", "smell", "maint"),
    reent("cpp-gethostbyaddr", "gethostbyaddr", "getnameinfo", "smell", "maint"),
    r(id="cpp-vfork", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of vfork()",
      desc="vfork() shares the parent's address space until exec/exit.",
      rationale="Any write in the child before exec is undefined behavior; vfork is error-prone (CWE-676).",
      remediation="Use fork() or posix_spawn().",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bvfork\s*\(', nc='pid_t p = vfork();', c='pid_t p = fork();'),
    r(id="cpp-signal", type="smell", qual="maint", sev="low", cwe="",
      title="Use of signal()",
      desc="signal() has implementation-defined semantics.",
      rationale="Its behavior varies across systems; sigaction is portable and precise.",
      remediation="Use sigaction().",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/SIG01-CPP",
      re=r'\bsignal\s*\(', nc='signal(SIGINT, handler);', c='sigaction(SIGINT, &sa, nullptr);'),
    r(id="cpp-putenv", type="bug", qual="rel", sev="low", cwe="CWE-686",
      title="Use of putenv()",
      desc="putenv() stores the passed pointer rather than copying it.",
      rationale="If the buffer is local or later modified, the environment holds a dangling string (CWE-686).",
      remediation="Use setenv(), which copies the value.",
      source="https://cwe.mitre.org/data/definitions/686.html",
      re=r'\bputenv\s*\(', nc='putenv(buf);', c='setenv("KEY", "value", 1);'),
    r(id="cpp-getpass", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of getpass()",
      desc="getpass() is obsolete and non-reentrant.",
      rationale="It was removed from POSIX and mishandles long input (CWE-676).",
      remediation="Read the password via termios with echo disabled.",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bgetpass\s*\(', nc='char* p = getpass("Password: ");', c='read_password(buf, sizeof(buf));'),
    r(id="cpp-strdup", type="smell", qual="maint", sev="info", cwe="",
      title="strdup() in C++",
      desc="C-style strdup returns a malloc'd copy that must be freed manually.",
      rationale="It pairs with free() and bypasses RAII; std::string owns automatically.",
      remediation="Use std::string.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r10-avoid-malloc-and-free",
      re=r'\bstrdup\s*\(', nc='char* d = strdup(src);', c='std::string d = src;'),
    r(id="cpp-atof", type="bug", qual="rel", sev="low", cwe="CWE-20",
      title="Use of atof()",
      desc="atof() reports no error on malformed input.",
      rationale="Invalid input silently yields 0.0 with no way to detect it (CWE-20).",
      remediation="Use std::from_chars / std::stod with error handling.",
      source="https://cwe.mitre.org/data/definitions/20.html",
      re=r'\batof\s*\(', nc='double d = atof(arg);', c='auto [p, ec] = std::from_chars(b, e, d);'),
    r(id="cpp-fscanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="fscanf(\"%s\") without a field width",
      desc="An fscanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token, overflowing the buffer (CWE-120).",
      remediation="Add a field width, or parse with iostreams.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bfscanf\s*\([^)]*"[^"]*%s', nc='fscanf(f, "%s", buf);', c='fscanf(f, "%63s", buf);'),
    r(id="cpp-wcscpy", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of wcscpy()",
      desc="wcscpy() copies a wide string with no destination bound.",
      rationale="It overflows when the source exceeds the destination (CWE-120).",
      remediation="Use std::wstring, or a bounded copy.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bwcscpy\s*\(', nc='wcscpy(dst, src);', c='std::wstring dst = src;'),
    r(id="cpp-wcscat", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of wcscat()",
      desc="wcscat() appends a wide string with no destination bound.",
      rationale="It overflows when the result exceeds the buffer (CWE-120).",
      remediation="Use std::wstring concatenation.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bwcscat\s*\(', nc='wcscat(dst, src);', c='dst_str += src;'),
    r(id="cpp-md4", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash function MD4",
      desc="MD4 computes a cryptographically broken digest.",
      rationale="MD4 is badly broken and unsuitable for any security use (CWE-327).",
      remediation="Use SHA-256.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bMD4(_Init)?\s*\(', nc='MD4(data, len, digest);', c='SHA256(data, len, digest);'),
    r(id="cpp-blowfish", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Blowfish encryption",
      desc="An OpenSSL Blowfish routine is used.",
      rationale="Blowfish has a 64-bit block (SWEET32) and is deprecated (CWE-327).",
      remediation="Use AES via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bBF_(ecb|cbc|cfb64|ofb64)_encrypt\s*\(', nc='BF_cbc_encrypt(in, out, len, &ks, iv, BF_ENCRYPT);', c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="cpp-evp-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="EVP_md5() digest",
      desc="An OpenSSL EVP digest is initialized with MD5.",
      rationale="MD5 is collision-prone and unsuitable for security use (CWE-327).",
      remediation="Use EVP_sha256().",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_md5\s*\(', nc='EVP_DigestInit_ex(ctx, EVP_md5(), nullptr);', c='EVP_DigestInit_ex(ctx, EVP_sha256(), nullptr);'),
    r(id="cpp-evp-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="EVP_sha1() digest",
      desc="An OpenSSL EVP digest is initialized with SHA-1.",
      rationale="SHA-1 is collision-broken and unsuitable for signatures (CWE-327).",
      remediation="Use EVP_sha256().",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_sha1\s*\(', nc='EVP_DigestInit_ex(ctx, EVP_sha1(), nullptr);', c='EVP_DigestInit_ex(ctx, EVP_sha256(), nullptr);'),
    r(id="cpp-crypt", type="hotspot", qual="sec", sev="medium", cwe="CWE-327",
      title="Use of crypt()",
      desc="crypt() defaults to weak DES-based hashing on many platforms.",
      rationale="Legacy crypt output is fast to brute-force and unsuitable for password storage (CWE-327).",
      remediation="Use a modern KDF (Argon2/bcrypt/scrypt).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bcrypt\s*\(', nc='char* h = crypt(pw, salt);', c='auto h = argon2_hash(pw, salt);'),
    csprng("cpp-rand-r", "rand_r()", r'\brand_r\s*\(', 'unsigned v = rand_r(&seed);'),
    csprng("cpp-random", "random()", r'\brandom\s*\(\s*\)', 'long v = random();'),
    csprng("cpp-drand48", "the drand48 family", r'\b(drand48|lrand48|mrand48|nrand48|jrand48)\s*\(', 'double v = drand48();'),
    csprng("cpp-srand-getpid", "srand(getpid())", r'\bsrand\s*\(\s*getpid\s*\(', 'srand(getpid());', "CWE-337", "guessable"),
    csprng("cpp-srandom-time", "srandom(time())", r'\bsrandom\s*\(\s*time\s*\(', 'srandom(time(nullptr));', "CWE-337", "guessable"),
    perm777("cpp-creat-777", "creat", r'\bcreat\s*\([^,]*,\s*0777\b'),
    perm777("cpp-mkfifo-777", "mkfifo", r'\bmkfifo\s*\([^,]*,\s*0777\b'),
    r(id="cpp-tempnam", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of tempnam()",
      desc="tempnam() returns a name whose file is created later (TOCTOU).",
      rationale="The named file is created later, allowing a race/symlink attack (CWE-377).",
      remediation="Use mkstemp().",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\btempnam\s*\(', nc='char* p = tempnam(dir, "app");', c='int fd = mkstemp(templ);'),
    r(id="cpp-inet-addr", type="smell", qual="maint", sev="low", cwe="",
      title="Use of inet_addr()",
      desc="inet_addr() has an ambiguous error return and is IPv4-only.",
      rationale="It returns INADDR_NONE (-1) for both the broadcast address and errors, and cannot parse IPv6.",
      remediation="Use inet_pton() (or getaddrinfo()).",
      source="https://man7.org/linux/man-pages/man3/inet_addr.3.html",
      re=r'\binet_addr\s*\(', nc='addr.s_addr = inet_addr(ip);', c='inet_pton(AF_INET, ip, &addr);'),
    r(id="cpp-basename-dirname", type="smell", qual="maint", sev="info", cwe="CWE-676",
      title="Use of basename()/dirname()",
      desc="basename()/dirname() may modify their argument and use static storage.",
      rationale="Behavior differs between POSIX and GNU variants and is not reentrant (CWE-676).",
      remediation="Use std::filesystem::path (filename()/parent_path()).",
      source="https://man7.org/linux/man-pages/man3/basename.3.html",
      re=r'\b(basename|dirname)\s*\(', nc='char* b = basename(path);', c='auto b = std::filesystem::path(path).filename();'),
    r(id="cpp-lambda-capture-all-ref", type="smell", qual="maint", sev="medium", cwe="CWE-562",
      title="Lambda captures everything by reference",
      desc="A lambda uses a [&] default capture.",
      rationale="Capturing everything by reference easily outlives the referents, dangling if the lambda escapes (CWE-562).",
      remediation="Capture the specific variables you need, by the correct kind.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f53-avoid-capturing-by-reference-in-lambdas-that-will-be-used-non-locally",
      re=r'\[\s*&\s*\]', nc='auto f = [&] { return total + tax; };', c='auto f = [total, tax] { return total + tax; };'),
    r(id="cpp-lambda-capture-all-value", type="smell", qual="maint", sev="info", cwe="",
      title="Lambda captures everything by value",
      desc="A lambda uses a [=] default capture.",
      rationale="A [=] default copies everything (and captures this by pointer in members), which is easy to misuse.",
      remediation="Capture the specific variables you need.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f54-if-you-capture-this-capture-all-variables-explicitly-no-default-capture",
      re=r'\[\s*=\s*\]', nc='auto f = [=] { return base + offset; };', c='auto f = [base, offset] { return base + offset; };'),
    r(id="cpp-make-pair-explicit", type="smell", qual="maint", sev="info", cwe="",
      title="make_pair with explicit template arguments",
      desc="std::make_pair is given explicit template arguments.",
      rationale="Explicit types defeat the deduction that make_pair exists for; it can also force unwanted conversions.",
      remediation="Let make_pair deduce, or use brace-init / std::pair directly.",
      source="https://en.cppreference.com/w/cpp/utility/pair/make_pair",
      re=r'make_pair\s*<', nc='auto p = std::make_pair<int, std::string>(1, name);', c='auto p = std::make_pair(1, name);'),
    r(id="cpp-erase-remove", type="smell", qual="maint", sev="info", cwe="",
      title="erase(remove(...)) idiom",
      desc="Elements are removed with the erase-remove idiom.",
      rationale="C++20 provides std::erase / std::erase_if, which are less error-prone.",
      remediation="Use std::erase / std::erase_if.",
      source="https://en.cppreference.com/w/cpp/container/vector/erase2",
      re=r'\.erase\(\s*std::remove', nc='v.erase(std::remove(v.begin(), v.end(), x), v.end());', c='std::erase(v, x);'),
    r(id="cpp-cast-after-int-division", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Widening cast applied after integer division",
      desc="An integer division is parenthesized and then cast to a floating-point type.",
      rationale="The division truncates before the cast, so the fraction is already lost (CWE-682).",
      remediation="Cast an operand before dividing.",
      source="https://cwe.mitre.org/data/definitions/682.html",
      re=r'\((?:double|float)\)\s*\(\s*\w+\s*/\s*\w+\s*\)', nc='auto r = (double)(hits / total);', c='auto r = static_cast<double>(hits) / total;'),
]
