# Rust language-pack rule specs — `err` (error handling) + `res` (resource management) families (#197).
# Clean-room, line-detectable; concept origins cited (Clippy, CWE, Rust std docs).
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "rust")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "rust", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- err (8 target) ----
    r("err", id="rust:let-underscore-must-use", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="Result discarded with let _",
      desc="A fallible call's result is bound to _ and ignored.",
      rationale="Binding a Result to _ silently drops the error, so failures go unnoticed (CWE-252, Clippy let_underscore_must_use).",
      remediation="Propagate with ? or handle the Err arm.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'let\s+_\s*=\s*[A-Za-z_]\w*\(',
      nc='let _ = write_all(buf);',
      c='write_all(buf)?;'),
    r("err", id="rust:map-err-discard", type="smell", qual="maint", sev="low", cwe="CWE-390",
      title="map_err discards the error",
      desc="map_err throws the original error away with a |_| closure.",
      rationale="Replacing an error with a value derived from nothing loses the failure cause (CWE-390).",
      remediation="Preserve the source error (map_err(|e| ...From(e))).",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r'\.map_err\(\s*\|_\|',
      nc='foo().map_err(|_| ())?;',
      c='foo().map_err(|e| MyErr::from(e))?;'),
    r("err", id="rust:unwrap-err", type="bug", qual="rel", sev="low", cwe="",
      title="unwrap_err() panics on Ok",
      desc="unwrap_err() assumes the Result is Err.",
      rationale="unwrap_err() panics if the Result is Ok, aborting the thread.",
      remediation="Match the Err arm with if let / match.",
      source="https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_err",
      re=r'\.unwrap_err\(\)',
      nc='let e = res.unwrap_err();',
      c='if let Err(e) = res { handle(e); }'),
    r("err", id="rust:expect-err", type="bug", qual="rel", sev="low", cwe="",
      title="expect_err() panics on Ok",
      desc="expect_err() assumes the Result is Err.",
      rationale="expect_err() panics if the Result is Ok, turning a value into an abort.",
      remediation="Match the Err arm explicitly.",
      source="https://doc.rust-lang.org/std/result/enum.Result.html#method.expect_err",
      re=r'\.expect_err\(',
      nc='let e = res.expect_err("want error");',
      c='if let Err(e) = res { handle(e); }'),
    r("err", id="rust:unwrap-or-else-panic", type="bug", qual="rel", sev="medium", cwe="",
      title="unwrap_or_else that panics",
      desc="unwrap_or_else runs a closure that panics.",
      rationale="Panicking inside the fallback defeats the recovery the combinator is meant to provide.",
      remediation="Return a real default or propagate the error.",
      source="https://rust-lang.github.io/rust-clippy/master/#panic",
      re=r'\.unwrap_or_else\(\s*\|\|\s*panic!',
      nc='x.unwrap_or_else(|| panic!("missing"));',
      c='x.unwrap_or_default();'),
    r("err", id="rust:error-unit-type", type="smell", qual="maint", sev="low", cwe="",
      title="Result with a () error type",
      desc="A function returns Result<T, ()>.",
      rationale="A unit error carries no information for the caller to act on (Rust API Guidelines C-GOOD-ERR).",
      remediation="Return a descriptive error type.",
      source="https://rust-lang.github.io/api-guidelines/interoperability.html",
      re=r'Result<[^,>]*,\s*\(\)>',
      nc='fn parse(s: &str) -> Result<u32, ()> {',
      c='fn parse(s: &str) -> Result<u32, ParseError> {'),
    r("err", id="rust:write-unwrap", type="bug", qual="rel", sev="low", cwe="",
      title="write! result unwrapped",
      desc="A write!/writeln! result is unwrapped instead of propagated.",
      rationale="Formatting into a fallible writer can fail; unwrap() panics on I/O error.",
      remediation="Propagate the fmt::Result with ?.",
      source="https://rust-lang.github.io/rust-clippy/master/#unwrap_used",
      re=r'\bwrite(ln)?!\([^)]*\)\.unwrap\(\)',
      nc='write!(f, "{}", x).unwrap();',
      c='write!(f, "{}", x)?;'),
    r("err", id="rust:map-unwrap", type="bug", qual="rel", sev="medium", cwe="CWE-248",
      title="map().unwrap() on a Result",
      desc="A Result is transformed with map() then unwrapped.",
      rationale="unwrap() after map() still panics on the Err path.",
      remediation="Propagate with ? after map().",
      source="https://rust-lang.github.io/rust-clippy/master/#unwrap_used",
      re=r'\.map\(.*\)\.unwrap\(\)',
      nc='let v = res.map(|x| x + 1).unwrap();',
      c='let v = res.map(|x| x + 1)?;'),
    r("err", id="rust:silent-error-continue", type="smell", qual="maint", sev="low", cwe="CWE-390",
      title="Error arm silently continues",
      desc="An Err(_) match arm swallows the error and continues.",
      rationale="Discarding the error and continuing hides failures from operators (CWE-390).",
      remediation="Log or propagate the error before continuing.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r'Err\(_\)\s*=>\s*(continue|\{\s*\})',
      nc='Err(_) => continue,',
      c='Err(e) => return Err(e),'),
    # ---- res (8 target) ----
    r("res", id="rust:box-leak", type="bug", qual="rel", sev="medium", cwe="CWE-401",
      title="Box::leak deliberately leaks",
      desc="Box::leak converts an owned box into a leaked 'static reference.",
      rationale="Box::leak never frees the allocation for the process lifetime (CWE-401).",
      remediation="Keep ownership of the Box, or ensure the leak is truly process-lifetime.",
      source="https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak",
      re=r'\bBox::leak\(',
      nc='let s = Box::leak(b);',
      c='let s = &*b;'),
    r("res", id="rust:manuallydrop-new", type="smell", qual="maint", sev="low", cwe="CWE-401",
      title="ManuallyDrop requires explicit drop",
      desc="A value is wrapped in ManuallyDrop.",
      rationale="ManuallyDrop suppresses the destructor; forgetting the manual drop leaks the resource (CWE-401).",
      remediation="Ensure ManuallyDrop::drop is called on every path, or avoid it.",
      source="https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html",
      re=r'\bManuallyDrop::new\(',
      nc='let m = ManuallyDrop::new(res);',
      c='let m = res;'),
    r("res", id="rust:from-raw-fd", type="hotspot", qual="sec", sev="medium", cwe="CWE-664",
      title="from_raw_fd descriptor ownership",
      desc="A type is constructed from a raw file descriptor.",
      rationale="from_raw_fd assumes exclusive ownership; a double-owned fd leads to double-close (CWE-664).",
      remediation="Prefer safe constructors (File::open); if unavoidable, document the ownership transfer.",
      source="https://doc.rust-lang.org/std/os/fd/trait.FromRawFd.html",
      re=r'\bfrom_raw_fd\(',
      nc='let f = unsafe { File::from_raw_fd(fd) };',
      c='let f = File::open(path)?;'),
    r("res", id="rust:cstring-into-raw", type="bug", qual="rel", sev="medium", cwe="CWE-401",
      title="CString::into_raw leaks without retake",
      desc="into_raw() releases ownership of a CString to a raw pointer.",
      rationale="The raw pointer must be reclaimed with from_raw or the buffer leaks (CWE-401).",
      remediation="Reclaim with CString::from_raw, or keep the owned CString.",
      source="https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw",
      re=r'\.into_raw\(\)',
      nc='let p = CString::new("x")?.into_raw();',
      c='let c = CString::new("x")?;'),
    r("res", id="rust:vec-set-len", type="bug", qual="rel", sev="high", cwe="CWE-908",
      title="Vec::set_len exposes uninitialized memory",
      desc="set_len grows the length without initializing elements.",
      rationale="set_len marks memory as initialized that was never written, causing use of uninitialized data (CWE-908).",
      remediation="Use resize/extend, or write elements before set_len.",
      source="https://doc.rust-lang.org/std/vec/struct.Vec.html#method.set_len",
      re=r'\.set_len\(',
      nc='unsafe { v.set_len(n); }',
      c='v.resize(n, 0);'),
    r("res", id="rust:mem-uninitialized", type="bug", qual="rel", sev="high", cwe="CWE-908",
      title="mem::uninitialized is undefined behavior",
      desc="mem::uninitialized produces an invalid value.",
      rationale="mem::uninitialized is deprecated and instantly UB for most types (CWE-908).",
      remediation="Use MaybeUninit and initialize before assume_init.",
      source="https://doc.rust-lang.org/std/mem/fn.uninitialized.html",
      re=r'\bmem::uninitialized\(',
      nc='let x = unsafe { mem::uninitialized() };',
      c='let x = MaybeUninit::uninit();'),
    r("res", id="rust:mem-zeroed", type="hotspot", qual="sec", sev="medium", cwe="CWE-908",
      title="mem::zeroed on a non-zeroable type",
      desc="mem::zeroed fabricates an all-zero value.",
      rationale="Zeroing a type with invalid zero bit-patterns (e.g. references) is undefined behavior (CWE-908).",
      remediation="Use MaybeUninit::zeroed only for types where zero is valid.",
      source="https://doc.rust-lang.org/std/mem/fn.zeroed.html",
      re=r'\bmem::zeroed\(',
      nc='let x = unsafe { mem::zeroed() };',
      c='let x = MaybeUninit::zeroed();'),
    r("res", id="rust:cstr-from-ptr", type="hotspot", qual="sec", sev="medium", cwe="CWE-825",
      title="CStr::from_ptr lifetime hazard",
      desc="A CStr is built from a raw pointer of unbounded lifetime.",
      rationale="from_ptr trusts the pointer to be valid and NUL-terminated for an unchecked lifetime (CWE-825).",
      remediation="Prefer from_bytes_with_nul on an owned buffer.",
      source="https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_ptr",
      re=r'\bCStr::from_ptr\(',
      nc='let s = unsafe { CStr::from_ptr(p) };',
      c='let s = CStr::from_bytes_with_nul(buf)?;'),
    r("res", id="rust:vec-from-raw-parts", type="hotspot", qual="sec", sev="high", cwe="CWE-787",
      title="Vec::from_raw_parts reconstructs ownership",
      desc="A Vec is rebuilt from a raw pointer, length and capacity.",
      rationale="Mismatched pointer/len/cap or a foreign allocator makes from_raw_parts undefined behavior (CWE-787).",
      remediation="Use safe conversions such as slice.to_vec().",
      source="https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_raw_parts",
      re=r'\bVec::from_raw_parts\(',
      nc='let v = unsafe { Vec::from_raw_parts(p, len, cap) };',
      c='let v = slice.to_vec();'),
]
