CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","java");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","java"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="java-empty-statement",type="smell",qual="maint",sev="low",cwe="",title="Empty statement",
   desc="A lone semicolon is an empty statement, usually a leftover.",
   rationale="A standalone semicolon does nothing and often indicates a deleted statement or a misplaced terminator.",
   remediation="Remove the stray semicolon.",
   source="https://pmd.github.io/pmd/pmd_rules_java_errorprone.html",
   re=r"^\s*;\s*$",nc="counter++;\n;",c="counter++;"),
 r(id="java-inefficient-append-concat",type="smell",qual="maint",sev="low",cwe="",title="Concatenation inside append()",
   desc="`append(a + b)` builds an intermediate string, defeating the builder.",
   rationale="Concatenating inside append() creates a throwaway String each call, negating the point of StringBuilder.",
   remediation="Chain separate append() calls instead of concatenating.",
   source="https://pmd.github.io/pmd/pmd_rules_java_performance.html",
   re=r"\.append\s*\([^)]*\+[^)]*\)",nc='sb.append("id=" + id);',c='sb.append("id=").append(id);'),
 r(id="java-import-java-lang",type="smell",qual="maint",sev="low",cwe="",title="Redundant java.lang import",
   desc="Types in java.lang are imported automatically.",
   rationale="An explicit import of a java.lang type is redundant noise.",
   remediation="Remove the java.lang import.",
   source="https://pmd.github.io/pmd/pmd_rules_java_codestyle.html",
   re=r"\bimport\s+java\.lang\.[A-Z]",nc="import java.lang.String;",c="import java.util.List;"),
 r(id="java-star-import",type="smell",qual="maint",sev="low",cwe="",title="Wildcard import",
   desc="A `.*` import pulls in a whole package and hides which types are used.",
   rationale="Wildcard imports obscure the actual dependencies and can cause ambiguous references when packages overlap.",
   remediation="Import the specific types you use.",
   source="https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports",
   re=r"\bimport\s+[\w.]+\.\*\s*;",nc="import java.util.*;",c="import java.util.List;"),
 r(id="java-new-threadgroup",type="smell",qual="maint",sev="low",cwe="",title="ThreadGroup usage",
   desc="ThreadGroup has broken/deprecated methods and poor thread management.",
   rationale="ThreadGroup's API is largely deprecated and error-prone; executors provide better lifecycle and error handling.",
   remediation="Use an ExecutorService from java.util.concurrent.",
   source="https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadGroup.html",
   re=r"\bnew\s+ThreadGroup\s*\(",nc='ThreadGroup g = new ThreadGroup("workers");',c="ExecutorService pool = Executors.newFixedThreadPool(4);"),
 r(id="java-explicit-finalize-call",type="bug",qual="rel",sev="medium",cwe="",title="Explicit finalize() call",
   desc="Calling finalize() directly runs it a second time; the JVM will still call it.",
   rationale="finalize() is meant to be invoked only by the garbage collector; an explicit call double-runs cleanup logic.",
   remediation="Use an explicit close()/dispose() method for deterministic cleanup.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/MET12-J.+Do+not+use+finalizers",
   re=r"\.finalize\s*\(\s*\)",nc="resource.finalize();",c="resource.close();"),
 r(id="java-biginteger-literal",type="smell",qual="maint",sev="low",cwe="",title="BigInteger from a 0/1 literal",
   desc="`new BigInteger(\"0\"|\"1\")` should reuse the ZERO/ONE constants.",
   rationale="BigInteger.ZERO/ONE/TEN are cached constants; constructing them from a string allocates needlessly.",
   remediation="Use BigInteger.ZERO / BigInteger.ONE / BigInteger.TEN.",
   source="https://pmd.github.io/pmd/pmd_rules_java_performance.html",
   re=r'\bnew\s+BigInteger\s*\(\s*"[01]"\s*\)',nc='BigInteger z = new BigInteger("0");',c="BigInteger z = BigInteger.ZERO;"),
]
