# Rust language-pack rule specs — `conc` (concurrency) + `inj` (injection) + `crypto` + `hotspot`
# families (#197). Clean-room, line-detectable; concept origins cited (CWE, OWASP, Rust docs).
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "rust")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "rust", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- conc (8 target) ----
    r("conc", id="rust:mutex-lock-unwrap", type="bug", qual="rel", sev="low", cwe="CWE-248",
      title="Mutex lock().unwrap()",
      desc="A Mutex lock result is unwrapped.",
      rationale="lock() returns a PoisonError if another thread panicked while holding the lock; unwrap() then panics too.",
      remediation="Handle the poison case (map_err / into_inner).",
      source="https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock",
      re=r'\.lock\(\)\.unwrap\(\)',
      nc='let g = m.lock().unwrap();',
      c='let g = m.lock().map_err(|_| Error::Poisoned)?;'),
    r("conc", id="rust:rwlock-write-unwrap", type="bug", qual="rel", sev="low", cwe="CWE-248",
      title="RwLock write().unwrap()",
      desc="A RwLock write guard is unwrapped.",
      rationale="write() can return a poison error after a panic; unwrap() propagates it as a new panic.",
      remediation="Handle the poison case instead of unwrapping.",
      source="https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.write",
      re=r'\.write\(\)\.unwrap\(\)',
      nc='let g = rw.write().unwrap();',
      c='let g = rw.write().map_err(|_| Error::Poisoned)?;'),
    r("conc", id="rust:rwlock-read-unwrap", type="bug", qual="rel", sev="low", cwe="CWE-248",
      title="RwLock read().unwrap()",
      desc="A RwLock read guard is unwrapped.",
      rationale="read() can return a poison error after a panic; unwrap() turns it into another panic.",
      remediation="Handle the poison case instead of unwrapping.",
      source="https://doc.rust-lang.org/std/sync/struct.RwLock.html#method.read",
      re=r'\.read\(\)\.unwrap\(\)',
      nc='let g = rw.read().unwrap();',
      c='let g = rw.read().map_err(|_| Error::Poisoned)?;'),
    r("conc", id="rust:atomic-relaxed", type="hotspot", qual="sec", sev="medium", cwe="CWE-362",
      title="Relaxed atomic ordering",
      desc="An atomic operation uses Ordering::Relaxed.",
      rationale="Relaxed ordering provides no happens-before guarantee and is a common source of races (CWE-362).",
      remediation="Use Acquire/Release/SeqCst unless Relaxed is proven correct.",
      source="https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html",
      re=r'\bOrdering::Relaxed\b',
      nc='ready.store(true, Ordering::Relaxed);',
      c='ready.store(true, Ordering::SeqCst);'),
    r("conc", id="rust:thread-join-unwrap", type="bug", qual="rel", sev="low", cwe="CWE-248",
      title="JoinHandle join().unwrap()",
      desc="A thread join result is unwrapped.",
      rationale="join() returns Err if the thread panicked; unwrap() re-panics on the caller.",
      remediation="Handle the join error rather than unwrapping.",
      source="https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join",
      re=r'\.join\(\)\.unwrap\(\)',
      nc='handle.join().unwrap();',
      c='handle.join().map_err(|_| Error::ThreadPanic)?;'),
    r("conc", id="rust:static-mut", type="hotspot", qual="sec", sev="high", cwe="CWE-362",
      title="Mutable static",
      desc="A static mut is declared.",
      rationale="Any access to a static mut is unsafe and racy across threads (CWE-362).",
      remediation="Use an atomic, Mutex, or OnceLock instead.",
      source="https://doc.rust-lang.org/reference/items/static-items.html#mutable-statics",
      re=r'\bstatic\s+mut\b',
      nc='static mut COUNTER: u32 = 0;',
      c='static COUNTER: AtomicU32 = AtomicU32::new(0);'),
    r("conc", id="rust:block-on-nested", type="bug", qual="rel", sev="medium", cwe="",
      title="block_on inside async context",
      desc="A future is driven with block_on.",
      rationale="Blocking on a runtime from within async code can deadlock the executor.",
      remediation="Await the future instead of blocking.",
      source="https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on",
      re=r'\bblock_on\s*\(',
      nc='let r = block_on(fut);',
      c='let r = fut.await;'),
    r("conc", id="rust:blocking-sleep-async", type="bug", qual="rel", sev="medium", cwe="",
      title="Blocking thread::sleep",
      desc="thread::sleep blocks the current OS thread.",
      rationale="A blocking sleep on an async executor stalls every task on that worker thread.",
      remediation="Use an async timer (tokio::time::sleep) in async code.",
      source="https://doc.rust-lang.org/std/thread/fn.sleep.html",
      re=r'\bthread::sleep\s*\(',
      nc='thread::sleep(Duration::from_secs(1));',
      c='tokio::time::sleep(Duration::from_secs(1)).await;'),
    # ---- inj (6 target) ----
    r("inj", id="rust:command-shell", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Command spawns a shell",
      desc="A process is launched via a shell interpreter.",
      rationale="Passing input to sh/bash/cmd allows shell metacharacter injection (CWE-78).",
      remediation="Invoke the target program directly with separate args, no shell.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'Command::new\(\s*"(sh|bash|cmd|powershell|zsh)"',
      nc='Command::new("sh").arg("-c").arg(input);',
      c='Command::new("ls").arg(dir);'),
    r("inj", id="rust:command-shell-flag", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="Command shell -c flag",
      desc="A command passes the shell -c flag.",
      rationale="The -c flag runs a shell command string, enabling injection if any part is attacker-controlled (CWE-78).",
      remediation="Run the program directly with argument vectors.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'\.arg\(\s*"-c"\s*\)',
      nc='cmd.arg("-c").arg(user_cmd);',
      c='cmd.arg("--version");'),
    r("inj", id="rust:sql-execute-format", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL built with format! at execute",
      desc="A SQL statement is executed from a format! string.",
      rationale="String-interpolated SQL is classic SQL injection (CWE-89).",
      remediation="Use parameterized queries with bound placeholders.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'(query|execute)\s*\(\s*&?format!\(',
      nc='conn.execute(&format!("SELECT * FROM t WHERE id={}", id), []);',
      c='conn.execute("SELECT * FROM t WHERE id=?1", params![id]);'),
    r("inj", id="rust:sql-format-let", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL string assembled with format!",
      desc="A SQL keyword string is assembled with format!.",
      rationale="Building a SQL statement by interpolation invites injection regardless of where it is later run (CWE-89).",
      remediation="Compose queries with bound parameters, not format!.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'let\s+\w+\s*=\s*format!\(\s*"[^"]*(SELECT|INSERT|UPDATE|DELETE)',
      nc='let q = format!("SELECT * FROM t WHERE u={}", u);',
      c='let q = "SELECT * FROM t WHERE u=?1";'),
    r("inj", id="rust:path-join-untrusted", type="vuln", qual="sec", sev="high", cwe="CWE-22", owasp="A01:2021",
      title="Path joined with untrusted input",
      desc="A base path is joined with an input-derived segment.",
      rationale="Joining unchecked input can traverse out of the intended directory (CWE-22).",
      remediation="Canonicalize and verify the result stays within the base directory.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'\.join\(\s*&?\w*(input|user|param|arg|req)\w*\s*\)',
      nc='let p = base.join(user_input);',
      c='let p = base.join("static.txt");'),
    r("inj", id="rust:deserialize-untrusted", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="Deserializing untrusted input",
      desc="Input-derived text is deserialized into a dynamic value.",
      rationale="Deserializing attacker-controlled data risks resource exhaustion or type-confusion (CWE-502).",
      remediation="Deserialize into a strict typed schema with size/time limits.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'serde_json::from_str\(\s*&?\w*(input|body|req|payload)',
      nc='let v: Value = serde_json::from_str(req_body)?;',
      c='let cfg: Config = serde_json::from_str(TRUSTED)?;'),
    # ---- crypto (4 target) ----
    r("crypto", id="rust:weak-hash-md5", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Weak hash MD5",
      desc="MD5 is used to hash data.",
      rationale="MD5 is collision-broken and unsuitable for security (CWE-327).",
      remediation="Use SHA-256 or stronger; use a KDF for passwords.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(md5::|Md5::new|Md5::digest)',
      nc='let d = md5::compute(data);',
      c='let d = Sha256::digest(data);'),
    r("crypto", id="rust:weak-hash-sha1", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Weak hash SHA-1",
      desc="SHA-1 is used to hash data.",
      rationale="SHA-1 is collision-broken and deprecated for security use (CWE-327).",
      remediation="Use SHA-256 or SHA-3.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(sha1::|Sha1::new|Sha1::digest)',
      nc='let h = Sha1::new();',
      c='let h = Sha256::new();'),
    r("crypto", id="rust:weak-cipher", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Weak cipher (DES/RC4/RC2)",
      desc="A broken symmetric cipher is instantiated.",
      rationale="DES, RC4 and RC2 are cryptographically broken (CWE-327).",
      remediation="Use an AEAD such as AES-GCM or ChaCha20-Poly1305.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(Des|Rc4|Rc2|TripleDes)\b::',
      nc='let c = Des::new(&key);',
      c='let c = Aes256Gcm::new(&key);'),
    r("crypto", id="rust:insecure-random-secret", type="hotspot", qual="sec", sev="medium", cwe="CWE-338", owasp="A02:2021",
      title="Non-CSPRNG for a secret",
      desc="A secret-looking value is generated from a non-cryptographic RNG.",
      rationale="thread_rng/rand::random are not guaranteed cryptographically secure for keys or tokens (CWE-338).",
      remediation="Use a CSPRNG such as OsRng.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\b(key|token|secret|nonce|salt|password)\w*[^;\n]*(thread_rng\(\)|rand::random)',
      nc='let secret = rand::random::<u64>();',
      c='let secret = OsRng.next_u64();'),
    r("crypto", id="rust:hardcoded-key", type="hotspot", qual="sec", sev="high", cwe="CWE-321", owasp="A02:2021",
      title="Hardcoded cryptographic key",
      desc="A key/IV/nonce is assigned a literal byte string.",
      rationale="Hardcoded key material is extractable from the binary and cannot be rotated (CWE-321).",
      remediation="Load key material from a secret store or environment at runtime.",
      source="https://cwe.mitre.org/data/definitions/321.html",
      re=r'\b(KEY|SECRET|IV|NONCE|PASSWORD|SALT)\b[^=\n]*=\s*b?"[^"]',
      nc='const KEY: &[u8] = b"0123456789abcdef";',
      c='let key = std::env::var("APP_KEY")?;'),
    # ---- hotspot (6 target) ----
    r("hotspot", id="rust:unsafe-block", type="hotspot", qual="sec", sev="medium", cwe="CWE-758",
      title="unsafe block",
      desc="An unsafe block bypasses compiler guarantees.",
      rationale="unsafe code can violate memory safety and needs an explicit safety justification (CWE-758).",
      remediation="Add a // SAFETY: rationale and minimize the unsafe scope.",
      source="https://doc.rust-lang.org/nomicon/meet-safe-and-unsafe.html",
      re=r'\bunsafe\s*\{',
      nc='let v = unsafe { transmute(x) };',
      c='let v = safe_convert(x);'),
    r("hotspot", id="rust:transmute", type="hotspot", qual="sec", sev="high", cwe="CWE-704",
      title="mem::transmute",
      desc="transmute reinterprets one type's bits as another.",
      rationale="transmute between incompatible layouts is undefined behavior (CWE-704).",
      remediation="Use safe conversions (from_bits/to_bits, From/TryFrom).",
      source="https://doc.rust-lang.org/std/mem/fn.transmute.html",
      re=r'\btransmute\s*(::<|\()',
      nc='let y: u64 = unsafe { transmute(x) };',
      c='let y = x.to_bits();'),
    r("hotspot", id="rust:ptr-offset", type="hotspot", qual="sec", sev="high", cwe="CWE-823",
      title="Raw pointer offset()",
      desc="A raw pointer is advanced with offset().",
      rationale="offset() is UB if the result leaves the allocation (CWE-823).",
      remediation="Use wrapping_add or bounds-checked slice access.",
      source="https://doc.rust-lang.org/std/primitive.pointer.html#method.offset",
      re=r'\.offset\(',
      nc='let q = unsafe { p.offset(4) };',
      c='let q = p.wrapping_add(4);'),
    r("hotspot", id="rust:inline-asm", type="hotspot", qual="sec", sev="medium", cwe="CWE-758",
      title="Inline assembly",
      desc="An asm! block emits raw assembly.",
      rationale="Inline assembly sidesteps every compiler check and needs careful review (CWE-758).",
      remediation="Prefer intrinsics or safe abstractions; justify any asm!.",
      source="https://doc.rust-lang.org/reference/inline-assembly.html",
      re=r'\basm!\s*\(',
      nc='unsafe { asm!("nop"); }',
      c='let x = a.wrapping_add(b);'),
    r("hotspot", id="rust:extern-c-block", type="hotspot", qual="sec", sev="medium", cwe="CWE-111",
      title="extern \"C\" FFI block",
      desc="Foreign functions are declared in an extern \"C\" block.",
      rationale="FFI declarations are unchecked contracts; a wrong signature is undefined behavior (CWE-111).",
      remediation="Verify signatures against the C headers and wrap them in a safe API.",
      source="https://doc.rust-lang.org/reference/items/external-blocks.html",
      re=r'\bextern\s+"C"\s*\{',
      nc='extern "C" { fn strlen(s: *const u8) -> usize; }',
      c='fn strlen(s: &str) -> usize { s.len() }'),
    r("hotspot", id="rust:from-utf8-unchecked", type="hotspot", qual="sec", sev="high", cwe="CWE-20",
      title="str::from_utf8_unchecked",
      desc="Bytes are treated as UTF-8 without validation.",
      rationale="Constructing a str from invalid UTF-8 is undefined behavior (CWE-20).",
      remediation="Use str::from_utf8 and handle the error.",
      source="https://doc.rust-lang.org/std/str/fn.from_utf8_unchecked.html",
      re=r'\bfrom_utf8_unchecked\(',
      nc='let s = unsafe { str::from_utf8_unchecked(bytes) };',
      c='let s = str::from_utf8(bytes)?;'),
    r("hotspot", id="rust:copy-nonoverlapping", type="hotspot", qual="sec", sev="high", cwe="CWE-787",
      title="ptr::copy_nonoverlapping",
      desc="Raw memory is copied with copy_nonoverlapping.",
      rationale="Wrong length or overlapping regions cause out-of-bounds writes (CWE-787).",
      remediation="Use copy_from_slice on slices where possible.",
      source="https://doc.rust-lang.org/std/ptr/fn.copy_nonoverlapping.html",
      re=r'\bcopy_nonoverlapping\(',
      nc='unsafe { copy_nonoverlapping(src, dst, n); }',
      c='dst.copy_from_slice(src);'),
]
