# C language-pack rule specs, batch 2 (#198). Clean-room, line-detectable — more banned funcs,
# permission/temp-file weaknesses, CERT-C bug patterns, weak-RNG variants. Concept origins cited.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "c")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "c"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="c-fscanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="fscanf(\"%s\") without a field width",
      desc="An fscanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token into the buffer, overflowing it (CWE-120).",
      remediation="Add a field width matching the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bfscanf\s*\([^)]*"[^"]*%s',
      nc='fscanf(f, "%s", buf);',
      c='fscanf(f, "%63s", buf);'),
    r(id="c-wcscpy", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of wcscpy()",
      desc="wcscpy() copies a wide string with no destination bound.",
      rationale="Like strcpy, wcscpy overflows when the source exceeds the destination (CWE-120).",
      remediation="Use wcslcpy()/swprintf() with an explicit size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bwcscpy\s*\(',
      nc='wcscpy(dst, src);',
      c='wcslcpy(dst, src, len);'),
    r(id="c-wcscat", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of wcscat()",
      desc="wcscat() appends a wide string with no destination bound.",
      rationale="Like strcat, wcscat overflows when the result exceeds the buffer (CWE-120).",
      remediation="Use wcslcat() with an explicit size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bwcscat\s*\(',
      nc='wcscat(dst, src);',
      c='wcslcat(dst, src, len);'),
    r(id="c-crypt", type="hotspot", qual="sec", sev="medium", cwe="CWE-327",
      title="Use of crypt()",
      desc="crypt() defaults to weak DES-based hashing on many platforms.",
      rationale="Legacy crypt output is fast to brute-force and unsuitable for password storage (CWE-327); review the algorithm/salt.",
      remediation="Use a modern KDF (Argon2/bcrypt/scrypt).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bcrypt\s*\(',
      nc='char *h = crypt(pw, salt);',
      c='char *h = argon2_hash(pw, salt);'),
    r(id="c-getpass", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of getpass()",
      desc="getpass() is obsolete and has fixed-size, non-reentrant behavior.",
      rationale="It was removed from POSIX and mishandles long input and terminals (CWE-676).",
      remediation="Read the password via termios with echo disabled.",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bgetpass\s*\(',
      nc='char *p = getpass("Password: ");',
      c='read_password(buf, sizeof(buf));'),
    r(id="c-cuserid", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of cuserid()",
      desc="cuserid() is obsolete and uses a static buffer.",
      rationale="It is not reentrant and was removed from POSIX (CWE-676).",
      remediation="Use getpwuid(getuid()).",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bcuserid\s*\(',
      nc='cuserid(name);',
      c='struct passwd *pw = getpwuid(getuid());'),
    r(id="c-bcopy", type="smell", qual="maint", sev="info", cwe="",
      title="Use of bcopy()",
      desc="bcopy() is a legacy BSD function superseded by memmove().",
      rationale="bcopy is non-standard and deprecated; memmove is portable and clearer.",
      remediation="Use memmove().",
      source="https://man7.org/linux/man-pages/man3/bcopy.3.html",
      re=r'\bbcopy\s*\(',
      nc='bcopy(src, dst, n);',
      c='memmove(dst, src, n);'),
    r(id="c-bzero", type="smell", qual="maint", sev="info", cwe="",
      title="Use of bzero()",
      desc="bzero() is a legacy BSD function superseded by memset().",
      rationale="bzero is non-standard and deprecated; memset is portable.",
      remediation="Use memset() (or explicit_bzero for secrets).",
      source="https://man7.org/linux/man-pages/man3/bzero.3.html",
      re=r'\bbzero\s*\(',
      nc='bzero(buf, sizeof(buf));',
      c='memset(buf, 0, sizeof(buf));'),
    r(id="c-bcmp", type="smell", qual="maint", sev="info", cwe="",
      title="Use of bcmp()",
      desc="bcmp() is a legacy BSD function superseded by memcmp().",
      rationale="bcmp is non-standard and deprecated; memcmp is portable.",
      remediation="Use memcmp().",
      source="https://man7.org/linux/man-pages/man3/bcmp.3.html",
      re=r'\bbcmp\s*\(',
      nc='if (bcmp(a, b, n)) return -1;',
      c='if (memcmp(a, b, n)) return -1;'),
    r(id="c-putenv", type="bug", qual="rel", sev="low", cwe="CWE-686",
      title="Use of putenv()",
      desc="putenv() stores the passed pointer rather than copying it.",
      rationale="If the buffer is local or later modified, the environment holds a dangling/mutated string (CWE-686).",
      remediation="Use setenv(), which copies the value.",
      source="https://cwe.mitre.org/data/definitions/686.html",
      re=r'\bputenv\s*\(',
      nc='putenv(buf);',
      c='setenv("KEY", "value", 1);'),
    r(id="c-signal", type="smell", qual="maint", sev="low", cwe="",
      title="Use of signal()",
      desc="signal() has implementation-defined semantics and races.",
      rationale="Its behavior varies across systems and it lacks the control needed for correct handlers; sigaction is portable.",
      remediation="Use sigaction().",
      source="https://wiki.sei.cmu.edu/confluence/display/c/SIG01-C.+Understand+implementation-specific+details+regarding+signal+handler+persistence",
      re=r'\bsignal\s*\(',
      nc='signal(SIGINT, handler);',
      c='sigaction(SIGINT, &sa, NULL);'),
    r(id="c-assignment-in-if", type="bug", qual="rel", sev="medium", cwe="CWE-481",
      title="Assignment in an if condition",
      desc="An if condition contains a single = (assignment) rather than ==.",
      rationale="An assignment in a condition is usually a typo for == and silently changes state (CWE-481).",
      remediation="Use == for comparison, or wrap an intentional assignment in extra parentheses.",
      source="https://cwe.mitre.org/data/definitions/481.html",
      re=r'\bif\s*\(\s*\w+\s*=\s*[^=]',
      nc='if (x = compute()) return;',
      c='if (x == compute()) return;'),
    r(id="c-void-main", type="smell", qual="maint", sev="low", cwe="",
      title="void main()",
      desc="main is declared to return void.",
      rationale="The standard requires main to return int; void main is non-conforming.",
      remediation="Declare int main(void) and return a status code.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/MSC00-C.+Compile+cleanly+at+high+warning+levels",
      re=r'\bvoid\s+main\s*\(',
      nc='void main(void) {',
      c='int main(void) {'),
    r(id="c-float-equality", type="bug", qual="rel", sev="low", cwe="CWE-1077",
      title="Floating-point equality against a literal",
      desc="A float/double is compared for exact equality with a decimal literal.",
      rationale="Binary floating-point cannot represent most decimals exactly, so == is unreliable (CWE-1077).",
      remediation="Compare within a tolerance (fabs(a - b) < epsilon).",
      source="https://cwe.mitre.org/data/definitions/1077.html",
      re=r'==\s*\d+\.\d+',
      nc='if (ratio == 0.5) apply();',
      c='if (fabs(ratio - 0.5) < EPS) apply();'),
    r(id="c-divide-by-zero-literal", type="bug", qual="rel", sev="high", cwe="CWE-369",
      title="Division by the literal 0",
      desc="A value is divided by the literal 0.",
      rationale="Integer division by zero is undefined behavior and typically crashes (CWE-369).",
      remediation="Guard the divisor, or fix the constant.",
      source="https://cwe.mitre.org/data/definitions/369.html",
      re=r'[^/*]/\s*0\s*[;)]',
      nc='int q = n / 0;',
      c='int q = n / d;'),
    r(id="c-malloc-cast", type="smell", qual="maint", sev="info", cwe="",
      title="Cast of malloc() result",
      desc="The result of malloc is cast to a pointer type.",
      rationale="In C the cast is unnecessary and can hide a missing <stdlib.h> declaration.",
      remediation="Remove the cast.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/MEM02-C.+Immediately+cast+the+result+of+a+memory+allocation+function+call+into+a+pointer+to+the+allocated+type",
      re=r'\(\s*\w[\w ]*\*\s*\)\s*malloc\s*\(',
      nc='int *p = (int *)malloc(n * sizeof(int));',
      c='int *p = malloc(n * sizeof(int));'),
    r(id="c-assert-side-effect", type="bug", qual="rel", sev="medium", cwe="CWE-617",
      title="Side effect inside assert()",
      desc="An assert expression contains ++ or -- (a side effect).",
      rationale="asserts are compiled out under NDEBUG, so the side effect vanishes in release builds (CWE-617).",
      remediation="Move the side effect out of the assert.",
      source="https://cwe.mitre.org/data/definitions/617.html",
      re=r'\bassert\s*\([^)]*(\+\+|--)',
      nc='assert(i++ < n);',
      c='assert(i < n); i++;'),
    r(id="c-fflush-stdin", type="bug", qual="rel", sev="medium", cwe="CWE-758",
      title="fflush() on an input stream",
      desc="fflush is called on stdin (an input stream).",
      rationale="fflush on an input stream is undefined behavior in standard C (CWE-758).",
      remediation="Consume the unwanted input with getchar() in a loop.",
      source="https://cwe.mitre.org/data/definitions/758.html",
      re=r'fflush\s*\(\s*stdin\s*\)',
      nc='fflush(stdin);',
      c='int c; while ((c = getchar()) != \'\\n\' && c != EOF);'),
    r(id="c-feof-loop", type="bug", qual="rel", sev="medium", cwe="CWE-241",
      title="feof() used as a loop condition",
      desc="A read loop is controlled by !feof().",
      rationale="feof only becomes true after a failed read, so the loop processes the last item twice or reads uninitialized data (CWE-241).",
      remediation="Loop on the return value of the read function itself.",
      source="https://cwe.mitre.org/data/definitions/241.html",
      re=r'while\s*\(\s*!\s*feof\s*\(',
      nc='while (!feof(f)) { fgets(line, n, f); process(line); }',
      c='while (fgets(line, n, f)) { process(line); }'),
    r(id="c-strlen-in-loop", type="smell", qual="maint", sev="low", cwe="",
      title="strlen() in a loop condition",
      desc="strlen is called in the loop condition, recomputing the length each iteration.",
      rationale="Re-scanning the string every iteration makes the loop O(n^2).",
      remediation="Compute the length once before the loop.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/",
      re=r'for\s*\([^;]*;[^;]*\bstrlen\s*\(',
      nc='for (i = 0; i < strlen(s); i++) upper(s, i);',
      c='for (i = 0, len = strlen(s); i < len; i++) upper(s, i);'),
    r(id="c-open-creat-no-mode", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="open() with O_CREAT but no mode argument",
      desc="A file is created with open()+O_CREAT but no explicit mode.",
      rationale="Without a mode the new file's permissions are indeterminate and may be world-accessible (CWE-732).",
      remediation="Pass an explicit restrictive mode (e.g. 0600).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bopen\s*\([^,]*,[^,)]*O_CREAT[^,)]*\)',
      nc='int fd = open(path, O_CREAT | O_WRONLY);',
      c='int fd = open(path, O_CREAT | O_WRONLY, 0600);'),
    r(id="c-chmod-777", type="vuln", qual="sec", sev="high", cwe="CWE-732",
      title="chmod() to 0777",
      desc="A file is made world-readable/writable/executable.",
      rationale="Mode 0777 lets any local user modify the file (CWE-732).",
      remediation="Grant the least privilege required (e.g. 0600/0700).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bchmod\s*\([^,]*,\s*0777\b',
      nc='chmod(path, 0777);',
      c='chmod(path, 0600);'),
    r(id="c-mkdir-777", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="mkdir() with mode 0777",
      desc="A directory is created world-writable.",
      rationale="A world-writable directory allows any local user to plant or replace files (CWE-732).",
      remediation="Use a restrictive mode (e.g. 0700).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bmkdir\s*\([^,]*,\s*0777\b',
      nc='mkdir(dir, 0777);',
      c='mkdir(dir, 0700);'),
    r(id="c-umask-zero", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="umask(0)",
      desc="The process file-mode creation mask is cleared.",
      rationale="umask(0) lets newly created files take fully permissive modes (CWE-732).",
      remediation="Set a restrictive umask (e.g. 077).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bumask\s*\(\s*0\s*\)',
      nc='umask(0);',
      c='umask(077);'),
    r(id="c-access-toctou", type="hotspot", qual="sec", sev="medium", cwe="CWE-367",
      title="access() permission check (TOCTOU)",
      desc="access() checks a path that is then opened separately.",
      rationale="The file can change between the access check and the open, enabling a TOCTOU race (CWE-367).",
      remediation="Open the file first and check permissions on the descriptor (fstat), or drop privileges.",
      source="https://cwe.mitre.org/data/definitions/367.html",
      re=r'\baccess\s*\(',
      nc='if (access(path, W_OK) == 0) fp = fopen(path, "w");',
      c='fp = fopen(path, "w"); if (fp) write_data(fp);'),
    r(id="c-empty-if-semicolon", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="if statement with an empty body (stray semicolon)",
      desc="An if is immediately terminated by a semicolon.",
      rationale="The stray ; makes the if a no-op and runs the following statement unconditionally (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*if\s*\([\w\s!=<>&|.]+\)\s*;\s*$',
      nc='if (ready);',
      c='if (ready) start();'),
    r(id="c-format-percent-n", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="%n conversion in a format string",
      desc="A printf-family format string contains the %n conversion.",
      rationale="%n writes the number of bytes written to a pointer argument, a classic write primitive in format-string attacks (CWE-134).",
      remediation="Remove %n; never use it with untrusted format strings.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\b(printf|fprintf|sprintf|snprintf|syslog)\s*\([^;]*"[^"]*%n',
      nc='fprintf(log, "wrote %n bytes", &count);',
      c='fprintf(log, "wrote %d bytes", count);'),
    r(id="c-rand-r", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="Use of rand_r() for security-sensitive values",
      desc="rand_r() is a non-cryptographic pseudo-random generator.",
      rationale="Its short state makes output predictable; unsuitable for tokens/keys (CWE-338).",
      remediation="Use a CSPRNG for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\brand_r\s*\(',
      nc='unsigned v = rand_r(&seed);',
      c='getrandom(&v, sizeof(v), 0);'),
    r(id="c-random", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="Use of random() for security-sensitive values",
      desc="random() is a non-cryptographic pseudo-random generator.",
      rationale="Its output is predictable and unsuitable for security values (CWE-338).",
      remediation="Use a CSPRNG for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\brandom\s*\(\s*\)',
      nc='long v = random();',
      c='getrandom(&v, sizeof(v), 0);'),
    r(id="c-drand48", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="Use of the drand48() family for security values",
      desc="The drand48/lrand48/mrand48 family are non-cryptographic generators.",
      rationale="Their linear-congruential output is predictable and unsuitable for security values (CWE-338).",
      remediation="Use a CSPRNG for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\b(drand48|lrand48|mrand48|nrand48|jrand48)\s*\(',
      nc='double v = drand48();',
      c='getrandom(&v, sizeof(v), 0);'),
]
