# C# language-pack rule specs, batch 6 (#189). Clean-room, line-detectable — insecure deserialization
# formatters, TLS/cert-trust, ASP.NET WebForms, StyleCop-family braces/naming, async deadlock, threading.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-cookie-samesite-none", type="vuln", qual="sec", sev="medium", cwe="CWE-1275", owasp="A01:2021",
      title="Cookie SameSite set to None",
      desc="A cookie is configured with SameSiteMode.None, so it is sent on cross-site requests.",
      rationale="SameSite=None disables the browser CSRF defense; use Lax or Strict unless the cookie is genuinely cross-site and Secure.",
      remediation="Use SameSiteMode.Lax or Strict.",
      source="https://cwe.mitre.org/data/definitions/1275.html",
      re=r'SameSite\s*=\s*SameSiteMode\.None\b',
      nc='opt.SameSite = SameSiteMode.None;',
      c='opt.SameSite = SameSiteMode.Lax;'),
    r(id="cs-x509-revocation-nocheck", type="vuln", qual="sec", sev="medium", cwe="CWE-299", owasp="A07:2021",
      title="X.509 revocation checking disabled",
      desc="Certificate chain validation is set to X509RevocationMode.NoCheck.",
      rationale="Skipping revocation lets a revoked/compromised certificate be accepted (CWE-299).",
      remediation="Use X509RevocationMode.Online (or Offline) revocation checking.",
      source="https://cwe.mitre.org/data/definitions/299.html",
      re=r'RevocationMode\s*=\s*X509RevocationMode\.NoCheck\b',
      nc='chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;',
      c='chain.ChainPolicy.RevocationMode = X509RevocationMode.Online;'),
    r(id="cs-hardcoded-symmetric-key", type="vuln", qual="sec", sev="high", cwe="CWE-798", owasp="A02:2021",
      title="Symmetric key from a hard-coded literal",
      desc="A SymmetricSecurityKey is built from a hard-coded string literal.",
      rationale="A signing/encryption key embedded in source is exposed to anyone with the binary (CWE-798).",
      remediation="Load the key from a secret store / configuration, not source.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'SymmetricSecurityKey\(\s*Encoding\.\w+\.GetBytes\(\s*"',
      nc='var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("s3cret-signing-key"));',
      c='var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]));'),
    r(id="cs-losformatter", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="LosFormatter deserialization",
      desc="LosFormatter deserializes arbitrary types and can execute attacker gadgets.",
      rationale="LosFormatter is an insecure binary deserializer vulnerable to gadget-chain RCE (CWE-502).",
      remediation="Use a safe serializer (System.Text.Json) with known types.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+LosFormatter\b',
      nc='var o = new LosFormatter().Deserialize(stream);',
      c='var o = JsonSerializer.Deserialize<Dto>(json);'),
    r(id="cs-netdatacontractserializer", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="NetDataContractSerializer deserialization",
      desc="NetDataContractSerializer embeds .NET type info and deserializes arbitrary types.",
      rationale="NetDataContractSerializer is insecure against untrusted input (type-confusion gadget RCE, CWE-502).",
      remediation="Use DataContractSerializer with a fixed known-type list, or System.Text.Json.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+NetDataContractSerializer\b',
      nc='var o = new NetDataContractSerializer().ReadObject(stream);',
      c='var o = JsonSerializer.Deserialize<Dto>(json);'),
    r(id="cs-soapformatter", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="SoapFormatter deserialization",
      desc="SoapFormatter is an obsolete binary deserializer that accepts arbitrary types.",
      rationale="SoapFormatter is insecure against untrusted input and enables gadget-chain RCE (CWE-502).",
      remediation="Use a safe serializer with known types.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+SoapFormatter\b',
      nc='var o = new SoapFormatter().Deserialize(stream);',
      c='var o = JsonSerializer.Deserialize<Dto>(json);'),
    r(id="cs-objectstateformatter", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="ObjectStateFormatter deserialization",
      desc="ObjectStateFormatter deserializes arbitrary object graphs (used by ViewState).",
      rationale="ObjectStateFormatter over untrusted data is exploitable for gadget-chain RCE (CWE-502).",
      remediation="Never deserialize untrusted data with ObjectStateFormatter; sign/validate ViewState.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+ObjectStateFormatter\b',
      nc='var o = new ObjectStateFormatter().Deserialize(input);',
      c='var o = JsonSerializer.Deserialize<Dto>(json);'),
    r(id="cs-xpath-injection", type="vuln", qual="sec", sev="high", cwe="CWE-643", owasp="A03:2021",
      title="XPath query built by concatenation",
      desc="An XPath expression passed to SelectNodes/SelectSingleNode is concatenated from a variable.",
      rationale="Concatenating input into XPath allows XPath injection to bypass access controls (CWE-643).",
      remediation="Use XPath variables (XsltArgumentList / XPathExpression with a variable resolver).",
      source="https://cwe.mitre.org/data/definitions/643.html",
      re=r'\.Select(Nodes|SingleNode)\(\s*"[^"]*"\s*\+',
      nc='doc.SelectSingleNode("//user[name=\'" + name + "\']");',
      c='doc.SelectSingleNode(BuildParameterizedQuery(), resolver);'),
    r(id="cs-servicepoint-cert-bypass", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="Global TLS certificate validation callback overridden",
      desc="ServicePointManager.ServerCertificateValidationCallback is assigned, overriding trust for the whole process.",
      rationale="A global validation callback (often returning true) disables certificate checks process-wide (CWE-295).",
      remediation="Do not override global cert validation; if pinning, validate the specific cert per connection.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'ServicePointManager\.ServerCertificateValidationCallback\s*\+?=',
      nc='ServicePointManager.ServerCertificateValidationCallback = (s, c, ch, e) => true;',
      c='// validate the certificate against a pinned thumbprint per request'),
    r(id="cs-viewstate-mac-disabled", type="vuln", qual="sec", sev="high", cwe="CWE-807", owasp="A08:2021",
      title="ViewState MAC disabled",
      desc="EnableViewStateMac is set to false, removing the integrity check on ViewState.",
      rationale="Without the MAC, ViewState can be tampered with and (with ObjectStateFormatter) exploited for RCE (CWE-807).",
      remediation="Leave EnableViewStateMac enabled (the default).",
      source="https://cwe.mitre.org/data/definitions/807.html",
      re=r'EnableViewStateMac\s*=\s*false\b',
      nc='this.EnableViewStateMac = false;',
      c='// leave EnableViewStateMac at its secure default'),
    r(id="cs-eventvalidation-disabled", type="vuln", qual="sec", sev="medium", cwe="CWE-807", owasp="A04:2021",
      title="ASP.NET event validation disabled",
      desc="EnableEventValidation is set to false on a WebForms page.",
      rationale="Disabling event validation lets clients post values/events the server never rendered (CWE-807).",
      remediation="Leave EnableEventValidation enabled.",
      source="https://cwe.mitre.org/data/definitions/807.html",
      re=r'EnableEventValidation\s*=\s*false\b',
      nc='this.EnableEventValidation = false;',
      c='// leave EnableEventValidation at its secure default'),
    r(id="cs-smtpclient-obsolete", type="smell", qual="maint", sev="info", cwe="",
      title="System.Net.Mail.SmtpClient (superseded)",
      desc="SmtpClient is used; Microsoft recommends a maintained library for new code.",
      rationale="SmtpClient does not support modern protocols well and is documented as not recommended for new development.",
      remediation="Use a maintained mail library (e.g. MailKit).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient",
      re=r'\bnew\s+SmtpClient\s*\(',
      nc='using var client = new SmtpClient(host);',
      c='using var client = new MailKit.Net.Smtp.SmtpClient();'),
    r(id="cs-for-no-braces", type="smell", qual="maint", sev="low", cwe="",
      title="for statement without braces",
      desc="A for loop's body is a single statement without braces.",
      rationale="Brace-less loops are error-prone when a second statement is later added.",
      remediation="Always use braces for loop bodies.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011",
      re=r'^\s*for\s*\(.*\)\s*[A-Za-z_][^{]*;\s*$',
      nc='for (int i = 0; i < n; i++) sum += i;',
      c='for (int i = 0; i < n; i++) { sum += i; }'),
    r(id="cs-while-no-braces", type="smell", qual="maint", sev="low", cwe="",
      title="while statement without braces",
      desc="A while loop's body is a single statement without braces (and not an empty ;).",
      rationale="Brace-less loops are error-prone when a second statement is later added.",
      remediation="Always use braces for loop bodies.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011",
      re=r'^\s*while\s*\(.*\)\s*[A-Za-z_][^{;]*;\s*$',
      nc='while (reader.Read()) count++;',
      c='while (reader.Read()) { count++; }'),
    r(id="cs-else-no-braces", type="smell", qual="maint", sev="low", cwe="",
      title="else without braces",
      desc="An else clause's body is a single statement without braces (and not else if).",
      rationale="Brace-less else clauses are error-prone when a second statement is later added.",
      remediation="Always use braces for else bodies.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0011",
      re=r'^\s*else\s+(?:return|throw|break|continue|[A-Za-z_][\w.]*\s*[=(])[^{]*;\s*$',
      nc='else return -1;',
      c='else { return -1; }'),
    r(id="cs-interface-naming", type="smell", qual="maint", sev="low", cwe="",
      title="Interface name not prefixed with I",
      desc="An interface is declared with a name that does not start with the conventional 'I' prefix.",
      rationale="The .NET convention (CA1715) is to prefix interface names with I for readability.",
      remediation="Prefix the interface name with I.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1715",
      re=r'\binterface\s+[A-HJ-Z]\w',
      nc='public interface Repository { }',
      c='public interface IRepository { }'),
    r(id="cs-fire-and-forget-task", type="smell", qual="maint", sev="medium", cwe="",
      title="Task discarded (fire-and-forget)",
      desc="An async call's Task is assigned to a discard, so failures go unobserved.",
      rationale="Discarding a Task swallows its exceptions and loses completion tracking; await it or handle it explicitly.",
      remediation="Await the task, or wrap it with explicit error handling.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'^\s*_\s*=\s*\w[\w.]*Async\(',
      nc='_ = SendEmailAsync(user);',
      c='await SendEmailAsync(user);'),
    r(id="cs-volatile-64bit", type="bug", qual="rel", sev="medium", cwe="CWE-662",
      title="volatile on a 64-bit field",
      desc="A long/ulong/double field is declared volatile.",
      rationale="volatile does not guarantee atomic reads/writes of 64-bit values on 32-bit runtimes; use Interlocked (CWE-662).",
      remediation="Use Interlocked (or a lock) for 64-bit atomicity.",
      source="https://cwe.mitre.org/data/definitions/662.html",
      re=r'\bvolatile\s+(long|ulong|double)\b',
      nc='private volatile long _counter;',
      c='private long _counter; // updated via Interlocked'),
    r(id="cs-do-while-false", type="smell", qual="maint", sev="low", cwe="",
      title="do/while(false) executes once",
      desc="A do-while loop with a constant-false condition runs exactly once.",
      rationale="do/while(false) is usually a disguised goto/break pattern; restructure for clarity.",
      remediation="Replace with straight-line code or explicit control flow.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements",
      re=r'\}\s*while\s*\(\s*false\s*\)',
      nc='do { Step(); } while (false);',
      c='Step();'),
    r(id="cs-catch-nullreference", type="smell", qual="maint", sev="medium", cwe="CWE-395",
      title="Catching NullReferenceException",
      desc="Code catches NullReferenceException instead of preventing the null dereference.",
      rationale="An NRE indicates a bug; catching it masks the defect rather than fixing the missing null check (CWE-395).",
      remediation="Add the missing null check; do not catch NullReferenceException.",
      source="https://cwe.mitre.org/data/definitions/395.html",
      re=r'\bcatch\s*\(\s*NullReferenceException\b',
      nc='try { Use(x); } catch (NullReferenceException) { }',
      c='if (x != null) { Use(x); }'),
    r(id="cs-catch-stackoverflow", type="bug", qual="rel", sev="medium", cwe="",
      title="Catching StackOverflowException",
      desc="Code attempts to catch StackOverflowException.",
      rationale="Since .NET 2.0 a StackOverflowException cannot be caught and terminates the process; the catch is dead code hiding a recursion bug.",
      remediation="Fix the unbounded recursion instead of catching.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.stackoverflowexception",
      re=r'\bcatch\s*\(\s*StackOverflowException\b',
      nc='try { Recurse(); } catch (StackOverflowException) { }',
      c='// add a depth guard to bound the recursion'),
    r(id="cs-catch-outofmemory", type="smell", qual="maint", sev="low", cwe="",
      title="Catching OutOfMemoryException",
      desc="Code catches OutOfMemoryException in ordinary logic.",
      rationale="Recovering from OOM is unreliable and usually masks an allocation problem; let it propagate.",
      remediation="Fix the allocation (stream/limit sizes) instead of catching OOM.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.outofmemoryexception",
      re=r'\bcatch\s*\(\s*OutOfMemoryException\b',
      nc='try { Load(all); } catch (OutOfMemoryException) { }',
      c='foreach (var chunk in Stream(all)) Load(chunk);'),
    r(id="cs-gc-waitforpendingfinalizers", type="smell", qual="maint", sev="low", cwe="",
      title="GC.WaitForPendingFinalizers()",
      desc="Code forces the finalizer thread to drain, usually to work around a resource leak.",
      rationale="Blocking on finalizers is a code smell for missing deterministic disposal (IDisposable/using).",
      remediation="Dispose resources deterministically with using; remove the GC call.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.gc.waitforpendingfinalizers",
      re=r'GC\.WaitForPendingFinalizers\(\)',
      nc='GC.Collect(); GC.WaitForPendingFinalizers();',
      c='using var handle = Open();'),
    r(id="cs-thread-priority", type="smell", qual="maint", sev="low", cwe="",
      title="Thread priority set",
      desc="A thread's Priority is explicitly set.",
      rationale="Manual thread priorities rarely behave as intended across OS schedulers and can starve other work.",
      remediation="Rely on the default scheduling; redesign rather than tuning priority.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.priority",
      re=r'\.Priority\s*=\s*ThreadPriority\.',
      nc='worker.Priority = ThreadPriority.Highest;',
      c='// keep default scheduling priority'),
    r(id="cs-getawaiter-getresult", type="bug", qual="rel", sev="high", cwe="CWE-833",
      title="Blocking on async via GetAwaiter().GetResult()",
      desc="An async result is obtained synchronously with GetAwaiter().GetResult().",
      rationale="Blocking on async work can deadlock under a synchronization context and wastes a thread (CWE-833).",
      remediation="Make the caller async and await the task.",
      source="https://cwe.mitre.org/data/definitions/833.html",
      re=r'\.GetAwaiter\(\)\.GetResult\(\)',
      nc='var data = FetchAsync().GetAwaiter().GetResult();',
      c='var data = await FetchAsync();'),
    r(id="cs-ef-tolist-then-where", type="smell", qual="maint", sev="medium", cwe="",
      title="Client-side filter after ToList()",
      desc="A query is materialized with ToList() and then filtered with Where, moving the filter off the database.",
      rationale="Filtering after ToList pulls the whole table into memory; apply Where before materializing.",
      remediation="Filter with Where before calling ToList().",
      source="https://learn.microsoft.com/en-us/ef/core/querying/",
      re=r'\.ToList\(\)\s*\.Where\(',
      nc='var open = ctx.Orders.ToList().Where(o => o.IsOpen);',
      c='var open = ctx.Orders.Where(o => o.IsOpen).ToList();'),
    r(id="cs-catch-when-true", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant catch filter when(true)",
      desc="A catch clause has an exception filter that is always true.",
      rationale="when(true) is a no-op filter; remove it.",
      remediation="Drop the redundant when(true) filter.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when",
      re=r'\bcatch\b[^\n]*\bwhen\s*\(\s*true\s*\)',
      nc='catch (Exception ex) when (true) { Log(ex); }',
      c='catch (Exception ex) { Log(ex); }'),
    r(id="cs-lock-empty-body", type="smell", qual="maint", sev="low", cwe="",
      title="Empty lock body",
      desc="A lock statement guards an empty block.",
      rationale="Locking with no protected work is dead synchronization or a leftover; remove it.",
      remediation="Remove the empty lock, or add the intended critical section.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock",
      re=r'\block\s*\([^)]*\)\s*\{\s*\}',
      nc='lock (_sync) { }',
      c='lock (_sync) { _cache.Clear(); }'),
    r(id="cs-append-single-char-string", type="smell", qual="maint", sev="info", cwe="",
      title="StringBuilder.Append with a single-character string",
      desc="StringBuilder.Append is called with a one-character string literal.",
      rationale="Appending a char literal avoids a string allocation and the length scan.",
      remediation="Use a char literal: Append('x').",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append",
      re=r'\.Append\(\s*"[^"\\]"\s*\)',
      nc='sb.Append(",");',
      c="sb.Append(',');"),
]
