# Rust language-pack rule specs — `bugs` family (#197). Clean-room, line-detectable correctness
# rules mirroring Clippy's correctness/suspicious categories (our own regexes; concept origins cited).
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "rust")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "rust", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r("bugs", id="rust:unwrap-used", type="bug", qual="rel", sev="medium", cwe="CWE-248",
      title="unwrap() on a Result/Option",
      desc="A Result or Option is unwrapped, panicking on Err/None.",
      rationale="unwrap() turns a recoverable error into a panic that aborts the thread; library code should propagate instead (Clippy unwrap_used).",
      remediation="Propagate with the ? operator or handle the None/Err arm explicitly.",
      source="https://rust-lang.github.io/rust-clippy/master/#unwrap_used",
      re=r'\.unwrap\(\)',
      nc='let v = parse(s).unwrap();',
      c='let v = parse(s)?;'),
    r("bugs", id="rust:expect-used", type="bug", qual="rel", sev="medium", cwe="CWE-248",
      title="expect() on a Result/Option",
      desc="A Result or Option is unwrapped with expect(), panicking on Err/None.",
      rationale="expect() panics on Err/None just like unwrap(); the message does not make the abort recoverable (Clippy expect_used).",
      remediation="Propagate with ? or match the Err/None arm.",
      source="https://rust-lang.github.io/rust-clippy/master/#expect_used",
      re=r'\.expect\(',
      nc='let v = parse(s).expect("bad input");',
      c='let v = parse(s)?;'),
    r("bugs", id="rust:panic-macro", type="smell", qual="maint", sev="medium", cwe="",
      title="panic! in library code",
      desc="A panic! macro aborts execution instead of returning an error.",
      rationale="panic! unwinds the thread and is not part of a function's contract; return a typed error so callers can recover (Clippy panic).",
      remediation="Return an Err with a typed error instead of panicking.",
      source="https://rust-lang.github.io/rust-clippy/master/#panic",
      re=r'\bpanic!\s*\(',
      nc='panic!("unexpected state");',
      c='return Err(Error::UnexpectedState);'),
    r("bugs", id="rust:todo-macro", type="smell", qual="maint", sev="info", cwe="",
      title="todo! placeholder left in code",
      desc="A todo! macro marks unfinished code that panics at runtime.",
      rationale="todo! compiles but panics when reached, shipping an incomplete code path.",
      remediation="Implement the branch or return a proper error.",
      source="https://doc.rust-lang.org/std/macro.todo.html",
      re=r'\btodo!\s*\(',
      nc='todo!()',
      c='return Ok(());'),
    r("bugs", id="rust:unimplemented-macro", type="smell", qual="maint", sev="low", cwe="",
      title="unimplemented! left in code",
      desc="An unimplemented! macro panics when the path is reached.",
      rationale="unimplemented! compiles but aborts at runtime, hiding a missing implementation.",
      remediation="Implement the branch or return a typed error.",
      source="https://doc.rust-lang.org/std/macro.unimplemented.html",
      re=r'\bunimplemented!\s*\(',
      nc='unimplemented!()',
      c='return Ok(());'),
    r("bugs", id="rust:unreachable-macro", type="bug", qual="rel", sev="low", cwe="",
      title="unreachable! on a reachable path",
      desc="An unreachable! macro asserts a path is never taken.",
      rationale="If the assumption is wrong, unreachable! panics; a fallible caller should return an error instead.",
      remediation="Return an error for the unexpected case rather than asserting unreachability.",
      source="https://doc.rust-lang.org/std/macro.unreachable.html",
      re=r'\bunreachable!\s*\(',
      nc='unreachable!("state should be closed");',
      c='return None;'),
    r("bugs", id="rust:unwrap-unchecked", type="bug", qual="rel", sev="high", cwe="CWE-476",
      title="unwrap_unchecked() undefined behavior",
      desc="unwrap_unchecked() assumes Some/Ok without checking.",
      rationale="If the value is None/Err, unwrap_unchecked() is undefined behavior rather than a panic.",
      remediation="Use unwrap_or_default() or verify the variant safely.",
      source="https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_unchecked",
      re=r'\.unwrap_unchecked\(',
      nc='let v = unsafe { o.unwrap_unchecked() };',
      c='let v = o.unwrap_or_default();'),
    r("bugs", id="rust:get-unchecked", type="bug", qual="rel", sev="high", cwe="CWE-125",
      title="get_unchecked() out-of-bounds access",
      desc="get_unchecked skips the bounds check on a slice.",
      rationale="An out-of-range index with get_unchecked is undefined behavior (out-of-bounds read).",
      remediation="Use get() and handle the None case.",
      source="https://doc.rust-lang.org/std/primitive.slice.html#method.get_unchecked",
      re=r'\.get_unchecked(_mut)?\(',
      nc='let x = unsafe { s.get_unchecked(3) };',
      c='let x = s.get(3);'),
    r("bugs", id="rust:indexing-slicing", type="bug", qual="rel", sev="medium", cwe="CWE-125",
      title="Direct indexing can panic",
      desc="A collection is indexed by a variable that may be out of range.",
      rationale="Index expressions panic on out-of-range access; get() returns an Option instead (Clippy indexing_slicing).",
      remediation="Use .get(idx) and handle None.",
      source="https://rust-lang.github.io/rust-clippy/master/#indexing_slicing",
      re=r'[A-Za-z_]\w*\[[a-z_]\w*\]',
      nc='let x = data[idx];',
      c='let x = data.get(idx);'),
    r("bugs", id="rust:slice-range-index", type="bug", qual="rel", sev="low", cwe="CWE-125",
      title="Slice range index can panic",
      desc="A slice is taken with a literal range that may exceed the length.",
      rationale="Range indexing panics if the end is past the slice length; get(range) is fallible.",
      remediation="Use .get(start..end) and handle None.",
      source="https://rust-lang.github.io/rust-clippy/master/#indexing_slicing",
      re=r'\[\s*\d+\s*\.\.\s*\d+\s*\]',
      nc='let s = &buf[0..10];',
      c='let s = buf.get(0..10);'),
    r("bugs", id="rust:cast-truncation", type="bug", qual="rel", sev="medium", cwe="CWE-197",
      title="Numeric cast may truncate",
      desc="A value is cast to a smaller integer type with as.",
      rationale="An as cast to a narrower type silently truncates; try_from surfaces the loss (Clippy cast_possible_truncation).",
      remediation="Use TryFrom/try_into and handle the error.",
      source="https://rust-lang.github.io/rust-clippy/master/#cast_possible_truncation",
      re=r'\bas\s+(u8|u16|i8|i16)\b',
      nc='let b = big as u8;',
      c='let b = u8::try_from(big)?;'),
    r("bugs", id="rust:cast-precision-loss", type="bug", qual="rel", sev="low", cwe="CWE-681",
      title="Cast to float loses precision",
      desc="A large integer is cast to a floating-point type.",
      rationale="Casting a wide integer to f32/f64 can silently lose precision (Clippy cast_precision_loss).",
      remediation="Use From for lossless widths or document the intended rounding.",
      source="https://rust-lang.github.io/rust-clippy/master/#cast_precision_loss",
      re=r'\bas\s+f(32|64)\b',
      nc='let f = big_u64 as f64;',
      c='let f = f64::from(small_u32);'),
    r("bugs", id="rust:mem-forget", type="bug", qual="rel", sev="medium", cwe="CWE-401",
      title="mem::forget leaks a value",
      desc="mem::forget suppresses a value's destructor.",
      rationale="mem::forget skips Drop, leaking owned resources such as file handles or memory (CWE-401).",
      remediation="Let the value drop normally, or use ManuallyDrop with an explicit drop.",
      source="https://doc.rust-lang.org/std/mem/fn.forget.html",
      re=r'\bmem::forget\s*\(',
      nc='mem::forget(guard);',
      c='drop(guard);'),
    r("bugs", id="rust:float-cmp-eq", type="bug", qual="rel", sev="medium", cwe="CWE-697",
      title="Exact float equality",
      desc="A floating-point value is compared for exact equality.",
      rationale="Floating-point rounding makes exact == comparisons unreliable (Clippy float_cmp).",
      remediation="Compare with an epsilon tolerance.",
      source="https://rust-lang.github.io/rust-clippy/master/#float_cmp",
      re=r'[=!]=\s*-?\d+\.\d+',
      nc='if x == 0.1 {',
      c='if (x - 0.1).abs() < f64::EPSILON {'),
    r("bugs", id="rust:approx-constant", type="smell", qual="maint", sev="low", cwe="",
      title="Approximated math constant",
      desc="A math constant is written as a hand-typed literal.",
      rationale="A truncated literal like 3.14159 is less precise than the library constant (Clippy approx_constant).",
      remediation="Use std::f64::consts::PI (or the appropriate constant).",
      source="https://rust-lang.github.io/rust-clippy/master/#approx_constant",
      re=r'\b3\.14\d*\b',
      nc='let pi = 3.14159;',
      c='let pi = std::f64::consts::PI;'),
    r("bugs", id="rust:drop-ref", type="bug", qual="rel", sev="medium", cwe="",
      title="drop() on a reference",
      desc="drop() is called on a reference, which does nothing.",
      rationale="Dropping a reference does not drop the referent, so the intended cleanup never happens (Clippy drop_ref).",
      remediation="Drop the owned value, not a borrow of it.",
      source="https://rust-lang.github.io/rust-clippy/master/#drop_ref",
      re=r'\bdrop\s*\(\s*&',
      nc='drop(&conn);',
      c='drop(conn);'),
    r("bugs", id="rust:clone-double", type="smell", qual="maint", sev="low", cwe="",
      title="Chained double clone",
      desc="clone() is called twice in a row.",
      rationale="A second clone on an owned value is redundant work.",
      remediation="Remove the extra clone().",
      source="https://rust-lang.github.io/rust-clippy/master/#redundant_clone",
      re=r'\.clone\(\)\.clone\(\)',
      nc='let y = x.clone().clone();',
      c='let y = x.clone();'),
    r("bugs", id="rust:iter-nth-zero", type="smell", qual="maint", sev="low", cwe="",
      title="nth(0) instead of next()",
      desc="The first element is fetched with nth(0).",
      rationale="nth(0) is a less clear and less direct way to get the first item (Clippy iter_nth_zero).",
      remediation="Use .next().",
      source="https://rust-lang.github.io/rust-clippy/master/#iter_nth_zero",
      re=r'\.nth\(\s*0\s*\)',
      nc='let f = it.nth(0);',
      c='let f = it.next();'),
    r("bugs", id="rust:ok-expect", type="bug", qual="rel", sev="low", cwe="",
      title="ok().expect() on a Result",
      desc="A Result is converted with ok() then expect().",
      rationale="ok().expect() discards the error before panicking, losing diagnostics (Clippy ok_expect).",
      remediation="Call expect() directly on the Result, or propagate with ?.",
      source="https://rust-lang.github.io/rust-clippy/master/#ok_expect",
      re=r'\.ok\(\)\.expect\(',
      nc='let v = res.ok().expect("value");',
      c='let v = res.expect("value");'),
    r("bugs", id="rust:filter-next", type="smell", qual="maint", sev="low", cwe="",
      title="filter().next() instead of find()",
      desc="An iterator is filtered then the first match taken with next().",
      rationale="filter().next() is exactly find() and less clear (Clippy filter_next).",
      remediation="Use .find(predicate).",
      source="https://rust-lang.github.io/rust-clippy/master/#filter_next",
      re=r'\.filter\(.*\)\.next\(\)',
      nc='let x = it.filter(|n| *n > 2).next();',
      c='let x = it.find(|n| *n > 2);'),
    r("bugs", id="rust:map-unwrap-or", type="smell", qual="maint", sev="low", cwe="",
      title="map().unwrap_or() instead of map_or()",
      desc="An Option is mapped then defaulted with unwrap_or().",
      rationale="map().unwrap_or() is map_or() written the long way (Clippy map_unwrap_or).",
      remediation="Use .map_or(default, f).",
      source="https://rust-lang.github.io/rust-clippy/master/#map_unwrap_or",
      re=r'\.map\(.*\)\.unwrap_or\(',
      nc='let n = o.map(|x| x + 1).unwrap_or(0);',
      c='let n = o.map_or(0, |x| x + 1);'),
    r("bugs", id="rust:needless-collect-len", type="smell", qual="maint", sev="low", cwe="",
      title="collect().len() instead of count()",
      desc="An iterator is collected into a Vec only to read its length.",
      rationale="Collecting to count allocates a throwaway Vec (Clippy needless_collect).",
      remediation="Use .count().",
      source="https://rust-lang.github.io/rust-clippy/master/#needless_collect",
      re=r'\.collect::<Vec<[^>]*>>\(\)\.len\(\)',
      nc='let n = it.collect::<Vec<_>>().len();',
      c='let n = it.count();'),
    r("bugs", id="rust:bool-comparison", type="smell", qual="maint", sev="low", cwe="",
      title="Comparison to a boolean literal",
      desc="A boolean is compared to true.",
      rationale="Comparing a bool to true is redundant and noisier than the value itself (Clippy bool_comparison).",
      remediation="Use the boolean directly.",
      source="https://rust-lang.github.io/rust-clippy/master/#bool_comparison",
      re=r'==\s*true\b',
      nc='if flag == true {',
      c='if flag {'),
]
