CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "java")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "java", "security"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


# Java security pack: precise crypto / TLS / deserialization / injection / cookie / file-permission
# sink patterns. Each rule keys off a specific API call plus a literal argument so the regex is
# well-anchored and low-false-positive. Concept origins cited (CWE, OWASP, find-sec-bugs, PMD, SEI
# CERT); rule prose is authored clean-room.
RULES = [
    r(id="java-weak-hash-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="MD5 message digest", desc="MD5 is cryptographically broken for integrity and signatures.",
      rationale="MD5 is collision-prone and unfit for security use; use SHA-256 or stronger.",
      remediation="Call MessageDigest.getInstance(\"SHA-256\") (or SHA-512) instead of MD5.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'getInstance\s*\(\s*"MD5"', nc='MessageDigest md = MessageDigest.getInstance("MD5");',
      c='MessageDigest md = MessageDigest.getInstance("SHA-256");'),
    r(id="java-weak-hash-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="SHA-1 message digest", desc="SHA-1 is deprecated for security due to practical collisions.",
      rationale="SHA-1 collisions are practical; do not use it for signatures or integrity.",
      remediation="Use SHA-256 or SHA-512 instead of SHA-1.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'getInstance\s*\(\s*"SHA-?1"', nc='MessageDigest md = MessageDigest.getInstance("SHA-1");',
      c='MessageDigest md = MessageDigest.getInstance("SHA-256");'),
    r(id="java-cipher-des", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="DES cipher", desc="DES has a 56-bit key and is trivially brute-forced.",
      rationale="DES's key length is far too short for modern security; use AES.",
      remediation="Use AES (e.g. \"AES/GCM/NoPadding\") instead of DES.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'Cipher\.getInstance\s*\(\s*"DES(/|")', nc='Cipher c = Cipher.getInstance("DES/CBC/PKCS5Padding");',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-cipher-3des", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Triple DES cipher", desc="3DES (DESede) is deprecated and offers weak effective security.",
      rationale="Triple DES is slow and deprecated by NIST; use AES.",
      remediation="Use AES (e.g. \"AES/GCM/NoPadding\") instead of DESede.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'Cipher\.getInstance\s*\(\s*"DESede', nc='Cipher c = Cipher.getInstance("DESede/CBC/PKCS5Padding");',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-cipher-ecb", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="ECB cipher mode", desc="ECB mode leaks plaintext structure because identical blocks encrypt identically.",
      rationale="ECB does not use an IV, so patterns in plaintext survive into ciphertext.",
      remediation="Use an authenticated mode such as GCM instead of ECB.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'getInstance\s*\(\s*"[A-Za-z0-9]+/ECB/', nc='Cipher c = Cipher.getInstance("AES/ECB/PKCS5Padding");',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-cipher-rc4", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="RC4 cipher", desc="RC4 has known biases and is prohibited by modern standards.",
      rationale="RC4 keystream biases allow plaintext recovery; it is banned in TLS.",
      remediation="Use AES-GCM instead of RC4.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'Cipher\.getInstance\s*\(\s*"RC4', nc='Cipher c = Cipher.getInstance("RC4");',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-cipher-blowfish", type="vuln", qual="sec", sev="low", cwe="CWE-327", owasp="A02:2021",
      title="Blowfish cipher", desc="Blowfish's 64-bit block is vulnerable to birthday attacks on large data.",
      rationale="Blowfish's small block size makes it unsuitable for bulk encryption; use AES.",
      remediation="Use AES (128-bit block) instead of Blowfish.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'Cipher\.getInstance\s*\(\s*"Blowfish', nc='Cipher c = Cipher.getInstance("Blowfish/CBC/PKCS5Padding");',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-cipher-rsa-pkcs1", type="vuln", qual="sec", sev="medium", cwe="CWE-780", owasp="A02:2021",
      title="RSA with PKCS#1 v1.5 padding", desc="RSA/ECB/PKCS1Padding is vulnerable to padding-oracle attacks.",
      rationale="PKCS#1 v1.5 encryption padding enables Bleichenbacher attacks; use OAEP.",
      remediation="Use \"RSA/ECB/OAEPWithSHA-256AndMGF1Padding\".",
      source="https://cwe.mitre.org/data/definitions/780.html",
      re=r'getInstance\s*\(\s*"RSA/[^"]*PKCS1Padding"', nc='Cipher c = Cipher.getInstance("RSA/ECB/PKCS1Padding");',
      c='Cipher c = Cipher.getInstance("RSA/ECB/OAEPWithSHA-256AndMGF1Padding");'),
    r(id="java-null-cipher", type="vuln", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="NullCipher used", desc="NullCipher performs no encryption; data is passed through in clear.",
      rationale="A NullCipher provides no confidentiality and is almost always a mistake.",
      remediation="Use a real cipher such as AES-GCM.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'new\s+NullCipher\s*\(', nc='Cipher c = new NullCipher();',
      c='Cipher c = Cipher.getInstance("AES/GCM/NoPadding");'),
    r(id="java-ssl-context-insecure", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Insecure SSL protocol context", desc="SSLContext.getInstance(\"SSL\") enables the broken SSLv2/SSLv3 protocols.",
      rationale="SSLv2/SSLv3 are broken (POODLE, DROWN); request a TLS context.",
      remediation="Use SSLContext.getInstance(\"TLSv1.2\") or \"TLSv1.3\".",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'SSLContext\.getInstance\s*\(\s*"SSL(v[23])?"\s*\)', nc='SSLContext ctx = SSLContext.getInstance("SSL");',
      c='SSLContext ctx = SSLContext.getInstance("TLSv1.2");'),
    r(id="java-tls-deprecated-version", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Deprecated TLS version", desc="TLSv1.0 and TLSv1.1 are deprecated and disabled by modern peers.",
      rationale="TLS 1.0/1.1 have known weaknesses and are deprecated (RFC 8996).",
      remediation="Request \"TLSv1.2\" or \"TLSv1.3\".",
      source="https://datatracker.ietf.org/doc/html/rfc8996",
      re=r'getInstance\s*\(\s*"TLSv1(\.1)?"\s*\)', nc='SSLContext ctx = SSLContext.getInstance("TLSv1");',
      c='SSLContext ctx = SSLContext.getInstance("TLSv1.2");'),
    r(id="java-hostname-verifier-allow-all", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="Allow-all hostname verifier", desc="ALLOW_ALL_HOSTNAME_VERIFIER disables TLS hostname checking.",
      rationale="Accepting any hostname lets an attacker present any valid certificate for a MITM.",
      remediation="Use the default (strict) hostname verifier.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'ALLOW_ALL_HOSTNAME_VERIFIER', nc='f.setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);',
      c='f.setHostnameVerifier(SSLSocketFactory.STRICT_HOSTNAME_VERIFIER);'),
    r(id="java-noop-hostname-verifier", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="No-op hostname verifier", desc="NoopHostnameVerifier accepts every hostname, disabling TLS identity checks.",
      rationale="A no-op verifier accepts any certificate hostname, enabling MITM.",
      remediation="Use DefaultHostnameVerifier.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'new\s+NoopHostnameVerifier\s*\(', nc='conn.setHostnameVerifier(new NoopHostnameVerifier());',
      c='conn.setHostnameVerifier(new DefaultHostnameVerifier());'),
    r(id="java-object-input-stream", type="hotspot", qual="sec", sev="medium", cwe="CWE-502", owasp="A08:2021",
      title="Java native deserialization", desc="ObjectInputStream deserializes arbitrary types, enabling gadget-chain RCE.",
      rationale="Native Java deserialization of untrusted data is a well-known RCE vector.",
      remediation="Avoid native serialization for untrusted input; use a data format like JSON with a schema, or an ObjectInputFilter.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'new\s+ObjectInputStream\s*\(', nc='ObjectInputStream in = new ObjectInputStream(sock.getInputStream());',
      c='JsonReader in = new JsonReader(sock.getInputStream());'),
    r(id="java-xml-decoder", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="XMLDecoder deserialization", desc="XMLDecoder can instantiate arbitrary classes and invoke methods from XML.",
      rationale="java.beans.XMLDecoder executes constructors/methods encoded in the XML, enabling RCE.",
      remediation="Do not use XMLDecoder on untrusted input; use a safe data binding library.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'new\s+XMLDecoder\s*\(', nc='XMLDecoder d = new XMLDecoder(input);',
      c='ObjectMapper d = new ObjectMapper();'),
    r(id="java-digestutils-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Apache Commons DigestUtils MD5", desc="DigestUtils.md5* uses the broken MD5 algorithm.",
      rationale="Commons Codec md5/md5Hex wraps MD5, which is unfit for security.",
      remediation="Use DigestUtils.sha256Hex or a stronger digest.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'DigestUtils\.md5', nc='String h = DigestUtils.md5Hex(data);', c='String h = DigestUtils.sha256Hex(data);'),
    r(id="java-digestutils-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Apache Commons DigestUtils SHA-1", desc="DigestUtils.sha1* uses the deprecated SHA-1 algorithm.",
      rationale="Commons Codec sha1/sha1Hex wraps SHA-1, which has practical collisions.",
      remediation="Use DigestUtils.sha256Hex or stronger.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'DigestUtils\.sha1', nc='String h = DigestUtils.sha1Hex(data);', c='String h = DigestUtils.sha256Hex(data);'),
    r(id="java-insecure-random", type="hotspot", qual="sec", sev="low", cwe="CWE-330", owasp="A02:2021",
      title="Predictable java.util.Random", desc="java.util.Random is predictable and unfit for security tokens.",
      rationale="Random is a linear PRNG whose output is predictable; do not use it for secrets, tokens, or nonces.",
      remediation="Use java.security.SecureRandom for security-sensitive values.",
      source="https://cwe.mitre.org/data/definitions/330.html",
      re=r'new\s+Random\s*\(', nc='Random r = new Random();', c='SecureRandom r = new SecureRandom();'),
    r(id="java-cookie-secure-false", type="vuln", qual="sec", sev="medium", cwe="CWE-614", owasp="A05:2021",
      title="Cookie without the secure flag", desc="setSecure(false) lets the cookie travel over plaintext HTTP.",
      rationale="A cookie without the secure flag can be sent over HTTP and intercepted.",
      remediation="Call setSecure(true) on session/auth cookies.",
      source="https://cwe.mitre.org/data/definitions/614.html",
      re=r'\.setSecure\s*\(\s*false\s*\)', nc='cookie.setSecure(false);', c='cookie.setSecure(true);'),
    r(id="java-cookie-httponly-false", type="vuln", qual="sec", sev="medium", cwe="CWE-1004", owasp="A05:2021",
      title="Cookie without HttpOnly", desc="setHttpOnly(false) exposes the cookie to client-side scripts.",
      rationale="A non-HttpOnly cookie can be read by JavaScript, aiding token theft via XSS.",
      remediation="Call setHttpOnly(true) on session/auth cookies.",
      source="https://cwe.mitre.org/data/definitions/1004.html",
      re=r'\.setHttpOnly\s*\(\s*false\s*\)', nc='cookie.setHttpOnly(false);', c='cookie.setHttpOnly(true);'),
    r(id="java-file-world-readable", type="hotspot", qual="sec", sev="medium", cwe="CWE-732", owasp="A01:2021",
      title="File made world-readable", desc="setReadable(true, false) grants read permission to all users.",
      rationale="The second argument false applies the permission to everyone, not just the owner.",
      remediation="Pass true as the second argument to restrict the permission to the owner.",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\.setReadable\s*\(\s*true\s*,\s*false\s*\)', nc='f.setReadable(true, false);', c='f.setReadable(true, true);'),
    r(id="java-file-world-writable", type="hotspot", qual="sec", sev="medium", cwe="CWE-732", owasp="A01:2021",
      title="File made world-writable", desc="setWritable(true, false) grants write permission to all users.",
      rationale="The second argument false applies the permission to everyone, not just the owner.",
      remediation="Pass true as the second argument to restrict the permission to the owner.",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\.setWritable\s*\(\s*true\s*,\s*false\s*\)', nc='f.setWritable(true, false);', c='f.setWritable(true, true);'),
    r(id="java-scriptengine-manager", type="hotspot", qual="sec", sev="medium", cwe="CWE-94", owasp="A03:2021",
      title="Script engine evaluation", desc="ScriptEngineManager can execute arbitrary script code (e.g. Nashorn JS).",
      rationale="Evaluating scripts through ScriptEngine on untrusted input allows code injection.",
      remediation="Avoid dynamic script evaluation, or sandbox and validate the script source.",
      source="https://cwe.mitre.org/data/definitions/94.html",
      re=r'new\s+ScriptEngineManager\s*\(', nc='ScriptEngine e = new ScriptEngineManager().getEngineByName("js");',
      c='Object result = compiledExpression.evaluate(context);'),
    r(id="java-temp-file-insecure", type="hotspot", qual="sec", sev="low", cwe="CWE-377", owasp="A01:2021",
      title="Insecure temporary file", desc="File.createTempFile creates a file with default, often world-readable, permissions.",
      rationale="The legacy File.createTempFile races and uses permissive defaults; Files.createTempFile is safer.",
      remediation="Use java.nio.file.Files.createTempFile, which sets owner-only permissions.",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'File\.createTempFile\s*\(', nc='File t = File.createTempFile("upload", ".tmp");',
      c='Path t = Files.createTempFile("upload", ".tmp");'),
    r(id="java-tolowercase-no-locale", type="bug", qual="rel", sev="low", cwe="", title="toLowerCase without a Locale",
      desc="toLowerCase() uses the default locale, giving locale-dependent results (e.g. the Turkish i).",
      rationale="Case conversion without an explicit Locale breaks in locales like tr_TR; pass Locale.ROOT.",
      remediation="Call toLowerCase(Locale.ROOT) for locale-independent conversion.",
      source="https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html",
      re=r'\.toLowerCase\s*\(\s*\)', nc='String key = header.toLowerCase();', c='String key = header.toLowerCase(Locale.ROOT);'),
    r(id="java-touppercase-no-locale", type="bug", qual="rel", sev="low", cwe="", title="toUpperCase without a Locale",
      desc="toUpperCase() uses the default locale, giving locale-dependent results.",
      rationale="Case conversion without an explicit Locale breaks in some locales; pass Locale.ROOT.",
      remediation="Call toUpperCase(Locale.ROOT) for locale-independent conversion.",
      source="https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html",
      re=r'\.toUpperCase\s*\(\s*\)', nc='String code = country.toUpperCase();', c='String code = country.toUpperCase(Locale.ROOT);'),
]
