CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","js");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","node"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="node-createhash-weak",type="vuln",qual="sec",sev="medium",cwe="CWE-327",owasp="A02:2021",title="Weak hash via crypto.createHash",
   desc="crypto.createHash('md5'|'sha1') uses a broken hash algorithm.",
   rationale="MD5 and SHA-1 are collision-vulnerable and unfit for signatures or integrity; Node's createHash accepts them silently.",
   remediation="Use sha256 or stronger; for passwords use a KDF (scrypt/argon2/bcrypt).",
   source="https://cwe.mitre.org/data/definitions/327.html",
   re=r"crypto\.createHash\s*\(\s*['\"](md5|sha1)['\"]",nc='const h = crypto.createHash("md5");',c='const h = crypto.createHash("sha256");'),
 r(id="node-cipher-ecb",type="vuln",qual="sec",sev="high",cwe="CWE-327",owasp="A02:2021",title="ECB cipher mode",
   desc="AES in ECB mode leaks plaintext structure (identical blocks encrypt identically).",
   rationale="ECB mode encrypts each block independently, so patterns in the plaintext remain visible in the ciphertext.",
   remediation="Use an authenticated mode such as aes-256-gcm with a random IV.",
   source="https://cwe.mitre.org/data/definitions/327.html",
   re=r"['\"]aes-[0-9]+-ecb['\"]",nc='const c = crypto.createCipheriv("aes-128-ecb", key, null);',c='const c = crypto.createCipheriv("aes-256-gcm", key, iv);'),
 r(id="node-jwt-decode-no-verify",type="hotspot",qual="sec",sev="medium",cwe="CWE-347",owasp="A07:2021",title="jwt.decode without verification",
   desc="jwt.decode reads claims without checking the signature.",
   rationale="decode() does not validate the signature, so an attacker can forge claims; trusting its output is an authentication bypass.",
   remediation="Use jwt.verify with the expected key and algorithms.",
   source="https://cwe.mitre.org/data/definitions/347.html",
   re=r"\bjwt\.decode\s*\(",nc="const claims = jwt.decode(token);",c="const claims = jwt.verify(token, key);"),
 r(id="node-sequelize-literal",type="hotspot",qual="sec",sev="medium",cwe="CWE-89",owasp="A03:2021",title="Sequelize literal() with dynamic input",
   desc="sequelize.literal injects raw SQL that bypasses parameterization.",
   rationale="literal() emits its argument verbatim into the query, so any input flowing into it is a SQL-injection sink.",
   remediation="Use bound parameters / structured query options instead of literal().",
   source="https://cwe.mitre.org/data/definitions/89.html",
   re=r"sequelize\.literal\s*\(",nc="order: [sequelize.literal(sortColumn)]",c='order: [["name", "ASC"]]'),
 r(id="node-sendfile-user-input",type="hotspot",qual="sec",sev="high",cwe="CWE-22",owasp="A01:2021",title="sendFile with request-controlled path",
   desc="Passing a request value to sendFile enables path traversal.",
   rationale="sendFile resolves the given path on disk; a request-controlled value can escape the intended directory with ../ sequences.",
   remediation="Resolve against a fixed root and reject paths that escape it (path.join + containment check).",
   source="https://cwe.mitre.org/data/definitions/22.html",
   re=r"\.sendFile\s*\([^)]*\breq\.",nc="res.sendFile(req.query.file);",c='res.sendFile(path.join(root, "index.html"));'),
 r(id="node-error-stack-in-response",type="hotspot",qual="sec",sev="medium",cwe="CWE-209",owasp="A05:2021",title="Error stack sent in a response",
   desc="Returning err.stack to the client leaks internal paths and logic.",
   rationale="A stack trace in the HTTP response discloses file paths, dependencies, and code structure that aid an attacker.",
   remediation="Return a generic message and log the stack server-side.",
   source="https://cwe.mitre.org/data/definitions/209.html",
   re=r"\.(send|json|render)\s*\([^)]*\.stack\b",nc="res.status(500).send(err.stack);",c='res.status(500).send("Internal Server Error");'),
 r(id="node-env-in-log",type="hotspot",qual="sec",sev="low",cwe="CWE-532",owasp="A09:2021",title="Environment logged",
   desc="Logging process.env can write secrets to logs.",
   rationale="process.env usually holds credentials/config; logging it persists secrets to log sinks that may be less protected.",
   remediation="Log only the specific, non-sensitive values you need.",
   source="https://cwe.mitre.org/data/definitions/532.html",
   re=r"console\.(log|info|debug|warn|error)\s*\([^)]*process\.env\b",nc="console.log(process.env);",c='console.log("service started");'),
 r(id="node-fs-exists-deprecated",type="bug",qual="rel",sev="low",cwe="",title="Deprecated fs.exists",
   desc="fs.exists is deprecated and has a misleading callback signature (race-prone).",
   rationale="fs.exists is deprecated; checking existence then acting is a TOCTOU race, and its callback omits the error argument.",
   remediation="Use fs.access (or just attempt the operation and handle ENOENT).",
   source="https://nodejs.org/api/fs.html#fsexistspath-callback",
   re=r"\bfs\.exists\s*\(",nc="fs.exists(p, (ok) => run(ok));",c="fs.access(p, (err) => run(!err));"),
 r(id="node-weak-tls-protocol",type="hotspot",qual="sec",sev="medium",cwe="CWE-327",owasp="A02:2021",title="Weak TLS protocol pinned",
   desc="Pinning SSLv3/TLSv1/TLSv1.1 forces a deprecated protocol.",
   rationale="secureProtocol pinned to an old method forbids modern TLS and enables downgrade/weak-cipher attacks.",
   remediation="Set minVersion: 'TLSv1.2' (or 1.3) instead of pinning a legacy method.",
   source="https://cwe.mitre.org/data/definitions/327.html",
   re=r"secureProtocol\s*:\s*['\"](SSLv3|TLSv1|TLSv1_method|TLSv1_1)",nc='const o = { secureProtocol: "TLSv1_method" };',c='const o = { minVersion: "TLSv1.2" };'),
]
