# C# language-pack rule specs, batch 10 (#189). Clean-room, line-detectable — globalization, collection/LINQ
# perf, weak TLS versions, dangerous cert validator, float equality, divide-by-zero, test-assertion smells.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-tostring-format-no-culture", type="smell", qual="maint", sev="info", cwe="",
      title="ToString(format) without a culture",
      desc="A value is formatted with ToString(format) but no IFormatProvider.",
      rationale="Numeric/date formatting is culture-sensitive by default, producing locale-dependent output (CA1305).",
      remediation="Pass CultureInfo.InvariantCulture (or the intended culture).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305",
      re=r'\.ToString\(\s*"[^"]*"\s*\)',
      nc='var s = amount.ToString("N2");',
      c='var s = amount.ToString("N2", CultureInfo.InvariantCulture);'),
    r(id="cs-dictionary-keys-contains", type="smell", qual="maint", sev="low", cwe="",
      title="Dictionary.Keys.Contains instead of ContainsKey",
      desc="Membership is tested via .Keys.Contains, which can enumerate the keys.",
      rationale="ContainsKey is an O(1) hash lookup; Keys.Contains may scan the collection.",
      remediation="Use ContainsKey.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.containskey",
      re=r'\.Keys\.Contains\(',
      nc='if (map.Keys.Contains(id)) Use(id);',
      c='if (map.ContainsKey(id)) Use(id);'),
    r(id="cs-task-run-fire-forget", type="smell", qual="maint", sev="medium", cwe="",
      title="Fire-and-forget Task.Run",
      desc="A Task.Run is invoked as a statement without awaiting or storing the returned task.",
      rationale="An unobserved Task swallows exceptions and loses completion tracking.",
      remediation="Await the task, or capture it and handle faults explicitly.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'^\s*Task\.Run\(',
      nc='Task.Run(() => Reindex());',
      c='await Task.Run(() => Reindex());'),
    r(id="cs-argnull-manual-check", type="smell", qual="maint", sev="info", cwe="",
      title="Manual null-check throwing ArgumentNullException",
      desc="A parameter is null-checked and throws ArgumentNullException by hand.",
      rationale="ArgumentNullException.ThrowIfNull is clearer and captures the parameter name automatically.",
      remediation="Use ArgumentNullException.ThrowIfNull(param).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull",
      re=r'if\s*\([^)]*==\s*null\)\s*throw\s+new\s+ArgumentNullException',
      nc='if (name == null) throw new ArgumentNullException(nameof(name));',
      c='ArgumentNullException.ThrowIfNull(name);'),
    r(id="cs-assert-true-equality", type="smell", qual="maint", sev="low", cwe="",
      title="Assert.True on an equality expression",
      desc="A test asserts equality via Assert.True(a == b).",
      rationale="Assert.Equal reports the expected and actual values on failure; Assert.True only reports 'false'.",
      remediation="Use Assert.Equal(expected, actual).",
      source="https://xunit.net/docs/comparisons",
      re=r'Assert\.(True|IsTrue)\(\s*[^,)]*==',
      nc='Assert.True(result == expected);',
      c='Assert.Equal(expected, result);'),
    r(id="cs-assert-false-equality", type="smell", qual="maint", sev="low", cwe="",
      title="Assert.False on an equality expression",
      desc="A test asserts inequality via Assert.False(a == b).",
      rationale="Assert.NotEqual reports the values on failure; Assert.False only reports 'true'.",
      remediation="Use Assert.NotEqual(expected, actual).",
      source="https://xunit.net/docs/comparisons",
      re=r'Assert\.(False|IsFalse)\(\s*[^,)]*==',
      nc='Assert.False(a == b);',
      c='Assert.NotEqual(b, a);'),
    r(id="cs-assert-equal-null", type="smell", qual="maint", sev="low", cwe="",
      title="Assert.Equal(null, ...)",
      desc="A test checks for null via Assert.Equal(null, x).",
      rationale="Assert.Null expresses the intent and gives a clearer failure message.",
      remediation="Use Assert.Null(x).",
      source="https://xunit.net/docs/comparisons",
      re=r'Assert\.Equal\(\s*null\s*,',
      nc='Assert.Equal(null, result);',
      c='Assert.Null(result);'),
    r(id="cs-divide-by-zero-literal", type="bug", qual="rel", sev="high", cwe="CWE-369",
      title="Integer division by the literal 0",
      desc="A value is divided by the literal 0.",
      rationale="Integer division by zero throws DivideByZeroException at runtime (CWE-369).",
      remediation="Guard the divisor, or fix the constant.",
      source="https://cwe.mitre.org/data/definitions/369.html",
      re=r'[^/*]/\s*0\s*[;)]',
      nc='var rate = total / 0;',
      c='var rate = total / divisor;'),
    r(id="cs-httpclient-dangerous-cert", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="DangerousAcceptAnyServerCertificateValidator used",
      desc="An HttpClientHandler uses the built-in accept-any-certificate validator.",
      rationale="This validator accepts every server certificate, disabling TLS trust (CWE-295).",
      remediation="Validate the certificate (e.g. pin the expected thumbprint).",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'DangerousAcceptAnyServerCertificateValidator\b',
      nc='handler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;',
      c='handler.ServerCertificateCustomValidationCallback = ValidatePinnedCertificate;'),
    r(id="cs-tls11", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="TLS 1.1 selected",
      desc="SslProtocols.Tls11 is used.",
      rationale="TLS 1.1 is deprecated and disallowed by modern standards; use TLS 1.2+ (CWE-327).",
      remediation="Use SslProtocols.Tls12 or Tls13 (or let the OS negotiate).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'SslProtocols\.Tls11\b',
      nc='var p = SslProtocols.Tls11;',
      c='var p = SslProtocols.Tls13;'),
    r(id="cs-ssl2", type="vuln", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="SSL 2.0 selected",
      desc="SslProtocols.Ssl2 is used.",
      rationale="SSL 2.0 is broken and must never be used (CWE-327).",
      remediation="Use SslProtocols.Tls12 or Tls13.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'SslProtocols\.Ssl2\b',
      nc='var p = SslProtocols.Ssl2;',
      c='var p = SslProtocols.Tls13;'),
    r(id="cs-float-equality-literal", type="bug", qual="rel", sev="low", cwe="CWE-1077",
      title="Floating-point equality against a literal",
      desc="A float/double is compared for exact equality with a decimal literal.",
      rationale="Binary floating-point cannot represent most decimals exactly, so == is unreliable (CWE-1077).",
      remediation="Compare within a tolerance (Math.Abs(a - b) < epsilon).",
      source="https://cwe.mitre.org/data/definitions/1077.html",
      re=r'[=!]=\s*\d+\.\d+[fdmFDM]?\b',
      nc='if (ratio == 0.5) Apply();',
      c='if (Math.Abs(ratio - 0.5) < Epsilon) Apply();'),
    r(id="cs-tolist-tolist-redundant", type="smell", qual="maint", sev="low", cwe="",
      title="Redundant ToList().ToList()",
      desc="A sequence is materialized to a list twice in a row.",
      rationale="The second ToList allocates another copy for no benefit.",
      remediation="Call ToList() once.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolist",
      re=r'\.ToList\(\)\s*\.ToList\(\)',
      nc='var items = query.ToList().ToList();',
      c='var items = query.ToList();'),
    r(id="cs-indexof-vs-contains", type="smell", qual="maint", sev="low", cwe="",
      title="IndexOf(...) >= 0 instead of Contains",
      desc="Membership is tested with IndexOf compared to 0 / -1.",
      rationale="Contains states the intent directly and avoids computing an unused position.",
      remediation="Use Contains.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.contains",
      re=r'\.IndexOf\([^)]*\)\s*(>=\s*0|!=\s*-1)',
      nc='if (names.IndexOf(name) >= 0) Use(name);',
      c='if (names.Contains(name)) Use(name);'),
    r(id="cs-replace-single-char", type="smell", qual="maint", sev="info", cwe="",
      title="String.Replace with single-character strings",
      desc="String.Replace is called with one-character string arguments.",
      rationale="The char,char overload avoids two string allocations and the substring search.",
      remediation="Use the char overload: Replace('a', 'b').",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.replace",
      re=r'\.Replace\(\s*"[^"\\]"\s*,\s*"[^"\\]"\s*\)',
      nc='var s = path.Replace("/", "-");',
      c="var s = path.Replace('/', '-');"),
    r(id="cs-cast-after-int-division", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Widening cast applied after integer division",
      desc="An integer division is parenthesized and then cast to a floating-point type.",
      rationale="The division truncates before the cast, so the fractional part is already lost (CWE-682).",
      remediation="Cast an operand before dividing: (double)a / b.",
      source="https://cwe.mitre.org/data/definitions/682.html",
      re=r'\((?:double|float|decimal)\)\s*\(\s*\w+\s*/\s*\w+\s*\)',
      nc='var pct = (double)(hits / total);',
      c='var pct = (double)hits / total;'),
]
