# C# language-pack rule specs, batch 1 (#189). Clean-room, line-detectable C# rules derived from the
# concepts in the .NET code-analysis rules (CAxxxx), StyleCop analyzer categories, .NET secure-coding
# guidance, and CWE — our own wording, examples, and detection. Flow/type rules (null-flow, IDisposable
# leak across scopes, async deadlock proof) are AST/dataflow-tier; these are precise line-regex rules.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- crypto ----
    r(id="cs-weak-hash-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash algorithm MD5",
      desc="MD5 is created via MD5.Create/new MD5CryptoServiceProvider; it is broken for security use.",
      rationale="MD5 is collision-vulnerable and unfit for signatures or integrity (CWE-327). Use SHA-256 or better.",
      remediation="Use SHA256 (SHA256.Create) or a password KDF; never MD5 for security.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(MD5\.Create|MD5CryptoServiceProvider|MD5\.HashData)\b',
      nc='using var h = MD5.Create();',
      c='using var h = SHA256.Create();'),
    r(id="cs-weak-hash-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash algorithm SHA-1",
      desc="SHA-1 is created via SHA1.Create/new SHA1CryptoServiceProvider/SHA1Managed.",
      rationale="SHA-1 is collision-vulnerable and deprecated for security (CWE-327). Use SHA-256 or better.",
      remediation="Use SHA256 or stronger.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(SHA1\.Create|SHA1CryptoServiceProvider|SHA1Managed|SHA1\.HashData)\b',
      nc='using var h = new SHA1Managed();',
      c='using var h = SHA256.Create();'),
    r(id="cs-des-cipher", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="DES / TripleDES cipher used",
      desc="DESCryptoServiceProvider or TripleDESCryptoServiceProvider creates an obsolete cipher.",
      rationale="DES (56-bit) and 3DES are obsolete and insecure (CWE-327). Use AES.",
      remediation="Use Aes.Create() with an authenticated mode.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(DESCryptoServiceProvider|TripleDESCryptoServiceProvider|DES\.Create|TripleDES\.Create)\b',
      nc='var des = new DESCryptoServiceProvider();',
      c='var aes = Aes.Create();'),
    r(id="cs-rc2-cipher", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="RC2 cipher used",
      desc="RC2CryptoServiceProvider creates a weak legacy cipher.",
      rationale="RC2 is a weak, obsolete cipher (CWE-327). Use AES.",
      remediation="Use Aes.Create().",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bRC2CryptoServiceProvider\b',
      nc='var c = new RC2CryptoServiceProvider();',
      c='var aes = Aes.Create();'),
    r(id="cs-cipher-ecb-mode", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="ECB cipher mode",
      desc="A cipher mode is set to CipherMode.ECB, which leaks plaintext structure.",
      rationale="ECB encrypts identical blocks identically, revealing patterns (CWE-327). Use an authenticated mode like GCM.",
      remediation="Use an AEAD mode (AesGcm) or at least CBC with a random IV and a MAC.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'CipherMode\.ECB\b',
      nc='aes.Mode = CipherMode.ECB;',
      c='using var gcm = new AesGcm(key);'),
    r(id="cs-random-for-security", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="System.Random used for a security value",
      desc="new Random() is a non-cryptographic PRNG; review any use for tokens, keys, or IDs.",
      rationale="System.Random is predictable and unsuitable for secrets (CWE-338). Use RandomNumberGenerator.",
      remediation="Use System.Security.Cryptography.RandomNumberGenerator for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\bnew\s+Random\s*\(',
      nc='var token = new Random().Next();',
      c='var bytes = RandomNumberGenerator.GetBytes(16);'),
    r(id="cs-rsa-small-key", type="vuln", qual="sec", sev="high", cwe="CWE-326",
      title="RSA key smaller than 2048 bits",
      desc="An RSA key of 512 or 1024 bits is generated.",
      rationale="RSA keys under 2048 bits are too weak (CWE-326).",
      remediation="Use an RSA key size of at least 2048 bits.",
      source="https://cwe.mitre.org/data/definitions/326.html",
      re=r'\bnew\s+RSACryptoServiceProvider\s*\(\s*(512|1024)\s*\)',
      nc='var rsa = new RSACryptoServiceProvider(1024);',
      c='var rsa = new RSACryptoServiceProvider(2048);'),
    # ---- inj: injection ----
    r(id="cs-sql-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL command built by string concatenation",
      desc="A SqlCommand text is assembled with + or string interpolation of variables.",
      rationale="Concatenating input into SQL enables injection (CWE-89). Use parameterized commands.",
      remediation="Use SqlCommand parameters (@p) and cmd.Parameters.Add.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'new\s+SqlCommand\(\s*(\$?"[^"]*"\s*\+|\$"[^"]*\{)',
      nc='var cmd = new SqlCommand("SELECT * FROM u WHERE n = " + name, conn);',
      c='var cmd = new SqlCommand("SELECT * FROM u WHERE n = @n", conn);'),
    r(id="cs-process-start-var", type="hotspot", qual="sec", sev="high", cwe="CWE-78",
      title="Process.Start with a non-literal argument",
      desc="Process.Start is invoked with a variable/expression, which may run an attacker-controlled command.",
      rationale="Starting a process from untrusted input enables command injection (CWE-78). Validate the target and pass arguments separately.",
      remediation="Use a fixed executable with a validated ProcessStartInfo.ArgumentList.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'Process\.Start\(\s*[a-z_]\w*\s*[,)]',
      nc='Process.Start(userCmd);',
      c='Process.Start("dotnet", "--version");'),
    r(id="cs-xxe-dtd-parse", type="vuln", qual="sec", sev="high", cwe="CWE-611",
      title="XML DTD processing enabled",
      desc="XmlReaderSettings sets DtdProcessing.Parse, enabling XML external entity attacks.",
      rationale="Allowing DTD processing lets an attacker read files or trigger SSRF via external entities (CWE-611).",
      remediation="Set DtdProcessing = DtdProcessing.Prohibit and XmlResolver = null.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r'DtdProcessing\s*=\s*DtdProcessing\.Parse',
      nc='settings.DtdProcessing = DtdProcessing.Parse;',
      c='settings.DtdProcessing = DtdProcessing.Prohibit;'),
    r(id="cs-binaryformatter", type="vuln", qual="sec", sev="high", cwe="CWE-502",
      title="BinaryFormatter deserialization",
      desc="BinaryFormatter is used; deserializing untrusted data with it enables remote code execution.",
      rationale="BinaryFormatter is unsafe and deprecated because malicious payloads can execute on deserialization (CWE-502).",
      remediation="Use a safe serializer (System.Text.Json) and never BinaryFormatter on untrusted data.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+BinaryFormatter\b',
      nc='var obj = new BinaryFormatter().Deserialize(stream);',
      c='var obj = JsonSerializer.Deserialize<T>(json);'),
    r(id="cs-json-typenamehandling", type="vuln", qual="sec", sev="high", cwe="CWE-502",
      title="Json.NET TypeNameHandling enabled",
      desc="TypeNameHandling.All/Auto/Objects lets embedded type names drive deserialization, enabling RCE.",
      rationale="Non-None TypeNameHandling instantiates attacker-named types during deserialization (CWE-502).",
      remediation="Use TypeNameHandling.None, or a strict SerializationBinder.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'TypeNameHandling\s*=\s*TypeNameHandling\.(All|Auto|Objects|Arrays)',
      nc='var s = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };',
      c='var s = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.None };'),
    r(id="cs-cert-validation-bypass", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="TLS certificate validation always returns true",
      desc="A ServerCertificateValidationCallback / RemoteCertificateValidationCallback returns true unconditionally.",
      rationale="Always accepting certificates disables TLS authentication and enables man-in-the-middle (CWE-295).",
      remediation="Validate the certificate chain and errors; do not return true unconditionally.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'ServerCertificateValidationCallback\s*(=|\+=)\s*.*=>\s*true',
      nc='ServicePointManager.ServerCertificateValidationCallback = (s, c, ch, e) => true;',
      c='ServicePointManager.ServerCertificateValidationCallback = (s, c, ch, e) => e == SslPolicyErrors.None;'),
    r(id="cs-response-write-var", type="hotspot", qual="sec", sev="medium", cwe="CWE-79",
      title="Response.Write with a variable (possible XSS)",
      desc="Response.Write outputs a non-literal value, which may reflect unencoded input.",
      rationale="Writing raw input to the response can inject script (CWE-79). Encode output for HTML.",
      remediation="HTML-encode the value (HttpUtility.HtmlEncode) or use a framework that auto-encodes.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'Response\.Write\(\s*[a-z_]\w*\s*\)',
      nc='Response.Write(comment);',
      c='Response.Write(HttpUtility.HtmlEncode(comment));'),
    # ---- err: error handling ----
    r(id="cs-empty-catch", type="bug", qual="rel", sev="medium", cwe="CWE-390",
      title="Empty catch block",
      desc="A catch block has no body, silently swallowing the exception.",
      rationale="An empty catch hides failures and complicates debugging (CWE-390).",
      remediation="Handle, log, or rethrow the exception.",
      source="https://cwe.mitre.org/data/definitions/390.html",
      re=r'catch\s*(\([^)]*\))?\s*\{\s*\}',
      nc='try { Load(); } catch (IOException) {}',
      c='try { Load(); } catch (IOException e) { log.LogWarning(e, "load"); }'),
    r(id="cs-catch-general", type="smell", qual="maint", sev="low", cwe="",
      title="Catching System.Exception",
      desc="A catch clause catches the base Exception (or System.Exception) type.",
      rationale="Catching Exception obscures which failures are handled and can swallow programming errors; catch specific types.",
      remediation="Catch the specific exception types the code can recover from.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031",
      re=r'catch\s*\(\s*(System\.)?Exception(\s+\w+)?\s*\)',
      nc='try { Work(); } catch (Exception ex) { Handle(ex); }',
      c='try { Work(); } catch (SqlException ex) { Handle(ex); }'),
    r(id="cs-throw-ex-loses-stack", type="bug", qual="rel", sev="medium", cwe="",
      title="`throw ex;` discards the stack trace",
      desc="Re-throwing with `throw ex;` resets the exception's stack trace.",
      rationale="`throw ex;` overwrites the original stack trace, hiding where the error occurred; use `throw;`.",
      remediation="Use `throw;` to preserve the stack trace, or wrap with an inner exception.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200",
      re=r'\bthrow\s+\w+\s*;',
      nc='catch (Exception ex) { Cleanup(); throw ex; }',
      c='catch (Exception ex) { Cleanup(); throw; }'),
    r(id="cs-catch-rethrow-only", type="smell", qual="maint", sev="low", cwe="",
      title="Catch block that only rethrows",
      desc="A catch clause whose only statement is `throw;` adds nothing.",
      rationale="Catching just to rethrow is dead code that obscures the flow; remove the try/catch or add handling.",
      remediation="Remove the redundant catch, or add real handling.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200",
      re=r'catch\s*(\([^)]*\))?\s*\{\s*throw\s*;\s*\}',
      nc='try { Do(); } catch (Exception) { throw; }',
      c='try { Do(); } finally { Cleanup(); }'),
    # ---- api / async ----
    r(id="cs-async-void", type="bug", qual="rel", sev="high", cwe="",
      title="async void method",
      desc="A method is declared async void (outside an event handler), so its exceptions cannot be awaited or caught.",
      rationale="async void cannot be awaited and its exceptions crash the process; use async Task.",
      remediation="Return Task from async methods; reserve async void for event handlers.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'\basync\s+void\s+\w+\s*\(',
      nc='public async void LoadAsync() { await Fetch(); }',
      c='public async Task LoadAsync() { await Fetch(); }'),
    r(id="cs-task-result-blocking", type="bug", qual="rel", sev="high", cwe="",
      title="Blocking on a Task with .Result or .Wait()",
      desc="Synchronously blocking on a Task via .Result or .Wait() can deadlock in a sync context.",
      rationale="Blocking on async work can deadlock (e.g. in ASP.NET/UI sync contexts) and wastes a thread; await instead.",
      remediation="await the task rather than calling .Result / .Wait().",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'\.(Result|Wait\(\))(\s*;|\.)',
      nc='var data = FetchAsync().Result;',
      c='var data = await FetchAsync();'),
    r(id="cs-thread-abort", type="bug", qual="rel", sev="medium", cwe="",
      title="Thread.Abort() used",
      desc="Thread.Abort forcibly terminates a thread and is unsafe/obsolete.",
      rationale="Thread.Abort can corrupt state by interrupting at arbitrary points and is not supported on modern .NET.",
      remediation="Use cooperative cancellation with CancellationToken.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.abort",
      re=r'\.Abort\s*\(\s*\)',
      nc='worker.Abort();',
      c='cts.Cancel();'),
    r(id="cs-gc-collect", type="smell", qual="maint", sev="medium", cwe="",
      title="Explicit GC.Collect() call",
      desc="GC.Collect forces a garbage collection, usually hurting performance.",
      rationale="Manual collection interferes with the runtime's tuned GC and rarely helps.",
      remediation="Remove GC.Collect; let the runtime manage collection.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1806",
      re=r'\bGC\.Collect\s*\(',
      nc='GC.Collect();',
      c='// rely on the runtime GC'),
    r(id="cs-environment-exit", type="smell", qual="maint", sev="medium", cwe="",
      title="Environment.Exit in library code",
      desc="Environment.Exit terminates the whole process, which library code must not do.",
      rationale="Exiting the process from a library kills unrelated work and skips cleanup; throw instead.",
      remediation="Throw an exception and let the host decide how to terminate.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.environment.exit",
      re=r'\bEnvironment\.Exit\s*\(',
      nc='if (fatal) Environment.Exit(1);',
      c='if (fatal) throw new InvalidOperationException("fatal");'),
    r(id="cs-console-writeline-lib", type="smell", qual="maint", sev="low", cwe="",
      title="Console.WriteLine used instead of a logger",
      desc="Console.Write/WriteLine bypasses the logging framework.",
      rationale="Direct console output cannot be leveled, routed, or disabled in production; use ILogger.",
      remediation="Log through ILogger.",
      source="https://learn.microsoft.com/en-us/dotnet/core/extensions/logging",
      re=r'\bConsole\.(Write|WriteLine)\s*\(',
      nc='Console.WriteLine("starting");',
      c='logger.LogInformation("starting");'),
    r(id="cs-string-format-sql", type="vuln", qual="sec", sev="high", cwe="CWE-89",
      title="SQL built with string.Format",
      desc="A SQL command text is produced with string.Format and inserted values.",
      rationale="string.Format into SQL text is injectable just like concatenation (CWE-89).",
      remediation="Use parameterized queries instead of formatting values into SQL.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'new\s+SqlCommand\(\s*string\.Format\(',
      nc='var cmd = new SqlCommand(string.Format("SELECT * FROM u WHERE id={0}", id), conn);',
      c='var cmd = new SqlCommand("SELECT * FROM u WHERE id=@id", conn);'),
    # ---- maint / style ----
    r(id="cs-public-mutable-field", type="smell", qual="maint", sev="low", cwe="",
      title="Public non-readonly field",
      desc="A public instance field is exposed without readonly, breaking encapsulation.",
      rationale="Public mutable fields expose internal state and cannot enforce invariants; use a property.",
      remediation="Expose a property, or make the field readonly.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051",
      re=r'^\s*public\s+[\w<>\[\].]+\s+\w+\s*;\s*$',
      nc='    public int Count;',
      c='    public int Count { get; private set; }'),
    r(id="cs-todo-marker", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="TODO/FIXME marker (tracked debt)",
      desc="A TODO/FIXME/HACK comment marks unfinished work.",
      rationale="Such markers record known incomplete work; surfacing them keeps the debt tracked (ISO/IEC 25010).",
      remediation="Resolve the item or link it to a tracked issue.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'//\s*(TODO|FIXME|HACK)\b',
      nc='// TODO: validate the input length',
      c='// validates the input length below'),
    r(id="cs-empty-block", type="smell", qual="maint", sev="low", cwe="",
      title="Empty statement block",
      desc="A control-flow block (if/else/while/for) has an empty body.",
      rationale="An empty block is usually a mistake or dead code; remove it or add the intended logic.",
      remediation="Remove the empty block or implement the intended behavior.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\b(if|else|while|for|foreach)\s*(\([^)]*\))?\s*\{\s*\}',
      nc='if (ready) {}',
      c='if (ready) { Start(); }'),
    r(id="cs-empty-finally", type="smell", qual="maint", sev="low", cwe="",
      title="Empty finally block",
      desc="A finally block has no body.",
      rationale="An empty finally adds noise and suggests missing cleanup.",
      remediation="Remove the empty finally or add the cleanup it was meant to hold.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\bfinally\s*\{\s*\}',
      nc='try { Do(); } finally {}',
      c='try { Do(); } finally { handle.Dispose(); }'),
    r(id="cs-goto", type="smell", qual="maint", sev="low", cwe="",
      title="goto statement",
      desc="A goto transfers control non-linearly, hurting readability.",
      rationale="goto makes control flow hard to follow; structured constructs are clearer.",
      remediation="Refactor to loops, methods, or early returns.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/jump-statements",
      re=r'^\s*goto\s+\w+\s*;',
      nc='    goto retry;',
      c='    continue;'),
    r(id="cs-lock-this", type="bug", qual="rel", sev="medium", cwe="CWE-662",
      title="lock(this) or lock on a public object",
      desc="Locking on `this` (or a public field) lets external code deadlock the instance.",
      rationale="External code can lock the same public object, causing deadlocks (CWE-662). Lock on a private object.",
      remediation="Lock on a private readonly object dedicated to the guard.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2002",
      re=r'\block\s*\(\s*this\s*\)',
      nc='lock (this) { balance += amount; }',
      c='lock (_sync) { balance += amount; }'),
    r(id="cs-httpclient-per-request", type="bug", qual="rel", sev="medium", cwe="",
      title="HttpClient instantiated per use",
      desc="`new HttpClient()` inside a using/short scope exhausts sockets under load.",
      rationale="Creating and disposing HttpClient per request leaks sockets (TIME_WAIT exhaustion); reuse a single client or IHttpClientFactory.",
      remediation="Reuse a static HttpClient or inject one via IHttpClientFactory.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000",
      re=r'\busing\s*\(\s*var\s+\w+\s*=\s*new\s+HttpClient\s*\(',
      nc='using (var client = new HttpClient()) { await client.GetAsync(url); }',
      c='var response = await _httpClient.GetAsync(url);'),
    r(id="cs-obsolete-webclient", type="smell", qual="maint", sev="low", cwe="",
      title="Obsolete WebClient used",
      desc="System.Net.WebClient is legacy; HttpClient is the supported API.",
      rationale="WebClient is superseded by HttpClient, which offers async and better resource handling.",
      remediation="Use HttpClient.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.net.webclient",
      re=r'\bnew\s+WebClient\s*\(',
      nc='var wc = new WebClient();',
      c='var response = await _httpClient.GetAsync(url);'),
    r(id="cs-string-concat-loop-append", type="smell", qual="maint", sev="low", cwe="",
      title="String built with += (use StringBuilder)",
      desc="A string is grown with += , which reallocates on each step.",
      rationale="Repeated string += allocates a new string each time; a StringBuilder is O(n).",
      remediation="Accumulate with StringBuilder.Append.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854",
      re=r'^\s*\w+\s*\+=\s*"',
      nc='    result += ", " ;',
      c='    sb.Append(", ");'),
    r(id="cs-empty-interface", type="smell", qual="maint", sev="low", cwe="",
      title="Empty (marker) interface",
      desc="An interface declares no members.",
      rationale="Marker interfaces are better expressed as attributes in .NET (CA1040).",
      remediation="Use a custom attribute instead of a marker interface.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1040",
      re=r'\binterface\s+I\w+\s*\{\s*\}',
      nc='public interface IMarker {}',
      c='[AttributeUsage(AttributeTargets.Class)] public sealed class MarkerAttribute : Attribute {}'),
    r(id="cs-not-implemented", type="bug", qual="rel", sev="medium", cwe="",
      title="throw new NotImplementedException()",
      desc="A member throws NotImplementedException, i.e. it is unfinished.",
      rationale="Unimplemented members shipped to production fail at runtime; finish or remove them.",
      remediation="Implement the member, or remove it until it is ready.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.notimplementedexception",
      re=r'throw\s+new\s+NotImplementedException\s*\(',
      nc='public int Total() { throw new NotImplementedException(); }',
      c='public int Total() { return _items.Sum(); }'),
    r(id="cs-debug-assert-sideeffect", type="smell", qual="maint", sev="low", cwe="",
      title="Console.ReadLine()/ReadKey() left in code",
      desc="A blocking Console.ReadLine/ReadKey pauses execution, usually leftover debugging.",
      rationale="A blocking console read stalls non-interactive runs (services, tests).",
      remediation="Remove the debug pause.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.console.readline",
      re=r'\bConsole\.(ReadLine|ReadKey)\s*\(',
      nc='Console.ReadLine();',
      c='// no interactive pause'),
    r(id="cs-empty-string-compare", type="smell", qual="maint", sev="low", cwe="",
      title='Comparison to "" instead of Length/IsNullOrEmpty',
      desc='A string is compared to "" with == / !=.',
      rationale='Comparing to "" is less clear and less null-safe than string.IsNullOrEmpty or Length == 0.',
      remediation="Use string.IsNullOrEmpty(s) or s.Length == 0.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1820",
      re=r'(==|!=)\s*""|""\s*(==|!=)',
      nc='if (name == "") return;',
      c='if (string.IsNullOrEmpty(name)) return;'),
    r(id="cs-tostring-culture", type="smell", qual="maint", sev="low", cwe="",
      title="ToString/Parse without a culture",
      desc="A numeric/date ToString or Parse is called without an explicit IFormatProvider.",
      rationale="Culture-dependent formatting/parsing produces locale-varying results; specify CultureInfo.InvariantCulture for machine-readable data (CA1305).",
      remediation="Pass CultureInfo.InvariantCulture (or the intended culture).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305",
      re=r'(int|long|double|decimal|DateTime)\.Parse\(\s*\w+\s*\)',
      nc='var n = int.Parse(raw);',
      c='var n = int.Parse(raw, CultureInfo.InvariantCulture);'),
    r(id="cs-equals-null", type="smell", qual="maint", sev="low", cwe="",
      title="Reference compared with .Equals(null)",
      desc="x.Equals(null) is called, which can itself throw if x is null.",
      rationale="Calling .Equals(null) can NRE and is clearer as `is null`.",
      remediation="Use `x is null` (or ReferenceEquals).",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns",
      re=r'\.Equals\(\s*null\s*\)',
      nc='if (value.Equals(null)) return;',
      c='if (value is null) return;'),
    r(id="cs-async-no-await", type="smell", qual="maint", sev="low", cwe="",
      title="Task returned via .Result inside an async chain",
      desc="Sync-over-async: awaiting is skipped and .GetAwaiter().GetResult() blocks.",
      rationale="GetAwaiter().GetResult() blocks a thread and can deadlock; await instead.",
      remediation="await the task.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'\.GetAwaiter\(\)\.GetResult\(\)',
      nc='var v = FetchAsync().GetAwaiter().GetResult();',
      c='var v = await FetchAsync();'),
    r(id="cs-hardcoded-conn-string", type="hotspot", qual="sec", sev="high", cwe="CWE-798",
      title="Connection string with an inline password",
      desc="A connection string literal contains Password=/Pwd= with a value.",
      rationale="Hardcoded credentials in source leak secrets (CWE-798). Load them from configuration/secret storage.",
      remediation="Read the connection string from configuration or a secret store.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'"[^"]*(Password|Pwd)\s*=\s*[^;"\s][^"]*"',
      nc='var cs = "Server=db;User Id=sa;Password=Sup3rSecret;";',
      c='var cs = configuration.GetConnectionString("Default");'),
    r(id="cs-path-combine-request", type="vuln", qual="sec", sev="high", cwe="CWE-22",
      title="Path.Combine with request input",
      desc="Path.Combine mixes a root with request-derived input, enabling directory traversal.",
      rationale="A request-controlled path segment can escape the root via ../ (CWE-22). Validate the resolved path stays within the root.",
      remediation="Validate Path.GetFullPath(result) starts with the intended root.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'Path\.Combine\([^)]*(Request\.|Request\[)',
      nc='var p = Path.Combine(root, Request.Query["file"]);',
      c='var p = SafeResolve(root, fileName);'),
    r(id="cs-weak-pbkdf-iterations", type="hotspot", qual="sec", sev="medium", cwe="CWE-916",
      title="Low PBKDF2 iteration count",
      desc="Rfc2898DeriveBytes is created with a small iteration count.",
      rationale="Too few iterations makes password hashing cheap to brute-force (CWE-916). Use a high count.",
      remediation="Use a high iteration count (100k+), or Argon2/scrypt.",
      source="https://cwe.mitre.org/data/definitions/916.html",
      re=r'new\s+Rfc2898DeriveBytes\([^)]*,\s*(1000|100|10|[1-9]|[1-9]\d{1,3})\s*[,)]',
      nc='var kdf = new Rfc2898DeriveBytes(pwd, salt, 1000);',
      c='var kdf = new Rfc2898DeriveBytes(pwd, salt, 210000, HashAlgorithmName.SHA256);'),
]
