# C# language-pack rule specs, batch 9 (#189). Clean-room, line-detectable — ADO.NET provider SQLi sinks,
# WCF security, weak KDF, hardcoded conn-string password, XAML/JS deserialization, getter-throws.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


def sqli(provider, cls):
    return r(id=f"cs-{provider}-command-concat", type="vuln", qual="sec", sev="high",
             cwe="CWE-89", owasp="A03:2021",
             title=f"{cls} built by string concatenation",
             desc=f"A {cls} text is concatenated from a variable.",
             rationale="Concatenating input into SQL enables SQL injection (CWE-89). Use parameters.",
             remediation="Use a parameterized command with named parameters.",
             source="https://cwe.mitre.org/data/definitions/89.html",
             re=rf'new\s+{cls}\([^)]*\+',
             nc=f'var cmd = new {cls}("SELECT * FROM t WHERE id=" + id);',
             c=f'var cmd = new {cls}("SELECT * FROM t WHERE id=@id");')


RULES = [
    sqli("oledb", "OleDbCommand"),
    sqli("odbc", "OdbcCommand"),
    sqli("mysql", "MySqlCommand"),
    sqli("npgsql", "NpgsqlCommand"),
    sqli("sqlite", "SQLiteCommand"),
    r(id="cs-passwordderivebytes", type="vuln", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="PasswordDeriveBytes (weak PBKDF1)",
      desc="PasswordDeriveBytes implements the weak PBKDF1 key-derivation function.",
      rationale="PBKDF1 is obsolete and unsuitable for deriving keys/passwords (CWE-327).",
      remediation="Use Rfc2898DeriveBytes (PBKDF2) with a high iteration count and SHA-256.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bPasswordDeriveBytes\b',
      nc='var kdf = new PasswordDeriveBytes(pwd, salt);',
      c='var kdf = new Rfc2898DeriveBytes(pwd, salt, 100000, HashAlgorithmName.SHA256);'),
    r(id="cs-wcf-security-none", type="vuln", qual="sec", sev="high", cwe="CWE-319", owasp="A02:2021",
      title="WCF binding with SecurityMode.None",
      desc="A WCF binding is created with SecurityMode.None.",
      rationale="SecurityMode.None disables transport and message security, sending data in cleartext (CWE-319).",
      remediation="Use SecurityMode.Transport or Message.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'SecurityMode\.None\b',
      nc='var b = new WSHttpBinding(SecurityMode.None);',
      c='var b = new WSHttpBinding(SecurityMode.Transport);'),
    r(id="cs-wcf-exception-detail", type="vuln", qual="sec", sev="medium", cwe="CWE-209", owasp="A05:2021",
      title="WCF IncludeExceptionDetailInFaults enabled",
      desc="A service behavior sets IncludeExceptionDetailInFaults to true.",
      rationale="Returning exception details in faults leaks stack traces and internals to clients (CWE-209).",
      remediation="Set IncludeExceptionDetailInFaults=false and return sanitized faults.",
      source="https://cwe.mitre.org/data/definitions/209.html",
      re=r'IncludeExceptionDetailInFaults\s*=\s*true\b',
      nc='behavior.IncludeExceptionDetailInFaults = true;',
      c='behavior.IncludeExceptionDetailInFaults = false;'),
    r(id="cs-jsserializer-typeresolver", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="JavaScriptSerializer with a type resolver",
      desc="JavaScriptSerializer is constructed with a SimpleTypeResolver, enabling polymorphic deserialization.",
      rationale="A type resolver lets the payload choose the CLR type, opening gadget-chain RCE (CWE-502).",
      remediation="Deserialize to known types without a type resolver (or use System.Text.Json).",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'new\s+JavaScriptSerializer\(\s*new\s+SimpleTypeResolver',
      nc='var s = new JavaScriptSerializer(new SimpleTypeResolver());',
      c='var s = new JavaScriptSerializer();'),
    r(id="cs-connstring-password-literal", type="hotspot", qual="sec", sev="medium", cwe="CWE-798", owasp="A07:2021",
      title="Hard-coded password in a connection string",
      desc="A connection-string literal contains an inline Password= value.",
      rationale="A password embedded in source is exposed to anyone with the code or binary (CWE-798).",
      remediation="Load the password from a secret store / configuration.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'Password\s*=\s*[^;"\s@${]+;',
      nc='var cs = "Server=db;User Id=app;Password=hunter2;";',
      c='var cs = $"Server=db;User Id=app;Password={secret};";'),
    r(id="cs-process-args-concat", type="vuln", qual="sec", sev="high", cwe="CWE-88", owasp="A03:2021",
      title="Process arguments built by concatenation",
      desc="ProcessStartInfo.Arguments is concatenated from a variable.",
      rationale="Concatenating input into a command line enables argument/command injection (CWE-88).",
      remediation="Use ArgumentList to pass each argument as a separate token.",
      source="https://cwe.mitre.org/data/definitions/88.html",
      re=r'\.Arguments\s*=\s*"[^"]*"\s*\+',
      nc='psi.Arguments = "/c " + userInput;',
      c='psi.ArgumentList.Add(userInput);'),
    r(id="cs-xamlreader-load", type="vuln", qual="sec", sev="high", cwe="CWE-502", owasp="A08:2021",
      title="XamlReader.Load/Parse on untrusted XAML",
      desc="XAML is materialized via XamlReader.Load/Parse.",
      rationale="XAML can instantiate arbitrary types and invoke members, so untrusted XAML is RCE (CWE-502).",
      remediation="Do not load untrusted XAML; restrict to known, static templates.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'XamlReader\.(Load|Parse)\(',
      nc='var view = XamlReader.Parse(userXaml);',
      c='var view = LoadKnownTemplate(templateId);'),
    r(id="cs-tostring-in-interpolation", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant ToString() in an interpolation hole",
      desc="An interpolated string calls .ToString() on the interpolated expression.",
      rationale="String interpolation already calls ToString on each hole; the explicit call is redundant.",
      remediation="Remove the .ToString() call (use a format specifier if needed).",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated",
      re=r'\{[^{}]*\.ToString\(\)\}',
      nc='var s = $"id={order.Id.ToString()}";',
      c='var s = $"id={order.Id}";'),
    r(id="cs-getter-throws", type="smell", qual="maint", sev="low", cwe="",
      title="Property getter throws",
      desc="A property getter's body throws an exception.",
      rationale="Getters should be simple and side-effect-free; throwing from a getter surprises callers (CA1065).",
      remediation="Expose a method (e.g. GetX()) for operations that can fail.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065",
      re=r'\bget\s*(?:=>|\{)\s*throw\b',
      nc='public string Name { get => throw new InvalidOperationException(); }',
      c='public string Name { get => _name; }'),
    r(id="cs-thread-currentprincipal-set", type="smell", qual="maint", sev="low", cwe="",
      title="Thread.CurrentPrincipal assigned",
      desc="The security principal is set on the current thread.",
      rationale="Thread.CurrentPrincipal does not flow reliably across async/await and thread-pool hops; carry identity in the request context.",
      remediation="Use the framework's request-scoped identity (e.g. HttpContext.User / ClaimsPrincipal).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.currentprincipal",
      re=r'Thread\.CurrentPrincipal\s*=',
      nc='Thread.CurrentPrincipal = principal;',
      c='httpContext.User = principal;'),
]
