# C# language-pack rule specs, batch 7 (#189). Clean-room, line-detectable — connection-string TLS,
# weak crypto params, off-by-one / OOB, null-deref (OrDefault/as), ignored immutable results, LDAP/path.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-connstring-trustservercert", type="vuln", qual="sec", sev="medium", cwe="CWE-295", owasp="A07:2021",
      title="SQL connection trusts the server certificate",
      desc="TrustServerCertificate is set to true, so the SQL Server certificate is not validated.",
      rationale="Trusting any server certificate enables man-in-the-middle attacks on the database connection (CWE-295).",
      remediation="Set TrustServerCertificate=false and install a valid certificate chain.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'TrustServerCertificate\s*=\s*[Tt]rue\b',
      nc='builder.TrustServerCertificate = true;',
      c='builder.TrustServerCertificate = false;'),
    r(id="cs-connstring-encrypt-false", type="vuln", qual="sec", sev="medium", cwe="CWE-319", owasp="A02:2021",
      title="SQL connection encryption disabled",
      desc="Encrypt is set to false on a SQL connection string builder.",
      rationale="Disabling transport encryption exposes credentials and data on the wire (CWE-319).",
      remediation="Set Encrypt=true.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'\bEncrypt\s*=\s*[Ff]alse\b',
      nc='builder.Encrypt = false;',
      c='builder.Encrypt = true;'),
    r(id="cs-jwt-validate-audience-false", type="vuln", qual="sec", sev="high", cwe="CWE-347", owasp="A02:2021",
      title="JWT audience validation disabled",
      desc="TokenValidationParameters sets ValidateAudience to false.",
      rationale="Skipping audience validation lets a token minted for another service be replayed here (CWE-347).",
      remediation="Set ValidateAudience=true and configure ValidAudience(s).",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r'ValidateAudience\s*=\s*false\b',
      nc='tvp.ValidateAudience = false;',
      c='tvp.ValidateAudience = true;'),
    r(id="cs-tripledes-weak", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Triple DES (3DES) cipher",
      desc="TripleDES is used for encryption.",
      rationale="3DES has a 64-bit block and is deprecated (SWEET32); use AES (CWE-327).",
      remediation="Use AES (Aes.Create).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bTripleDES\w*',
      nc='var alg = TripleDES.Create();',
      c='var alg = Aes.Create();'),
    r(id="cs-static-iv", type="vuln", qual="sec", sev="high", cwe="CWE-329", owasp="A02:2021",
      title="Hard-coded/static initialization vector",
      desc="A symmetric algorithm's IV is assigned from a fixed byte array literal.",
      rationale="A reused/static IV in CBC/GCM breaks semantic security and can leak plaintext (CWE-329).",
      remediation="Generate a fresh random IV per message (alg.GenerateIV) and transmit it alongside the ciphertext.",
      source="https://cwe.mitre.org/data/definitions/329.html",
      re=r'\bIV\s*=\s*new\s+byte\[\]\s*\{',
      nc='aes.IV = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0 };',
      c='aes.GenerateIV();'),
    r(id="cs-cleartext-http-baseaddress", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021",
      title="HttpClient base address uses http://",
      desc="An HttpClient BaseAddress is built from a cleartext http:// URL.",
      rationale="Cleartext HTTP exposes traffic to interception and tampering (CWE-319).",
      remediation="Use https:// for the base address.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'BaseAddress\s*=\s*new\s+Uri\(\s*"http://',
      nc='client.BaseAddress = new Uri("http://api.example.com");',
      c='client.BaseAddress = new Uri("https://api.example.com");'),
    r(id="cs-ftp-cleartext", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021",
      title="Cleartext FTP URL",
      desc="A plain ftp:// URL is used for a transfer.",
      rationale="FTP transmits credentials and data in cleartext (CWE-319); use FTPS or SFTP.",
      remediation="Use ftps:// (or SFTP).",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'"ftp://',
      nc='var url = "ftp://files.example.com/data.csv";',
      c='var url = "ftps://files.example.com/data.csv";'),
    r(id="cs-off-by-one-length", type="bug", qual="rel", sev="high", cwe="CWE-193",
      title="Loop bound uses <= Length/Count",
      desc="A loop condition compares an index with <= collection.Length/Count.",
      rationale="Indices run 0..Length-1, so <= Length reads one past the end (CWE-193, IndexOutOfRange).",
      remediation="Use < Length / < Count.",
      source="https://cwe.mitre.org/data/definitions/193.html",
      re=r'<=\s*\w+\.(Length|Count)\s*[;)]',
      nc='for (int i = 0; i <= items.Length; i++) Use(items[i]);',
      c='for (int i = 0; i < items.Length; i++) Use(items[i]);'),
    r(id="cs-index-at-length", type="bug", qual="rel", sev="high", cwe="CWE-125",
      title="Indexing arr[arr.Length]",
      desc="An element is accessed at index Length, which is out of bounds.",
      rationale="The last valid index is Length-1; arr[arr.Length] throws IndexOutOfRange (CWE-125).",
      remediation="Use arr[arr.Length - 1] (or the ^1 index).",
      source="https://cwe.mitre.org/data/definitions/125.html",
      re=r'\[\s*\w+\.Length\s*\]',
      nc='var last = data[data.Length];',
      c='var last = data[data.Length - 1];'),
    r(id="cs-ordefault-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing a *OrDefault() result",
      desc="A member is accessed directly on the result of FirstOrDefault/SingleOrDefault/LastOrDefault.",
      rationale="These return null (or default) when no element matches, so an immediate member access can NRE (CWE-476).",
      remediation="Check the result for null, or use First/Single when a match is guaranteed.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\.(FirstOrDefault|SingleOrDefault|LastOrDefault)\([^)]*\)\.\w',
      nc='var name = users.FirstOrDefault(u => u.Id == id).Name;',
      c='var user = users.FirstOrDefault(u => u.Id == id); var name = user?.Name;'),
    r(id="cs-tolist-toarray-redundant", type="smell", qual="maint", sev="low", cwe="",
      title="Redundant ToList().ToArray()",
      desc="A sequence is materialized to a list and then copied to an array.",
      rationale="ToList().ToArray() allocates twice; call ToArray() directly.",
      remediation="Use ToArray() alone.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.toarray",
      re=r'\.ToList\(\)\s*\.ToArray\(\)',
      nc='var a = query.ToList().ToArray();',
      c='var a = query.ToArray();'),
    r(id="cs-as-cast-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Member access on an (x as T) result",
      desc="A member is accessed on a parenthesized as-cast without a null check.",
      rationale="`as` yields null on a type mismatch, so an immediate member access can NRE (CWE-476).",
      remediation="Null-check the as-result, or use pattern matching (if (x is T t)).",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\(\s*\w+\s+as\s+\w[\w<>.]*\)\.\w',
      nc='var len = (value as string).Length;',
      c='if (value is string s) { var len = s.Length; }'),
    r(id="cs-datetime-add-result-ignored", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="DateTime Add* result ignored",
      desc="A DateTime Add*/Subtract result is discarded; DateTime is immutable.",
      rationale="AddDays/AddHours/etc. return a new value; ignoring it leaves the original unchanged (CWE-252).",
      remediation="Assign the result: date = date.AddDays(n).",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*\w+\.Add(Days|Hours|Minutes|Seconds|Milliseconds|Months|Years|Ticks)\([^;]*\)\s*;',
      nc='dueDate.AddDays(7);',
      c='dueDate = dueDate.AddDays(7);'),
    r(id="cs-string-result-ignored", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="String transform result ignored",
      desc="The result of an immutable string method is discarded as a statement.",
      rationale="Strings are immutable; Trim/Substring/ToUpper/etc. return a new string, so ignoring it is a no-op (CWE-252).",
      remediation="Assign the returned string.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*\w+\.(Trim|TrimStart|TrimEnd|ToUpper|ToLower|Substring|PadLeft|PadRight)\([^;]*\)\s*;',
      nc='input.Trim();',
      c='input = input.Trim();'),
    r(id="cs-linq-result-ignored", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="Deferred LINQ result ignored",
      desc="A deferred LINQ operator's result is discarded as a statement.",
      rationale="Where/Select/OrderBy/Distinct are lazy and side-effect-free; discarding the result does nothing (CWE-252).",
      remediation="Consume the result (assign or materialize it), or drop the dead statement.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*\w+\.(Where|Select|OrderBy|OrderByDescending|Distinct)\([^;]*\)\s*;',
      nc='items.Where(x => x.Active);',
      c='var active = items.Where(x => x.Active).ToList();'),
    r(id="cs-throw-null", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="throw null",
      desc="Code executes throw null, which raises a NullReferenceException.",
      rationale="throw null throws an NRE rather than a meaningful exception (CWE-476).",
      remediation="Throw a specific exception with a message.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\bthrow\s+null\s*;',
      nc='throw null;',
      c='throw new InvalidOperationException("state not initialized");'),
    r(id="cs-new-exception-discarded", type="bug", qual="rel", sev="medium", cwe="",
      title="Exception constructed but not thrown",
      desc="An exception object is created as a statement and immediately discarded.",
      rationale="Constructing an exception without throwing (or storing) it is almost always a missing throw.",
      remediation="throw the exception (or assign it).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'^\s*new\s+\w*Exception\([^;]*\)\s*;',
      nc='new InvalidOperationException("bad state");',
      c='throw new InvalidOperationException("bad state");'),
    r(id="cs-empty-switch", type="smell", qual="maint", sev="low", cwe="",
      title="Empty switch statement",
      desc="A switch has no case bodies.",
      rationale="An empty switch is dead control flow, usually a stub.",
      remediation="Implement the cases or remove the switch.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/selection-statements",
      re=r'\bswitch\s*\(.*\)\s*\{\s*\}',
      nc='switch (state) { }',
      c='switch (state) { case State.Open: Handle(); break; }'),
    r(id="cs-ldap-searcher-concat", type="vuln", qual="sec", sev="high", cwe="CWE-90", owasp="A03:2021",
      title="LDAP filter built by concatenation",
      desc="A DirectorySearcher filter is concatenated from a variable.",
      rationale="Unescaped input in an LDAP filter allows LDAP injection (CWE-90).",
      remediation="Escape the input per RFC 4515 before building the filter.",
      source="https://cwe.mitre.org/data/definitions/90.html",
      re=r'new\s+DirectorySearcher\([^)]*\+',
      nc='var s = new DirectorySearcher("(uid=" + user + ")");',
      c='var s = new DirectorySearcher(BuildEscapedFilter(user));'),
    r(id="cs-server-mappath-tainted", type="vuln", qual="sec", sev="high", cwe="CWE-22", owasp="A01:2021",
      title="Server.MapPath on request input",
      desc="Server.MapPath is called with a value taken from the request.",
      rationale="Mapping request-controlled paths enables directory traversal outside the web root (CWE-22).",
      remediation="Validate against an allow-list and canonicalize before mapping.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'Server\.MapPath\([^)]*[Rr]equest',
      nc='var path = Server.MapPath(Request.QueryString["file"]);',
      c='var path = Server.MapPath(ResolveAllowedName(id));'),
    r(id="cs-environment-failfast", type="smell", qual="maint", sev="medium", cwe="",
      title="Environment.FailFast used",
      desc="Environment.FailFast terminates the process without normal cleanup.",
      rationale="FailFast is a blunt instrument that skips finally/dispose and crashes the host; reserve it for truly unrecoverable corruption.",
      remediation="Throw a specific exception and let it propagate, unless state is genuinely unrecoverable.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.environment.failfast",
      re=r'Environment\.FailFast\(',
      nc='Environment.FailFast("unexpected state");',
      c='throw new InvalidOperationException("unexpected state");'),
    r(id="cs-reflection-nonpublic", type="smell", qual="maint", sev="low", cwe="",
      title="Reflection over non-public members",
      desc="BindingFlags.NonPublic is used to access private/internal members.",
      rationale="Reaching private members via reflection breaks encapsulation and is fragile across versions.",
      remediation="Use the public API, or expose a proper extension point.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'BindingFlags\.NonPublic\b',
      nc='var m = t.GetMethod("Secret", BindingFlags.NonPublic | BindingFlags.Instance);',
      c='var m = t.GetMethod("PublicApi");'),
]
