# Rust language-pack rule specs — `api` (API guidelines) + `perf` (performance) + `maint`
# (maintainability) families (#197). Clean-room, line-detectable; concept origins cited.
CC = "commentOnlyLine"


def r(fam, **k):
    k.setdefault("lang", "rust")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k["tags"] = ["sast", "rust", fam]
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- api (6 target) ----
    r("api", id="rust:wildcard-import", type="smell", qual="maint", sev="low", cwe="",
      title="Wildcard import",
      desc="A module is imported with a glob.",
      rationale="Glob imports pull in unknown names and hide where symbols come from (Clippy wildcard_imports).",
      remediation="Import the specific items you use.",
      source="https://rust-lang.github.io/rust-clippy/master/#wildcard_imports",
      re=r'\buse\s+[\w:]+::\*\s*;',
      nc='use std::collections::*;',
      c='use std::collections::HashMap;'),
    r("api", id="rust:self-convention-to", type="smell", qual="maint", sev="low", cwe="",
      title="to_ method takes self by value",
      desc="A to_* conversion consumes self by value.",
      rationale="By convention to_* borrows (&self) and into_* consumes; a by-value to_ misleads callers (Rust API Guidelines C-CONV).",
      remediation="Take &self in to_*, or rename to into_*.",
      source="https://rust-lang.github.io/api-guidelines/naming.html",
      re=r'fn\s+to_\w+\s*\(\s*self\b',
      nc='fn to_bytes(self) -> Vec<u8> {',
      c='fn to_bytes(&self) -> Vec<u8> {'),
    r("api", id="rust:deprecated-no-note", type="smell", qual="maint", sev="low", cwe="", skip="",
      title="deprecated attribute without a note",
      desc="A #[deprecated] attribute gives no migration note.",
      rationale="Without a note, callers get no guidance on the replacement (Rust API Guidelines C-STABLE).",
      remediation="Add note and since fields to #[deprecated].",
      source="https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-deprecated-attribute",
      re=r'#\[deprecated\]',
      nc='#[deprecated]',
      c='#[deprecated(note = "use encode_v2")]'),
    r("api", id="rust:extern-crate", type="smell", qual="maint", sev="low", cwe="",
      title="extern crate declaration",
      desc="A dependency is imported with extern crate.",
      rationale="extern crate is legacy since the 2018 edition; paths use use instead.",
      remediation="Remove extern crate and use a use path.",
      source="https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html",
      re=r'^\s*extern\s+crate\s+\w',
      nc='extern crate serde;',
      c='use serde::Serialize;'),
    r("api", id="rust:type-complexity", type="smell", qual="maint", sev="low", cwe="",
      title="Overly complex type",
      desc="A deeply nested generic type appears in a signature.",
      rationale="Triple-nested containers are hard to read and usually want a type alias (Clippy type_complexity).",
      remediation="Introduce a type alias or a named struct.",
      source="https://rust-lang.github.io/rust-clippy/master/#type_complexity",
      re=r'Vec<Vec<Vec<',
      nc='let x: Vec<Vec<Vec<u8>>> = Vec::new();',
      c='let x: Grid = Grid::new();'),
    r("api", id="rust:redundant-pub-self", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant pub(self)",
      desc="An item is marked pub(self).",
      rationale="pub(self) is identical to private visibility and only adds noise.",
      remediation="Remove the redundant visibility modifier.",
      source="https://doc.rust-lang.org/reference/visibility-and-privacy.html",
      re=r'\bpub\(self\)',
      nc='pub(self) fn helper() {}',
      c='fn helper() {}'),
    # ---- perf (6 target) ----
    r("perf", id="rust:to-string-in-format", type="smell", qual="maint", sev="low", cwe="",
      title="to_string() inside format!",
      desc="An argument is converted with to_string() inside format!.",
      rationale="format! already stringifies Display args, so the to_string() allocation is wasted (Clippy to_string_in_format_args).",
      remediation="Pass the value directly to format!.",
      source="https://rust-lang.github.io/rust-clippy/master/#to_string_in_format_args",
      re=r'format!\([^)]*\.to_string\(\)',
      nc='let s = format!("{}", x.to_string());',
      c='let s = format!("{}", x);'),
    r("perf", id="rust:string-plus-to-string", type="smell", qual="maint", sev="low", cwe="",
      title="String concatenation via + and to_string()",
      desc="Strings are joined with + and a to_string() temporary.",
      rationale="The + / to_string() pattern allocates an intermediate String on each step.",
      remediation="Build the result with format! or write!.",
      source="https://rust-lang.github.io/rust-clippy/master/#string_add",
      re=r'\+\s*&\w+\.to_string\(\)',
      nc='let s = a + &b.to_string();',
      c='let s = format!("{}{}", a, b);'),
    r("perf", id="rust:needless-collect-iter", type="smell", qual="maint", sev="low", cwe="",
      title="Collect then iterate",
      desc="An iterator is collected into a Vec only to iterate it again.",
      rationale="Collecting solely to re-iterate allocates a throwaway Vec (Clippy needless_collect).",
      remediation="Iterate the original iterator directly.",
      source="https://rust-lang.github.io/rust-clippy/master/#needless_collect",
      re=r'\.collect::<Vec<[^>]*>>\(\)\.iter\(\)',
      nc='for x in v.collect::<Vec<_>>().iter() {',
      c='for x in v {'),
    r("perf", id="rust:box-collection", type="smell", qual="maint", sev="low", cwe="",
      title="Boxed collection",
      desc="A collection is wrapped in a Box.",
      rationale="Collections already heap-allocate; boxing them adds a pointless indirection (Clippy box_collection).",
      remediation="Store the collection directly.",
      source="https://rust-lang.github.io/rust-clippy/master/#box_collection",
      re=r'Box<Vec<',
      nc='let b: Box<Vec<u8>> = Box::new(vec![]);',
      c='let b: Vec<u8> = vec![];'),
    r("perf", id="rust:borrowed-box", type="smell", qual="maint", sev="low", cwe="",
      title="Borrowed Box parameter",
      desc="A parameter is &Box<T> instead of &T.",
      rationale="&Box<T> forces an extra indirection over the equivalent &T (Clippy borrowed_box).",
      remediation="Take &T directly.",
      source="https://rust-lang.github.io/rust-clippy/master/#borrowed_box",
      re=r'&Box<',
      nc='fn render(x: &Box<Node>) {}',
      c='fn render(x: &Node) {}'),
    r("perf", id="rust:iter-cloned-collect", type="smell", qual="maint", sev="low", cwe="",
      title="iter().cloned().collect() to copy",
      desc="A collection is duplicated via iter().cloned().collect().",
      rationale="Cloning every element to rebuild the same container is slower than cloning the container (Clippy).",
      remediation="Use .clone() (or .to_vec()) on the collection.",
      source="https://rust-lang.github.io/rust-clippy/master/#iter_cloned_collect",
      re=r'\.iter\(\)\.cloned\(\)\.collect\(\)',
      nc='let v2 = v.iter().cloned().collect();',
      c='let v2 = v.clone();'),
    # ---- maint (8 target) ----
    r("maint", id="rust:todo-comment", type="smell", qual="maint", sev="info", cwe="CWE-546", skip="",
      title="Marker comment left in code",
      desc="A tracking marker comment remains in the source.",
      rationale="Leftover marker comments flag unfinished or suspicious code that should be resolved before release (CWE-546).",
      remediation="Resolve the note and remove the marker, or track it in an issue.",
      source="https://cwe.mitre.org/data/definitions/546.html",
      re=r'//\s*(TODO|FIXME)\b',
      nc='// TODO: handle the timeout branch',
      c='// Handles the timeout branch below'),
    r("maint", id="rust:dbg-macro", type="smell", qual="maint", sev="low", cwe="",
      title="dbg! left in code",
      desc="A dbg! debugging macro remains in the source.",
      rationale="dbg! writes to stderr and is meant for temporary debugging, not shipped code (Clippy dbg_macro).",
      remediation="Remove dbg! or switch to a logging call.",
      source="https://rust-lang.github.io/rust-clippy/master/#dbg_macro",
      re=r'\bdbg!\s*\(',
      nc='dbg!(user);',
      c='tracing::debug!("user={}", user);'),
    r("maint", id="rust:print-stdout", type="smell", qual="maint", sev="low", cwe="",
      title="println! / print! in library code",
      desc="Output is written directly to stdout.",
      rationale="Printing to stdout from library code bypasses the host's logging and cannot be filtered (Clippy print_stdout).",
      remediation="Use a logging facade (log/tracing).",
      source="https://rust-lang.github.io/rust-clippy/master/#print_stdout",
      re=r'\b(println!|print!)\s*\(',
      nc='println!("value: {}", v);',
      c='log::info!("value: {}", v);'),
    r("maint", id="rust:eprint-stderr", type="smell", qual="maint", sev="low", cwe="",
      title="eprintln! / eprint! in library code",
      desc="Diagnostics are written directly to stderr.",
      rationale="Writing to stderr from library code bypasses structured logging (Clippy print_stderr).",
      remediation="Use a logging facade at error level.",
      source="https://rust-lang.github.io/rust-clippy/master/#print_stderr",
      re=r'\b(eprintln!|eprint!)\s*\(',
      nc='eprintln!("request failed");',
      c='log::error!("request failed");'),
    r("maint", id="rust:empty-loop", type="bug", qual="rel", sev="low", cwe="",
      title="Empty busy loop",
      desc="A loop has an empty body.",
      rationale="An empty loop spins the CPU at 100% with no progress (Clippy empty_loop).",
      remediation="Park the thread, sleep, or await instead of spinning.",
      source="https://rust-lang.github.io/rust-clippy/master/#empty_loop",
      re=r'\bloop\s*\{\s*\}',
      nc='loop {}',
      c='loop { poll_once(); }'),
    r("maint", id="rust:large-stack-array", type="bug", qual="rel", sev="low", cwe="",
      title="Large array on the stack",
      desc="A large fixed-size array is allocated on the stack.",
      rationale="A very large stack array risks stack overflow (Clippy large_stack_arrays).",
      remediation="Allocate large buffers on the heap (Vec/Box).",
      source="https://rust-lang.github.io/rust-clippy/master/#large_stack_arrays",
      re=r'=\s*\[\s*0\s*;\s*\d{6,}',
      nc='let buf = [0; 1000000];',
      c='let buf = vec![0; 1000000];'),
    r("maint", id="rust:while-true", type="smell", qual="maint", sev="low", cwe="",
      title="while true loop",
      desc="An infinite loop is written as while true.",
      rationale="loop expresses an infinite loop more clearly and enables control-flow checks (Clippy while_true).",
      remediation="Use loop { ... }.",
      source="https://rust-lang.github.io/rust-clippy/master/#while_true",
      re=r'\bwhile\s+true\b',
      nc='while true {',
      c='loop {'),
    r("maint", id="rust:allow-unused", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="Suppressed unused lint",
      desc="An unused-code lint is suppressed with #[allow].",
      rationale="Blanket allow(unused_*) hides dead code that should be removed.",
      remediation="Remove the dead code instead of silencing the lint.",
      source="https://doc.rust-lang.org/rustc/lints/levels.html",
      re=r'#\[allow\(unused',
      nc='#[allow(unused_variables)]',
      c='#[warn(unused)]'),
]
