# C++ language-pack rule specs, batch 1 (#199). Clean-room, line-detectable — C++ Core Guidelines /
# modernization idioms (casts, RAII, nullptr, removed-in-C++17 APIs, macros). Concept origins cited.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cpp")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "cpp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cpp-c-style-cast", type="smell", qual="maint", sev="low", cwe="",
      title="C-style cast",
      desc="A value is converted with a C-style cast to a fundamental type.",
      rationale="C-style casts silently perform any conversion; named casts state intent and are searchable (Core Guidelines ES.49).",
      remediation="Use static_cast / reinterpret_cast / const_cast as appropriate.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es49-if-you-must-use-a-cast-use-a-named-cast",
      re=r'\(\s*(unsigned\s+)?(int|char|long|short|float|double|size_t|bool|uint8_t|uint16_t|uint32_t|uint64_t|int8_t|int16_t|int32_t|int64_t)\s*\*?\s*\)\s*[\w(]',
      nc='int y = (int)value;',
      c='int y = static_cast<int>(value);'),
    r(id="cpp-using-namespace-std", type="smell", qual="maint", sev="low", cwe="",
      title="using namespace std;",
      desc="The entire std namespace is imported.",
      rationale="Importing all of std invites name collisions and ambiguity, especially at global/header scope (Core Guidelines SF.7).",
      remediation="Import specific names (using std::vector;) or qualify at the use site.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file",
      re=r'using\s+namespace\s+std\s*;',
      nc='using namespace std;',
      c='using std::vector;'),
    r(id="cpp-null-macro", type="smell", qual="maint", sev="info", cwe="",
      title="NULL used instead of nullptr",
      desc="The NULL macro is used as a pointer value.",
      rationale="NULL is an integer constant that can bind to overloads incorrectly; nullptr is type-safe (Core Guidelines ES.47).",
      remediation="Use nullptr.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es47-use-nullptr-rather-than-0-or-null",
      re=r'[=(,]\s*NULL\b',
      nc='Widget* w = NULL;',
      c='Widget* w = nullptr;'),
    r(id="cpp-raw-new", type="smell", qual="maint", sev="low", cwe="",
      title="Raw new for a single object",
      desc="An object is allocated with a raw new and an owning raw pointer.",
      rationale="Manual new/delete leaks on early return/exception; smart pointers own automatically (Core Guidelines R.11).",
      remediation="Use std::make_unique / std::make_shared.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly",
      re=r'=\s*new\s+[A-Za-z_][\w:<>]*\s*[({;]',
      nc='Widget* w = new Widget();',
      c='auto w = std::make_unique<Widget>();'),
    r(id="cpp-raw-new-array", type="smell", qual="maint", sev="low", cwe="",
      title="Raw new[] array",
      desc="An array is allocated with new[].",
      rationale="Owning raw arrays are error-prone (size tracking, exception safety); containers manage this (Core Guidelines R.11).",
      remediation="Use std::vector (or std::array).",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly",
      re=r'=\s*new\s+[A-Za-z_][\w:<>]*\s*\[',
      nc='int* a = new int[n];',
      c='std::vector<int> a(n);'),
    r(id="cpp-raw-delete", type="smell", qual="maint", sev="low", cwe="",
      title="Explicit delete",
      desc="An object is freed with an explicit delete.",
      rationale="Manual delete is a symptom of manual ownership that RAII should handle (Core Guidelines R.11).",
      remediation="Let a smart pointer / container own the object.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly",
      re=r'\bdelete\s+[A-Za-z_]',
      nc='delete widget;',
      c='widget.reset();'),
    r(id="cpp-delete-array", type="smell", qual="maint", sev="low", cwe="",
      title="Explicit delete[]",
      desc="An array is freed with delete[].",
      rationale="Manual array deletion is error-prone and unnecessary with containers (Core Guidelines R.11).",
      remediation="Use a std::vector that frees automatically.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly",
      re=r'\bdelete\s*\[\s*\]',
      nc='delete[] arr;',
      c='arr.clear();'),
    r(id="cpp-endl", type="smell", qual="maint", sev="info", cwe="",
      title="std::endl instead of '\\n'",
      desc="A stream insertion uses std::endl.",
      rationale="endl flushes the stream on every call, which is slow in loops; '\\n' just writes a newline (Core Guidelines SL.io.50).",
      remediation="Use '\\n' and flush explicitly only when needed.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slio50-avoid-endl",
      re=r'<<\s*(std::)?endl\b',
      nc='std::cout << "done" << std::endl;',
      c="std::cout << \"done\" << '\\n';"),
    r(id="cpp-catch-by-value", type="smell", qual="maint", sev="medium", cwe="",
      title="Catching an exception by value",
      desc="A namespaced exception type is caught by value.",
      rationale="Catching by value slices derived exceptions and copies unnecessarily (Core Guidelines E.15).",
      remediation="Catch by const reference.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference",
      re=r'catch\s*\([^&)]*::[^&)]*\s+\w+\s*\)',
      nc='catch (std::exception e) { log(e); }',
      c='catch (const std::exception& e) { log(e); }'),
    r(id="cpp-malloc", type="smell", qual="maint", sev="info", cwe="",
      title="malloc() in C++",
      desc="C-style malloc is used to allocate memory in C++.",
      rationale="malloc does not run constructors and pairs with manual free; C++ has RAII allocation.",
      remediation="Use new/make_unique (or a container).",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r10-avoid-malloc-and-free",
      re=r'\bmalloc\s*\(',
      nc='char* p = (char*)malloc(n);',
      c='auto p = std::make_unique<char[]>(n);'),
    r(id="cpp-free", type="smell", qual="maint", sev="info", cwe="",
      title="free() in C++",
      desc="C-style free is used in C++.",
      rationale="Manual free pairs with malloc and is unnecessary under RAII ownership.",
      remediation="Let a smart pointer / container release the memory.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r10-avoid-malloc-and-free",
      re=r'\bfree\s*\(',
      nc='free(p);',
      c='ptr.reset();'),
    r(id="cpp-realloc", type="smell", qual="maint", sev="info", cwe="",
      title="realloc() in C++",
      desc="C-style realloc is used in C++.",
      rationale="realloc bypasses constructors/destructors and copies bytes, which is unsafe for non-trivial types.",
      remediation="Use a container (std::vector) that resizes correctly.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r10-avoid-malloc-and-free",
      re=r'\brealloc\s*\(',
      nc='p = (T*)realloc(p, n * sizeof(T));',
      c='vec.resize(n);'),
    r(id="cpp-typedef", type="smell", qual="maint", sev="info", cwe="",
      title="typedef instead of a using alias",
      desc="A type alias is declared with typedef.",
      rationale="using aliases read left-to-right and support templates; typedef is the legacy form (Core Guidelines T.43).",
      remediation="Use a using alias.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#t43-prefer-using-over-typedef-for-defining-aliases",
      re=r'\btypedef\s+',
      nc='typedef std::vector<int> IntVec;',
      c='using IntVec = std::vector<int>;'),
    r(id="cpp-register", type="smell", qual="maint", sev="low", cwe="",
      title="register storage-class specifier",
      desc="A variable uses the register keyword.",
      rationale="register has no effect and was removed in C++17.",
      remediation="Remove register.",
      source="https://en.cppreference.com/w/cpp/keyword/register",
      re=r'\bregister\s+[A-Za-z_]',
      nc='register int i = 0;',
      c='int i = 0;'),
    r(id="cpp-auto-ptr", type="smell", qual="maint", sev="medium", cwe="",
      title="std::auto_ptr",
      desc="The removed std::auto_ptr smart pointer is used.",
      rationale="auto_ptr has surprising copy-moves and was removed in C++17.",
      remediation="Use std::unique_ptr.",
      source="https://en.cppreference.com/w/cpp/memory/auto_ptr",
      re=r'\bauto_ptr\b',
      nc='std::auto_ptr<Widget> w(new Widget());',
      c='auto w = std::make_unique<Widget>();'),
    r(id="cpp-bind1st-bind2nd", type="smell", qual="maint", sev="low", cwe="",
      title="std::bind1st / std::bind2nd",
      desc="A removed binder adaptor is used.",
      rationale="bind1st/bind2nd were removed in C++17.",
      remediation="Use a lambda (or std::bind).",
      source="https://en.cppreference.com/w/cpp/utility/functional/bind12",
      re=r'\b(bind1st|bind2nd)\s*\(',
      nc='auto f = std::bind1st(std::plus<int>(), 1);',
      c='auto f = [](int x) { return x + 1; };'),
    r(id="cpp-mem-fun", type="smell", qual="maint", sev="low", cwe="",
      title="std::mem_fun / std::mem_fun_ref",
      desc="A removed member-function adaptor is used.",
      rationale="mem_fun/mem_fun_ref were removed in C++17.",
      remediation="Use std::mem_fn (or a lambda).",
      source="https://en.cppreference.com/w/cpp/utility/functional/mem_fun",
      re=r'\b(mem_fun|mem_fun_ref)\s*\(',
      nc='auto f = std::mem_fun(&Widget::draw);',
      c='auto f = std::mem_fn(&Widget::draw);'),
    r(id="cpp-random-shuffle", type="smell", qual="maint", sev="low", cwe="",
      title="std::random_shuffle",
      desc="The removed std::random_shuffle algorithm is used.",
      rationale="random_shuffle was removed in C++17 and used an unspecified source of randomness.",
      remediation="Use std::shuffle with a seeded generator.",
      source="https://en.cppreference.com/w/cpp/algorithm/random_shuffle",
      re=r'\brandom_shuffle\s*\(',
      nc='std::random_shuffle(v.begin(), v.end());',
      c='std::shuffle(v.begin(), v.end(), gen);'),
    r(id="cpp-dynamic-exception-spec", type="smell", qual="maint", sev="low", cwe="",
      title="Dynamic exception specification",
      desc="A function declares a throw(...) dynamic exception specification.",
      rationale="Dynamic exception specifications were deprecated in C++11 and removed in C++17.",
      remediation="Use noexcept (or omit the specification).",
      source="https://en.cppreference.com/w/cpp/language/except_spec",
      re=r'\)\s*throw\s*\(',
      nc='void load() throw(std::runtime_error);',
      c='void load() noexcept(false);'),
    r(id="cpp-function-like-macro", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="Function-like macro",
      desc="A function-like preprocessor macro is defined.",
      rationale="Macros ignore scope and types and evaluate arguments unexpectedly; inline/constexpr functions are safer (Core Guidelines ES.31).",
      remediation="Use an inline or constexpr function.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es31-dont-use-macros-for-constants-or-functions",
      re=r'^\s*#\s*define\s+\w+\([^)]*\)\s+\S',
      nc='#define SQUARE(x) ((x) * (x))',
      c='constexpr int square(int x) { return x * x; }'),
    r(id="cpp-define-constant", type="smell", qual="maint", sev="info", cwe="", skip="",
      title="#define constant",
      desc="A numeric constant is defined with the preprocessor.",
      rationale="Macro constants ignore scope and type; constexpr constants are typed and debuggable (Core Guidelines ES.31/Enum.1).",
      remediation="Use a constexpr constant.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es31-dont-use-macros-for-constants-or-functions",
      re=r'^\s*#\s*define\s+\w+\s+-?\d',
      nc='#define MAX_LEN 256',
      c='constexpr int kMaxLen = 256;'),
    r(id="cpp-const-cast", type="smell", qual="maint", sev="medium", cwe="",
      title="const_cast",
      desc="const_cast removes const/volatile qualification.",
      rationale="Modifying an object through a cast-away-const pointer is often undefined behavior and hides a design problem.",
      remediation="Redesign so the mutation is expressed without casting away const.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const",
      re=r'\bconst_cast\s*<',
      nc='auto* w = const_cast<Widget*>(cw);',
      c='Widget* w = registry.getMutable(id);'),
    r(id="cpp-reinterpret-cast", type="smell", qual="maint", sev="low", cwe="",
      title="reinterpret_cast",
      desc="reinterpret_cast performs an unchecked bit reinterpretation.",
      rationale="It bypasses the type system and often causes UB (alignment/strict aliasing); confine and justify it (Core Guidelines Type.1).",
      remediation="Avoid it where possible; use std::bit_cast or a typed API.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#pro-type-reinterpretcast",
      re=r'\breinterpret_cast\s*<',
      nc='auto* p = reinterpret_cast<int*>(buffer);',
      c='auto v = std::bit_cast<int>(buffer);'),
]
