# C# language-pack rule specs, batch 11 (#189). Clean-room, line-detectable — zip-slip, crypto-by-name,
# cert password, async-lambda-in-LINQ bugs, Yoda conditions, string/collection idioms.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-zip-slip-fullname", type="vuln", qual="sec", sev="high", cwe="CWE-22", owasp="A01:2021",
      title="Zip entry FullName used to build an extraction path",
      desc="Path.Combine is called with a zip entry's FullName, which can contain ../ traversal.",
      rationale="A malicious archive entry named ../../etc can write outside the target directory (Zip Slip, CWE-22).",
      remediation="Canonicalize the combined path and verify it stays under the destination root.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'Path\.Combine\([^)]*\.FullName',
      nc='var dest = Path.Combine(root, entry.FullName);',
      c='var dest = SafeCombine(root, entry.FullName);'),
    r(id="cs-cryptoconfig-createfromname", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Algorithm created by name via CryptoConfig",
      desc="A cryptographic algorithm is instantiated from a name string with CryptoConfig.CreateFromName.",
      rationale="Selecting an algorithm by name can silently pick a weak/legacy primitive (CWE-327); review the source of the name.",
      remediation="Instantiate a specific strong algorithm directly (e.g. SHA256.Create()).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'CryptoConfig\.CreateFromName\(',
      nc='var alg = CryptoConfig.CreateFromName(name);',
      c='var alg = SHA256.Create();'),
    r(id="cs-x509-password-literal", type="hotspot", qual="sec", sev="medium", cwe="CWE-798", owasp="A07:2021",
      title="Certificate loaded with a hard-coded password",
      desc="An X509Certificate2 is constructed with a string-literal password.",
      rationale="A PFX password embedded in source exposes the private key to anyone with the code (CWE-798).",
      remediation="Load the password from a secret store.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'X509Certificate2\([^)]*,\s*"[^"]+"\s*\)',
      nc='var cert = new X509Certificate2("client.pfx", "p@ssw0rd");',
      c='var cert = new X509Certificate2("client.pfx", GetPfxPassword());'),
    r(id="cs-request-unvalidated", type="vuln", qual="sec", sev="high", cwe="CWE-79", owasp="A03:2021",
      title="Request.Unvalidated bypasses request validation",
      desc="Input is read through Request.Unvalidated, skipping ASP.NET request validation.",
      rationale="Unvalidated input reaches the app without the built-in dangerous-markup check, enabling XSS (CWE-79).",
      remediation="Read validated input and HTML-encode on output.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'Request\.Unvalidated\b',
      nc='var comment = Request.Unvalidated.Form["comment"];',
      c='var comment = Request.Form["comment"];'),
    r(id="cs-select-async-lambda", type="bug", qual="rel", sev="high", cwe="CWE-670",
      title="async lambda passed to Select",
      desc="An async lambda is passed to Enumerable.Select, producing an IEnumerable<Task>.",
      rationale="The tasks are never awaited by Select, so the work runs unobserved or not at all (CWE-670).",
      remediation="Project to tasks and await them (Task.WhenAll), or use an await foreach / IAsyncEnumerable.",
      source="https://cwe.mitre.org/data/definitions/670.html",
      re=r'\.Select\(\s*async\b',
      nc='var tasks = ids.Select(async id => await LoadAsync(id));',
      c='var results = await Task.WhenAll(ids.Select(id => LoadAsync(id)));'),
    r(id="cs-where-async-lambda", type="bug", qual="rel", sev="high", cwe="CWE-670",
      title="async lambda passed to Where",
      desc="An async lambda is passed to Enumerable.Where, so the predicate returns a Task.",
      rationale="A Task is always truthy as a reference, so the filter keeps every element (CWE-670).",
      remediation="Evaluate the async predicate first (await Task.WhenAll) and filter on the results.",
      source="https://cwe.mitre.org/data/definitions/670.html",
      re=r'\.Where\(\s*async\b',
      nc='var open = items.Where(async i => await i.IsOpenAsync());',
      c='var flags = await Task.WhenAll(items.Select(i => i.IsOpenAsync()));'),
    r(id="cs-tryparse-result-ignored", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="TryParse result ignored",
      desc="A TryParse call is a bare statement, discarding the success/failure bool.",
      rationale="Ignoring the return means a failed parse silently leaves the out value at its default (CWE-252).",
      remediation="Check the boolean result before using the parsed value.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*(?:int|long|short|byte|double|decimal|float|bool|DateTime|Guid|TimeSpan)\.TryParse\([^;]*\)\s*;',
      nc='int.TryParse(input, out var count);',
      c='if (!int.TryParse(input, out var count)) return;'),
    r(id="cs-indexof-not-contains", type="smell", qual="maint", sev="low", cwe="",
      title="IndexOf(...) == -1 instead of !Contains",
      desc="Absence is tested with IndexOf compared to -1 / < 0.",
      rationale="!Contains states the intent directly and avoids computing an unused index.",
      remediation="Use !Contains.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2249",
      re=r'\.IndexOf\([^)]*\)\s*(==\s*-1|<\s*0)',
      nc='if (names.IndexOf(name) == -1) Add(name);',
      c='if (!names.Contains(name)) Add(name);'),
    r(id="cs-yoda-condition", type="smell", qual="maint", sev="info", cwe="",
      title="Yoda condition (constant on the left)",
      desc="A comparison places the literal on the left of ==.",
      rationale="Reversed operands read awkwardly; modern C# doesn't need Yoda conditions to avoid accidental assignment (SA1131).",
      remediation="Put the variable on the left: x == null.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/equality-operators",
      re=r'\(\s*(?:null|true|false|-?\d+)\s*==\s*[A-Za-z_]',
      nc='if (null == user) return;',
      c='if (user == null) return;'),
    r(id="cs-contains-single-char", type="smell", qual="maint", sev="info", cwe="",
      title="String.Contains with a single-character string",
      desc="String.Contains is called with a one-character string literal.",
      rationale="The char overload avoids allocating a search string (CA1847).",
      remediation="Use the char overload: Contains('x').",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1847",
      re=r'\.Contains\(\s*"[^"\\]"\s*\)',
      nc='if (path.Contains("/")) Split(path);',
      c="if (path.Contains('/')) Split(path);"),
    r(id="cs-endswith-no-comparison", type="smell", qual="maint", sev="low", cwe="",
      title="String EndsWith without a StringComparison",
      desc="String.EndsWith is called with a string but no StringComparison.",
      rationale="The default is culture-sensitive; pass StringComparison for predictable, faster matching (CA1310).",
      remediation="Pass StringComparison.Ordinal (or the intended comparison).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310",
      re=r'\.EndsWith\(\s*"[^"]*"\s*\)',
      nc='if (file.EndsWith(".tmp")) Delete(file);',
      c='if (file.EndsWith(".tmp", StringComparison.Ordinal)) Delete(file);'),
    r(id="cs-interpolation-no-holes", type="smell", qual="maint", sev="info", cwe="",
      title="Interpolated string with no interpolation holes",
      desc="A $-prefixed string contains no {expression} holes.",
      rationale="Without holes the $ prefix is noise; use a plain string literal.",
      remediation="Drop the $ prefix.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated",
      re=r'\$"[^"{}]*"',
      nc='var msg = $"operation complete";',
      c='var msg = "operation complete";'),
    r(id="cs-task-delay-zero", type="smell", qual="maint", sev="low", cwe="",
      title="Task.Delay(0)",
      desc="Task.Delay is awaited with a zero delay.",
      rationale="Task.Delay(0) completes immediately and does nothing useful; it is usually a leftover or a mistaken yield.",
      remediation="Remove it, or use Task.Yield() if a yield point is intended.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay",
      re=r'Task\.Delay\(\s*0\s*\)',
      nc='await Task.Delay(0);',
      c='await Task.Yield();'),
    r(id="cs-elementat-zero", type="smell", qual="maint", sev="info", cwe="",
      title="ElementAt(0) instead of First()",
      desc="The first element is taken via ElementAt(0).",
      rationale="First() reads clearer and is optimized for the common first-element case.",
      remediation="Use First() (or FirstOrDefault).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first",
      re=r'\.ElementAt\(\s*0\s*\)',
      nc='var head = sequence.ElementAt(0);',
      c='var head = sequence.First();'),
    r(id="cs-null-coalesce-assign", type="smell", qual="maint", sev="info", cwe="",
      title="if (x == null) x = ... instead of ??=",
      desc="A lazy-init pattern uses an explicit null-check assignment.",
      rationale="The null-coalescing assignment ??= expresses lazy initialization more concisely.",
      remediation="Use x ??= value.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator",
      re=r'if\s*\(\s*\w+\s*==\s*null\s*\)\s*\w+\s*=',
      nc='if (cache == null) cache = Build();',
      c='cache ??= Build();'),
    r(id="cs-tochararray-foreach", type="smell", qual="maint", sev="low", cwe="",
      title="foreach over string.ToCharArray()",
      desc="A foreach iterates the array returned by ToCharArray() on a string.",
      rationale="A string is already IEnumerable<char>; ToCharArray allocates an extra array to iterate.",
      remediation="Iterate the string directly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.tochararray",
      re=r'foreach\s*\([^)]*\bin\s+[\w.]+\.ToCharArray\(\)',
      nc='foreach (var ch in text.ToCharArray()) Handle(ch);',
      c='foreach (var ch in text) Handle(ch);'),
    r(id="cs-assert-true-notnull", type="smell", qual="maint", sev="low", cwe="",
      title="Assert.True(x != null) instead of Assert.NotNull",
      desc="A test checks non-null via Assert.True(x != null).",
      rationale="Assert.NotNull gives a clearer failure message than a boolean assertion.",
      remediation="Use Assert.NotNull(x).",
      source="https://xunit.net/docs/comparisons",
      re=r'Assert\.(True|IsTrue)\(\s*[^,)]*!=\s*null',
      nc='Assert.True(result != null);',
      c='Assert.NotNull(result);'),
    r(id="cs-sortedlist-nongeneric", type="smell", qual="maint", sev="low", cwe="",
      title="Non-generic SortedList",
      desc="The non-generic System.Collections.SortedList is instantiated.",
      rationale="The non-generic collection boxes value types and loses type safety; use SortedList<TKey,TValue>.",
      remediation="Use the generic SortedList<TKey, TValue>.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2",
      re=r'\bnew\s+SortedList\(\s*\)',
      nc='var m = new SortedList();',
      c='var m = new SortedList<string, int>();'),
]
