# C# language-pack rule specs, batch 3 (#189). Clean-room, line-detectable — auth/JWT/CORS, EF Core
# injection, legacy deserializers, transport, and correctness/idiom rules. Same clean-room policy.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- auth / JWT / CORS / CSRF ----
    r(id="cs-jwt-validate-issuer-off", type="vuln", qual="sec", sev="high", cwe="CWE-347",
      title="JWT issuer validation disabled",
      desc="TokenValidationParameters sets ValidateIssuer = false.",
      rationale="Not validating the issuer lets tokens from any issuer be accepted (CWE-347).",
      remediation="Set ValidateIssuer = true and configure ValidIssuer(s).",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r'ValidateIssuer\s*=\s*false',
      nc='ValidateIssuer = false,',
      c='ValidateIssuer = true,'),
    r(id="cs-jwt-validate-lifetime-off", type="vuln", qual="sec", sev="high", cwe="CWE-613",
      title="JWT lifetime validation disabled",
      desc="TokenValidationParameters sets ValidateLifetime = false.",
      rationale="Skipping lifetime validation accepts expired tokens (CWE-613).",
      remediation="Set ValidateLifetime = true.",
      source="https://cwe.mitre.org/data/definitions/613.html",
      re=r'ValidateLifetime\s*=\s*false',
      nc='ValidateLifetime = false,',
      c='ValidateLifetime = true,'),
    r(id="cs-jwt-require-signed-off", type="vuln", qual="sec", sev="high", cwe="CWE-347",
      title="JWT signed-tokens requirement disabled",
      desc="TokenValidationParameters sets RequireSignedTokens = false.",
      rationale="Accepting unsigned tokens lets an attacker forge claims (CWE-347).",
      remediation="Set RequireSignedTokens = true and validate the signing key.",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r'RequireSignedTokens\s*=\s*false',
      nc='RequireSignedTokens = false,',
      c='RequireSignedTokens = true,'),
    r(id="cs-cors-allow-any-origin", type="hotspot", qual="sec", sev="medium", cwe="CWE-942",
      title="CORS AllowAnyOrigin()",
      desc="A CORS policy calls AllowAnyOrigin(), exposing the API to every site.",
      rationale="Allowing any origin is unsafe, especially with credentials (CWE-942). Restrict to known origins.",
      remediation="Use WithOrigins(...) for an allow-list; never combine AllowAnyOrigin with AllowCredentials.",
      source="https://cwe.mitre.org/data/definitions/942.html",
      re=r'\.AllowAnyOrigin\(\s*\)',
      nc='policy.AllowAnyOrigin();',
      c='policy.WithOrigins("https://app.example.com");'),
    r(id="cs-antiforgery-ignore", type="vuln", qual="sec", sev="high", cwe="CWE-352",
      title="Anti-forgery token check disabled",
      desc="[IgnoreAntiforgeryToken] turns off CSRF protection on an action.",
      rationale="Ignoring the anti-forgery token exposes the action to CSRF (CWE-352).",
      remediation="Keep [ValidateAntiForgeryToken] on state-changing actions.",
      source="https://cwe.mitre.org/data/definitions/352.html",
      re=r'\[IgnoreAntiforgeryToken\]',
      nc='[IgnoreAntiforgeryToken]',
      c='[ValidateAntiForgeryToken]'),
    r(id="cs-open-redirect", type="vuln", qual="sec", sev="medium", cwe="CWE-601",
      title="Redirect to a request-supplied URL",
      desc="Redirect/RedirectPermanent is passed a value taken from the request.",
      rationale="Redirecting to an attacker-controlled URL enables phishing (CWE-601). Use LocalRedirect or validate the target.",
      remediation="Use LocalRedirect, or validate the URL against an allow-list.",
      source="https://cwe.mitre.org/data/definitions/601.html",
      re=r'\bRedirect(Permanent)?\(\s*(Request\.|Request\[)',
      nc='return Redirect(Request.Query["returnUrl"]);',
      c='return LocalRedirect(returnUrl);'),
    # ---- injection: EF Core / files / process ----
    r(id="cs-ef-raw-sql-interp", type="vuln", qual="sec", sev="high", cwe="CWE-89",
      title="EF Core FromSqlRaw/ExecuteSqlRaw with interpolation",
      desc="A raw-SQL EF Core call is passed an interpolated ($) string.",
      rationale="Interpolating values into FromSqlRaw/ExecuteSqlRaw is injectable; use the FromSql/parameterized form (CWE-89).",
      remediation="Use FromSql/ExecuteSql (interpolated-but-parameterized) or pass SqlParameters.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'\.(FromSqlRaw|ExecuteSqlRaw|ExecuteSqlRawAsync)\(\s*\$"',
      nc='ctx.Users.FromSqlRaw($"SELECT * FROM Users WHERE Name = {name}");',
      c='ctx.Users.FromSql($"SELECT * FROM Users WHERE Name = {name}");'),
    r(id="cs-command-text-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89",
      title="CommandText assembled by concatenation",
      desc="A DbCommand.CommandText is built with + or interpolation of variables.",
      rationale="Concatenating input into CommandText enables SQL injection (CWE-89).",
      remediation="Use parameters (cmd.Parameters.Add) instead of building the text.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'\.CommandText\s*=\s*(\$?"[^"]*"\s*\+|\$"[^"]*\{)',
      nc='cmd.CommandText = "SELECT * FROM u WHERE id=" + id;',
      c='cmd.CommandText = "SELECT * FROM u WHERE id=@id";'),
    r(id="cs-file-read-request", type="vuln", qual="sec", sev="high", cwe="CWE-22",
      title="File read from a request-supplied path",
      desc="File.ReadAllText/ReadAllBytes/OpenRead is passed a request-derived path.",
      rationale="Reading a request-controlled path allows directory traversal (CWE-22).",
      remediation="Validate the resolved path stays within an allowed root.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'File\.(ReadAllText|ReadAllBytes|OpenRead|ReadAllLines)\([^)]*(Request\.|Request\[)',
      nc='var data = File.ReadAllText(Request.Query["path"]);',
      c='var data = File.ReadAllText(SafeResolve(root, name));'),
    r(id="cs-zip-extract-slip", type="hotspot", qual="sec", sev="medium", cwe="CWE-22",
      title="ZipFile.ExtractToDirectory (zip-slip risk)",
      desc="Archive entries are extracted without validating their destination paths.",
      rationale="A crafted archive entry name (../) can write outside the target directory (CWE-22, 'zip slip'). Validate each entry's full path.",
      remediation="Validate each entry's resolved path is within the destination before extracting.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'ZipFile\.ExtractToDirectory\(',
      nc='ZipFile.ExtractToDirectory(archivePath, destDir);',
      c='foreach (var e in zip.Entries) { SafeExtract(e, destDir); }'),
    r(id="cs-process-useshellexecute", type="hotspot", qual="sec", sev="medium", cwe="CWE-78",
      title="ProcessStartInfo.UseShellExecute = true",
      desc="UseShellExecute routes the launch through the OS shell.",
      rationale="Shell execution reinterprets the arguments/filename and can run unexpected commands or handlers (CWE-78). Review the inputs.",
      remediation="Set UseShellExecute = false and pass an explicit file + ArgumentList.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'UseShellExecute\s*=\s*true',
      nc='var psi = new ProcessStartInfo { UseShellExecute = true };',
      c='var psi = new ProcessStartInfo { UseShellExecute = false };'),
    # ---- legacy deserializers / crypto extras ----
    r(id="cs-legacy-formatter", type="vuln", qual="sec", sev="high", cwe="CWE-502",
      title="Insecure legacy serializer",
      desc="SoapFormatter, NetDataContractSerializer, LosFormatter, or ObjectStateFormatter is used.",
      rationale="These serializers deserialize arbitrary types and enable RCE on untrusted input (CWE-502).",
      remediation="Use a safe serializer (System.Text.Json) with known types.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r'\bnew\s+(SoapFormatter|NetDataContractSerializer|LosFormatter|ObjectStateFormatter)\b',
      nc='var f = new SoapFormatter();',
      c='var o = JsonSerializer.Deserialize<T>(json);'),
    r(id="cs-hmac-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="HMAC-MD5 used",
      desc="HMACMD5 uses the broken MD5 hash under HMAC.",
      rationale="HMAC-MD5 relies on MD5 and should be avoided for new designs (CWE-327).",
      remediation="Use HMACSHA256 or stronger.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bnew\s+HMACMD5\b|\bHMACMD5\.',
      nc='using var h = new HMACMD5(key);',
      c='using var h = new HMACSHA256(key);'),
    r(id="cs-servercert-handler-true", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="HttpClientHandler certificate check bypassed",
      desc="ServerCertificateCustomValidationCallback is set to a delegate returning true.",
      rationale="Always returning true from the validation callback disables TLS authentication (CWE-295).",
      remediation="Validate the chain and SslPolicyErrors; do not return true unconditionally.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'ServerCertificateCustomValidationCallback\s*=\s*.*=>\s*true',
      nc='handler.ServerCertificateCustomValidationCallback = (m, c, ch, e) => true;',
      c='handler.ServerCertificateCustomValidationCallback = (m, c, ch, e) => e == SslPolicyErrors.None;'),
    r(id="cs-x509-ignore-flags", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="X.509 chain verification flags weakened",
      desc="X509ChainPolicy.VerificationFlags is set to ignore validation errors / AllFlags.",
      rationale="Ignoring chain-validation flags defeats certificate checking (CWE-295).",
      remediation="Leave VerificationFlags at NoFlag and handle errors explicitly.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'VerificationFlags\s*=\s*X509VerificationFlags\.(AllFlags|Ignore)',
      nc='chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllFlags;',
      c='chain.ChainPolicy.VerificationFlags = X509VerificationFlags.NoFlag;'),
    r(id="cs-smtp-no-ssl", type="hotspot", qual="sec", sev="low", cwe="CWE-319",
      title="SMTP client with SSL disabled",
      desc="SmtpClient.EnableSsl is set to false, sending mail (and credentials) in cleartext.",
      rationale="Cleartext SMTP exposes credentials and content (CWE-319).",
      remediation="Set EnableSsl = true (or use a TLS-enforcing transport).",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'EnableSsl\s*=\s*false',
      nc='client.EnableSsl = false;',
      c='client.EnableSsl = true;'),
    r(id="cs-basic-auth-literal", type="hotspot", qual="sec", sev="medium", cwe="CWE-798",
      title="Hardcoded HTTP Basic auth header",
      desc="An Authorization header is set to a literal 'Basic ...' value.",
      rationale="A hardcoded Basic credential embeds a secret in source (CWE-798).",
      remediation="Build the header from a securely stored credential at runtime.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'"Authorization"\s*,\s*"Basic\s',
      nc='client.DefaultRequestHeaders.Add("Authorization", "Basic dXNlcjpwYXNz");',
      c='client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", token);'),
    r(id="cs-lock-string", type="bug", qual="rel", sev="medium", cwe="CWE-662",
      title="lock on a string",
      desc="A lock is taken on a string literal or interned string.",
      rationale="Interned strings are shared process-wide, so locking one risks cross-component deadlock (CWE-662).",
      remediation="Lock on a private readonly object.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2002",
      re=r'\block\s*\(\s*"',
      nc='lock ("cacheLock") { Refresh(); }',
      c='lock (_cacheLock) { Refresh(); }'),
    # ---- correctness / bugs ----
    r(id="cs-assignment-in-condition", type="bug", qual="rel", sev="medium", cwe="CWE-481",
      title="Assignment inside an if condition",
      desc="An if condition uses = (assignment) where == (comparison) was likely intended.",
      rationale="Assigning in a condition is a common typo for comparison (CWE-481).",
      remediation="Use == for comparison; if assignment is intended, do it before the if.",
      source="https://cwe.mitre.org/data/definitions/481.html",
      re=r'\bif\s*\(\s*\w+\s*=[^=]',
      nc='if (result = Compute()) { }',
      c='if (result == Compute()) { }'),
    r(id="cs-return-in-finally", type="bug", qual="rel", sev="high", cwe="CWE-584",
      title="return inside a finally block",
      desc="A finally block contains a return, which discards pending exceptions.",
      rationale="Returning from finally swallows in-flight exceptions and overrides the try's result (CWE-584).",
      remediation="Do not return from finally; move the return out of it.",
      source="https://cwe.mitre.org/data/definitions/584.html",
      re=r'\bfinally\s*\{[^}]*\breturn\b',
      nc='try { return A(); } finally { return B(); }',
      c='try { return A(); } finally { Cleanup(); }'),
    r(id="cs-if-single-statement-no-braces", type="smell", qual="maint", sev="low", cwe="",
      title="if with a single statement and no braces",
      desc="An if body is a single unbraced statement on the same line.",
      rationale="Always using braces prevents the dangling-else / goto-fail class of bugs (StyleCop SA1503).",
      remediation="Wrap the body in braces.",
      source="https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1503.md",
      re=r'\bif\s*\([^)]*\)\s*(return|throw|break|continue|goto)\b',
      nc='if (x < 0) return;',
      c='if (x < 0) { return; }'),
    r(id="cs-empty-while", type="bug", qual="rel", sev="medium", cwe="",
      title="while loop with an empty body",
      desc="A while loop's body is an empty statement (;).",
      rationale="A while with an empty body is usually a mistake (a misplaced semicolon) and may spin forever.",
      remediation="Remove the stray semicolon or give the loop a body.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements",
      re=r'\bwhile\s*\([^)]*\)\s*;',
      nc='while (running);',
      c='while (running) { Thread.Yield(); }'),
    r(id="cs-array-empty-alloc", type="smell", qual="maint", sev="info", cwe="",
      title="Zero-length array allocation",
      desc="new T[0] allocates a new empty array on each call.",
      rationale="Array.Empty<T>() returns a cached singleton, avoiding the allocation (CA1825).",
      remediation="Use Array.Empty<T>().",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825",
      re=r'\bnew\s+\w[\w<>]*\[\s*0\s*\]',
      nc='return new string[0];',
      c='return Array.Empty<string>();'),
    r(id="cs-public-readonly-mutable-collection", type="smell", qual="maint", sev="low", cwe="",
      title="Public readonly mutable collection field",
      desc="A public readonly List/Dictionary/HashSet exposes a mutable collection.",
      rationale="readonly protects only the reference; callers can still mutate the collection (CA2227). Expose a read-only view.",
      remediation="Expose IReadOnlyList/IReadOnlyCollection, or a get-only property.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227",
      re=r'\bpublic\s+readonly\s+(List|Dictionary|HashSet|Collection)<',
      nc='    public readonly List<string> Items = new();',
      c='    public IReadOnlyList<string> Items => _items;'),
    r(id="cs-enum-parse-unchecked", type="smell", qual="maint", sev="low", cwe="",
      title="Enum.Parse without TryParse",
      desc="Enum.Parse throws on an unknown value and can yield an undefined enum.",
      rationale="Enum.Parse throws on invalid input and does not verify the value is defined; Enum.TryParse + IsDefined is safer.",
      remediation="Use Enum.TryParse and validate with Enum.IsDefined.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.enum.tryparse",
      re=r'\bEnum\.Parse\(',
      nc='var c = (Color)Enum.Parse(typeof(Color), raw);',
      c='Enum.TryParse<Color>(raw, out var c);'),
    r(id="cs-insert-at-zero", type="smell", qual="maint", sev="low", cwe="",
      title="List.Insert(0, ...) in a hot path",
      desc="Inserting at index 0 of a List<T> is O(n) because it shifts all elements.",
      rationale="Prepending to a List shifts the whole backing array each time; use a different structure (e.g. LinkedList/Queue) if prepending is frequent.",
      remediation="Use a data structure with O(1) prepend, or append then reverse.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.insert",
      re=r'\.Insert\(\s*0\s*,',
      nc='queue.Insert(0, item);',
      c='deque.AddFirst(item);'),
    r(id="cs-task-run-in-controller", type="smell", qual="maint", sev="low", cwe="",
      title="Task.Run wrapping already-async work",
      desc="Task.Run is used to offload work that is already asynchronous.",
      rationale="Wrapping async work in Task.Run wastes a thread-pool thread and adds no concurrency; just await it.",
      remediation="await the async method directly instead of Task.Run.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'Task\.Run\(\s*async\b',
      nc='await Task.Run(async () => await FetchAsync());',
      c='await FetchAsync();'),
    r(id="cs-catch-when-false", type="bug", qual="rel", sev="low", cwe="",
      title="Exception filter that is always false",
      desc="A catch filter `when (false)` never matches, making the catch dead.",
      rationale="A constant-false exception filter is dead code and hides intent.",
      remediation="Remove the dead catch or fix the filter condition.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when",
      re=r'\bcatch\b[^\n]*\bwhen\s*\(\s*false\s*\)',
      nc='catch (Exception e) when (false) { }',
      c='catch (IOException e) { Log(e); }'),
    r(id="cs-double-cast", type="smell", qual="maint", sev="low", cwe="",
      title="`is` type check followed by a cast",
      desc="Code checks `x is T` and then casts x to T separately, testing the type twice.",
      rationale="A pattern match (`x is T t`) does the check and bind in one step (IDE0019).",
      remediation="Use `if (x is T t)` to check and bind together.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0019",
      re=r'\bis\s+\w+\s*\)\s*\{\s*\w+\s+\w+\s*=\s*\(\w+\)',
      nc='if (o is Node) { Node n = (Node)o;',
      c='if (o is Node n) {'),
    r(id="cs-throw-in-finally", type="bug", qual="rel", sev="high", cwe="CWE-584",
      title="throw inside a finally block",
      desc="A finally block throws, which masks any in-flight exception from the try.",
      rationale="Throwing from finally replaces the original exception, hiding the real failure (CWE-584).",
      remediation="Do not throw from finally; handle the condition elsewhere.",
      source="https://cwe.mitre.org/data/definitions/584.html",
      re=r'\bfinally\s*\{[^}]*\bthrow\b',
      nc='try { Do(); } finally { throw new Exception("cleanup"); }',
      c='try { Do(); } finally { Cleanup(); }'),
    r(id="cs-convert-tostring-null", type="bug", qual="rel", sev="low", cwe="",
      title="ToString() on a possibly-null value in interpolation-free concat",
      desc="A nullable value has .ToString() called directly, which throws if it is null.",
      rationale="Calling .ToString() on a null reference throws NullReferenceException; use ?. or Convert.ToString.",
      remediation="Use value?.ToString() or Convert.ToString(value).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.convert.tostring",
      re=r'\?\?\s*\w+\.ToString\(\)',
      nc='var s = maybe ?? other.ToString();',
      c='var s = maybe ?? other?.ToString() ?? "";'),
    r(id="cs-guid-tostring-format", type="smell", qual="maint", sev="info", cwe="",
      title="new Guid() creates an empty GUID",
      desc="new Guid() (parameterless) yields Guid.Empty, rarely what is intended.",
      rationale="new Guid() is all-zeros; to create a fresh id use Guid.NewGuid(), and for empty use Guid.Empty explicitly.",
      remediation="Use Guid.NewGuid() (new id) or Guid.Empty (explicit empty).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.guid.newguid",
      re=r'\bnew\s+Guid\(\s*\)',
      nc='var id = new Guid();',
      c='var id = Guid.NewGuid();'),
    r(id="cs-stopwatch-datetime", type="smell", qual="maint", sev="low", cwe="",
      title="Elapsed time measured with DateTime subtraction",
      desc="A duration is computed by subtracting DateTime.Now values.",
      rationale="DateTime is wall-clock (subject to NTP/DST jumps); use Stopwatch for elapsed time.",
      remediation="Measure elapsed time with System.Diagnostics.Stopwatch.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch",
      re=r'DateTime\.Now\s*-\s*\w+',
      nc='var elapsed = DateTime.Now - start;',
      c='var elapsed = stopwatch.Elapsed;'),
]
