CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "py")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "python"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


# Python quality pack, batch 12: Python-2 artifacts, removed stdlib APIs, leftover debuggers, idioms.
RULES = [
    # --- Python 2 builtins / syntax (broken on Python 3) ---
    r(id="python-xrange", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 xrange",
      desc="xrange does not exist in Python 3.", rationale="xrange raises NameError on Python 3; range is now lazy.",
      remediation="Use range().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bxrange\s*\(", nc="for i in xrange(10):", c="for i in range(10):"),
    r(id="python-unicode-builtin", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 unicode()",
      desc="The unicode builtin was removed in Python 3.", rationale="unicode() raises NameError on Python 3; str is unicode.",
      remediation="Use str().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bunicode\s*\(", nc="text = unicode(value)", c="text = str(value)"),
    r(id="python-basestring", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 basestring",
      desc="basestring was removed in Python 3.", rationale="basestring raises NameError on Python 3.",
      remediation="Use str (or (str, bytes) when both are expected).", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bbasestring\b", nc="if isinstance(x, basestring):", c="if isinstance(x, str):"),
    r(id="python-raw-input", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 raw_input()",
      desc="raw_input was renamed input in Python 3.", rationale="raw_input raises NameError on Python 3.",
      remediation="Use input().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\braw_input\s*\(", nc='name = raw_input("name: ")', c='name = input("name: ")'),
    r(id="python-print-statement", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 print statement",
      desc="print is a function in Python 3 and requires parentheses.", rationale="A print statement is a SyntaxError on Python 3.",
      remediation="Call print(...).", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"^\s*print\s+[^(=]", nc='print "done"', c='print("done")'),
    r(id="python-dict-iteritems", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 dict.iteritems()",
      desc="iteritems was removed in Python 3.", rationale="dict.iteritems raises AttributeError on Python 3.",
      remediation="Use items().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\.iteritems\s*\(", nc="for k, v in data.iteritems():", c="for k, v in data.items():"),
    r(id="python-dict-iterkeys", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 dict.iterkeys()",
      desc="iterkeys was removed in Python 3.", rationale="dict.iterkeys raises AttributeError on Python 3.",
      remediation="Iterate the dict directly, or use keys().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\.iterkeys\s*\(", nc="for k in data.iterkeys():", c="for k in data:"),
    r(id="python-dict-itervalues", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 dict.itervalues()",
      desc="itervalues was removed in Python 3.", rationale="dict.itervalues raises AttributeError on Python 3.",
      remediation="Use values().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\.itervalues\s*\(", nc="for v in data.itervalues():", c="for v in data.values():"),
    r(id="python-itertools-izip", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 itertools.izip",
      desc="izip/imap/ifilter were removed in Python 3.", rationale="itertools.izip raises AttributeError; zip is lazy in Python 3.",
      remediation="Use the builtin zip().", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bitertools\.izip\b", nc="for a, b in itertools.izip(xs, ys):", c="for a, b in zip(xs, ys):"),
    # --- Python 2 stdlib module names ---
    r(id="python-thread-module", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 thread module",
      desc="The thread module was renamed _thread in Python 3.", rationale="import thread fails on Python 3.",
      remediation="Use threading (or _thread).", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"^\s*import\s+thread\b", nc="import thread", c="import threading"),
    r(id="python-urllib2-module", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 urllib2 module",
      desc="urllib2 was reorganized into urllib in Python 3.", rationale="import urllib2 fails on Python 3.",
      remediation="Use urllib.request.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bimport\s+urllib2\b", nc="import urllib2", c="import urllib.request"),
    r(id="python-urlparse-module", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 urlparse module",
      desc="urlparse moved into urllib.parse in Python 3.", rationale="importing urlparse fails on Python 3.",
      remediation="Use urllib.parse.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\b(import\s+urlparse|from\s+urlparse\b)", nc="from urlparse import urljoin", c="from urllib.parse import urljoin"),
    r(id="python-cstringio-module", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 cStringIO module",
      desc="cStringIO was removed in Python 3.", rationale="importing cStringIO fails on Python 3.",
      remediation="Use io.StringIO / io.BytesIO.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\b(import\s+cStringIO|from\s+cStringIO\b)", nc="from cStringIO import StringIO", c="from io import StringIO"),
    r(id="python-stringio-module", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 StringIO module",
      desc="The StringIO module was removed in Python 3.", rationale="import StringIO fails on Python 3.",
      remediation="Use io.StringIO.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"^\s*import\s+StringIO\b", nc="import StringIO", c="from io import StringIO"),
    r(id="python-queue-module-py2", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 Queue module",
      desc="The Queue module was renamed queue in Python 3.", rationale="import Queue fails on Python 3.",
      remediation="Use queue.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"^\s*import\s+Queue\b", nc="import Queue", c="import queue"),
    r(id="python-configparser-py2", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 ConfigParser module",
      desc="ConfigParser was renamed configparser in Python 3.", rationale="importing ConfigParser fails on Python 3.",
      remediation="Use configparser.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\b(import\s+ConfigParser|from\s+ConfigParser\b)", nc="import ConfigParser", c="import configparser"),
    r(id="python-builtin-module-py2", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 __builtin__ module",
      desc="__builtin__ was renamed builtins in Python 3.", rationale="importing __builtin__ fails on Python 3.",
      remediation="Use builtins.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\b(import\s+__builtin__|from\s+__builtin__\b)", nc="import __builtin__", c="import builtins"),
    # --- Removed stdlib APIs (later Python 3) ---
    r(id="python-sys-version-slice", type="bug", qual="rel", sev="medium", cwe="", title="Slicing sys.version",
      desc="Comparing sys.version string slices breaks for Python 3.10+.", rationale="sys.version[:3] returns '3.1' for 3.10, so version checks misfire (flake8-2020 YTT101).",
      remediation="Use sys.version_info tuples.", source="https://github.com/asottile/flake8-2020",
      re=r"sys\.version\[", nc='if sys.version[:3] == "3.9":', c="if sys.version_info >= (3, 9):"),
    r(id="python-inspect-getargspec", type="bug", qual="rel", sev="medium", cwe="", title="inspect.getargspec()",
      desc="getargspec was removed in Python 3.11.", rationale="inspect.getargspec raises AttributeError on Python 3.11+.",
      remediation="Use inspect.getfullargspec or inspect.signature.", source="https://docs.python.org/3/whatsnew/3.11.html",
      re=r"inspect\.getargspec\s*\(", nc="spec = inspect.getargspec(fn)", c="spec = inspect.getfullargspec(fn)"),
    r(id="python-fractions-gcd", type="bug", qual="rel", sev="medium", cwe="", title="fractions.gcd()",
      desc="fractions.gcd moved to math.gcd and was removed.", rationale="fractions.gcd raises AttributeError on modern Python.",
      remediation="Use math.gcd.", source="https://docs.python.org/3/whatsnew/3.9.html",
      re=r"\bfractions\.gcd\b", nc="g = fractions.gcd(a, b)", c="g = math.gcd(a, b)"),
    r(id="python-os-tempnam", type="bug", qual="rel", sev="medium", cwe="", title="os.tempnam()",
      desc="os.tempnam was removed (and was insecure).", rationale="os.tempnam raises AttributeError on Python 3 and had a race condition.",
      remediation="Use tempfile.mkstemp / NamedTemporaryFile.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bos\.tempnam\s*\(", nc="path = os.tempnam()", c="fd, path = tempfile.mkstemp()"),
    r(id="python-platform-dist", type="bug", qual="rel", sev="medium", cwe="", title="platform.linux_distribution()",
      desc="platform.dist/linux_distribution were removed in Python 3.8.", rationale="These raise AttributeError on Python 3.8+.",
      remediation="Use the distro package.", source="https://docs.python.org/3/whatsnew/3.8.html",
      re=r"\bplatform\.(dist|linux_distribution)\s*\(", nc="info = platform.linux_distribution()", c="info = distro.linux_distribution()"),
    r(id="python-string-letters", type="bug", qual="rel", sev="medium", cwe="", title="Python 2 string.letters",
      desc="string.letters/lowercase/uppercase were removed in Python 3.", rationale="These raise AttributeError on Python 3.",
      remediation="Use string.ascii_letters / ascii_lowercase / ascii_uppercase.", source="https://docs.python.org/3/whatsnew/3.0.html",
      re=r"\bstring\.(letters|lowercase|uppercase)\b", nc="chars = string.letters", c="chars = string.ascii_letters"),
    # --- Leftover debuggers ---
    r(id="python-debugger-set-trace", type="bug", qual="rel", sev="medium", cwe="", title="Leftover debugger breakpoint",
      desc="pdb/ipdb set_trace() left in code halts execution.", rationale="A committed set_trace() blocks the program waiting for a debugger.",
      remediation="Remove the debugger call.", source="https://github.com/JBKahn/flake8-debugger",
      re=r"\b(pdb|ipdb)\.set_trace\s*\(", nc="pdb.set_trace()", c='logger.debug("checkpoint")'),
    r(id="python-breakpoint-call", type="bug", qual="rel", sev="medium", cwe="", title="Leftover breakpoint()",
      desc="A committed breakpoint() call drops into the debugger.", rationale="breakpoint() left in code halts execution in production.",
      remediation="Remove the breakpoint() call.", source="https://github.com/JBKahn/flake8-debugger",
      re=r"\bbreakpoint\s*\(\s*\)", nc="breakpoint()", c='logger.debug("checkpoint")'),
    # --- Idioms ---
    r(id="python-map-lambda", type="smell", qual="maint", sev="low", cwe="", title="map() with a lambda",
      desc="map(lambda ...) is clearer as a generator expression.", rationale="A generator expression avoids the lambda call overhead and reads better (flake8-comprehensions C417).",
      remediation="Use a generator expression.", source="https://github.com/adamchainz/flake8-comprehensions",
      re=r"\bmap\s*\(\s*lambda", nc="out = map(lambda x: x * 2, items)", c="out = (x * 2 for x in items)"),
    r(id="python-filter-lambda", type="smell", qual="maint", sev="low", cwe="", title="filter() with a lambda",
      desc="filter(lambda ...) is clearer as a generator expression.", rationale="A generator with an if clause avoids the lambda and reads better.",
      remediation="Use a generator expression with an if clause.", source="https://github.com/adamchainz/flake8-comprehensions",
      re=r"\bfilter\s*\(\s*lambda", nc="out = filter(lambda x: x > 0, items)", c="out = (x for x in items if x > 0)"),
    r(id="python-pytest-raises-broad", type="smell", qual="maint", sev="low", cwe="", title="pytest.raises(Exception)",
      desc="Asserting a broad Exception may hide the wrong error.", rationale="A broad pytest.raises can pass on an unrelated exception (flake8-pytest-style PT011).",
      remediation="Assert the specific exception type.", source="https://github.com/m-burst/flake8-pytest-style",
      re=r"pytest\.raises\s*\(\s*Exception\s*\)", nc="with pytest.raises(Exception):", c="with pytest.raises(ValueError):"),
    r(id="python-django-charfield-null", type="smell", qual="maint", sev="low", cwe="", title="null=True on a string field",
      desc="Using null=True on Char/TextField creates two empty states.", rationale="Django prefers blank=True for optional text; null=True adds a confusing NULL vs '' distinction (flake8-django DJ01).",
      remediation="Use blank=True for optional text fields.", source="https://docs.djangoproject.com/en/stable/ref/models/fields/#null",
      re=r"\b(CharField|TextField)\s*\([^)]*null\s*=\s*True", nc="name = models.CharField(max_length=50, null=True)", c="name = models.CharField(max_length=50, blank=True)"),
]
