# C# language-pack rule specs, batch 8 (#189). Clean-room, line-detectable — ASP.NET/CORS/CSP,
# XXE, DataTable/LDAP injection, LINQ perf, ordering bug, legacy-web smells. Clean-room.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-developer-exception-page", type="hotspot", qual="sec", sev="medium", cwe="CWE-489", owasp="A05:2021",
      title="UseDeveloperExceptionPage in the pipeline",
      desc="The developer exception page middleware is registered.",
      rationale="The developer exception page leaks stack traces and configuration; it must be limited to development (CWE-489).",
      remediation="Guard it with env.IsDevelopment(), and use UseExceptionHandler in production.",
      source="https://cwe.mitre.org/data/definitions/489.html",
      re=r'UseDeveloperExceptionPage\(\)',
      nc='app.UseDeveloperExceptionPage();',
      c='app.UseExceptionHandler("/error");'),
    r(id="cs-cors-withorigins-wildcard", type="vuln", qual="sec", sev="high", cwe="CWE-942", owasp="A05:2021",
      title="CORS WithOrigins(\"*\")",
      desc="A CORS policy allows the wildcard origin.",
      rationale="A wildcard origin lets any site make credentialed cross-origin calls (CWE-942).",
      remediation="List the specific trusted origins.",
      source="https://cwe.mitre.org/data/definitions/942.html",
      re=r'WithOrigins\(\s*"\*"',
      nc='policy.WithOrigins("*");',
      c='policy.WithOrigins("https://app.example.com");'),
    r(id="cs-cors-header-wildcard", type="vuln", qual="sec", sev="high", cwe="CWE-942", owasp="A05:2021",
      title="Access-Control-Allow-Origin set to *",
      desc="The CORS allow-origin response header is set to the wildcard manually.",
      rationale="Emitting Access-Control-Allow-Origin: * exposes the endpoint to any origin (CWE-942).",
      remediation="Echo a validated allow-listed origin instead of *.",
      source="https://cwe.mitre.org/data/definitions/942.html",
      re=r'"Access-Control-Allow-Origin"\s*,\s*"\*"',
      nc='Response.Headers.Add("Access-Control-Allow-Origin", "*");',
      c='Response.Headers.Add("Access-Control-Allow-Origin", allowedOrigin);'),
    r(id="cs-csp-unsafe-inline", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Content-Security-Policy allows 'unsafe-inline'",
      desc="A CSP string contains 'unsafe-inline'.",
      rationale="'unsafe-inline' permits inline scripts/styles, defeating CSP's XSS protection (CWE-79).",
      remediation="Use nonces or hashes instead of 'unsafe-inline'.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'unsafe-inline',
      nc='var csp = "script-src \'self\' \'unsafe-inline\'";',
      c='var csp = "script-src \'self\' \'nonce-{cspNonce}\'";'),
    r(id="cs-empty-if-semicolon", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="if statement with an empty body (stray semicolon)",
      desc="An if is immediately terminated by a semicolon, so the guarded code never depends on the condition.",
      rationale="A stray ; makes the if a no-op and silently runs the following statement unconditionally (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*if\s*\([\w.\s!=<>&|]+\)\s*;\s*$',
      nc='if (ready);',
      c='if (ready) { Start(); }'),
    r(id="cs-not-supported-stub", type="smell", qual="maint", sev="low", cwe="",
      title="NotSupportedException thrown with no message",
      desc="A NotSupportedException is thrown with no explanation.",
      rationale="A messageless NotSupportedException gives callers no guidance on why or what to use instead.",
      remediation="Add a message explaining the unsupported operation.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.notsupportedexception",
      re=r'\bthrow\s+new\s+NotSupportedException\(\s*\)',
      nc='throw new NotSupportedException();',
      c='throw new NotSupportedException("streaming is not supported for this format");'),
    r(id="cs-obsolete-no-message", type="smell", qual="maint", sev="low", cwe="",
      title="[Obsolete] without a message",
      desc="A member is marked [Obsolete] without a migration message.",
      rationale="A bare [Obsolete] tells callers something is deprecated but not what to use instead (CA1041).",
      remediation="Provide a message pointing to the replacement.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1041",
      re=r'\[Obsolete\]',
      nc='[Obsolete]',
      c='[Obsolete("Use ParseV2 instead.")]'),
    r(id="cs-linq-count-gt-zero", type="smell", qual="maint", sev="low", cwe="",
      title="Count() > 0 instead of Any()",
      desc="An emptiness test uses Count() > 0, which enumerates the whole sequence.",
      rationale="Any() short-circuits at the first element; Count() > 0 may walk the entire sequence (CA1860).",
      remediation="Use Any().",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1860",
      re=r'\.Count\(\)\s*>\s*0',
      nc='if (items.Count() > 0) Process();',
      c='if (items.Any()) Process();'),
    r(id="cs-indexof-no-comparison", type="smell", qual="maint", sev="low", cwe="",
      title="String IndexOf without a StringComparison",
      desc="String.IndexOf is called with a string but no StringComparison.",
      rationale="The default is culture-sensitive and locale-dependent; pass StringComparison explicitly (CA1307).",
      remediation="Pass StringComparison.Ordinal (or the intended comparison).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1307",
      re=r'\.IndexOf\(\s*"[^"]*"\s*\)',
      nc='var i = text.IndexOf("token");',
      c='var i = text.IndexOf("token", StringComparison.Ordinal);'),
    r(id="cs-formsauth-weak-hash", type="vuln", qual="sec", sev="high", cwe="CWE-327", owasp="A02:2021",
      title="FormsAuthentication weak password hashing",
      desc="HashPasswordForStoringInConfigFile is used to hash a password.",
      rationale="This API produces an unsalted MD5/SHA1 digest, unsuitable for password storage (CWE-327).",
      remediation="Use a salted, slow KDF (PBKDF2/bcrypt/Argon2).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'HashPasswordForStoringInConfigFile\b',
      nc='var h = FormsAuthentication.HashPasswordForStoringInConfigFile(pwd, "SHA1");',
      c='var h = HashWithPbkdf2(pwd, salt);'),
    r(id="cs-htmlstring-raw", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Raw HtmlString from a variable",
      desc="An HtmlString is constructed from a variable, emitting it without HTML-encoding.",
      rationale="HtmlString marks content as pre-encoded; feeding it unencoded data enables XSS (CWE-79).",
      remediation="HTML-encode the value, or bind it as text so the framework encodes it.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'new\s+HtmlString\(\s*\w',
      nc='return new HtmlString(comment);',
      c='return Content(HttpUtility.HtmlEncode(comment));'),
    r(id="cs-markupstring-raw", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Blazor MarkupString from a variable",
      desc="A MarkupString is constructed from a variable, rendering raw HTML in Blazor.",
      rationale="MarkupString bypasses Blazor's automatic encoding; untrusted data becomes XSS (CWE-79).",
      remediation="Render the value as text, or sanitize it before wrapping.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r'new\s+MarkupString\(\s*\w',
      nc='builder.AddContent(0, new MarkupString(body));',
      c='builder.AddContent(0, body);'),
    r(id="cs-datatable-select-injection", type="vuln", qual="sec", sev="high", cwe="CWE-943", owasp="A03:2021",
      title="DataTable.Select filter built by concatenation",
      desc="A DataTable.Select filter expression is concatenated from a variable.",
      rationale="Unescaped input in a DataColumn expression allows filter injection (CWE-943).",
      remediation="Escape the value, or filter with LINQ over the typed rows.",
      source="https://cwe.mitre.org/data/definitions/943.html",
      re=r'\.Select\(\s*"[^"]*"\s*\+',
      nc='var rows = table.Select("Name = \'" + name + "\'");',
      c='var rows = table.AsEnumerable().Where(row => row.Field<string>("Name") == name);'),
    r(id="cs-xmlurlresolver", type="vuln", qual="sec", sev="high", cwe="CWE-611", owasp="A05:2021",
      title="XmlUrlResolver enabled on an XML document",
      desc="An XmlResolver is set to a new XmlUrlResolver, allowing external entity/DTD resolution.",
      rationale="Resolving external references enables XXE (file read, SSRF) on untrusted XML (CWE-611).",
      remediation="Set XmlResolver = null.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r'XmlResolver\s*=\s*new\s+XmlUrlResolver',
      nc='doc.XmlResolver = new XmlUrlResolver();',
      c='doc.XmlResolver = null;'),
    r(id="cs-orderby-orderby", type="bug", qual="rel", sev="medium", cwe="",
      title="OrderBy followed by OrderBy",
      desc="A second OrderBy is chained after the first, discarding the first ordering.",
      rationale="OrderBy resets the sort key; chaining two means only the last one takes effect. Use ThenBy for secondary sorts.",
      remediation="Use ThenBy/ThenByDescending for subsequent keys.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.thenby",
      re=r'\.OrderBy\([^)]*\)\s*\.OrderBy\(',
      nc='var s = rows.OrderBy(r => r.Group).OrderBy(r => r.Name);',
      c='var s = rows.OrderBy(r => r.Group).ThenBy(r => r.Name);'),
    r(id="cs-httpcontext-current", type="smell", qual="maint", sev="medium", cwe="",
      title="HttpContext.Current used",
      desc="The static HttpContext.Current accessor is used.",
      rationale="HttpContext.Current is null on background/async flows and is removed in ASP.NET Core; inject IHttpContextAccessor.",
      remediation="Inject IHttpContextAccessor and use its HttpContext.",
      source="https://learn.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current",
      re=r'HttpContext\.Current\b',
      nc='var user = HttpContext.Current.User;',
      c='var user = _httpContextAccessor.HttpContext?.User;'),
    r(id="cs-response-end", type="smell", qual="maint", sev="low", cwe="",
      title="Response.End() used",
      desc="Response.End() is called to stop request processing.",
      rationale="Response.End raises a ThreadAbortException to halt the thread, an expensive control-flow anti-pattern.",
      remediation="Return from the handler (or use CompleteAsync) instead of Response.End.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.web.httpresponse.end",
      re=r'Response\.End\(\)',
      nc='Response.End();',
      c='return; // let the pipeline finish the response'),
]
