# C++ language-pack rule specs, batch 3 (#199). Clean-room, line-detectable — STL/modern-C++ idioms,
# smart-pointer construction, CERT-C++ bug patterns, control-flow/UB. Concept origins cited.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cpp")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "cpp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cpp-size-zero-vs-empty", type="smell", qual="maint", sev="low", cwe="",
      title="size() == 0 instead of empty()",
      desc="Emptiness is tested with size() == 0.",
      rationale="empty() is O(1) for every container and states intent; size() may be O(n) (e.g. some list impls).",
      remediation="Use empty().",
      source="https://en.cppreference.com/w/cpp/container/vector/empty",
      re=r'\.size\(\)\s*==\s*0', nc='if (items.size() == 0) return;', c='if (items.empty()) return;'),
    r(id="cpp-size-gt-zero-vs-empty", type="smell", qual="maint", sev="low", cwe="",
      title="size() > 0 instead of !empty()",
      desc="Non-emptiness is tested with size() > 0.",
      rationale="!empty() is O(1) and clearer than size() > 0.",
      remediation="Use !empty().",
      source="https://en.cppreference.com/w/cpp/container/vector/empty",
      re=r'\.size\(\)\s*>\s*0', nc='if (items.size() > 0) process();', c='if (!items.empty()) process();'),
    r(id="cpp-count-vs-contains", type="smell", qual="maint", sev="info", cwe="",
      title="count() > 0 instead of contains()",
      desc="Set/map membership is tested with count().",
      rationale="contains() (C++20) states intent and cannot be misread as a multiplicity.",
      remediation="Use contains().",
      source="https://en.cppreference.com/w/cpp/container/set/contains",
      re=r'\.count\(\s*\w+\s*\)\s*(>\s*0|!=\s*0|==\s*0)', nc='if (seen.count(x) > 0) skip();', c='if (seen.contains(x)) skip();'),
    r(id="cpp-find-vs-contains", type="smell", qual="maint", sev="info", cwe="",
      title="find() != end() instead of contains()",
      desc="Membership is tested with find() compared to end().",
      rationale="contains() (C++20) is clearer for a pure membership check.",
      remediation="Use contains() when only membership is needed.",
      source="https://en.cppreference.com/w/cpp/container/map/contains",
      re=r'\.find\([^)]*\)\s*!=\s*\w+\.end\(\)', nc='if (m.find(k) != m.end()) hit();', c='if (m.contains(k)) hit();'),
    r(id="cpp-push-back-temp", type="smell", qual="maint", sev="low", cwe="",
      title="push_back of a temporary",
      desc="push_back constructs a temporary that is then moved/copied in.",
      rationale="emplace_back constructs the element in place, avoiding the temporary.",
      remediation="Use emplace_back with the constructor arguments.",
      source="https://en.cppreference.com/w/cpp/container/vector/emplace_back",
      re=r'\.push_back\s*\(\s*[A-Z]\w*\s*\(', nc='items.push_back(Widget(id));', c='items.emplace_back(id);'),
    r(id="cpp-string-compare-zero", type="smell", qual="maint", sev="low", cwe="",
      title="string::compare(...) == 0",
      desc="String equality is tested via compare() == 0.",
      rationale="operator== is clearer and does not compute an ordering.",
      remediation="Use the == operator for equality.",
      source="https://en.cppreference.com/w/cpp/string/basic_string/compare",
      re=r'\.compare\([^)]*\)\s*==\s*0', nc='if (a.compare(b) == 0) same();', c='if (a == b) same();'),
    r(id="cpp-shared-ptr-new", type="smell", qual="maint", sev="low", cwe="",
      title="shared_ptr constructed from new",
      desc="A shared_ptr is built directly from a new expression.",
      rationale="make_shared is exception-safe and allocates the control block and object together (Core Guidelines R.22).",
      remediation="Use std::make_shared.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r22-use-make_shared-to-make-shared_ptrs",
      re=r'shared_ptr<[^>]*>\s*[\w ]*\(\s*new\b', nc='std::shared_ptr<Widget> w(new Widget());', c='auto w = std::make_shared<Widget>();'),
    r(id="cpp-unique-ptr-new", type="smell", qual="maint", sev="low", cwe="",
      title="unique_ptr constructed from new",
      desc="A unique_ptr is built directly from a new expression.",
      rationale="make_unique is exception-safe and avoids a naked new (Core Guidelines R.23).",
      remediation="Use std::make_unique.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r23-use-make_unique-to-make-unique_ptrs",
      re=r'unique_ptr<[^>]*>\s*[\w ]*\(\s*new\b', nc='std::unique_ptr<Widget> w(new Widget());', c='auto w = std::make_unique<Widget>();'),
    r(id="cpp-return-std-move", type="smell", qual="maint", sev="low", cwe="",
      title="return std::move(local)",
      desc="A local variable is returned via std::move.",
      rationale="std::move on a return value inhibits copy/move elision (RVO), often pessimizing performance.",
      remediation="Return the local directly.",
      source="https://en.cppreference.com/w/cpp/language/copy_elision",
      re=r'return\s+std::move\s*\(', nc='return std::move(result);', c='return result;'),
    r(id="cpp-throw-new", type="smell", qual="maint", sev="medium", cwe="",
      title="throw of a new expression",
      desc="An exception is thrown as a pointer allocated with new.",
      rationale="Throwing a pointer leaks (the catch cannot delete it safely) and breaks by-value catching (Core Guidelines E.15).",
      remediation="Throw the exception object by value.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference",
      re=r'\bthrow\s+new\b', nc='throw new std::runtime_error("bad");', c='throw std::runtime_error("bad");'),
    r(id="cpp-empty-catch", type="smell", qual="maint", sev="medium", cwe="",
      title="Empty catch block",
      desc="A catch handler has no statements.",
      rationale="Silently swallowing an exception hides failures (CERT ERR).",
      remediation="Handle, log, or rethrow the exception.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR50-CPP.+Do+not+abruptly+terminate+the+program",
      re=r'catch\s*\([^)]*\)\s*\{\s*\}', nc='catch (const std::exception& e) {}', c='catch (const std::exception& e) { log(e); }'),
    r(id="cpp-catch-ellipsis", type="smell", qual="maint", sev="info", cwe="",
      title="Catch-all handler (...)",
      desc="A catch(...) handler catches every exception type.",
      rationale="A catch-all discards type information and can mask unrelated failures; catch specific types where possible.",
      remediation="Catch the specific exception types you can handle.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR50-CPP.+Do+not+abruptly+terminate+the+program",
      re=r'catch\s*\(\s*\.\.\.\s*\)', nc='catch (...) { cleanup(); }', c='catch (const std::exception& e) { cleanup(); }'),
    r(id="cpp-assert-side-effect", type="bug", qual="rel", sev="medium", cwe="CWE-617",
      title="Side effect inside assert()",
      desc="An assert expression contains ++ or -- (a side effect).",
      rationale="asserts are compiled out under NDEBUG, so the side effect vanishes in release builds (CWE-617).",
      remediation="Move the side effect out of the assert.",
      source="https://cwe.mitre.org/data/definitions/617.html",
      re=r'\bassert\s*\([^)]*(\+\+|--)', nc='assert(i++ < n);', c='assert(i < n); ++i;'),
    r(id="cpp-float-equality", type="bug", qual="rel", sev="low", cwe="CWE-1077",
      title="Floating-point equality against a literal",
      desc="A float/double is compared for exact equality with a decimal literal.",
      rationale="Binary floating-point cannot represent most decimals exactly, so == is unreliable (CWE-1077).",
      remediation="Compare within a tolerance (std::abs(a - b) < epsilon).",
      source="https://cwe.mitre.org/data/definitions/1077.html",
      re=r'==\s*\d+\.\d+', nc='if (ratio == 0.5) apply();', c='if (std::abs(ratio - 0.5) < eps) apply();'),
    r(id="cpp-divide-by-zero-literal", type="bug", qual="rel", sev="high", cwe="CWE-369",
      title="Division by the literal 0",
      desc="A value is divided by the literal 0.",
      rationale="Integer division by zero is undefined behavior (CWE-369).",
      remediation="Guard the divisor, or fix the constant.",
      source="https://cwe.mitre.org/data/definitions/369.html",
      re=r'[^/*]/\s*0\s*[;)]', nc='int q = n / 0;', c='int q = n / d;'),
    r(id="cpp-assignment-in-if", type="bug", qual="rel", sev="medium", cwe="CWE-481",
      title="Assignment in an if condition",
      desc="An if condition contains a single = (assignment) rather than ==.",
      rationale="An assignment in a condition is usually a typo for == (CWE-481).",
      remediation="Use ==, or wrap an intentional assignment in extra parentheses.",
      source="https://cwe.mitre.org/data/definitions/481.html",
      re=r'\bif\s*\(\s*\w+\s*=\s*[^=]', nc='if (x = compute()) use();', c='if (x == compute()) use();'),
    r(id="cpp-assignment-in-while", type="bug", qual="rel", sev="medium", cwe="CWE-481",
      title="Assignment in a while condition",
      desc="A while condition contains a single = (assignment) rather than ==.",
      rationale="An assignment in a condition is usually a typo for == (CWE-481).",
      remediation="Use ==, or wrap an intentional assignment in extra parentheses.",
      source="https://cwe.mitre.org/data/definitions/481.html",
      re=r'\bwhile\s*\(\s*\w+\s*=\s*[^=]', nc='while (c = next()) emit(c);', c='while (c == next()) emit(c);'),
    r(id="cpp-strlen-in-loop", type="smell", qual="maint", sev="low", cwe="",
      title="strlen() in a loop condition",
      desc="strlen is called in the loop condition, recomputing the length each iteration.",
      rationale="Re-scanning the string every iteration makes the loop O(n^2).",
      remediation="Compute the length once, or iterate a std::string/std::string_view.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/",
      re=r'for\s*\([^;]*;[^;]*\bstrlen\s*\(', nc='for (i = 0; i < strlen(s); i++) up(s, i);', c='for (i = 0, n = strlen(s); i < n; i++) up(s, i);'),
    r(id="cpp-empty-if-semicolon", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="if statement with an empty body (stray semicolon)",
      desc="An if is immediately terminated by a semicolon.",
      rationale="The stray ; makes the if a no-op and runs the following statement unconditionally (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*if\s*\([\w\s!=<>&|.]+\)\s*;\s*$', nc='if (ready);', c='if (ready) start();'),
    r(id="cpp-empty-for-body", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="for loop with an empty body (stray semicolon)",
      desc="A for loop is immediately terminated by a semicolon.",
      rationale="The stray ; makes the loop body empty and any following block runs once (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*for\s*\([\w\s;=<>!&|+.*/%-]+\)\s*;\s*$', nc='for (i = 0; i < n; i++);', c='for (i = 0; i < n; i++) work(i);'),
    r(id="cpp-delete-this", type="smell", qual="maint", sev="medium", cwe="",
      title="delete this",
      desc="A member function deletes the object it is called on.",
      rationale="delete this is fragile: any later member access, and destruction by the owner, is undefined behavior.",
      remediation="Manage the object's lifetime with a smart pointer / owner.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r-resource-management",
      re=r'\bdelete\s+this\b', nc='delete this;', c='owner->release(this);'),
    r(id="cpp-dynamic-cast-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing a dynamic_cast pointer result",
      desc="A member is accessed on a dynamic_cast<T*> result without a null check.",
      rationale="dynamic_cast to a pointer yields nullptr on failure, so an immediate dereference can crash (CWE-476).",
      remediation="Check the result for null, or dynamic_cast to a reference to get a throw on failure.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'dynamic_cast<[^>]*>\s*\([^)]*\)\s*->', nc='auto id = dynamic_cast<Node*>(base)->id;', c='if (auto* n = dynamic_cast<Node*>(base)) use(n->id);'),
    r(id="cpp-range-for-copy", type="smell", qual="maint", sev="info", cwe="",
      title="Range-based for loop copies each element",
      desc="A range-for binds each element by value (auto x).",
      rationale="Binding by value copies each element; for non-trivial types this is wasteful.",
      remediation="Bind by const reference (const auto&) unless a copy is intended.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es71-prefer-a-range-for-statement-to-a-for-statement-when-there-is-a-choice",
      re=r'for\s*\(\s*auto\s+\w+\s*:', nc='for (auto item : items) total += item.cost;', c='for (const auto& item : items) total += item.cost;'),
    r(id="cpp-void-main", type="smell", qual="maint", sev="low", cwe="",
      title="void main()",
      desc="main is declared to return void.",
      rationale="The standard requires main to return int; void main is non-conforming.",
      remediation="Declare int main() and return a status code.",
      source="https://en.cppreference.com/w/cpp/language/main_function",
      re=r'\bvoid\s+main\s*\(', nc='void main() {', c='int main() {'),
    r(id="cpp-return-addr-local", type="bug", qual="rel", sev="high", cwe="CWE-562",
      title="Return of the address of a local variable",
      desc="A function returns the address of a named local variable.",
      rationale="The variable's storage is reclaimed on return, leaving a dangling pointer (CWE-562).",
      remediation="Return by value, or manage a longer lifetime.",
      source="https://cwe.mitre.org/data/definitions/562.html",
      re=r'\breturn\s+&\s*\w+\s*;', nc='return &local;', c='return result;'),
    r(id="cpp-null-return-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing a string-search result directly",
      desc="A value is read from strchr/strstr/etc. without a NULL check.",
      rationale="These return NULL when not found, so an immediate dereference can crash (CWE-476).",
      remediation="Store the result and check for null first (or use std::string::find).",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\*\s*(strchr|strrchr|strstr|strpbrk|memchr)\s*\(', nc='char sep = *strchr(line, \'=\');', c='auto pos = line.find(\'=\');'),
    r(id="cpp-int-to-char-getchar", type="bug", qual="rel", sev="medium", cwe="CWE-704",
      title="getchar()/getc() result stored in a char",
      desc="The int result of a character-input function is assigned to a char.",
      rationale="Narrowing to char loses the ability to distinguish EOF from a valid byte (CWE-704).",
      remediation="Store the result in an int.",
      source="https://cwe.mitre.org/data/definitions/704.html",
      re=r'\bchar\s+\w+\s*=\s*(getchar|getc|fgetc)\s*\(', nc='char c = getchar();', c='int c = getchar();'),
    r(id="cpp-feof-loop", type="bug", qual="rel", sev="medium", cwe="CWE-241",
      title="feof() used as a loop condition",
      desc="A read loop is controlled by !feof().",
      rationale="feof only becomes true after a failed read, so the loop over-processes the last item (CWE-241).",
      remediation="Loop on the return value of the read itself.",
      source="https://cwe.mitre.org/data/definitions/241.html",
      re=r'while\s*\(\s*!\s*feof\s*\(', nc='while (!feof(f)) { fgets(l, n, f); use(l); }', c='while (fgets(l, n, f)) { use(l); }'),
    r(id="cpp-fflush-stdin", type="bug", qual="rel", sev="medium", cwe="CWE-758",
      title="fflush() on an input stream",
      desc="fflush is called on stdin (an input stream).",
      rationale="fflush on an input stream is undefined behavior in standard C/C++ (CWE-758).",
      remediation="Discard input with std::cin.ignore().",
      source="https://cwe.mitre.org/data/definitions/758.html",
      re=r'fflush\s*\(\s*stdin\s*\)', nc='fflush(stdin);', c="std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\\n');"),
    r(id="cpp-scanf-scanset-unbounded", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="scanf scanset without a field width",
      desc="A scanf %[ scanset conversion has no maximum field width.",
      rationale="Without a width, a scanset writes an unbounded run, overflowing the buffer (CWE-120).",
      remediation="Add a field width, or read into a std::string.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bscanf\s*\([^)]*%\[', nc='scanf("%[^\\n]", line);', c='std::getline(std::cin, line);'),
    r(id="cpp-abort", type="smell", qual="maint", sev="low", cwe="",
      title="abort() in library code",
      desc="abort() terminates the whole process abnormally.",
      rationale="A library that aborts denies the caller any chance to recover or run destructors.",
      remediation="Throw an exception and let the caller decide.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR50-CPP.+Do+not+abruptly+terminate+the+program",
      re=r'\babort\s*\(\s*\)', nc='abort();', c='throw std::runtime_error("fatal state");'),
    r(id="cpp-longjmp", type="bug", qual="rel", sev="medium", cwe="",
      title="Use of longjmp() in C++",
      desc="longjmp() performs a non-local jump.",
      rationale="longjmp does not run destructors, so any non-trivial object in scope leaks/UB in C++.",
      remediation="Use C++ exceptions for non-local control flow.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR52-CPP.+Do+not+use+setjmp+or+longjmp",
      re=r'\blongjmp\s*\(', nc='longjmp(env, 1);', c='throw ParseError{};'),
    r(id="cpp-setjmp", type="bug", qual="rel", sev="medium", cwe="",
      title="Use of setjmp() in C++",
      desc="setjmp() sets up a non-local jump target.",
      rationale="Combined with longjmp it skips destructors, causing leaks/UB with non-trivial objects.",
      remediation="Use C++ exceptions for error propagation.",
      source="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR52-CPP.+Do+not+use+setjmp+or+longjmp",
      re=r'\bsetjmp\s*\(', nc='if (setjmp(env)) recover();', c='try { parse(); } catch (...) { recover(); }'),
    r(id="cpp-bool-literal-compare", type="smell", qual="maint", sev="info", cwe="",
      title="Comparison to a boolean literal",
      desc="A condition compares a value to true/false.",
      rationale="== true / == false is redundant and error-prone (easy to typo into =).",
      remediation="Use the value (or its negation) directly.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es-expr",
      re=r'==\s*(true|false)\b', nc='if (ok == true) go();', c='if (ok) go();'),
    r(id="cpp-weak-ptr-lock-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing weak_ptr::lock() without a null check",
      desc="A member is accessed on the result of weak_ptr::lock() directly.",
      rationale="lock() returns an empty shared_ptr if the object expired, so an immediate dereference can crash (CWE-476).",
      remediation="Store the shared_ptr and check it before dereferencing.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\.lock\(\)\s*->', nc='auto v = observer.lock()->value;', c='if (auto sp = observer.lock()) use(sp->value);'),
    r(id="cpp-do-while-false", type="smell", qual="maint", sev="low", cwe="",
      title="do/while(false) executes once",
      desc="A do-while loop with a constant-false condition runs exactly once.",
      rationale="do/while(false) is usually a disguised goto/break; restructure for clarity.",
      remediation="Replace with straight-line code or explicit control flow.",
      source="https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es-control",
      re=r'\}\s*while\s*\(\s*false\s*\)', nc='do { step(); } while (false);', c='step();'),
]
