# C# language-pack rule specs, batch 5 (#189). Clean-room, line-detectable — threading/locking,
# analyzer-suppression + diagnostics smells, EF/JSON, obsolete threading, reflection/typeof. Clean-room.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-lock-typeof", type="bug", qual="rel", sev="medium", cwe="CWE-662",
      title="lock on a typeof() expression",
      desc="Locking on a Type object shares the lock across all callers of that type process-wide.",
      rationale="Type objects are shared, so locking one risks cross-component deadlock (CWE-662, CA2002).",
      remediation="Lock on a private static readonly object.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2002",
      re=r'\block\s*\(\s*typeof\(',
      nc='lock (typeof(Cache)) { Rebuild(); }',
      c='lock (_sync) { Rebuild(); }'),
    r(id="cs-pragma-warning-disable", type="smell", qual="maint", sev="low", cwe="", skip="",
      title="#pragma warning disable",
      desc="A compiler/analyzer warning is suppressed with #pragma warning disable.",
      rationale="Blanket warning suppression hides real issues; fix the cause or scope/justify the suppression.",
      remediation="Address the warning, or scope the suppression narrowly with a justification.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives",
      re=r'#pragma\s+warning\s+disable\b',
      nc='#pragma warning disable CS0168',
      c='// fixed the unused-variable warning instead'),
    r(id="cs-suppressmessage", type="smell", qual="maint", sev="info", cwe="",
      title="[SuppressMessage] analyzer suppression",
      desc="An analyzer finding is suppressed with a SuppressMessage attribute.",
      rationale="Suppressions accumulate and hide regressions; each should carry a justification and be revisited.",
      remediation="Fix the underlying issue, or add a Justification and track the suppression.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/suppress-warnings",
      re=r'\[SuppressMessage\(',
      nc='[SuppressMessage("Security", "CA5350")]',
      c='// resolved the flagged issue'),
    r(id="cs-debugger-break", type="smell", qual="maint", sev="medium", cwe="",
      title="Debugger.Break() left in code",
      desc="Debugger.Break() halts execution under a debugger and is leftover debugging.",
      rationale="A stray Debugger.Break stalls or aborts non-interactive runs and must not ship.",
      remediation="Remove the Debugger.Break call.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.break",
      re=r'\bDebugger\.Break\(\)',
      nc='Debugger.Break();',
      c='// removed debug breakpoint'),
    r(id="cs-configmanager-appsettings", type="smell", qual="maint", sev="low", cwe="",
      title="ConfigurationManager.AppSettings (legacy config)",
      desc="Legacy System.Configuration AppSettings is used instead of the options/config system.",
      rationale="ConfigurationManager is the .NET Framework config API; modern .NET uses IConfiguration/Options.",
      remediation="Use IConfiguration / the Options pattern.",
      source="https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration",
      re=r'ConfigurationManager\.AppSettings\b',
      nc='var v = ConfigurationManager.AppSettings["Key"];',
      c='var v = _config["Key"];'),
    r(id="cs-encoding-default", type="bug", qual="rel", sev="medium", cwe="CWE-176",
      title="Encoding.Default used",
      desc="Encoding.Default depends on the OS/locale and varies between machines.",
      rationale="Using the platform-default encoding produces inconsistent bytes across systems (CWE-176). Use an explicit encoding.",
      remediation="Use an explicit encoding (Encoding.UTF8).",
      source="https://cwe.mitre.org/data/definitions/176.html",
      re=r'\bEncoding\.Default\b',
      nc='var bytes = Encoding.Default.GetBytes(text);',
      c='var bytes = Encoding.UTF8.GetBytes(text);'),
    r(id="cs-dynamic-keyword", type="smell", qual="maint", sev="low", cwe="",
      title="dynamic used for a typed value",
      desc="A variable is declared dynamic, deferring binding to runtime and losing type safety.",
      rationale="dynamic disables compile-time checking and adds overhead; use a concrete type where possible.",
      remediation="Use a concrete/static type (or an interface).",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/interop/using-type-dynamic",
      re=r'\bdynamic\s+\w+\s*=',
      nc='dynamic result = Parse(input);',
      c='var result = Parse(input);'),
    r(id="cs-unsafe-block", type="hotspot", qual="sec", sev="low", cwe="CWE-119",
      title="unsafe block",
      desc="An unsafe context enables pointer arithmetic, bypassing memory safety.",
      rationale="Unsafe code can corrupt memory if mismanaged (CWE-119). Review each unsafe region.",
      remediation="Avoid unsafe where possible; confine and document it (or use Span<T>).",
      source="https://cwe.mitre.org/data/definitions/119.html",
      re=r'\bunsafe\s*\{|\bunsafe\s+(static\s+)?\w',
      nc='unsafe { *p = 0; }',
      c='span[0] = 0;'),
    r(id="cs-tempfile-predictable", type="hotspot", qual="sec", sev="medium", cwe="CWE-377",
      title="Path.GetTempFileName() (predictable temp file)",
      desc="Path.GetTempFileName creates a file with a predictable name and a small name space.",
      rationale="Predictable temp names enable races/hijacking and exhaust after 64k files (CWE-377).",
      remediation="Create a temp file with a random name and restrictive permissions.",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'Path\.GetTempFileName\(\)',
      nc='var tmp = Path.GetTempFileName();',
      c='var tmp = Path.Combine(dir, Guid.NewGuid().ToString("N"));'),
    r(id="cs-log-exception-message-only", type="bug", qual="rel", sev="medium", cwe="",
      title="Logging exception.Message instead of the exception",
      desc="A logger is passed ex.Message, discarding the type and stack trace.",
      rationale="Logging only Message loses the stack trace and inner exceptions needed for diagnosis; pass the exception object.",
      remediation="Log the exception object: logger.LogError(ex, \"...\").",
      source="https://learn.microsoft.com/en-us/dotnet/core/extensions/logging",
      re=r'\.Log(Error|Warning|Critical)\([^,)]*\.Message\s*\)',
      nc='logger.LogError(ex.Message);',
      c='logger.LogError(ex, "operation failed");'),
    r(id="cs-null-forgiving-operator", type="smell", qual="maint", sev="low", cwe="",
      title="Null-forgiving operator (!) used",
      desc="The null-forgiving operator suppresses a nullable warning without proving non-null.",
      rationale="`x!` tells the compiler to trust you; if wrong it NREs at runtime. Prefer a real null check.",
      remediation="Add a null check (or restructure) instead of suppressing with !.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving",
      re=r'\w!\.\w',
      nc='var name = user!.Name;',
      c='var name = user?.Name ?? "";'),
    r(id="cs-ef-include-string", type="smell", qual="maint", sev="low", cwe="",
      title="EF Core Include with a string path",
      desc="A related entity is included via a magic string rather than a lambda.",
      rationale="String-based Include is not refactor-safe or compile-checked; use the lambda overload.",
      remediation="Use Include(e => e.Related).",
      source="https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager",
      re=r'\.Include\(\s*"',
      nc='ctx.Orders.Include("Customer");',
      c='ctx.Orders.Include(o => o.Customer);'),
    r(id="cs-jsonconvert-nontyped", type="smell", qual="maint", sev="low", cwe="",
      title="DeserializeObject without a target type",
      desc="JsonConvert.DeserializeObject is called without a generic type, returning object/dynamic.",
      rationale="Non-generic deserialization loses type safety and forces casts; specify the type.",
      remediation="Use DeserializeObject<T>(json).",
      source="https://www.newtonsoft.com/json/help/html/DeserializeObject.htm",
      re=r'JsonConvert\.DeserializeObject\(',
      nc='var o = JsonConvert.DeserializeObject(json);',
      c='var o = JsonConvert.DeserializeObject<Order>(json);'),
    r(id="cs-typeof-name-vs-nameof", type="smell", qual="maint", sev="info", cwe="",
      title="typeof(X).Name instead of nameof(X)",
      desc="A type's name is obtained via reflection (typeof(X).Name) where nameof(X) suffices.",
      rationale="nameof is compile-time, refactor-safe, and avoids the reflection call.",
      remediation="Use nameof(X).",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/nameof",
      re=r'typeof\(\s*\w+\s*\)\.Name\b',
      nc='var n = typeof(Order).Name;',
      c='var n = nameof(Order);'),
    r(id="cs-gettype-name-compare", type="smell", qual="maint", sev="low", cwe="",
      title="Type dispatched by GetType().Name string compare",
      desc="Code branches on obj.GetType().Name compared to a string literal.",
      rationale="String-name type checks are fragile (namespace/rename) and slow; use pattern matching or is/as.",
      remediation="Use `is`/pattern matching on the type instead of comparing names.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is",
      re=r'\.GetType\(\)\.Name\s*==\s*"',
      nc='if (node.GetType().Name == "Leaf") { }',
      c='if (node is Leaf) { }'),
    r(id="cs-configureawait-true", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant ConfigureAwait(true)",
      desc="ConfigureAwait(true) is the default and adds nothing.",
      rationale="ConfigureAwait(true) is redundant; omit it (use false only when you intend to skip the captured context).",
      remediation="Remove ConfigureAwait(true).",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'\.ConfigureAwait\(\s*true\s*\)',
      nc='await Fetch().ConfigureAwait(true);',
      c='await Fetch();'),
    r(id="cs-goto-case", type="smell", qual="maint", sev="low", cwe="",
      title="goto case in a switch",
      desc="Control jumps between switch cases with goto case.",
      rationale="goto case entangles case logic and hurts readability; restructure the cases.",
      remediation="Refactor so cases don't jump into each other.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/jump-statements",
      re=r'\bgoto\s+case\b',
      nc='goto case 1;',
      c='HandleShared();'),
    r(id="cs-task-factory-startnew", type="smell", qual="maint", sev="low", cwe="",
      title="Task.Factory.StartNew instead of Task.Run",
      desc="Task.Factory.StartNew has surprising defaults (no async unwrap, current scheduler).",
      rationale="StartNew does not unwrap async delegates and uses the current TaskScheduler; Task.Run is the safe default.",
      remediation="Use Task.Run for offloading work.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/",
      re=r'Task\.Factory\.StartNew\(',
      nc='Task.Factory.StartNew(() => Work());',
      c='Task.Run(() => Work());'),
    r(id="cs-new-thread", type="smell", qual="maint", sev="low", cwe="",
      title="new Thread instead of the thread pool / tasks",
      desc="A raw Thread is created for short-lived work.",
      rationale="Manually created threads are costly and unmanaged; use Task/ThreadPool for most work.",
      remediation="Use Task.Run / the thread pool (reserve raw Threads for long-running dedicated work).",
      source="https://learn.microsoft.com/en-us/dotnet/standard/threading/",
      re=r'\bnew\s+Thread\s*\(',
      nc='var t = new Thread(Work);',
      c='var t = Task.Run(Work);'),
    r(id="cs-exception-no-message", type="smell", qual="maint", sev="low", cwe="",
      title="Exception thrown with no message",
      desc="An exception is constructed with no message argument.",
      rationale="A messageless exception gives no context at the failure site.",
      remediation="Provide a descriptive message (and inner exception if wrapping).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\bthrow\s+new\s+\w*Exception\(\s*\)',
      nc='throw new InvalidOperationException();',
      c='throw new InvalidOperationException("cache not initialized");'),
    r(id="cs-double-cast-object", type="smell", qual="maint", sev="low", cwe="",
      title="Cast to object then back",
      desc="A value is boxed to object and immediately cast back to a concrete type.",
      rationale="Casting through object boxes/unboxes needlessly; keep the concrete type.",
      remediation="Avoid the round-trip through object.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions",
      re=r'\(\s*int\s*\)\s*\(\s*object\s*\)',
      nc='var n = (int)(object)value;',
      c='var n = value;'),
    r(id="cs-empty-array-length-check", type="smell", qual="maint", sev="info", cwe="",
      title="arr.Length == 0 could use a clearer emptiness check",
      desc="An array/collection emptiness test uses .Length == 0 inline in a hot branch marker.",
      rationale="For clarity across arrays and collections, prefer a consistent emptiness idiom.",
      remediation="Use Length == 0 consistently, or a helper; ensure the collection isn't null first.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1827",
      re=r'\.Count\s*==\s*0\b',
      nc='if (list.Count == 0) return;',
      c='if (list.Count is 0) return;'),
    r(id="cs-string-isnullorwhitespace-preferred", type="smell", qual="maint", sev="info", cwe="",
      title="Trim().Length check instead of IsNullOrWhiteSpace",
      desc="Emptiness/whitespace is tested via Trim().Length rather than IsNullOrWhiteSpace.",
      rationale="string.IsNullOrWhiteSpace is clearer and null-safe and avoids the Trim allocation.",
      remediation="Use string.IsNullOrWhiteSpace(s).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace",
      re=r'\.Trim\(\)\.Length\s*==\s*0',
      nc='if (input.Trim().Length == 0) return;',
      c='if (string.IsNullOrWhiteSpace(input)) return;'),
    r(id="cs-datetimeoffset-now", type="smell", qual="maint", sev="low", cwe="",
      title="DateTimeOffset.Now for stored instants",
      desc="DateTimeOffset.Now carries the local offset; stored/compared instants should be UTC.",
      rationale="Persisting local-offset times complicates comparison across zones; use UtcNow.",
      remediation="Use DateTimeOffset.UtcNow.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.utcnow",
      re=r'\bDateTimeOffset\.Now\b',
      nc='var t = DateTimeOffset.Now;',
      c='var t = DateTimeOffset.UtcNow;'),
    r(id="cs-guid-parse-unchecked", type="smell", qual="maint", sev="low", cwe="",
      title="Guid.Parse without TryParse",
      desc="Guid.Parse throws on malformed input.",
      rationale="Guid.Parse throws on bad input; Guid.TryParse lets the caller handle it gracefully.",
      remediation="Use Guid.TryParse.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.guid.tryparse",
      re=r'\bGuid\.Parse\(',
      nc='var id = Guid.Parse(raw);',
      c='Guid.TryParse(raw, out var id);'),
    r(id="cs-int-cast-double-div", type="bug", qual="rel", sev="medium", cwe="CWE-682",
      title="Integer division assigned to a floating-point variable",
      desc="Two integers are divided and the result stored in a double/float, truncating first.",
      rationale="Integer division happens before the widening, so the fraction is lost (CWE-682).",
      remediation="Cast an operand to double before dividing.",
      source="https://cwe.mitre.org/data/definitions/682.html",
      re=r'(double|float|decimal)\s+\w+\s*=\s*\w+\s*/\s*\w+\s*;',
      nc='double ratio = count / total;',
      c='double ratio = (double)count / total;'),
    r(id="cs-string-format-noargs", type="smell", qual="maint", sev="info", cwe="",
      title="string.Format with no arguments",
      desc="string.Format is called with only a format string and no arguments.",
      rationale="string.Format with no args is just the string; drop the call.",
      remediation="Use the string literal directly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.format",
      re=r'string\.Format\(\s*"[^"{}]*"\s*\)',
      nc='var s = string.Format("hello");',
      c='var s = "hello";'),
    r(id="cs-empty-lambda-body", type="smell", qual="maint", sev="low", cwe="",
      title="Empty lambda / delegate body",
      desc="A lambda body is empty ({}), a likely stub or dropped handler.",
      rationale="An empty handler silently ignores the event/callback; make the intent explicit.",
      remediation="Implement the body or remove the handler.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-expressions",
      re=r'=>\s*\{\s*\}',
      nc='button.Click += (s, e) => {};',
      c='button.Click += (s, e) => OnClick();'),
    r(id="cs-readonly-array-field", type="smell", qual="maint", sev="low", cwe="",
      title="public static readonly array (mutable elements)",
      desc="A public static readonly array is exposed; its elements can still be replaced by callers.",
      rationale="readonly protects the reference, not the elements; a shared array is mutable global state (CA2105).",
      remediation="Expose a ReadOnlyCollection or a method returning a copy.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1819",
      re=r'\bpublic\s+static\s+readonly\s+\w[\w<>.]*\[\]',
      nc='    public static readonly int[] Primes = { 2, 3, 5 };',
      c='    public static readonly IReadOnlyList<int> Primes = new[] { 2, 3, 5 };'),
]
