CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","js");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","node"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="node-cookie-insecure-flag",type="hotspot",qual="sec",sev="low",cwe="CWE-614",owasp="A05:2021",title="Cookie with secure:false",
   desc="secure:false lets the cookie travel over plaintext HTTP.",
   rationale="Without the Secure flag a session cookie is sent over http and can be intercepted on the network.",
   remediation="Set secure:true (and serve over HTTPS).",
   source="https://cwe.mitre.org/data/definitions/614.html",
   re=r"secure\s*:\s*false",nc='res.cookie("sid", v, { httpOnly: true, secure: false });',c='res.cookie("sid", v, { httpOnly: true, secure: true });'),
 r(id="node-cookie-httponly-false",type="hotspot",qual="sec",sev="low",cwe="CWE-1004",owasp="A05:2021",title="Cookie with httpOnly:false",
   desc="httpOnly:false exposes the cookie to JavaScript (XSS theft).",
   rationale="Without HttpOnly, a cookie is readable by page scripts, so an XSS can exfiltrate the session.",
   remediation="Set httpOnly:true for session cookies.",
   source="https://cwe.mitre.org/data/definitions/1004.html",
   re=r"httpOnly\s*:\s*false",nc='res.cookie("sid", v, { httpOnly: false });',c='res.cookie("sid", v, { httpOnly: true });'),
 r(id="node-cors-credentials-true",type="hotspot",qual="sec",sev="low",cwe="CWE-942",owasp="A05:2021",title="CORS credentials enabled",
   desc="credentials:true sends cookies cross-origin; dangerous with a permissive origin.",
   rationale="Allowing credentials on CORS combined with a broad origin lets other sites make authenticated requests to the API.",
   remediation="Only enable credentials with a strict, explicit origin allow-list.",
   source="https://cwe.mitre.org/data/definitions/942.html",
   re=r"credentials\s*:\s*true",nc="app.use(cors({ origin: allowed, credentials: true }));",c="app.use(cors({ origin: allowed, credentials: false }));"),
 r(id="node-cookie-domain-leading-dot",type="hotspot",qual="sec",sev="low",cwe="CWE-1275",owasp="A05:2021",title="Cookie scoped to a parent domain",
   desc="A leading-dot cookie domain shares the cookie with all subdomains.",
   rationale="A parent-domain cookie is sent to every subdomain, widening exposure if any subdomain is compromised.",
   remediation="Scope the cookie to the specific host that needs it.",
   source="https://cwe.mitre.org/data/definitions/1275.html",
   re=r"domain\s*:\s*['\"]\.",nc='res.cookie("s", v, { domain: ".corp.example" });',c='res.cookie("s", v, { domain: "app.corp.example" });'),
 r(id="node-createhmac-weak",type="vuln",qual="sec",sev="medium",cwe="CWE-327",owasp="A02:2021",title="Weak HMAC hash",
   desc="createHmac('md5'|'sha1') uses a weak underlying hash.",
   rationale="MD5/SHA-1 HMACs are weaker than modern options and should be avoided for new signatures.",
   remediation="Use sha256 or stronger for the HMAC.",
   source="https://cwe.mitre.org/data/definitions/327.html",
   re=r"createHmac\s*\(\s*['\"](md5|sha1)['\"]",nc='const mac = crypto.createHmac("sha1", key);',c='const mac = crypto.createHmac("sha256", key);'),
 r(id="node-static-dotfiles-allow",type="hotspot",qual="sec",sev="low",cwe="CWE-548",owasp="A05:2021",title="Static server allows dotfiles",
   desc="dotfiles:'allow' serves .env, .git, and other hidden files.",
   rationale="Serving dotfiles can expose secrets and VCS metadata (.env, .git/config) to anyone.",
   remediation="Use dotfiles:'ignore' (the default) or 'deny'.",
   source="https://cwe.mitre.org/data/definitions/548.html",
   re=r"dotfiles\s*:\s*['\"]allow['\"]",nc='app.use(express.static(dir, { dotfiles: "allow" }));',c='app.use(express.static(dir, { dotfiles: "ignore" }));'),
 r(id="node-request-strictssl-false",type="hotspot",qual="sec",sev="high",cwe="CWE-295",owasp="A07:2021",title="strictSSL disabled",
   desc="strictSSL:false disables TLS certificate validation for the request.",
   rationale="Turning off strict SSL allows machine-in-the-middle attacks by accepting any certificate.",
   remediation="Leave strictSSL enabled and fix the underlying trust issue.",
   source="https://cwe.mitre.org/data/definitions/295.html",
   re=r"strictSSL\s*:\s*false",nc="request({ url: u, strictSSL: false });",c="request({ url: u, strictSSL: true });"),
 r(id="node-uncaught-exception-handler",type="bug",qual="rel",sev="medium",cwe="",title="uncaughtException handler that continues",
   desc="Handling uncaughtException and continuing leaves the process in an undefined state.",
   rationale="After an uncaught exception the process state is unreliable; the documented safe action is to log and exit, not resume.",
   remediation="Log the error and let the process exit (then restart via a supervisor).",
   source="https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly",
   re=r"process\.on\s*\(\s*['\"]uncaughtException['\"]",nc='process.on("uncaughtException", (e) => log(e));',c='process.on("SIGTERM", () => shutdown());'),
]
