# C# language-pack rule specs, batch 12 (#189). Clean-room, line-detectable — ORM/ADO SQLi sinks,
# XXE via XmlTextReader, upload path traversal, redundant ToString, empty-for, ReadLine null-deref.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cs-split-single-char", type="smell", qual="maint", sev="info", cwe="",
      title="String.Split with a single-character string",
      desc="String.Split is called with a one-character string separator.",
      rationale="The char separator overload avoids allocating a params string[] for the separators.",
      remediation="Use the char overload: Split(',').",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.split",
      re=r'\.Split\(\s*"[^"\\]"\s*\)',
      nc='var parts = line.Split(",");',
      c="var parts = line.Split(',');"),
    r(id="cs-append-tostring-redundant", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant ToString() in StringBuilder.Append",
      desc="A value is converted with ToString() before being passed to Append.",
      rationale="Append has typed overloads and calls ToString internally; the explicit call is redundant.",
      remediation="Pass the value directly to Append.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.append",
      re=r'\.Append\([^)]*\.ToString\(\)\)',
      nc='sb.Append(count.ToString());',
      c='sb.Append(count);'),
    r(id="cs-writeline-tostring-redundant", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant ToString() in Console.WriteLine",
      desc="A value is converted with ToString() before being passed to Console.WriteLine.",
      rationale="WriteLine(object) calls ToString itself; the explicit call is redundant.",
      remediation="Pass the value directly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.console.writeline",
      re=r'Console\.WriteLine\([^)]*\.ToString\(\)\)',
      nc='Console.WriteLine(result.ToString());',
      c='Console.WriteLine(result);'),
    r(id="cs-httpclient-infinite-timeout", type="smell", qual="maint", sev="medium", cwe="",
      title="HttpClient infinite timeout",
      desc="An HttpClient Timeout is set to Timeout.InfiniteTimeSpan.",
      rationale="An infinite timeout lets a stalled server hang the caller indefinitely and exhaust connections.",
      remediation="Set a finite timeout appropriate to the call.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout",
      re=r'Timeout\s*=\s*Timeout\.InfiniteTimeSpan\b',
      nc='client.Timeout = Timeout.InfiniteTimeSpan;',
      c='client.Timeout = TimeSpan.FromSeconds(30);'),
    r(id="cs-oracle-command-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="OracleCommand built by string concatenation",
      desc="An OracleCommand text is concatenated from a variable.",
      rationale="Concatenating input into SQL enables SQL injection (CWE-89). Use bind parameters.",
      remediation="Use a parameterized command with bind variables.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'new\s+OracleCommand\([^)]*\+',
      nc='var cmd = new OracleCommand("SELECT * FROM t WHERE id=" + id);',
      c='var cmd = new OracleCommand("SELECT * FROM t WHERE id=:id");'),
    r(id="cs-ef6-sqlquery-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="EF Database.SqlQuery built by concatenation",
      desc="A Database.SqlQuery text is concatenated from a variable.",
      rationale="Concatenating input into a raw SQL query enables SQL injection (CWE-89).",
      remediation="Use parameter placeholders with SqlParameter arguments.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'\.SqlQuery<[^>]*>\([^)]*\+',
      nc='var users = ctx.Database.SqlQuery<User>("SELECT * FROM Users WHERE Id=" + id);',
      c='var users = ctx.Database.SqlQuery<User>("SELECT * FROM Users WHERE Id=@p0", idParam);'),
    r(id="cs-ef6-executesqlcommand-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="EF Database.ExecuteSqlCommand built by concatenation",
      desc="A Database.ExecuteSqlCommand text is concatenated from a variable.",
      rationale="Concatenating input into a raw SQL command enables SQL injection (CWE-89).",
      remediation="Use parameter placeholders with SqlParameter arguments.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'ExecuteSqlCommand\([^)]*\+',
      nc='ctx.Database.ExecuteSqlCommand("DELETE FROM Logs WHERE Id=" + id);',
      c='ctx.Database.ExecuteSqlCommand("DELETE FROM Logs WHERE Id=@p0", idParam);'),
    r(id="cs-dapper-query-concat", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="Dapper Query built by concatenation",
      desc="A Dapper Query<T> SQL string is concatenated from a variable.",
      rationale="Concatenating input into the SQL passed to Dapper enables SQL injection (CWE-89).",
      remediation="Use named parameters and pass an anonymous parameter object.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'\.Query<[^>]*>\([^)]*\+',
      nc='var u = conn.Query<User>("SELECT * FROM Users WHERE Name=\'" + name + "\'");',
      c='var u = conn.Query<User>("SELECT * FROM Users WHERE Name=@name", new { name });'),
    r(id="cs-command-timeout-zero", type="smell", qual="maint", sev="low", cwe="",
      title="CommandTimeout set to 0 (no timeout)",
      desc="A database command's CommandTimeout is set to 0, meaning wait indefinitely.",
      rationale="A zero timeout lets a runaway query block the caller forever and exhaust the connection pool.",
      remediation="Set a finite CommandTimeout appropriate to the query.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.data.idbcommand.commandtimeout",
      re=r'CommandTimeout\s*=\s*0\b',
      nc='cmd.CommandTimeout = 0;',
      c='cmd.CommandTimeout = 30;'),
    r(id="cs-xmltextreader", type="vuln", qual="sec", sev="high", cwe="CWE-611", owasp="A05:2021",
      title="XmlTextReader (DTD processing enabled)",
      desc="An XmlTextReader is created directly, which historically resolves DTDs/external entities.",
      rationale="XmlTextReader does not prohibit DTDs by default, exposing XXE on untrusted XML (CWE-611).",
      remediation="Use XmlReader.Create with DtdProcessing.Prohibit and a null resolver.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r'\bnew\s+XmlTextReader\(',
      nc='var reader = new XmlTextReader(stream);',
      c='var reader = XmlReader.Create(stream, new XmlReaderSettings { DtdProcessing = DtdProcessing.Prohibit });'),
    r(id="cs-savefile-request", type="vuln", qual="sec", sev="high", cwe="CWE-22", owasp="A01:2021",
      title="Uploaded file saved to a request-controlled path",
      desc="SaveAs is called with a value taken from the request.",
      rationale="A request-controlled destination path enables directory traversal to overwrite arbitrary files (CWE-22).",
      remediation="Save under a fixed root with a sanitized, generated file name.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'\.SaveAs\([^)]*[Rr]equest',
      nc='file.SaveAs(Request.QueryString["path"]);',
      c='file.SaveAs(Path.Combine(uploadRoot, SafeName(file.FileName)));'),
    r(id="cs-substring-then-compare", type="smell", qual="maint", sev="low", cwe="",
      title="Substring(...) compared to a literal",
      desc="A prefix/segment is extracted with Substring and compared to a string literal.",
      rationale="Substring allocates a new string; StartsWith (or a span) compares in place.",
      remediation="Use StartsWith with a StringComparison (or slice with a Span).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.startswith",
      re=r'\.Substring\([^)]*\)\s*==\s*"',
      nc='if (code.Substring(0, 3) == "ERR") Handle();',
      c='if (code.StartsWith("ERR", StringComparison.Ordinal)) Handle();'),
    r(id="cs-tolower-contains", type="smell", qual="maint", sev="low", cwe="",
      title="ToLower().Contains for case-insensitive search",
      desc="A case-insensitive search lowercases the string and then calls Contains.",
      rationale="ToLower allocates a new string each call; Contains with StringComparison.OrdinalIgnoreCase avoids it.",
      remediation="Use Contains(value, StringComparison.OrdinalIgnoreCase).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.contains",
      re=r'\.ToLower\(\)\.Contains\(',
      nc='if (name.ToLower().Contains("admin")) Deny();',
      c='if (name.Contains("admin", StringComparison.OrdinalIgnoreCase)) Deny();'),
    r(id="cs-empty-for-body", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="for loop with an empty body (stray semicolon)",
      desc="A for loop is immediately terminated by a semicolon, so its body is empty.",
      rationale="A stray ; makes the loop run its counter but no work, and any following block runs once (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*for\s*\([\w\s;=<>!&|+.*/%-]+\)\s*;\s*$',
      nc='for (int i = 0; i < n; i++);',
      c='for (int i = 0; i < n; i++) Work(i);'),
    r(id="cs-console-readline-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing Console.ReadLine() directly",
      desc="A member is accessed on the result of Console.ReadLine() without a null check.",
      rationale="ReadLine returns null at end of input, so an immediate member access can NRE (CWE-476).",
      remediation="Store the result and null-check it before use.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'Console\.ReadLine\(\)\.',
      nc='var n = Console.ReadLine().Trim();',
      c='var line = Console.ReadLine(); var n = line?.Trim();'),
]
