# C# language-pack rule specs, batch 4 (#189). Clean-room, line-detectable — more crypto, LINQ/perf,
# reserved-exception misuse, globalization, and obsolete-API rules. Same clean-room policy.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cs")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "csharp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- crypto extras ----
    r(id="cs-dsa-weak", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="DSACryptoServiceProvider used",
      desc="DSA (via DSACryptoServiceProvider) is a legacy signature algorithm with small key limits.",
      rationale="Classic DSA is constrained and largely superseded; prefer ECDSA or RSA (CWE-327).",
      remediation="Use ECDsa or RSA for signatures.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bDSACryptoServiceProvider\b',
      nc='var dsa = new DSACryptoServiceProvider();',
      c='var ecdsa = ECDsa.Create();'),
    r(id="cs-rijndael-managed", type="smell", qual="maint", sev="low", cwe="",
      title="RijndaelManaged used",
      desc="RijndaelManaged is obsolete; it also allows non-AES block sizes.",
      rationale="RijndaelManaged is deprecated in favor of Aes.Create(), which is the standardized AES.",
      remediation="Use Aes.Create().",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.rijndaelmanaged",
      re=r'\bRijndaelManaged\b',
      nc='var alg = new RijndaelManaged();',
      c='var alg = Aes.Create();'),
    r(id="cs-aes-managed-obsolete", type="smell", qual="maint", sev="info", cwe="",
      title="AesManaged / SHA256Managed used",
      desc="The *Managed crypto classes are obsolete; use the factory Create() methods.",
      rationale="The *Managed types are deprecated in modern .NET; Aes.Create()/SHA256.Create() pick the best implementation.",
      remediation="Use the algorithm's static Create() method.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesmanaged",
      re=r'\bnew\s+(AesManaged|SHA256Managed|SHA512Managed|SHA384Managed)\b',
      nc='var alg = new AesManaged();',
      c='var alg = Aes.Create();'),
    r(id="cs-rsa-pkcs1-padding", type="vuln", qual="sec", sev="medium", cwe="CWE-780",
      title="RSA encryption with PKCS#1 v1.5 padding",
      desc="RSAEncryptionPadding.Pkcs1 is vulnerable to padding-oracle attacks.",
      rationale="PKCS#1 v1.5 encryption padding is susceptible to Bleichenbacher attacks (CWE-780); use OAEP.",
      remediation="Use RSAEncryptionPadding.OaepSHA256.",
      source="https://cwe.mitre.org/data/definitions/780.html",
      re=r'RSAEncryptionPadding\.Pkcs1\b',
      nc='var ct = rsa.Encrypt(data, RSAEncryptionPadding.Pkcs1);',
      c='var ct = rsa.Encrypt(data, RSAEncryptionPadding.OaepSHA256);'),
    r(id="cs-pbkdf2-fixed-salt", type="vuln", qual="sec", sev="medium", cwe="CWE-760",
      title="PBKDF2 with a fixed/derived salt",
      desc="Rfc2898DeriveBytes uses a salt from a string/Encoding rather than a random per-secret value.",
      rationale="A constant salt lets precomputed (rainbow) attacks target all secrets at once (CWE-760).",
      remediation="Generate a random salt per secret with RandomNumberGenerator.",
      source="https://cwe.mitre.org/data/definitions/760.html",
      re=r'new\s+Rfc2898DeriveBytes\([^,]*,\s*Encoding\.',
      nc='var kdf = new Rfc2898DeriveBytes(pwd, Encoding.UTF8.GetBytes("salt"), 100000);',
      c='var kdf = new Rfc2898DeriveBytes(pwd, RandomNumberGenerator.GetBytes(16), 100000);'),
    # ---- LINQ / perf ----
    r(id="cs-tolist-count", type="smell", qual="maint", sev="low", cwe="",
      title=".ToList().Count instead of .Count()",
      desc="A sequence is materialized with ToList() only to read .Count.",
      rationale="ToList() allocates the whole list just to count it; .Count() avoids the allocation (CA1829).",
      remediation="Use sequence.Count().",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829",
      re=r'\.ToList\(\)\.Count\b',
      nc='var n = query.ToList().Count;',
      c='var n = query.Count();'),
    r(id="cs-tolist-foreach", type="smell", qual="maint", sev="low", cwe="",
      title=".ToList().ForEach(...)",
      desc="ToList().ForEach materializes a list only to iterate it.",
      rationale="A foreach loop over the sequence avoids the extra allocation and is clearer.",
      remediation="Use a foreach loop over the sequence.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.tolist",
      re=r'\.ToList\(\)\.ForEach\(',
      nc='items.ToList().ForEach(x => Process(x));',
      c='foreach (var x in items) Process(x);'),
    r(id="cs-where-any", type="smell", qual="maint", sev="low", cwe="",
      title=".Where(...).Any() instead of .Any(predicate)",
      desc="A filtered existence check uses Where(...).Any() rather than Any(predicate).",
      rationale="Any(predicate) expresses the check directly without the intermediate query (CA1827-adjacent).",
      remediation="Use sequence.Any(predicate).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any",
      re=r'\.Where\([^)]*\)\.Any\(\s*\)',
      nc='if (users.Where(u => u.Active).Any()) { }',
      c='if (users.Any(u => u.Active)) { }'),
    r(id="cs-where-first", type="smell", qual="maint", sev="low", cwe="",
      title=".Where(...).First()/FirstOrDefault() instead of the predicate overload",
      desc="A filtered lookup uses Where(...).First() rather than First(predicate).",
      rationale="First(predicate)/FirstOrDefault(predicate) is the direct form (CA1826-adjacent).",
      remediation="Use sequence.First(predicate) / FirstOrDefault(predicate).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first",
      re=r'\.Where\([^)]*\)\.(First|FirstOrDefault|Single|SingleOrDefault|Last)\(',
      nc='var u = users.Where(x => x.Id == id).First();',
      c='var u = users.First(x => x.Id == id);'),
    r(id="cs-substring-zero", type="smell", qual="maint", sev="info", cwe="",
      title="Substring(0) is a no-op",
      desc="s.Substring(0) returns the same string.",
      rationale="Substring(0) does nothing but allocate; remove it.",
      remediation="Remove the redundant Substring(0) call.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.string.substring",
      re=r'\.Substring\(\s*0\s*\)',
      nc='var s = raw.Substring(0);',
      c='var s = raw;'),
    r(id="cs-count-property-linq-enumerable", type="smell", qual="maint", sev="low", cwe="",
      title=".Count() on a materialized collection",
      desc="LINQ .Count() is called on something that already exposes a .Count/.Length property.",
      rationale="Arrays/Lists expose an O(1) Count/Length; the LINQ .Count() adds indirection (CA1829).",
      remediation="Use the .Count / .Length property.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829",
      re=r'\.ToArray\(\)\.Count\(\)',
      nc='var n = seq.ToArray().Count();',
      c='var n = seq.Count();'),
    r(id="cs-orderby-first", type="smell", qual="maint", sev="low", cwe="",
      title=".OrderBy(...).First() to get a minimum/maximum",
      desc="Sorting then taking First() finds a min/max by sorting the whole sequence.",
      rationale="OrderBy().First() is O(n log n) for what MinBy/MaxBy do in O(n).",
      remediation="Use MinBy/MaxBy (or Min/Max).",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.minby",
      re=r'\.OrderBy(Descending)?\([^)]*\)\.First(OrDefault)?\(',
      nc='var top = items.OrderByDescending(x => x.Score).First();',
      c='var top = items.MaxBy(x => x.Score);'),
    # ---- reserved / base exception misuse (CA2201) ----
    r(id="cs-throw-base-exception", type="smell", qual="maint", sev="medium", cwe="",
      title="Throwing System.Exception directly",
      desc="Code throws the base Exception type instead of a specific exception.",
      rationale="Throwing the base Exception forces callers to catch too broadly; throw a specific type (CA2201).",
      remediation="Throw a specific exception type (e.g. InvalidOperationException).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201",
      re=r'\bthrow\s+new\s+(System\.)?Exception\s*\(',
      nc='throw new Exception("bad state");',
      c='throw new InvalidOperationException("bad state");'),
    r(id="cs-throw-application-exception", type="smell", qual="maint", sev="medium", cwe="",
      title="Throwing ApplicationException",
      desc="ApplicationException is a legacy base type not meant to be thrown directly.",
      rationale="ApplicationException adds no value over Exception and should not be thrown (CA2201).",
      remediation="Throw a specific exception type.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201",
      re=r'\bthrow\s+new\s+ApplicationException\s*\(',
      nc='throw new ApplicationException("failure");',
      c='throw new InvalidOperationException("failure");'),
    r(id="cs-throw-reserved-exception", type="bug", qual="rel", sev="medium", cwe="",
      title="Throwing a runtime-reserved exception type",
      desc="Code throws NullReferenceException / IndexOutOfRangeException / AccessViolationException, which the runtime reserves.",
      rationale="These types are reserved for the runtime; throwing them confuses debugging (CA2201).",
      remediation="Throw ArgumentNullException/ArgumentOutOfRangeException as appropriate.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201",
      re=r'\bthrow\s+new\s+(NullReferenceException|IndexOutOfRangeException|AccessViolationException)\s*\(',
      nc='throw new NullReferenceException("x was null");',
      c='throw new ArgumentNullException(nameof(x));'),
    r(id="cs-catch-and-continue-loop", type="smell", qual="maint", sev="low", cwe="",
      title="try/catch wrapping a loop body without handling",
      desc="A general catch inside a loop continues on any failure.",
      rationale="Catching all exceptions per iteration can mask systematic failures; scope the catch and decide per exception.",
      remediation="Catch the specific expected exception and log/act on it.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031",
      re=r'catch\s*\(\s*Exception\s+\w+\s*\)\s*\{\s*continue\s*;\s*\}',
      nc='foreach (var x in xs) { try { P(x); } catch (Exception e) { continue; } }',
      c='foreach (var x in xs) { try { P(x); } catch (FormatException e) { Log(e); } }'),
    # ---- globalization ----
    r(id="cs-toupper-no-culture", type="smell", qual="maint", sev="info", cwe="",
      title="ToUpper()/ToLower() without a culture",
      desc="A string is upper/lower-cased without specifying a culture.",
      rationale="Culture-dependent casing gives locale-varying results (e.g. Turkish 'I'); use *Invariant or a StringComparison for machine data (CA1311).",
      remediation="Use ToUpperInvariant()/ToLowerInvariant() (or specify a culture).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1311",
      re=r'\.To(Upper|Lower)\(\s*\)',
      nc='var key = code.ToUpper();',
      c='var key = code.ToUpperInvariant();'),
    r(id="cs-string-compareto", type="smell", qual="maint", sev="low", cwe="",
      title="String.CompareTo for ordering (culture-sensitive)",
      desc="String.CompareTo compares using the current culture, giving locale-varying order.",
      rationale="CompareTo is culture-sensitive; use string.Compare with an explicit StringComparison for deterministic ordering.",
      remediation="Use string.Compare(a, b, StringComparison.Ordinal).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310",
      re=r'\.CompareTo\(\s*"',
      nc='if (a.CompareTo("m") < 0) { }',
      c='if (string.Compare(a, "m", StringComparison.Ordinal) < 0) { }'),
    r(id="cs-startswith-no-comparison", type="smell", qual="maint", sev="low", cwe="",
      title="StartsWith/EndsWith with a string but no StringComparison",
      desc="StartsWith/EndsWith is called with a single string argument (culture-sensitive by default).",
      rationale="The single-argument overload is culture-sensitive; pass a StringComparison for predictable, faster matching (CA1310).",
      remediation="Pass StringComparison.Ordinal (or the intended comparison).",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1310",
      re=r'\.(StartsWith|EndsWith)\(\s*"[^"]*"\s*\)',
      nc='if (name.StartsWith("tmp")) { }',
      c='if (name.StartsWith("tmp", StringComparison.Ordinal)) { }'),
    # ---- obsolete / api ----
    r(id="cs-webrequest-create", type="smell", qual="maint", sev="low", cwe="",
      title="WebRequest.Create (obsolete)",
      desc="WebRequest/HttpWebRequest is legacy; HttpClient is the supported API.",
      rationale="WebRequest is obsolete on modern .NET; use HttpClient.",
      remediation="Use HttpClient.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.net.webrequest",
      re=r'\bWebRequest\.Create\(',
      nc='var req = WebRequest.Create(url);',
      c='var resp = await _httpClient.GetAsync(url);'),
    r(id="cs-double-negation", type="smell", qual="maint", sev="info", cwe="",
      title="Double boolean negation (!!)",
      desc="A boolean is negated twice (!!x), which is a no-op.",
      rationale="Double negation is redundant and confusing; drop it.",
      remediation="Remove the redundant negation.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators",
      re=r'[^!=]!!\w',
      nc='if (!!ready) Go();',
      c='if (ready) Go();'),
    r(id="cs-tuple-item1", type="smell", qual="maint", sev="info", cwe="",
      title="ValueTuple accessed via .Item1/.Item2",
      desc="A tuple is accessed by positional .Item1/.Item2 instead of named elements.",
      rationale="Named tuple elements are clearer than positional Item1/Item2 (IDE-style).",
      remediation="Name the tuple elements and use the names.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples",
      re=r'\.Item[1-9]\b',
      nc='var name = pair.Item1;',
      c='var (name, age) = pair;'),
    r(id="cs-empty-generic-catch-when", type="smell", qual="maint", sev="low", cwe="",
      title="catch (Exception) without a filter",
      desc="A broad catch (Exception) is used where an exception filter (when) could scope it.",
      rationale="An exception filter avoids unwinding the stack for exceptions you will not handle; a bare catch(Exception) cannot discriminate.",
      remediation="Add a `when (...)` filter or catch a specific type.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when",
      re=r'catch\s*\(\s*Exception\s+\w+\s*\)\s*\{\s*if\s*\(',
      nc='catch (Exception e) { if (e is IOException) Log(e); else throw; }',
      c='catch (IOException e) { Log(e); }'),
    r(id="cs-explicit-default-of-value", type="smell", qual="maint", sev="info", cwe="",
      title="Redundant default(T) for a value type",
      desc="default(int)/default(bool) etc. is used where a literal is clearer.",
      rationale="default(T) on a well-known value type is less readable than the literal (0/false).",
      remediation="Use the literal value (0, false, ...) or the target-typed default.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default",
      re=r'default\(\s*(int|bool|long|double|float|decimal)\s*\)',
      nc='int n = default(int);',
      c='int n = 0;'),
    r(id="cs-empty-else", type="smell", qual="maint", sev="low", cwe="",
      title="Empty else block",
      desc="An else clause has an empty body.",
      rationale="An empty else is dead code that obscures intent; remove it.",
      remediation="Remove the empty else.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\belse\s*\{\s*\}',
      nc='if (ok) Go(); else {}',
      c='if (ok) Go();'),
    r(id="cs-if-empty-then-else", type="smell", qual="maint", sev="low", cwe="",
      title="if with an empty body but a non-empty else",
      desc="An if has an empty body while its else does the work, an inverted condition.",
      rationale="An empty then-branch usually means the condition should be negated for clarity.",
      remediation="Negate the condition and drop the empty branch.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\bif\s*\([^)]*\)\s*\{\s*\}\s*else\b',
      nc='if (ready) {} else { Wait(); }',
      c='if (!ready) { Wait(); }'),
    r(id="cs-redundant-boolean-return", type="smell", qual="maint", sev="low", cwe="",
      title="return with a redundant boolean literal ternary",
      desc="A ternary returns true/false literals for a boolean expression.",
      rationale="`return cond ? true : false;` is just `return cond;`.",
      remediation="Return the boolean expression directly.",
      source="https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/",
      re=r'\?\s*true\s*:\s*false\b|\?\s*false\s*:\s*true\b',
      nc='return x > 0 ? true : false;',
      c='return x > 0;'),
    r(id="cs-string-plus-empty", type="smell", qual="maint", sev="info", cwe="",
      title='Concatenation with "" to stringify',
      desc='A value is concatenated with "" to convert it to a string.',
      rationale='"" + x is an obscure way to call ToString; use interpolation or an explicit conversion.',
      remediation="Use string interpolation or Convert.ToString.",
      source="https://learn.microsoft.com/en-us/dotnet/csharp/how-to/concatenate-multiple-strings",
      re=r'""\s*\+\s*\w+|"\s*"\s*\+\s*\w',
      nc='var s = "" + count;',
      c='var s = count.ToString();'),
    r(id="cs-list-capacity-in-loop", type="smell", qual="maint", sev="low", cwe="",
      title="new List<T>() then Add in a for loop of known size",
      desc="A list is grown element-by-element in a counted loop without a preset capacity.",
      rationale="Presizing the list (new List<T>(count)) avoids repeated backing-array reallocations.",
      remediation="Construct the list with the known capacity.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.-ctor",
      re=r'for\s*\([^)]*\)\s*\w+\.Add\(',
      nc='for (int i=0;i<n;i++) acc.Add(items[i]);',
      c='var acc = new List<T>(n);'),
    r(id="cs-async-task-delay-result", type="bug", qual="rel", sev="medium", cwe="",
      title="Task.Delay without await",
      desc="Task.Delay is called without await, so the delay does not actually pause execution.",
      rationale="An un-awaited Task.Delay returns immediately; the intended pause never happens.",
      remediation="await the Task.Delay call.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay",
      re=r'^\s*Task\.Delay\([^)]*\)\s*;',
      nc='Task.Delay(500);',
      c='await Task.Delay(500);'),
    r(id="cs-parse-bool-eq-true", type="smell", qual="maint", sev="info", cwe="",
      title="bool.Parse compared to true",
      desc="bool.Parse(...) == true is a redundant comparison.",
      rationale="Comparing a bool to true is redundant; use the value directly.",
      remediation="Use the boolean value directly.",
      source="https://learn.microsoft.com/en-us/dotnet/api/system.boolean.parse",
      re=r'bool\.Parse\([^)]*\)\s*==\s*true',
      nc='if (bool.Parse(flag) == true) Go();',
      c='if (bool.Parse(flag)) Go();'),
]
