# C language-pack rule specs, batch 4 (#198). Clean-room, line-detectable — ECB mode, unbounded scansets,
# memcpy/strlen truncation, assignment-in-while, int-to-char, NULL-return deref, non-reentrant getpw/getgr.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "c")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "c"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


def nonreentrant(id_, fn, rfn, extra=""):
    return r(id=id_, type="smell", qual="maint", sev="low", cwe="CWE-676",
             title=f"Use of {fn}()",
             desc=f"{fn}() returns a pointer to shared static storage.",
             rationale=f"Concurrent calls overwrite the shared result; {fn} is not thread-safe (CWE-676).{extra}",
             remediation=f"Use {rfn}().",
             source="https://cwe.mitre.org/data/definitions/676.html",
             re=rf'\b{fn}\s*\(',
             nc=f'r = {fn}(arg);',
             c=f'{rfn}(arg, &buf, storage, sizeof(storage), &r);')


RULES = [
    r(id="c-evp-ecb", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="ECB cipher mode",
      desc="An OpenSSL EVP cipher is created in ECB mode.",
      rationale="ECB encrypts identical blocks identically, leaking plaintext structure (CWE-327).",
      remediation="Use an authenticated mode (GCM) or at least CBC with a random IV.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_[a-z0-9_]*_ecb\s*\(',
      nc='EVP_EncryptInit_ex(ctx, EVP_aes_128_ecb(), NULL, key, NULL);',
      c='EVP_EncryptInit_ex(ctx, EVP_aes_128_gcm(), NULL, key, iv);'),
    r(id="c-scanf-scanset-unbounded", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="scanf scanset without a field width",
      desc="A scanf %[ scanset conversion has no maximum field width.",
      rationale="Without a width, a scanset writes an unbounded run into the buffer, overflowing it (CWE-120).",
      remediation="Add a field width matching the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bscanf\s*\([^)]*%\[',
      nc='scanf("%[^\\n]", line);',
      c='scanf("%127[^\\n]", line);'),
    r(id="c-sscanf-scanset-unbounded", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="sscanf scanset without a field width",
      desc="An sscanf %[ scanset conversion has no maximum field width.",
      rationale="Without a width, a scanset writes an unbounded run into the buffer, overflowing it (CWE-120).",
      remediation="Add a field width matching the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bsscanf\s*\([^)]*%\[',
      nc='sscanf(s, "%[^,]", field);',
      c='sscanf(s, "%63[^,]", field);'),
    r(id="c-memcpy-strlen", type="bug", qual="rel", sev="medium", cwe="CWE-170",
      title="memcpy() sized with strlen() (drops the NUL)",
      desc="memcpy copies strlen(src) bytes, omitting the terminating NUL.",
      rationale="The destination is left without a NUL terminator, causing later over-reads (CWE-170).",
      remediation="Copy strlen(src)+1 bytes, or use a bounded string copy.",
      source="https://cwe.mitre.org/data/definitions/170.html",
      re=r'\bmemcpy\s*\([^,]*,[^,]*,\s*strlen\s*\([^)]*\)\s*\)',
      nc='memcpy(dst, src, strlen(src));',
      c='memcpy(dst, src, strlen(src) + 1);'),
    r(id="c-assignment-in-while", type="bug", qual="rel", sev="medium", cwe="CWE-481",
      title="Assignment in a while condition",
      desc="A while condition contains a single = (assignment) rather than ==.",
      rationale="An assignment in a condition is usually a typo for == (CWE-481).",
      remediation="Use == for comparison, or wrap an intentional assignment in extra parentheses.",
      source="https://cwe.mitre.org/data/definitions/481.html",
      re=r'\bwhile\s*\(\s*\w+\s*=\s*[^=]',
      nc='while (c = next()) emit(c);',
      c='while (c == next()) emit(c);'),
    r(id="c-int-to-char-getchar", type="bug", qual="rel", sev="medium", cwe="CWE-704",
      title="getchar()/getc() result stored in a char",
      desc="The int result of a character-input function is assigned to a char.",
      rationale="Narrowing to char loses the ability to distinguish EOF from a valid byte (CWE-704).",
      remediation="Store the result in an int.",
      source="https://cwe.mitre.org/data/definitions/704.html",
      re=r'\bchar\s+\w+\s*=\s*(getchar|getc|fgetc)\s*\(',
      nc='char c = getchar();',
      c='int c = getchar();'),
    r(id="c-null-return-deref", type="bug", qual="rel", sev="medium", cwe="CWE-476",
      title="Dereferencing a string-search result directly",
      desc="A member/value is read from the result of strchr/strstr/etc. without a NULL check.",
      rationale="These functions return NULL when not found, so an immediate dereference can crash (CWE-476).",
      remediation="Store the result and check for NULL before dereferencing.",
      source="https://cwe.mitre.org/data/definitions/476.html",
      re=r'\*\s*(strchr|strrchr|strstr|strpbrk|memchr)\s*\(',
      nc='char sep = *strchr(line, \'=\');',
      c='char *p = strchr(line, \'=\'); char sep = p ? *p : 0;'),
    r(id="c-rsa-generate-key", type="smell", qual="maint", sev="low", cwe="",
      title="Use of RSA_generate_key()",
      desc="The deprecated OpenSSL RSA_generate_key() is used.",
      rationale="RSA_generate_key is deprecated and its callback-based API is error-prone.",
      remediation="Use RSA_generate_key_ex()/EVP_PKEY_keygen() with a 2048-bit+ key.",
      source="https://www.openssl.org/docs/man1.1.1/man3/RSA_generate_key.html",
      re=r'\bRSA_generate_key\s*\(',
      nc='RSA *r = RSA_generate_key(1024, 3, NULL, NULL);',
      c='RSA_generate_key_ex(rsa, 2048, e, NULL);'),
    r(id="c-abort", type="smell", qual="maint", sev="low", cwe="",
      title="abort() in library code",
      desc="abort() terminates the whole process abnormally.",
      rationale="A library that aborts denies the caller any chance to recover or clean up.",
      remediation="Return an error code and let the caller decide.",
      source="https://wiki.sei.cmu.edu/confluence/display/c/ERR06-C.+Understand+the+termination+behavior+of+assert%28%29+and+abort%28%29",
      re=r'\babort\s*\(\s*\)',
      nc='abort();',
      c='return ERR_FATAL;'),
    r(id="c-static-iv-array", type="hotspot", qual="sec", sev="medium", cwe="CWE-329",
      title="Static IV byte array",
      desc="An initialization vector named iv is initialized from a fixed byte array.",
      rationale="A reused/static IV breaks semantic security in CBC/GCM and can leak plaintext (CWE-329); review its source.",
      remediation="Generate a fresh random IV per message and transmit it with the ciphertext.",
      source="https://cwe.mitre.org/data/definitions/329.html",
      re=r'\biv\s*\[\s*\d*\s*\]\s*=\s*\{',
      nc='unsigned char iv[16] = { 0 };',
      c='unsigned char iv[16]; RAND_bytes(iv, sizeof(iv));'),
    r(id="c-hardcoded-key-array", type="hotspot", qual="sec", sev="high", cwe="CWE-798",
      title="Hard-coded key byte array",
      desc="A buffer named key is initialized from a fixed byte array literal.",
      rationale="An embedded key is exposed to anyone with the binary (CWE-798); review its source.",
      remediation="Load the key from a secret store / KMS at runtime.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'\bkey\s*\[\s*\d*\s*\]\s*=\s*\{',
      nc='unsigned char key[32] = { 0x00, 0x01, 0x02 };',
      c='unsigned char key[32]; load_key_from_kms(key, sizeof(key));'),
    r(id="c-strdupa", type="bug", qual="rel", sev="medium", cwe="CWE-770",
      title="Use of strdupa()",
      desc="strdupa() duplicates a string onto the stack via alloca.",
      rationale="A long or attacker-influenced string silently overflows the stack (CWE-770).",
      remediation="Use strdup() and free the result.",
      source="https://cwe.mitre.org/data/definitions/770.html",
      re=r'\bstrdupa\s*\(',
      nc='char *d = strdupa(input);',
      c='char *d = strdup(input);'),
    r(id="c-basename-dirname", type="smell", qual="maint", sev="info", cwe="CWE-676",
      title="Use of basename()/dirname()",
      desc="basename()/dirname() may modify their argument and can use static storage.",
      rationale="Behavior differs between POSIX and GNU versions and is not reentrant (CWE-676).",
      remediation="Operate on a mutable copy of the path and be explicit about the variant.",
      source="https://man7.org/linux/man-pages/man3/basename.3.html",
      re=r'\b(basename|dirname)\s*\(',
      nc='char *b = basename(path);',
      c='const char *b = strrchr(path, \'/\');'),
    nonreentrant("c-ctermid", "ctermid", "ctermid_r"),
    nonreentrant("c-getgrgid", "getgrgid", "getgrgid_r"),
    nonreentrant("c-getpwnam", "getpwnam", "getpwnam_r"),
    nonreentrant("c-getpwuid", "getpwuid", "getpwuid_r"),
]
