# C language-pack rule specs, batch 3 (#198). Clean-room, line-detectable — weak crypto (libc/OpenSSL),
# obsolete/non-reentrant APIs, permission/RNG, return-of-local, empty-body bugs. Concept origins cited.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "c")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "c"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


def weakhash(id_, fn, re_):
    return r(id=id_, type="vuln", qual="sec", sev="medium", cwe="CWE-327",
             title=f"Weak hash function {fn}",
             desc=f"{fn} computes a cryptographically broken digest.",
             rationale=f"{fn} is vulnerable to collisions and unsuitable for integrity/signatures (CWE-327).",
             remediation="Use SHA-256 or SHA-3.",
             source="https://cwe.mitre.org/data/definitions/327.html",
             re=re_,
             nc=f'{fn}(data, len, digest);',
             c='SHA256(data, len, digest);')


RULES = [
    weakhash("c-md5", "MD5", r'\bMD5(_Init)?\s*\('),
    weakhash("c-sha1", "SHA1", r'\bSHA1(_Init)?\s*\('),
    weakhash("c-md4", "MD4", r'\bMD4(_Init)?\s*\('),
    weakhash("c-md2", "MD2", r'\bMD2(_Init)?\s*\('),
    r(id="c-evp-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="EVP_md5() digest",
      desc="An OpenSSL EVP digest context is initialized with MD5.",
      rationale="MD5 is collision-prone and unsuitable for security use (CWE-327).",
      remediation="Use EVP_sha256().",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_md5\s*\(',
      nc='EVP_DigestInit_ex(ctx, EVP_md5(), NULL);',
      c='EVP_DigestInit_ex(ctx, EVP_sha256(), NULL);'),
    r(id="c-evp-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="EVP_sha1() digest",
      desc="An OpenSSL EVP digest context is initialized with SHA-1.",
      rationale="SHA-1 is collision-broken and unsuitable for signatures (CWE-327).",
      remediation="Use EVP_sha256().",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_sha1\s*\(',
      nc='EVP_DigestInit_ex(ctx, EVP_sha1(), NULL);',
      c='EVP_DigestInit_ex(ctx, EVP_sha256(), NULL);'),
    r(id="c-des-encrypt", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="DES encryption",
      desc="A single-DES OpenSSL routine is used.",
      rationale="DES has a 56-bit key and is trivially brute-forced (CWE-327).",
      remediation="Use AES via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bDES_(ecb|cbc|ncbc|cfb64|ofb64)_encrypt\s*\(',
      nc='DES_ecb_encrypt(&in, &out, &ks, DES_ENCRYPT);',
      c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="c-blowfish", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Blowfish encryption",
      desc="An OpenSSL Blowfish routine is used.",
      rationale="Blowfish has a 64-bit block (SWEET32) and is deprecated (CWE-327).",
      remediation="Use AES via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bBF_(ecb|cbc|cfb64|ofb64)_encrypt\s*\(',
      nc='BF_cbc_encrypt(in, out, len, &ks, iv, BF_ENCRYPT);',
      c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="c-rc4", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="RC4 stream cipher",
      desc="The RC4 stream cipher is used.",
      rationale="RC4 has known biases and is prohibited for secure use (CWE-327).",
      remediation="Use AES-GCM via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bRC4\s*\(',
      nc='RC4(&key, len, in, out);',
      c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="c-ssl-verify-none", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="TLS certificate verification disabled (SSL_VERIFY_NONE)",
      desc="An OpenSSL context is set to SSL_VERIFY_NONE.",
      rationale="Disabling peer verification allows man-in-the-middle attacks (CWE-295).",
      remediation="Use SSL_VERIFY_PEER and validate the certificate chain.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'\bSSL_VERIFY_NONE\b',
      nc='SSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, NULL);',
      c='SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, verify_cb);'),
    r(id="c-ssl-weak-method", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="Obsolete SSL/TLS protocol method",
      desc="A connection uses an SSLv2/SSLv3/TLSv1.0 method.",
      rationale="These protocols are broken/deprecated and must not be negotiated (CWE-327).",
      remediation="Use TLS_client_method()/TLS_server_method() and require TLS 1.2+.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(SSLv2|SSLv3|TLSv1)_(client|server)_method\s*\(',
      nc='ctx = SSL_CTX_new(SSLv3_client_method());',
      c='ctx = SSL_CTX_new(TLS_client_method());'),
    # --- weak RNG seeding variants (CWE-337) ---
    r(id="c-srand-getpid", type="hotspot", qual="sec", sev="medium", cwe="CWE-337",
      title="srand() seeded with getpid()",
      desc="The PRNG is seeded from the process id.",
      rationale="A PID is low-entropy and guessable, making the sequence predictable (CWE-337).",
      remediation="Seed from a CSPRNG, or use a CSPRNG directly for security values.",
      source="https://cwe.mitre.org/data/definitions/337.html",
      re=r'\bsrand\s*\(\s*getpid\s*\(',
      nc='srand(getpid());',
      c='getrandom(&seed, sizeof(seed), 0);'),
    r(id="c-srandom-time", type="hotspot", qual="sec", sev="medium", cwe="CWE-337",
      title="srandom() seeded with time()",
      desc="The random() generator is seeded with the current time.",
      rationale="A time-based seed is guessable, making the sequence predictable (CWE-337).",
      remediation="Seed from a CSPRNG, or use a CSPRNG directly for security values.",
      source="https://cwe.mitre.org/data/definitions/337.html",
      re=r'\bsrandom\s*\(\s*time\s*\(',
      nc='srandom(time(NULL));',
      c='getrandom(&seed, sizeof(seed), 0);'),
    # --- permissive file creation (CWE-732) ---
    r(id="c-creat-777", type="vuln", qual="sec", sev="high", cwe="CWE-732",
      title="creat() with mode 0777",
      desc="A file is created world-readable/writable/executable.",
      rationale="Mode 0777 lets any local user modify the file (CWE-732).",
      remediation="Use a restrictive mode (e.g. 0600).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bcreat\s*\([^,]*,\s*0777\b',
      nc='int fd = creat(path, 0777);',
      c='int fd = creat(path, 0600);'),
    r(id="c-mkfifo-777", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="mkfifo() with mode 0777",
      desc="A FIFO is created world-writable.",
      rationale="A world-writable FIFO lets any local user inject or read data (CWE-732).",
      remediation="Use a restrictive mode (e.g. 0600).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bmkfifo\s*\([^,]*,\s*0777\b',
      nc='mkfifo(path, 0777);',
      c='mkfifo(path, 0600);'),
    # --- return address of a local (CWE-562) ---
    r(id="c-return-addr-local", type="bug", qual="rel", sev="high", cwe="CWE-562",
      title="Return of the address of a local variable",
      desc="A function returns the address of a named local variable.",
      rationale="The variable's storage is reclaimed when the function returns, leaving a dangling pointer (CWE-562).",
      remediation="Return by value, or allocate the object with a lifetime beyond the call.",
      source="https://cwe.mitre.org/data/definitions/562.html",
      re=r'\breturn\s+&\s*\w+\s*;',
      nc='return &local;',
      c='return result;'),
    # --- non-literal va_list format sinks (CWE-134) ---
    r(id="c-vprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="vprintf() with a non-literal format",
      desc="vprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bvprintf\s*\(\s*[a-zA-Z_]\w*\s*,',
      nc='vprintf(fmt, ap);',
      c='vprintf("%s", ap);'),
    r(id="c-vfprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="vfprintf() with a non-literal format",
      desc="vfprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bvfprintf\s*\([^,)]*,\s*[a-zA-Z_]\w*\s*,',
      nc='vfprintf(stderr, fmt, ap);',
      c='vfprintf(stderr, "%s", ap);'),
    # --- empty-body control-flow bugs ---
    r(id="c-empty-else", type="bug", qual="rel", sev="low", cwe="CWE-483",
      title="else with an empty body (stray semicolon)",
      desc="An else clause is immediately terminated by a semicolon.",
      rationale="The stray ; makes the else a no-op and runs the following statement unconditionally (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*else\s*;\s*$',
      nc='else ;',
      c='else handle_default();'),
    r(id="c-empty-for-body", type="bug", qual="rel", sev="medium", cwe="CWE-483",
      title="for loop with an empty body (stray semicolon)",
      desc="A for loop is immediately terminated by a semicolon.",
      rationale="The stray ; makes the loop body empty and any following block runs once (CWE-483).",
      remediation="Remove the semicolon and use a block.",
      source="https://cwe.mitre.org/data/definitions/483.html",
      re=r'^\s*for\s*\([\w\s;=<>!&|+.*/%-]+\)\s*;\s*$',
      nc='for (i = 0; i < n; i++);',
      c='for (i = 0; i < n; i++) work(i);'),
    # --- obsolete / superseded APIs (maintainability) ---
    r(id="c-ecvt", type="smell", qual="maint", sev="info", cwe="",
      title="Use of ecvt()",
      desc="ecvt() is an obsolete float-to-string function using a static buffer.",
      rationale="It is removed from POSIX and not reentrant.",
      remediation="Use snprintf() with a %g/%e/%f conversion.",
      source="https://man7.org/linux/man-pages/man3/ecvt.3.html",
      re=r'\becvt\s*\(',
      nc='char *s = ecvt(v, 6, &dec, &sign);',
      c='snprintf(buf, sizeof(buf), "%g", v);'),
    r(id="c-fcvt", type="smell", qual="maint", sev="info", cwe="",
      title="Use of fcvt()",
      desc="fcvt() is an obsolete float-to-string function using a static buffer.",
      rationale="It is removed from POSIX and not reentrant.",
      remediation="Use snprintf() with a %f conversion.",
      source="https://man7.org/linux/man-pages/man3/fcvt.3.html",
      re=r'\bfcvt\s*\(',
      nc='char *s = fcvt(v, 6, &dec, &sign);',
      c='snprintf(buf, sizeof(buf), "%f", v);'),
    r(id="c-gcvt", type="smell", qual="maint", sev="info", cwe="",
      title="Use of gcvt()",
      desc="gcvt() is an obsolete float-to-string function.",
      rationale="It is removed from POSIX; snprintf is portable and safer.",
      remediation="Use snprintf() with a %g conversion.",
      source="https://man7.org/linux/man-pages/man3/gcvt.3.html",
      re=r'\bgcvt\s*\(',
      nc='gcvt(v, 6, buf);',
      c='snprintf(buf, sizeof(buf), "%g", v);'),
    r(id="c-valloc", type="smell", qual="maint", sev="info", cwe="",
      title="Use of valloc()",
      desc="valloc() is an obsolete page-aligned allocator.",
      rationale="It is deprecated and non-portable.",
      remediation="Use posix_memalign() / aligned_alloc().",
      source="https://man7.org/linux/man-pages/man3/valloc.3.html",
      re=r'\bvalloc\s*\(',
      nc='void *p = valloc(size);',
      c='posix_memalign(&p, pagesize, size);'),
    r(id="c-memalign", type="smell", qual="maint", sev="info", cwe="",
      title="Use of memalign()",
      desc="memalign() is an obsolete aligned allocator.",
      rationale="It is deprecated in favor of standard aligned allocation.",
      remediation="Use posix_memalign() / aligned_alloc().",
      source="https://man7.org/linux/man-pages/man3/memalign.3.html",
      re=r'\bmemalign\s*\(',
      nc='void *p = memalign(align, size);',
      c='posix_memalign(&p, align, size);'),
    r(id="c-sbrk", type="smell", qual="maint", sev="info", cwe="",
      title="Use of sbrk()",
      desc="sbrk() manipulates the program break directly.",
      rationale="It is deprecated, interacts badly with malloc, and is non-portable.",
      remediation="Use malloc()/mmap().",
      source="https://man7.org/linux/man-pages/man2/sbrk.2.html",
      re=r'\bsbrk\s*\(',
      nc='void *p = sbrk(size);',
      c='void *p = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_ANON | MAP_PRIVATE, -1, 0);'),
    r(id="c-usleep", type="smell", qual="maint", sev="info", cwe="",
      title="Use of usleep()",
      desc="usleep() is obsolete.",
      rationale="It was removed from POSIX.1-2008 and has interaction issues with signals.",
      remediation="Use nanosleep() (or clock_nanosleep()).",
      source="https://man7.org/linux/man-pages/man3/usleep.3.html",
      re=r'\busleep\s*\(',
      nc='usleep(1000);',
      c='nanosleep(&ts, NULL);'),
    r(id="c-gettimeofday", type="smell", qual="maint", sev="info", cwe="",
      title="Use of gettimeofday()",
      desc="gettimeofday() is obsolescent.",
      rationale="clock_gettime provides higher resolution and a monotonic clock.",
      remediation="Use clock_gettime().",
      source="https://man7.org/linux/man-pages/man2/gettimeofday.2.html",
      re=r'\bgettimeofday\s*\(',
      nc='gettimeofday(&tv, NULL);',
      c='clock_gettime(CLOCK_MONOTONIC, &ts);'),
    r(id="c-ftime", type="smell", qual="maint", sev="info", cwe="",
      title="Use of ftime()",
      desc="ftime() is a removed legacy time function.",
      rationale="It was removed from POSIX and is non-portable.",
      remediation="Use clock_gettime().",
      source="https://man7.org/linux/man-pages/man3/ftime.3.html",
      re=r'\bftime\s*\(',
      nc='ftime(&tb);',
      c='clock_gettime(CLOCK_REALTIME, &ts);'),
    r(id="c-getpw", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of getpw()",
      desc="getpw() writes into a caller buffer with no size and is obsolete.",
      rationale="It is removed from POSIX and can overflow the buffer.",
      remediation="Use getpwuid_r().",
      source="https://man7.org/linux/man-pages/man3/getpw.3.html",
      re=r'\bgetpw\s*\(',
      nc='getpw(uid, buf);',
      c='getpwuid_r(uid, &pwd, buf, sizeof(buf), &res);'),
    r(id="c-getlogin", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of getlogin()",
      desc="getlogin() returns a pointer to static storage and can be spoofed.",
      rationale="It is not reentrant and its result is unreliable for security decisions (CWE-676).",
      remediation="Use getlogin_r(), or derive identity from getuid()/getpwuid().",
      source="https://man7.org/linux/man-pages/man3/getlogin.3.html",
      re=r'\bgetlogin\s*\(\s*\)',
      nc='char *u = getlogin();',
      c='getlogin_r(buf, sizeof(buf));'),
    r(id="c-ttyname", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of ttyname()",
      desc="ttyname() returns a pointer to static storage.",
      rationale="It is not thread-safe (CWE-676).",
      remediation="Use ttyname_r().",
      source="https://man7.org/linux/man-pages/man3/ttyname.3.html",
      re=r'\bttyname\s*\(',
      nc='char *t = ttyname(fd);',
      c='char t[64]; ttyname_r(fd, t, sizeof(t));'),
    r(id="c-inet-addr", type="smell", qual="maint", sev="low", cwe="",
      title="Use of inet_addr()",
      desc="inet_addr() has an ambiguous error return and is IPv4-only.",
      rationale="It returns INADDR_NONE (-1) both for the broadcast address and for errors, and cannot parse IPv6.",
      remediation="Use inet_pton() (or getaddrinfo()).",
      source="https://man7.org/linux/man-pages/man3/inet_addr.3.html",
      re=r'\binet_addr\s*\(',
      nc='addr.s_addr = inet_addr(ip);',
      c='inet_pton(AF_INET, ip, &addr);'),
    r(id="c-gethostbyaddr", type="smell", qual="maint", sev="low", cwe="CWE-676",
      title="Use of gethostbyaddr()",
      desc="gethostbyaddr() is obsolete and not reentrant.",
      rationale="It uses static storage and is IPv4-centric (CWE-676).",
      remediation="Use getnameinfo().",
      source="https://man7.org/linux/man-pages/man3/gethostbyaddr.3.html",
      re=r'\bgethostbyaddr\s*\(',
      nc='struct hostent *h = gethostbyaddr(&a, len, AF_INET);',
      c='getnameinfo(sa, salen, host, sizeof(host), NULL, 0, 0);'),
    r(id="c-toascii", type="smell", qual="maint", sev="info", cwe="",
      title="Use of toascii()",
      desc="toascii() is an obsolete character function.",
      rationale="It was removed from POSIX.1-2008 and is locale-dependent.",
      remediation="Mask explicitly (c & 0x7f) if 7-bit truncation is truly intended.",
      source="https://man7.org/linux/man-pages/man3/toascii.3.html",
      re=r'\btoascii\s*\(',
      nc='int a = toascii(c);',
      c='int a = c & 0x7f;'),
]
