# C++ language-pack rule specs, batch 2 (#199). Clean-room, line-detectable — dangerous C-library sinks
# that remain exploitable in .cpp translation units (buffer overflow, format string, command injection,
# weak crypto/RNG, unsafe permissions). C++-idiomatic remediations. Concept origins cited (CWE, CERT).
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "cpp")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "cpp"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    r(id="cpp-gets", type="vuln", qual="sec", sev="critical", cwe="CWE-242",
      title="Use of gets()",
      desc="gets() reads a line with no destination bound.",
      rationale="gets cannot know the buffer size and always risks overflow (CWE-242/120).",
      remediation="Use std::getline with a std::string.",
      source="https://cwe.mitre.org/data/definitions/242.html",
      re=r'\bgets\s*\(', nc='gets(buffer);', c='std::getline(std::cin, line);'),
    r(id="cpp-strcpy", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of strcpy()",
      desc="strcpy() copies with no destination bound.",
      rationale="A source longer than the destination overflows the buffer (CWE-120).",
      remediation="Use std::string assignment, or snprintf with a size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bstrcpy\s*\(', nc='strcpy(dst, src);', c='std::string dst = src;'),
    r(id="cpp-strcat", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of strcat()",
      desc="strcat() appends with no destination bound.",
      rationale="A result exceeding the buffer overflows it (CWE-120).",
      remediation="Use std::string concatenation (operator+=).",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bstrcat\s*\(', nc='strcat(path, suffix);', c='path += suffix;'),
    r(id="cpp-sprintf", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of sprintf()",
      desc="sprintf() writes formatted output with no destination bound.",
      rationale="A wide field or long %s writes past the buffer (CWE-120).",
      remediation="Use std::format / snprintf with a size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bsprintf\s*\(', nc='sprintf(buf, "%s", name);', c='auto s = std::format("{}", name);'),
    r(id="cpp-vsprintf", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="Use of vsprintf()",
      desc="vsprintf() writes from a va_list with no destination bound.",
      rationale="Like sprintf, vsprintf can overflow the destination (CWE-120).",
      remediation="Use vsnprintf() with the buffer size.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bvsprintf\s*\(', nc='vsprintf(buf, fmt, args);', c='vsnprintf(buf, sizeof(buf), fmt, args);'),
    r(id="cpp-scanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="scanf(\"%s\") without a field width",
      desc="A scanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token, overflowing the buffer (CWE-120).",
      remediation="Read into a std::string with operator>>, or add a field width.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bscanf\s*\(\s*"[^"]*%s', nc='scanf("%s", name);', c='std::cin >> name;'),
    r(id="cpp-sscanf-unbounded-s", type="vuln", qual="sec", sev="high", cwe="CWE-120",
      title="sscanf(\"%s\") without a field width",
      desc="An sscanf %s conversion has no maximum field width.",
      rationale="Without a width, %s writes an unbounded token, overflowing the buffer (CWE-120).",
      remediation="Parse with std::istringstream, or add a field width.",
      source="https://cwe.mitre.org/data/definitions/120.html",
      re=r'\bsscanf\s*\([^)]*"[^"]*%s', nc='sscanf(line, "%s", tok);', c='std::istringstream(line) >> tok;'),
    r(id="cpp-strncpy", type="bug", qual="rel", sev="medium", cwe="CWE-170",
      title="Use of strncpy()",
      desc="strncpy() does not NUL-terminate when the source fills the buffer.",
      rationale="A non-terminated buffer causes later over-reads (CWE-170).",
      remediation="Use std::string, or NUL-terminate explicitly.",
      source="https://cwe.mitre.org/data/definitions/170.html",
      re=r'\bstrncpy\s*\(', nc='strncpy(dst, src, sizeof(dst));', c='std::string dst(src, n);'),
    r(id="cpp-strncat", type="bug", qual="rel", sev="medium", cwe="CWE-787",
      title="Use of strncat()",
      desc="strncat()'s size argument is the remaining space, not the buffer size.",
      rationale="Passing the total buffer size overflows the destination (CWE-787).",
      remediation="Use std::string concatenation.",
      source="https://cwe.mitre.org/data/definitions/787.html",
      re=r'\bstrncat\s*\(', nc='strncat(dst, src, sizeof(dst));', c='dst_str += src;'),
    r(id="cpp-printf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="printf() with a non-literal format",
      desc="printf() is called with a single variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format, or std::format/std::print.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bprintf\s*\(\s*[a-zA-Z_]\w*\s*\)', nc='printf(msg);', c='printf("%s", msg);'),
    r(id="cpp-fprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="fprintf() with a non-literal format",
      desc="fprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bfprintf\s*\([^,)]*,\s*[a-zA-Z_]\w*\s*\)', nc='fprintf(stderr, msg);', c='fprintf(stderr, "%s", msg);'),
    r(id="cpp-snprintf-nonliteral", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="snprintf() with a non-literal format",
      desc="snprintf() is called with a variable as the format string.",
      rationale="An attacker-controlled format string enables memory disclosure/corruption (CWE-134).",
      remediation="Use a literal format string.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\bsnprintf\s*\([^,]*,[^,]*,\s*[a-zA-Z_]\w*\s*\)', nc='snprintf(buf, sizeof(buf), fmt);', c='snprintf(buf, sizeof(buf), "%s", fmt);'),
    r(id="cpp-format-percent-n", type="vuln", qual="sec", sev="high", cwe="CWE-134",
      title="%n conversion in a format string",
      desc="A printf-family format string contains the %n conversion.",
      rationale="%n writes to a pointer argument, a classic format-string write primitive (CWE-134).",
      remediation="Remove %n; never use it with untrusted format strings.",
      source="https://cwe.mitre.org/data/definitions/134.html",
      re=r'\b(printf|fprintf|sprintf|snprintf)\s*\([^;]*"[^"]*%n', nc='fprintf(log, "%n done", &count);', c='fprintf(log, "%d done", count);'),
    r(id="cpp-system", type="vuln", qual="sec", sev="high", cwe="CWE-78",
      title="Use of system()",
      desc="system() runs a command through the shell.",
      rationale="Any input in the command string can be shell-injected (CWE-78).",
      remediation="Spawn the process directly (posix_spawn/exec) with an argv array.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'\bsystem\s*\(', nc='system(cmd.c_str());', c='posix_spawn(&pid, "/bin/prog", NULL, NULL, argv, environ);'),
    r(id="cpp-popen", type="vuln", qual="sec", sev="high", cwe="CWE-78",
      title="Use of popen()",
      desc="popen() runs a command through the shell.",
      rationale="Input in the command string can be shell-injected (CWE-78).",
      remediation="Use a pipe with exec and no shell.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'\bpopen\s*\(', nc='FILE* f = popen(cmd.c_str(), "r");', c='auto proc = spawn_no_shell(args);'),
    r(id="cpp-execlp", type="vuln", qual="sec", sev="medium", cwe="CWE-426",
      title="Use of execlp()",
      desc="execlp() resolves the program via PATH.",
      rationale="A PATH-based lookup can execute an attacker-planted binary (CWE-426).",
      remediation="Use execv() with an absolute path.",
      source="https://cwe.mitre.org/data/definitions/426.html",
      re=r'\bexeclp\s*\(', nc='execlp("prog", "prog", nullptr);', c='execv("/usr/bin/prog", argv);'),
    r(id="cpp-execvp", type="vuln", qual="sec", sev="medium", cwe="CWE-426",
      title="Use of execvp()",
      desc="execvp() resolves the program via PATH.",
      rationale="A PATH-based lookup can execute an attacker-planted binary (CWE-426).",
      remediation="Use execv() with an absolute path.",
      source="https://cwe.mitre.org/data/definitions/426.html",
      re=r'\bexecvp\s*\(', nc='execvp("prog", argv);', c='execv("/usr/bin/prog", argv);'),
    r(id="cpp-tmpnam", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of tmpnam()",
      desc="tmpnam() returns a name whose file is created later (TOCTOU).",
      rationale="An attacker can create/symlink the path between naming and opening (CWE-377).",
      remediation="Use mkstemp() (or std::filesystem with O_EXCL).",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\btmpnam\s*\(', nc='char* p = tmpnam(nullptr);', c='int fd = mkstemp(templ);'),
    r(id="cpp-mktemp", type="vuln", qual="sec", sev="medium", cwe="CWE-377",
      title="Use of mktemp()",
      desc="mktemp() only generates a name; the file is created separately (TOCTOU).",
      rationale="The naming/creation gap enables a race/symlink attack (CWE-377).",
      remediation="Use mkstemp().",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r'\bmktemp\s*\(', nc='mktemp(templ);', c='int fd = mkstemp(templ);'),
    r(id="cpp-rand", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="Use of rand()/std::rand() for security values",
      desc="rand() is a non-cryptographic pseudo-random generator.",
      rationale="Its output is predictable and unsuitable for tokens/keys (CWE-338).",
      remediation="Use std::random_device / a CSPRNG for security values.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'\brand\s*\(\s*\)', nc='int token = rand();', c='auto token = secure_rng();'),
    r(id="cpp-srand-time", type="hotspot", qual="sec", sev="medium", cwe="CWE-337",
      title="srand() seeded with time()",
      desc="The PRNG is seeded with the current time.",
      rationale="A time-based seed is guessable, making the sequence predictable (CWE-337).",
      remediation="Seed from std::random_device, or use a CSPRNG.",
      source="https://cwe.mitre.org/data/definitions/337.html",
      re=r'\bsrand\s*\(\s*time\s*\(', nc='srand(time(nullptr));', c='std::mt19937 gen{std::random_device{}()};'),
    r(id="cpp-malloc-multiply", type="bug", qual="rel", sev="high", cwe="CWE-190",
      title="malloc() with a multiplication size",
      desc="An allocation size is computed by multiplying two values.",
      rationale="The product can overflow size_t, allocating a too-small buffer (CWE-190).",
      remediation="Use a std::vector, or check for overflow before multiplying.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\bmalloc\s*\(\s*\w+\s*\*', nc='auto* a = (int*)malloc(n * sizeof(int));', c='std::vector<int> a(n);'),
    r(id="cpp-alloca", type="bug", qual="rel", sev="medium", cwe="CWE-770",
      title="Use of alloca()",
      desc="alloca() allocates on the stack with no failure path.",
      rationale="A large or attacker-influenced size silently overflows the stack (CWE-770).",
      remediation="Use a std::vector or a fixed-size buffer.",
      source="https://cwe.mitre.org/data/definitions/770.html",
      re=r'\balloca\s*\(', nc='char* buf = (char*)alloca(n);', c='std::vector<char> buf(n);'),
    r(id="cpp-atoi", type="bug", qual="rel", sev="low", cwe="CWE-190",
      title="Use of atoi()",
      desc="atoi() reports no error and has UB on overflow.",
      rationale="Invalid/out-of-range input silently yields 0 or UB (CWE-190).",
      remediation="Use std::from_chars / std::stoi with error handling.",
      source="https://cwe.mitre.org/data/definitions/190.html",
      re=r'\batoi\s*\(', nc='int n = atoi(arg);', c='auto [p, ec] = std::from_chars(b, e, n);'),
    r(id="cpp-strtok", type="bug", qual="rel", sev="low", cwe="CWE-676",
      title="Use of strtok()",
      desc="strtok() keeps hidden static state and mutates its input.",
      rationale="It is not reentrant or thread-safe (CWE-676).",
      remediation="Split with std::string_view / std::ranges, or use strtok_r.",
      source="https://cwe.mitre.org/data/definitions/676.html",
      re=r'\bstrtok\s*\(', nc='char* t = strtok(line, ",");', c='for (auto part : std::views::split(line, \',\')) {}'),
    r(id="cpp-memcpy-strlen", type="bug", qual="rel", sev="medium", cwe="CWE-170",
      title="memcpy() sized with strlen() (drops the NUL)",
      desc="memcpy copies strlen(src) bytes, omitting the terminating NUL.",
      rationale="The destination is left without a NUL terminator, causing over-reads (CWE-170).",
      remediation="Use std::string, or copy strlen(src)+1 bytes.",
      source="https://cwe.mitre.org/data/definitions/170.html",
      re=r'\bmemcpy\s*\([^,]*,[^,]*,\s*strlen\s*\([^)]*\)\s*\)', nc='memcpy(dst, src, strlen(src));', c='std::string dst = src;'),
    r(id="cpp-md5", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash function MD5",
      desc="MD5 computes a cryptographically broken digest.",
      rationale="MD5 is collision-prone and unsuitable for integrity/signatures (CWE-327).",
      remediation="Use SHA-256 (EVP_sha256).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bMD5(_Init)?\s*\(', nc='MD5(data, len, digest);', c='SHA256(data, len, digest);'),
    r(id="cpp-sha1", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash function SHA1",
      desc="SHA1 computes a collision-broken digest.",
      rationale="SHA-1 is unsuitable for signatures/integrity (CWE-327).",
      remediation="Use SHA-256 (EVP_sha256).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bSHA1(_Init)?\s*\(', nc='SHA1(data, len, digest);', c='SHA256(data, len, digest);'),
    r(id="cpp-des-encrypt", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="DES encryption",
      desc="A single-DES OpenSSL routine is used.",
      rationale="DES has a 56-bit key and is trivially brute-forced (CWE-327).",
      remediation="Use AES via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bDES_(ecb|cbc|ncbc|cfb64|ofb64)_encrypt\s*\(', nc='DES_ecb_encrypt(&in, &out, &ks, DES_ENCRYPT);', c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="cpp-rc4", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="RC4 stream cipher",
      desc="The RC4 stream cipher is used.",
      rationale="RC4 has known biases and is prohibited for secure use (CWE-327).",
      remediation="Use AES-GCM via the EVP interface.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bRC4\s*\(', nc='RC4(&key, len, in, out);', c='EVP_EncryptUpdate(ctx, out, &n, in, len);'),
    r(id="cpp-evp-ecb", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="ECB cipher mode",
      desc="An OpenSSL EVP cipher is created in ECB mode.",
      rationale="ECB encrypts identical blocks identically, leaking plaintext structure (CWE-327).",
      remediation="Use an authenticated mode (GCM).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\bEVP_[a-z0-9_]*_ecb\s*\(', nc='EVP_EncryptInit_ex(ctx, EVP_aes_128_ecb(), nullptr, key, nullptr);', c='EVP_EncryptInit_ex(ctx, EVP_aes_128_gcm(), nullptr, key, iv);'),
    r(id="cpp-ssl-verify-none", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="TLS certificate verification disabled (SSL_VERIFY_NONE)",
      desc="An OpenSSL context is set to SSL_VERIFY_NONE.",
      rationale="Disabling peer verification allows man-in-the-middle attacks (CWE-295).",
      remediation="Use SSL_VERIFY_PEER and validate the chain.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'\bSSL_VERIFY_NONE\b', nc='SSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, nullptr);', c='SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, cb);'),
    r(id="cpp-ssl-weak-method", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="Obsolete SSL/TLS protocol method",
      desc="A connection uses an SSLv2/SSLv3/TLSv1.0 method.",
      rationale="These protocols are broken/deprecated (CWE-327).",
      remediation="Use TLS_client_method()/TLS_server_method() and require TLS 1.2+.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'\b(SSLv2|SSLv3|TLSv1)_(client|server)_method\s*\(', nc='ctx = SSL_CTX_new(SSLv3_client_method());', c='ctx = SSL_CTX_new(TLS_client_method());'),
    r(id="cpp-chmod-777", type="vuln", qual="sec", sev="high", cwe="CWE-732",
      title="chmod() to 0777",
      desc="A file is made world-readable/writable/executable.",
      rationale="Mode 0777 lets any local user modify the file (CWE-732).",
      remediation="Grant least privilege (e.g. 0600).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bchmod\s*\([^,]*,\s*0777\b', nc='chmod(path, 0777);', c='chmod(path, 0600);'),
    r(id="cpp-mkdir-777", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="mkdir() with mode 0777",
      desc="A directory is created world-writable.",
      rationale="A world-writable directory lets any local user plant files (CWE-732).",
      remediation="Use a restrictive mode (e.g. 0700).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bmkdir\s*\([^,]*,\s*0777\b', nc='mkdir(dir, 0777);', c='mkdir(dir, 0700);'),
    r(id="cpp-umask-zero", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="umask(0)",
      desc="The file-mode creation mask is cleared.",
      rationale="umask(0) lets new files take fully permissive modes (CWE-732).",
      remediation="Set a restrictive umask (e.g. 077).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bumask\s*\(\s*0\s*\)', nc='umask(0);', c='umask(077);'),
    r(id="cpp-open-creat-no-mode", type="vuln", qual="sec", sev="medium", cwe="CWE-732",
      title="open() with O_CREAT but no mode argument",
      desc="A file is created with open()+O_CREAT but no explicit mode.",
      rationale="The new file's permissions are indeterminate and may be world-accessible (CWE-732).",
      remediation="Pass an explicit restrictive mode (e.g. 0600).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r'\bopen\s*\([^,]*,[^,)]*O_CREAT[^,)]*\)', nc='int fd = open(path, O_CREAT | O_WRONLY);', c='int fd = open(path, O_CREAT | O_WRONLY, 0600);'),
    r(id="cpp-access-toctou", type="hotspot", qual="sec", sev="medium", cwe="CWE-367",
      title="access() permission check (TOCTOU)",
      desc="access() checks a path that is then opened separately.",
      rationale="The file can change between the check and the open, enabling a race (CWE-367).",
      remediation="Open first and check on the descriptor, or drop privileges.",
      source="https://cwe.mitre.org/data/definitions/367.html",
      re=r'\baccess\s*\(', nc='if (access(path, W_OK) == 0) open(path, O_WRONLY);', c='int fd = open(path, O_WRONLY); if (fd >= 0) {}'),
    r(id="cpp-static-iv", type="hotspot", qual="sec", sev="medium", cwe="CWE-329",
      title="Static IV byte array",
      desc="An initialization vector named iv is initialized from a fixed byte array.",
      rationale="A reused/static IV breaks semantic security in CBC/GCM (CWE-329); review its source.",
      remediation="Generate a fresh random IV per message.",
      source="https://cwe.mitre.org/data/definitions/329.html",
      re=r'\biv\s*\[\s*\d*\s*\]\s*=\s*\{', nc='unsigned char iv[16] = { 0 };', c='unsigned char iv[16]; RAND_bytes(iv, sizeof(iv));'),
    r(id="cpp-hardcoded-key", type="hotspot", qual="sec", sev="high", cwe="CWE-798",
      title="Hard-coded key byte array",
      desc="A buffer named key is initialized from a fixed byte array literal.",
      rationale="An embedded key is exposed to anyone with the binary (CWE-798); review its source.",
      remediation="Load the key from a secret store / KMS at runtime.",
      source="https://cwe.mitre.org/data/definitions/798.html",
      re=r'\bkey\s*\[\s*\d*\s*\]\s*=\s*\{', nc='unsigned char key[32] = { 0x00, 0x01 };', c='unsigned char key[32]; load_key(key, sizeof(key));'),
]
