package jarlicense

import (
	"archive/zip"
	"bytes"
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const mitText = `MIT License

Copyright (c) 2024 Example

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`

func pomProps(group, artifact, version string) string {
	return "#Generated by Maven\ngroupId=" + group + "\nartifactId=" + artifact + "\nversion=" + version + "\n"
}

func writeJAR(t *testing.T, dir, name string, entries map[string]string) {
	t.Helper()
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	zw := zip.NewWriter(f)
	for n, content := range entries {
		w, err := zw.Create(n)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
}

// pomXML builds a minimal Maven pom.xml (with the real POM namespace) declaring the given licenses.
func pomXML(names ...string) string {
	var b bytes.Buffer
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString(`<project xmlns="http://maven.apache.org/POM/4.0.0"><licenses>`)
	for _, n := range names {
		b.WriteString("<license><name>" + n + "</name></license>")
	}
	b.WriteString(`</licenses></project>`)
	return b.String()
}

// The core P1 fix: syft CONCLUDES a spray of licenses from a JAR that bundles third-party notices
// (mysql-connector-java → ~10 spurious ids). The JAR's own pom.xml declares ONE license — authoritative —
// which must replace the spray. Mirrors what Trivy reports.
func TestResolveOverridesSprayWithDeclaredPom(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "mysql-connector-java-8.0.21.jar", map[string]string{
		"META-INF/maven/mysql/mysql-connector-java/pom.properties": pomProps("mysql", "mysql-connector-java", "8.0.21"),
		"META-INF/maven/mysql/mysql-connector-java/pom.xml":        pomXML("The GNU General Public License, v2 with FOSS exception"),
	})
	// Component carries syft's 10-license spray.
	comps := []sbom.Component{{Name: "mysql-connector-java", Version: "8.0.21", Licenses: []sbom.License{
		{SPDXID: "Apache-2.0"}, {SPDXID: "Artistic-1.0-Perl"}, {SPDXID: "BSD-3-Clause"}, {SPDXID: "EPL-1.0"},
		{SPDXID: "EPL-2.0"}, {SPDXID: "GPL-2.0-only"}, {SPDXID: "LGPL-2.0-only"}, {SPDXID: "LGPL-2.1-only"},
		{SPDXID: "MIT"}, {SPDXID: "Zlib"},
	}}}
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("resolved = %d, want 1", n)
	}
	if got := comps[0].Licenses; len(got) != 1 || got[0].Name != "The GNU General Public License, v2 with FOSS exception" {
		t.Fatalf("licenses = %+v, want the single declared pom license", got)
	}
	if comps[0].LicenseSource != sbom.LicenseSourceManifest || comps[0].LicenseConfidence != "declared" {
		t.Errorf("provenance = %q/%q, want manifest/declared", comps[0].LicenseSource, comps[0].LicenseConfidence)
	}
}

// A declared pom license also FILLS a missing one (no embedded LICENSE text needed).
func TestResolveDeclaredPomFillsMissing(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "lib-2.0.0.jar", map[string]string{
		"META-INF/maven/com.acme/lib/pom.properties": pomProps("com.acme", "lib", "2.0.0"),
		"META-INF/maven/com.acme/lib/pom.xml":        pomXML("Apache License, Version 2.0"),
	})
	comps := []sbom.Component{{Name: "lib", Version: "2.0.0"}} // no license
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("resolved = %d, want 1", n)
	}
	if got := comps[0].Licenses; len(got) != 1 || got[0].Name != "Apache License, Version 2.0" {
		t.Fatalf("licenses = %+v, want the declared pom license", got)
	}
}

// A single existing license must be left ALONE even when a declared pom exists — nothing to
// disambiguate, and the declared name is not always more precise than a clean single id.
func TestResolveLeavesSingleLicenseAlone(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "single-1.0.0.jar", map[string]string{
		"META-INF/maven/com.acme/single/pom.properties": pomProps("com.acme", "single", "1.0.0"),
		"META-INF/maven/com.acme/single/pom.xml":        pomXML("Apache License, Version 2.0"),
	})
	comps := []sbom.Component{{Name: "single", Version: "1.0.0", Licenses: []sbom.License{{SPDXID: "MIT"}}}}
	if n := New().Resolve(context.Background(), dir, comps); n != 0 {
		t.Fatalf("resolved = %d, want 0 (single license untouched)", n)
	}
	if comps[0].Licenses[0].SPDXID != "MIT" {
		t.Errorf("single license overwritten: %+v", comps[0].Licenses)
	}
}

func TestResolveFromJARLicenseText(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "grpc-core-1.62.2.jar", map[string]string{
		"META-INF/maven/io.grpc/grpc-core/pom.properties": pomProps("io.grpc", "grpc-core", "1.62.2"),
		"META-INF/LICENSE": mitText,
	})
	// Component has no license and even a mis-derived group — matched by artifact@version.
	comps := []sbom.Component{{Name: "grpc-core", Version: "1.62.2", PURL: "pkg:maven/io.grpc.internal/grpc-core@1.62.2"}}
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("resolved = %d, want 1", n)
	}
	if len(comps[0].Licenses) == 0 || comps[0].Licenses[0].SPDXID != "MIT" {
		t.Fatalf("license = %+v, want SPDXID MIT", comps[0].Licenses)
	}
	if comps[0].LicenseSource != "local-file" {
		t.Fatalf("LicenseSource = %q, want local-file", comps[0].LicenseSource)
	}
}

func TestResolveLeavesDeclaredAndUnmatchedAlone(t *testing.T) {
	dir := t.TempDir()
	writeJAR(t, dir, "x-1.0.0.jar", map[string]string{
		"META-INF/maven/com.x/x/pom.properties": pomProps("com.x", "x", "1.0.0"),
		"META-INF/LICENSE":                      mitText,
	})
	comps := []sbom.Component{
		{Name: "x", Version: "1.0.0", Licenses: []sbom.License{{SPDXID: "Apache-2.0"}}}, // already declared → untouched
		{Name: "ghost", Version: "9.9.9"},                                               // no matching JAR → stays unknown
	}
	if n := New().Resolve(context.Background(), dir, comps); n != 0 {
		t.Fatalf("resolved = %d, want 0", n)
	}
	if comps[0].Licenses[0].SPDXID != "Apache-2.0" {
		t.Errorf("declared license overwritten: %+v", comps[0].Licenses)
	}
	if len(comps[1].Licenses) != 0 {
		t.Errorf("unmatched component got a license: %+v", comps[1].Licenses)
	}
}

func TestResolveNestedSpringBootJAR(t *testing.T) {
	dir := t.TempDir()
	var nested bytes.Buffer
	nz := zip.NewWriter(&nested)
	pw, _ := nz.Create("META-INF/maven/org.jetbrains/annotations/pom.properties")
	_, _ = pw.Write([]byte(pomProps("org.jetbrains", "annotations", "26.0.1")))
	lw, _ := nz.Create("META-INF/LICENSE.txt")
	_, _ = lw.Write([]byte(mitText))
	_ = nz.Close()

	f, _ := os.Create(filepath.Join(dir, "app-1.0.0.jar"))
	fz := zip.NewWriter(f)
	bw, _ := fz.Create("BOOT-INF/lib/annotations-26.0.1.jar")
	_, _ = bw.Write(nested.Bytes())
	_ = fz.Close()
	_ = f.Close()

	comps := []sbom.Component{{Name: "annotations", Version: "26.0.1"}}
	if n := New().Resolve(context.Background(), dir, comps); n != 1 {
		t.Fatalf("nested resolved = %d, want 1", n)
	}
	if len(comps[0].Licenses) == 0 || comps[0].Licenses[0].SPDXID != "MIT" {
		t.Fatalf("nested license = %+v, want MIT", comps[0].Licenses)
	}
}
