-- +goose Up
-- PR4b review (tail-truncation detection): give timestamp_tokens a monotonic insertion order so
-- "latest retained head" (LatestHead) is the genuinely last-anchored one, independent of
-- created_at wall-clock collisions. Several heads anchored in the same now() tick would otherwise
-- tiebreak on the chain-meaningless sha256 hex (head DESC); a sequence makes "latest" the truly
-- last-inserted row regardless of timestamp ties.
ALTER TABLE timestamp_tokens ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX timestamp_tokens_latest_idx ON timestamp_tokens (chain, engagement_id, seq DESC);

-- +goose Down
DROP INDEX IF EXISTS timestamp_tokens_latest_idx;
ALTER TABLE timestamp_tokens DROP COLUMN seq;
