package ownsbom

import (
	"context"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const poetryLockFixture = `# This file is automatically @generated by Poetry.

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
category = "main"
optional = false

[package.dependencies]
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"

[[package]]
name = "Pytest"
version = "8.0.0"
category = "dev"
optional = false

[[package]]
name = "charset-normalizer"
version = "3.3.2"
category = "main"
`

func TestPoetryParse(t *testing.T) {
	comps, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(poetryLockFixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	// Edges: requests' [package.dependencies] resolves charset-normalizer (it has its own [[package]])
	// but NOT idna (no [[package]] entry → no edge). pytest + charset-normalizer have no [package.dependencies].
	if len(deps) != 1 {
		t.Fatalf("want exactly 1 edge-set (requests), got %d: %+v", len(deps), deps)
	}
	if deps[0].Ref != "pkg:pypi/requests@2.31.0" {
		t.Errorf("edge ref = %q, want pkg:pypi/requests@2.31.0", deps[0].Ref)
	}
	if len(deps[0].DependsOn) != 1 || deps[0].DependsOn[0] != "pkg:pypi/charset-normalizer@3.3.2" {
		t.Errorf("requests must depend on charset-normalizer@3.3.2 only (idna unresolved → no edge), got %v", deps[0].DependsOn)
	}
	if len(comps) != 3 {
		t.Fatalf("want 3 components, got %d: %+v", len(comps), comps)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	// resolved version + PURL; category "main" -> production. The [package.dependencies] sub-table keys
	// (charset-normalizer/idna as RANGES) must NOT be emitted as components.
	if c := byName["requests"]; c.Version != "2.31.0" || c.PURL != "pkg:pypi/requests@2.31.0" || c.Scope != sbom.ScopeProduction {
		t.Errorf("requests = %+v, want 2.31.0 / pkg:pypi/requests@2.31.0 / production", c)
	}
	// category "dev" -> development scope; name PEP 503-normalized (Pytest -> pytest)
	if c := byName["pytest"]; c.Version != "8.0.0" || c.Scope != sbom.ScopeDevelopment {
		t.Errorf("pytest = %+v, want 8.0.0 / dev / normalized name", c)
	}
	// charset-normalizer is emitted via its OWN [[package]] (resolved), not as the requests sub-table key
	if c := byName["charset-normalizer"]; c.Version != "3.3.2" {
		t.Errorf("charset-normalizer should come from its own [[package]] @3.3.2, got %+v", c)
	}
	// idna appears only as a sub-table dependency range (no [[package]]) -> not a component
	if _, ok := byName["idna"]; ok {
		t.Error("a [package.dependencies] range key (idna) must not be emitted as a component")
	}
}

// A dep serialized as a multi-line inline-table array: the key line `tomli = [` resolves the edge, while
// the `{...}` continuation lines + the closing `]` must NOT be harvested as false dependency keys.
func TestPoetryParseMultiLineArrayDep(t *testing.T) {
	lock := `[[package]]
name = "pkg"
version = "1.0.0"
category = "main"

[package.dependencies]
tomli = [
    {version = ">=1.1.0", markers = "python_version < \"3.11\""},
]

[[package]]
name = "tomli"
version = "2.0.1"
category = "main"
`
	_, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(deps) != 1 || deps[0].Ref != "pkg:pypi/pkg@1.0.0" {
		t.Fatalf("want one edge-set rooted at pkg, got %+v", deps)
	}
	if len(deps[0].DependsOn) != 1 || deps[0].DependsOn[0] != "pkg:pypi/tomli@2.0.1" {
		t.Errorf("the array dep must resolve to tomli only (no false keys from {...}/]), got %v", deps[0].DependsOn)
	}
}

// A (crafted) lock whose two [[package]] blocks normalize to the SAME name makes that name ambiguous, so an
// edge to it is DROPPED (never guess which version) — mirroring the Cargo resolver.
func TestPoetryParseAmbiguousDepNoEdge(t *testing.T) {
	lock := `[[package]]
name = "app"
version = "1.0.0"
category = "main"

[package.dependencies]
dup-pkg = ">=1"

[[package]]
name = "dup-pkg"
version = "1.0.0"
category = "main"

[[package]]
name = "dup_pkg"
version = "2.0.0"
category = "main"
`
	_, deps, err := Poetry{}.Parse(context.Background(), ParseInput{Path: "poetry.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	// dup-pkg and dup_pkg both PEP 503-normalize to "dup-pkg" → 2 versions → ambiguous → app gets no edge.
	if len(deps) != 0 {
		t.Errorf("an ambiguous duplicate-name dep must yield no edge, got %+v", deps)
	}
}
