package ownsbom

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
)

const yarnV1Fixture = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1

"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.23.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.23.0.tgz"
  integrity sha512-abc
  dependencies:
    "@babel/code-frame" "^7.22.0"
    lodash "^4.17.21"

"@babel/code-frame@^7.22.0":
  version "7.22.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

mocha@^10.0.0:
  version "10.2.0"
  resolved "https://registry.yarnpkg.com/mocha/-/mocha-10.2.0.tgz"
`

func TestYarnV1(t *testing.T) {
	dir := t.TempDir()
	mustWrite(t, filepath.Join(dir, "yarn.lock"), yarnV1Fixture)
	mustWrite(t, filepath.Join(dir, "package.json"), `{"dependencies":{"lodash":"^4.17.21","@babel/core":"^7.0.0"},"devDependencies":{"mocha":"^10.0.0"}}`)

	comps, deps, err := Yarn{}.Parse(context.Background(), ParseInput{Dir: dir, Path: filepath.Join(dir, "yarn.lock"), Content: []byte(yarnV1Fixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(comps) != 4 {
		t.Fatalf("want 4 packages, got %d: %+v", len(comps), comps)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	// Edges: @babel/core's dependencies: block resolves via the descriptor map to @babel/code-frame
	// (a multi-spec key entry) + lodash (a single-spec key). The descriptor "@babel/code-frame@^7.22.0" is
	// claimed by the code-frame entry's key line, so the edge points at its resolved 7.22.13.
	on := map[string][]string{}
	for _, d := range deps {
		on[d.Ref] = d.DependsOn
	}
	ng := on["pkg:npm/%40babel/core@7.23.0"]
	if !contains(ng, "pkg:npm/%40babel/code-frame@7.22.13") || !contains(ng, "pkg:npm/lodash@4.17.21") {
		t.Errorf("@babel/core must depend on the resolved code-frame@7.22.13 + lodash@4.17.21, got %v", ng)
	}
	// multi-spec key + scoped %40 PURL + resolved version (NOT the transitive "@babel/code-frame" spec line)
	if c := byName["@babel/core"]; c.Version != "7.23.0" || c.PURL != "pkg:npm/%40babel/core@7.23.0" {
		t.Errorf("@babel/core = %+v, want 7.23.0 / pkg:npm/%%40babel/core@7.23.0", c)
	}
	// dev-scope from the companion package.json [devDependencies]
	if c := byName["mocha"]; c.Scope != sbom.ScopeDevelopment {
		t.Errorf("mocha must be dev-scoped via companion package.json: %+v", c)
	}
	if c := byName["lodash"]; c.Scope != sbom.ScopeProduction {
		t.Errorf("lodash must be production: %+v", c)
	}
	// @babel/code-frame now has its OWN lock entry, so it is a real component (resolved 7.22.13).
	if c := byName["@babel/code-frame"]; c.Version != "7.22.13" {
		t.Errorf("@babel/code-frame (own entry) must be a component @7.22.13, got %+v", c)
	}
}

const yarnBerryFixture = `# This file is generated by running "yarn install"

__metadata:
  version: 6
  cacheKey: 8

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"@types/node@npm:^20.0.0":
  version: 20.10.0
  resolution: "@types/node@npm:20.10.0"

"webpack-cli@npm:@scope/forked-webpack-cli@^4.0.0":
  version: 4.10.0
  resolution: "@scope/forked-webpack-cli@npm:4.10.0"
`

func TestYarnBerry(t *testing.T) {
	comps, _, err := Yarn{}.Parse(context.Background(), ParseInput{Path: "yarn.lock", Content: []byte(yarnBerryFixture)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	byName := map[string]sbom.Component{}
	for _, c := range comps {
		byName[c.Name] = c
	}
	// the __metadata block (lockfile metadata) and the my-app@workspace:. root (the project itself) are NOT packages
	for _, notPkg := range []string{"__metadata", "my-app"} {
		if _, ok := byName[notPkg]; ok {
			t.Errorf("%s must not be emitted as a component", notPkg)
		}
	}
	// Berry `version: x` + `name@npm:range`, and an ALIASED `name@npm:other@range` -> the alias name (the
	// name Yarn installs it under), with a CLEAN PURL (not the protocol-target garbage the LAST-@ split gave)
	if byName["lodash"].Version != "4.17.21" || byName["@types/node"].Version != "20.10.0" {
		t.Fatalf("berry parse wrong: %+v", byName)
	}
	if c := byName["webpack-cli"]; c.Version != "4.10.0" || c.PURL != "pkg:npm/webpack-cli@4.10.0" {
		t.Errorf("aliased webpack-cli = %+v, want 4.10.0 / pkg:npm/webpack-cli@4.10.0", c)
	}
	if len(comps) != 3 {
		t.Fatalf("want 3 packages (workspace root excluded), got %d: %+v", len(comps), comps)
	}
}

// Berry's dependencies: block is colon-separated (`name: "npm:range"`); the descriptor reconstructed from a
// dep (name@range) must match the target entry's key-line descriptor for the edge to resolve.
func TestYarnBerryEdges(t *testing.T) {
	lock := `"app@npm:^1.0.0":
  version: 1.0.0
  resolution: "app@npm:1.0.0"
  dependencies:
    lodash: "npm:^4.17.21"
    "@scope/x": "npm:^2.0.0"

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"@scope/x@npm:^2.0.0":
  version: 2.3.0
  resolution: "@scope/x@npm:2.3.0"
`
	_, deps, err := Yarn{}.Parse(context.Background(), ParseInput{Path: "yarn.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	on := map[string][]string{}
	for _, d := range deps {
		on[d.Ref] = d.DependsOn
	}
	app := on["pkg:npm/app@1.0.0"]
	if !contains(app, "pkg:npm/lodash@4.17.21") || !contains(app, "pkg:npm/%40scope/x@2.3.0") {
		t.Errorf("berry app must depend on lodash@4.17.21 + @scope/x@2.3.0 (colon-form descriptors), got %v", app)
	}
}

// optionalDependencies must produce edges too (parity with the npm parser), while peerDependencies must not.
func TestYarnOptionalDepsEdge(t *testing.T) {
	lock := `pkg@^1.0.0:
  version "1.0.0"
  optionalDependencies:
    fsevents "^2.0.0"
  peerDependencies:
    react "^18.0.0"

fsevents@^2.0.0:
  version "2.3.3"

react@^18.0.0:
  version "18.2.0"
`
	_, deps, err := Yarn{}.Parse(context.Background(), ParseInput{Path: "yarn.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	var on []string
	for _, d := range deps {
		if d.Ref == "pkg:npm/pkg@1.0.0" {
			on = d.DependsOn
		}
	}
	if !contains(on, "pkg:npm/fsevents@2.3.3") {
		t.Errorf("optionalDependencies must produce an edge to fsevents@2.3.3, got %v", on)
	}
	if contains(on, "pkg:npm/react@18.2.0") {
		t.Errorf("peerDependencies must NOT produce an edge (host-provides), got %v", on)
	}
}

// Hostile/malformed dependency-block lines must never panic and must yield no garbage edge (locks the
// parseYarnDep slice-safety the security review reasoned about).
func TestYarnParseDepHostileLines(t *testing.T) {
	for _, line := range []string{``, `"`, `""`, `:`, `   `, `"unterminated`, `name`, `"@scope/x"`} {
		if d, ok := parseYarnDep(line); ok {
			t.Errorf("hostile dep line %q must not parse to a dep, got %+v", line, d)
		}
	}
	// A consistently TAB-indented file must still resolve edges (leadingIndent counts tabs, agreeing with
	// indented()): entry fields at 1 tab, dependencies: members at 2 tabs.
	lock := "a@^1:\n\tversion \"1.0.0\"\n\tdependencies:\n\t\tb \"^2\"\n\nb@^2:\n\tversion \"2.0.0\"\n"
	_, deps, err := Yarn{}.Parse(context.Background(), ParseInput{Path: "yarn.lock", Content: []byte(lock)})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	var found bool
	for _, d := range deps {
		if d.Ref == "pkg:npm/a@1.0.0" && contains(d.DependsOn, "pkg:npm/b@2.0.0") {
			found = true
		}
	}
	if !found {
		t.Errorf("a tab-indented dependencies: block must still resolve edges, got %+v", deps)
	}
}
