package sca

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/KKloudTarus/synapse-ce/internal/domain/importedsbom"
	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
	"github.com/KKloudTarus/synapse-ce/internal/usecase/ports"
)

// ImportSBOM ingests a client-supplied CycloneDX SBOM (consultancies receive
// client SBOMs) as the engagement's scan result, so its components are visible,
// license-summarized, exportable (SPDX), and sealed into the evidence chain. It does
// NOT run vulnerability detection on the imported components — that reuses the
// post-SBOM half of the scan pipeline and is a follow-up; importing makes the
// client's inventory a first-class, attested artifact today. Audited.
func (s *Service) ImportSBOM(ctx context.Context, actor string, tenantID, engagementID shared.ID, data []byte) (*ScanResult, error) {
	return s.ImportSBOMFile(ctx, actor, tenantID, engagementID, importedsbom.DefaultFilename, data)
}

// ImportSBOMFile ingests a named client-supplied CycloneDX SBOM.
func (s *Service) ImportSBOMFile(ctx context.Context, actor string, tenantID, engagementID shared.ID, filename string, data []byte) (*ScanResult, error) {
	if _, err := s.engagements.GetByIDInTenant(ctx, tenantID, engagementID); err != nil {
		return nil, fmt.Errorf("load engagement: %w", err)
	}
	parsed, err := parseCycloneDX(data)
	if err != nil {
		return nil, err
	}
	now := s.clock.Now()
	comps, target := parsed.Components, parsed.TargetRef
	if target == "" {
		target = "imported-sbom"
	}
	doc := &sbom.SBOM{
		TargetRef:        target,
		Source:           "imported-cyclonedx",
		GeneratorVersion: parsed.GeneratorVersion,
		Components:       comps,
		Dependencies:     parsed.Dependencies,
		Raw:              append([]byte(nil), data...),
		Audit:            shared.Audit{CreatedAt: now, UpdatedAt: now},
	}
	resolved := 0
	for _, c := range comps {
		if sbom.IsResolvedVersion(c.Version) {
			resolved++
		}
	}
	res := &ScanResult{
		Target:          target,
		SBOM:            doc,
		LicenseCoverage: sbom.ComputeLicenseCoverage(comps),
		Completeness: ports.Completeness{
			ComponentsTotal:    len(comps),
			ComponentsResolved: resolved,
			Confident:          true,
			Warning:            "imported client SBOM (not generated by Synapse); vulnerability detection not run on import",
		},
		ToolVersions: map[string]string{"import": "cyclonedx"},
		// Pin a snapshot marker so SPDX export stays byte-reproducible (scanTime parses
		// the timestamp after the last '@').
		VulnDBSnapshot: "imported@" + now.UTC().Format(time.RFC3339),
		// Anchor the evidence seal to the exact SBOM that was imported.
		Manifest: ports.ScanManifest{SBOMSHA256: hashHex(data)},
	}

	if s.importedSBOM != nil {
		if strings.TrimSpace(filename) == "" {
			filename = importedsbom.DefaultFilename
		}
		record := importedsbom.Record{
			ID:              s.importedSBOMID(data),
			TenantID:        tenantID,
			EngagementID:    engagementID,
			Filename:        filename,
			Format:          importedsbom.FormatCycloneDX,
			SpecVersion:     parsed.SpecVersion,
			TargetRef:       target,
			ComponentCount:  len(comps),
			DependencyCount: len(parsed.Dependencies),
			SHA256:          hashHex(data),
			RawJSON:         append([]byte(nil), data...),
			CreatedBy:       actor,
			CreatedAt:       now,
		}
		if err := s.importedSBOM.SaveActive(ctx, record); err != nil {
			return nil, fmt.Errorf("save imported SBOM artifact: %w", err)
		}
	}

	if s.results != nil {
		out, err := json.Marshal(res)
		if err != nil {
			return nil, fmt.Errorf("encode imported result: %w", err)
		}
		if err := s.results.SaveResult(ctx, engagementID, out); err != nil {
			return nil, fmt.Errorf("save imported result: %w", err)
		}
	}
	// Seal a tamper-evident summary into the chain + audit.
	s.sealEvidence(ctx, actor, engagementID, now, res)
	_ = s.audit.Record(ctx, ports.AuditEntry{
		Actor: actor, Action: "sca.sbom.imported", Target: target,
		Metadata: map[string]string{"engagement": engagementID.String(), "components": strconv.Itoa(len(comps)), "dependencies": strconv.Itoa(len(parsed.Dependencies)), "format": "cyclonedx", "spec_version": parsed.SpecVersion, "sha256": hashHex(data)},
		At:       now,
	})
	return res, nil
}

func (s *Service) importedSBOMID(data []byte) shared.ID {
	if s.ids != nil {
		return s.ids.NewID()
	}
	h := hashHex(data)
	if len(h) > 16 {
		h = h[:16]
	}
	return shared.ID("imported-sbom-" + h)
}

// ImportedSBOMMetadata returns safe metadata for the active imported SBOM.
func (s *Service) ImportedSBOMMetadata(ctx context.Context, tenantID, engagementID shared.ID) (importedsbom.Metadata, error) {
	if _, err := s.engagements.GetByIDInTenant(ctx, tenantID, engagementID); err != nil {
		return importedsbom.Metadata{}, fmt.Errorf("load engagement: %w", err)
	}
	if s.importedSBOM == nil {
		return importedsbom.Metadata{}, fmt.Errorf("imported SBOM for engagement %s: %w", engagementID, shared.ErrNotFound)
	}
	record, err := s.importedSBOM.LatestByEngagement(ctx, tenantID, engagementID)
	if err != nil {
		return importedsbom.Metadata{}, err
	}
	return record.Metadata(), nil
}

// ---- minimal CycloneDX JSON parser (components only) ----

type parsedCycloneDX struct {
	SpecVersion      string
	TargetRef        string
	GeneratorVersion string
	Components       []sbom.Component
	Dependencies     []sbom.Dependency
}

type cdxBOM struct {
	BOMFormat   string `json:"bomFormat"`
	SpecVersion string `json:"specVersion"`
	Metadata    struct {
		Tools []struct {
			Vendor  string `json:"vendor"`
			Name    string `json:"name"`
			Version string `json:"version"`
		} `json:"tools"`
		Component cdxComponent `json:"component"`
	} `json:"metadata"`
	Components   []cdxComponent  `json:"components"`
	Dependencies []cdxDependency `json:"dependencies"`
}

type cdxComponent struct {
	Group    string `json:"group"`
	Type     string `json:"type"`
	Name     string `json:"name"`
	Version  string `json:"version"`
	PURL     string `json:"purl"`
	BOMRef   string `json:"bom-ref"`
	Scope    string `json:"scope"` // CycloneDX scope: required|optional|excluded
	Licenses []struct {
		License struct {
			ID   string `json:"id"`
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"license"`
		Expression string `json:"expression"`
	} `json:"licenses"`
}

type cdxDependency struct {
	Ref       string   `json:"ref"`
	DependsOn []string `json:"dependsOn"`
}

// parseCycloneDX decodes a CycloneDX JSON document into domain components + the
// target name from metadata. Rejects a non-CycloneDX or empty document.
func parseCycloneDX(data []byte) (parsedCycloneDX, error) {
	var bom cdxBOM
	if err := json.Unmarshal(data, &bom); err != nil {
		return parsedCycloneDX{}, fmt.Errorf("%w: invalid CycloneDX JSON: %v", shared.ErrValidation, err)
	}
	if !strings.EqualFold(bom.BOMFormat, "CycloneDX") {
		return parsedCycloneDX{}, fmt.Errorf("%w: not a CycloneDX document (bomFormat=%q)", shared.ErrValidation, bom.BOMFormat)
	}
	if strings.TrimSpace(bom.SpecVersion) != "1.4" {
		return parsedCycloneDX{}, fmt.Errorf("%w: unsupported CycloneDX specVersion %q", shared.ErrValidation, bom.SpecVersion)
	}
	if len(bom.Components) == 0 {
		return parsedCycloneDX{}, fmt.Errorf("%w: CycloneDX document has no components", shared.ErrValidation)
	}
	out := make([]sbom.Component, 0, len(bom.Components)+1)
	if metadataComponentHasIdentity(bom.Metadata.Component) {
		if comp, ok := cdxComponentToDomain(bom.Metadata.Component); ok {
			comp.FirstParty = true
			out = append(out, comp)
		}
	}
	for _, c := range bom.Components {
		if comp, ok := cdxComponentToDomain(c); ok {
			out = append(out, comp)
		}
	}
	if len(out) == 0 {
		return parsedCycloneDX{}, fmt.Errorf("%w: no named components in the SBOM", shared.ErrValidation)
	}
	deps := make([]sbom.Dependency, 0, len(bom.Dependencies))
	for _, d := range bom.Dependencies {
		ref := strings.TrimSpace(d.Ref)
		if ref == "" {
			continue
		}
		dependsOn := make([]string, 0, len(d.DependsOn))
		for _, dep := range d.DependsOn {
			if dep = strings.TrimSpace(dep); dep != "" {
				dependsOn = append(dependsOn, dep)
			}
		}
		deps = append(deps, sbom.Dependency{Ref: ref, DependsOn: dependsOn})
	}
	return parsedCycloneDX{
		SpecVersion:      bom.SpecVersion,
		TargetRef:        bom.Metadata.Component.Name,
		GeneratorVersion: cdxGeneratorVersion(bom.Metadata.Tools),
		Components:       out,
		Dependencies:     deps,
	}, nil
}

func metadataComponentHasIdentity(c cdxComponent) bool {
	return strings.TrimSpace(c.PURL) != "" || strings.TrimSpace(c.Version) != "" || len(c.Licenses) > 0
}

func cdxComponentToDomain(c cdxComponent) (sbom.Component, bool) {
	if strings.TrimSpace(c.Name) == "" {
		return sbom.Component{}, false
	}
	name := c.Name
	if c.Group != "" && strings.HasPrefix(c.PURL, "pkg:maven/") {
		name = c.Group + ":" + c.Name
	}
	comp := sbom.Component{Name: name, Version: c.Version, PURL: c.PURL}
	// No on-disk location for an imported component; the CycloneDX scope still
	// classifies dev/excluded (excluded -> development).
	comp.Scope = sbom.ClassifyScope("", c.Scope)
	for _, lc := range c.Licenses {
		switch {
		case lc.License.ID != "":
			comp.Licenses = append(comp.Licenses, sbom.License{SPDXID: lc.License.ID})
		case lc.License.URL != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.License.URL})
		case lc.License.Name != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.License.Name})
		case lc.Expression != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.Expression})
		}
	}
	if len(comp.Licenses) > 0 {
		comp.LicenseSource = "sbom"
		comp.LicenseConfidence = "declared"
	}
	return comp, true
}

func cdxGeneratorVersion(tools []struct {
	Vendor  string `json:"vendor"`
	Name    string `json:"name"`
	Version string `json:"version"`
}) string {
	if len(tools) == 0 {
		return ""
	}
	tool := tools[0]
	name := strings.TrimSpace(tool.Name)
	if name == "" {
		name = strings.TrimSpace(tool.Vendor)
	}
	version := strings.TrimSpace(tool.Version)
	if name == "" {
		return version
	}
	if version == "" {
		return name
	}
	return name + "/" + version
}

func hashHex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}
