package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func cssRules() []rule.Rule {
	rules := []rule.Rule{
		{
			Key:                 "css:duplicate-property",
			Name:                "Duplicate property declaration",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "cascade", "properties"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects repeated identical property declarations in the same declaration block.",
			Rationale:           "When the exact same property and value is declared twice in a block, the second declaration overrides the first with no change in effect. This is usually redundant code leftover from refactoring.\n\nSource: https://www.w3.org/TR/css-cascade-5/",
			Remediation:         "Remove the duplicate declaration.",
			CompliantExample:    "a {\n  color: red;\n}",
			NoncompliantExample: "a {\n  color: red;\n  color: red;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:invalid-hex-color",
			Name:                "Invalid hexadecimal color token",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "color"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects malformed hexadecimal color tokens.",
			Rationale:           "Hexadecimal colors must contain exactly 3, 4, 6, or 8 valid hex digits. Invalid lengths or invalid characters will cause the property to be ignored by browsers.\n\nSource: https://www.w3.org/TR/css-color-4/",
			Remediation:         "Provide a valid hex color string.",
			CompliantExample:    "a {\n  color: #fff;\n}",
			NoncompliantExample: "a {\n  color: #ff;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:unknown-property",
			Name:                "Unknown CSS property",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "properties"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects properties that are not present in the W3C CSS property inventory.",
			Rationale:           "A misspelled or unknown CSS property will be ignored by browsers. Standardizing on recognized properties ensures styles are applied as intended.\n\nSource: https://www.w3.org/Style/CSS/all-properties.en.html",
			Remediation:         "Correct the property name.",
			CompliantExample:    "a {\n  color: red;\n}",
			NoncompliantExample: "a {\n  colr: red;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:invalid-unit",
			Name:                "Invalid CSS unit",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "units"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects dimensions that use an unknown or invalid CSS unit suffix.",
			Rationale:           "Using an unrecognized unit makes the dimension invalid, causing the browser to drop the declaration.\n\nSource: https://www.w3.org/TR/css-values-4/",
			Remediation:         "Use a valid CSS unit such as px, rem, %, or vh.",
			CompliantExample:    "a {\n  width: 10px;\n}",
			NoncompliantExample: "a {\n  width: 10pzz;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:invalid-keyframe-selector",
			Name:                "Invalid keyframe offset",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"css", "correctness", "animations"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects keyframe percentage selectors outside the 0% to 100% range, or invalid raw numbers.",
			Rationale:           "Keyframe percentage offsets must be between 0% and 100%. Values outside this range, or bare numbers without the % unit, render the keyframe block invalid.\n\nSource: https://www.w3.org/TR/css-animations-1/",
			Remediation:         "Use a percentage between 0% and 100%, or the keywords 'from' and 'to'.",
			CompliantExample:    "@keyframes fade {\n  0% { opacity: 0; }\n}",
			NoncompliantExample: "@keyframes fade {\n  101% { opacity: 1; }\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:negative-animation-duration",
			Name:                "Negative animation duration",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"css", "correctness", "animations"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects negative time literals for animation-duration.",
			Rationale:           "An animation duration cannot be negative. If a negative duration is provided, the declaration is invalid and ignored by the browser.\n\nSource: https://www.w3.org/TR/css-animations-1/",
			Remediation:         "Use a positive duration (or 0s).",
			CompliantExample:    "a {\n  animation-duration: 1s;\n}",
			NoncompliantExample: "a {\n  animation-duration: -1s;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:invalid-font-weight",
			Name:                "Invalid font weight",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "fonts"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects numeric literal font weights that are outside the allowed 1–1000 range.",
			Rationale:           "Font weights specified as raw numbers must be between 1 and 1000 inclusive. Other numeric values are invalid.\n\nSource: https://www.w3.org/TR/css-fonts-4/",
			Remediation:         "Specify a valid font weight between 1 and 1000.",
			CompliantExample:    "a {\n  font-weight: 400;\n}",
			NoncompliantExample: "a {\n  font-weight: 0;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
		{
			Key:                 "css:negative-flex-factor",
			Name:                "Negative flex factor",
			Language:            "CSS",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"css", "correctness", "flexbox"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects negative numeric literals assigned to flex-grow or flex-shrink.",
			Rationale:           "Flex grow and flex shrink factors must be zero or positive. Negative values make the declaration invalid.\n\nSource: https://www.w3.org/TR/css-flexbox-1/",
			Remediation:         "Use 0 or a positive number.",
			CompliantExample:    "a {\n  flex-grow: 1;\n}",
			NoncompliantExample: "a {\n  flex-grow: -1;\n}",
			RemediationEffort:   5,
			Detection:           rule.DetectionAST,
		},
	}
	return append(rules, cssMaintainabilityRules...)
}
