package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

var cssMaintainabilityRules = []rule.Rule{
	{
		Key:                 "css:empty-block",
		Name:                "Empty CSS block",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "style"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects empty style blocks.",
		Rationale:           "An empty rule block provides no styling and adds noise to the stylesheet.\n\nSource: https://www.w3.org/TR/css-syntax-3/",
		Remediation:         "Remove the empty block or add style rules.",
		CompliantExample:    `a { color: red; }`,
		NoncompliantExample: `a { /* empty block */ }`,
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:important-overuse",
		Name:                "Overuse of !important flag",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "cascade"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects overuse of the !important declaration flag.",
		Rationale:           "Using !important overrides cascade specificity and makes CSS difficult to maintain and extend.\n\nSource: https://www.w3.org/TR/css-cascade-5/",
		Remediation:         "Refactor selectors to use specificity instead of !important.",
		CompliantExample:    "a {\n  color: red;\n}",
		NoncompliantExample: "a {\n  color: red !important;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:duplicate-selector",
		Name:                "Duplicate selector in same scope",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects repeated identical selector blocks within the same media or enclosing scope.",
		Rationale:           "Duplicated selectors fragment rule declarations across the stylesheet.\n\nSource: https://www.w3.org/TR/css-syntax-3/",
		Remediation:         "Merge declarations under a single selector rule.",
		CompliantExample:    ".a {\n  color: red;\n}\n.b {\n  color: blue;\n}",
		NoncompliantExample: ".a {\n  color: red;\n}\n.a {\n  color: blue;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:zero-with-unit",
		Name:                "Zero value with redundant length unit",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "units"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects zero values specified with unnecessary length units.",
		Rationale:           "Zero values do not require length units in CSS.\n\nSource: https://www.w3.org/TR/css-values-4/",
		Remediation:         "Remove the unit suffix from zero values.",
		CompliantExample:    "a {\n  margin: 0;\n}",
		NoncompliantExample: "a {\n  margin: 0px;\n}",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:font-no-fallback",
		Name:                "Font family missing generic fallback",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "fonts"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects font-family declarations missing a generic fallback family keyword.",
		Rationale:           "Failing to specify a generic font family fallback (e.g. sans-serif, serif) can lead to unpredictable rendering if custom fonts fail to load.\n\nSource: https://www.w3.org/TR/css-fonts-4/",
		Remediation:         "Add a generic font family keyword as the final fallback.",
		CompliantExample:    "a {\n  font-family: Inter, sans-serif;\n}",
		NoncompliantExample: "a {\n  font-family: Inter;\n}",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:id-selector-overuse",
		Name:                "ID selector overuse in stylesheet",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects selector list items containing ID selectors.",
		Rationale:           "ID selectors have high specificity, making rules difficult to override in modular component stylesheets.\n\nSource: https://www.w3.org/TR/selectors-4/",
		Remediation:         "Replace ID selectors with class selectors.",
		CompliantExample:    ".app {\n  color: red;\n}",
		NoncompliantExample: "#app {\n  color: red;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:vendor-prefix-no-standard",
		Name:                "Vendor prefix missing standard property",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "compatibility"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects vendor-prefixed properties declared without the corresponding standard property.",
		Rationale:           "Using vendor prefixes without standard property fallbacks risks breakdown when browsers drop prefix support.\n\nSource: https://www.w3.org/TR/css-will-change-1/",
		Remediation:         "Include the standard property alongside the prefixed property.",
		CompliantExample:    "a {\n  -webkit-transform: scale(1);\n  transform: scale(1);\n}",
		NoncompliantExample: "a {\n  -webkit-transform: scale(1);\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:shorthand-redundant",
		Name:                "Longhand property overridden by later shorthand",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "cascade"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects longhand property declarations overridden by a subsequent shorthand in the same block.",
		Rationale:           "Declaring a longhand property followed by a shorthand resets the earlier longhand value.\n\nSource: https://www.w3.org/TR/css-cascade-5/",
		Remediation:         "Place shorthand properties before longhand properties or merge them.",
		CompliantExample:    "a {\n  margin: 2rem;\n  margin-left: 1rem;\n}",
		NoncompliantExample: "a {\n  margin-left: 1rem;\n  margin: 2rem;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:negative-zindex",
		Name:                "Negative z-index value",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "layout"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects negative integer literals assigned to z-index.",
		Rationale:           "Negative z-index values can place elements behind parent stacking contexts and body backgrounds, creating stacking bugs.\n\nSource: https://www.w3.org/TR/css22/visuren.html#z-index",
		Remediation:         "Use non-negative z-index values and adjust parent stacking contexts.",
		CompliantExample:    "a {\n  z-index: 1;\n}",
		NoncompliantExample: "a {\n  z-index: -1;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:duplicate-font-face",
		Name:                "Duplicate @font-face rule",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "fonts"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects repeated @font-face definitions with identical descriptor sets.",
		Rationale:           "Duplicate @font-face rules cause redundant font loading and parsing overhead.\n\nSource: https://www.w3.org/TR/css-fonts-4/",
		Remediation:         "Remove duplicate @font-face declarations.",
		CompliantExample:    "@font-face {\n  font-family: Demo;\n  src: url(regular.woff2);\n}\n@font-face {\n  font-family: Demo;\n  src: url(bold.woff2);\n  font-weight: 700;\n}",
		NoncompliantExample: "@font-face {\n  font-family: Demo;\n  src: url(demo.woff2);\n}\n@font-face {\n  src: url(demo.woff2);\n  font-family: Demo;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:todo-marker",
		Name:                "TODO or FIXME comment marker",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityInfo,
		Tags:                []string{"css", "maintainability", "comments"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects TODO or FIXME markers inside CSS comments.",
		Rationale:           "Unresolved TODO/FIXME markers in production stylesheets indicate incomplete work.\n\nSource: https://www.w3.org/TR/css-syntax-3/",
		Remediation:         "Address the pending work and remove the comment marker.",
		CompliantExample:    "/* ordinary comment */",
		NoncompliantExample: "/* TODO: fix style */",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:selector-specificity-high",
		Name:                "Excessive selector specificity",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects selectors exceeding recommended specificity thresholds.",
		Rationale:           "Selectors with high specificity create cascade conflicts and force downstream overrides to use !important.\n\nSource: https://www.w3.org/TR/selectors-4/#specificity-rules",
		Remediation:         "Simplify selectors and reduce class/attribute/type nesting.",
		CompliantExample:    ".card:hover {\n  color: red;\n}",
		NoncompliantExample: ".card.active[data-state=\"open\"]:hover {\n  color: red;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:selector-depth-high",
		Name:                "Excessive selector combinator depth",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects selectors containing more than 4 compound selector segments.",
		Rationale:           "Deeply nested selectors couple styling tightly to HTML structure and reduce maintainability.\n\nSource: https://www.w3.org/TR/selectors-4/",
		Remediation:         "Use direct class names to flatten selector depth.",
		CompliantExample:    "main .card .title {\n  color: red;\n}",
		NoncompliantExample: "body main section article .card .title {\n  color: red;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:selector-list-too-long",
		Name:                "Selector list contains too many selectors",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects rule blocks containing more than 8 top-level selectors.",
		Rationale:           "Very long selector lists reduce stylesheet readability and maintainability.\n\nSource: https://www.w3.org/TR/selectors-4/",
		Remediation:         "Split selector lists or use a shared class.",
		CompliantExample:    ".a,.b,.c,.d {\n  color: red;\n}",
		NoncompliantExample: ".a,.b,.c,.d,.e,.f,.g,.h,.i {\n  color: red;\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:declaration-block-too-large",
		Name:                "Declaration block contains too many declarations",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "style"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects style blocks containing more than 20 direct declarations.",
		Rationale:           "Large declaration blocks indicate a component with too many responsibilities.\n\nSource: https://www.w3.org/TR/css-syntax-3/",
		Remediation:         "Break large declaration blocks into smaller sub-components.",
		CompliantExample:    "a {\n  color: red;\n}",
		NoncompliantExample: "a {\n  color: red;\n  width: 1px;\n  height: 1px;\n  margin: 1px;\n  padding: 1px;\n  display: block;\n  position: absolute;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  z-index: 1;\n  opacity: 1;\n  visibility: visible;\n  cursor: pointer;\n  overflow: hidden;\n  float: left;\n  clear: both;\n  font-size: 14px;\n  line-height: 1.5;\n  background: blue;\n}",
		RemediationEffort:   30,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:overqualified-selector",
		Name:                "Overqualified type selector",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "selectors"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects type selectors combined with class or ID in the same compound selector.",
		Rationale:           "Qualifying class or ID selectors with element tags increases specificity unnecessarily and prevents element reuse.\n\nSource: https://www.w3.org/TR/selectors-4/",
		Remediation:         "Remove unnecessary element tag prefixes.",
		CompliantExample:    ".card {\n  color: red;\n}",
		NoncompliantExample: "div.card {\n  color: red;\n}",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:duplicate-keyframes",
		Name:                "Duplicate @keyframes name in same scope",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "animations"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects repeated @keyframes animation names in identical enclosing scopes.",
		Rationale:           "Duplicate keyframe definitions in the same scope overwrite earlier definitions.\n\nSource: https://www.w3.org/TR/css-animations-1/",
		Remediation:         "Use unique animation names or consolidate keyframe rules.",
		CompliantExample:    "@keyframes fade {\n  0% { opacity: 0; }\n}\n@keyframes slide {\n  0% { left: 0; }\n}",
		NoncompliantExample: "@keyframes Fade {\n  0% { opacity: 0; }\n}\n@keyframes Fade {\n  0% { opacity: 1; }\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:duplicate-media-query",
		Name:                "Duplicate @media query in same scope",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "responsive"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects repeated canonical @media query preludes in the same scope.",
		Rationale:           "Duplicate media queries should be merged to simplify responsive stylesheet structure.\n\nSource: https://www.w3.org/TR/css-conditional-3/",
		Remediation:         "Merge style rules under a single media query block.",
		CompliantExample:    "@media (min-width: 600px) {}\n@media (min-width: 800px) {}",
		NoncompliantExample: "@media screen and (min-width: 800px) {}\n@media screen and (min-width: 800px) {}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:duplicate-import",
		Name:                "Duplicate @import statement",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "imports"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects repeated canonical @import statement preludes.",
		Rationale:           "Importing the same stylesheet multiple times causes duplicate network requests or build processing.\n\nSource: https://www.w3.org/TR/css-cascade-5/",
		Remediation:         "Remove duplicate @import statements.",
		CompliantExample:    "@import url(\"base.css\");\n@import url(\"theme.css\");",
		NoncompliantExample: "@import url(\"base.css\");\n@import url(\"base.css\");",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:legacy-property",
		Name:                "Deprecated legacy CSS property",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "compatibility"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects deprecated CSS properties with modern standard replacements.",
		Rationale:           "Legacy properties like clip or page-break-* are deprecated in modern W3C specifications.\n\nSource: https://www.w3.org/TR/css-masking-1/",
		Remediation:         "Replace legacy properties with standard replacements (e.g. clip-path, break-before).",
		CompliantExample:    "a {\n  clip-path: inset(0);\n}",
		NoncompliantExample: "a {\n  clip: rect(0, 0, 0, 0);\n}",
		RemediationEffort:   15,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:legacy-pseudo-element",
		Name:                "Legacy single-colon pseudo-element syntax",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "syntax"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects single-colon syntax used for standard pseudo-elements.",
		Rationale:           "Modern CSS requires double colons (::before, ::after) for pseudo-elements to distinguish them from pseudo-classes.\n\nSource: https://www.w3.org/TR/selectors-4/",
		Remediation:         "Use double colon syntax (::before, ::after, ::first-line, ::first-letter).",
		CompliantExample:    "a::before {\n  content: \"\";\n}",
		NoncompliantExample: "a:before {\n  content: \"\";\n}",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
	{
		Key:                 "css:redundant-value-list",
		Name:                "Redundant shorthand value list",
		Language:            "CSS",
		Type:                rule.TypeCodeSmell,
		Qualities:           []rule.Quality{rule.QualityMaintainability},
		DefaultSeverity:     shared.SeverityLow,
		Tags:                []string{"css", "maintainability", "style"},
		CWE:                 []string{},
		OWASP:               []string{},
		Description:         "Detects shorthand property value lists with redundant repetitive values.",
		Rationale:           "Shorthand value lists like 'margin: 1rem 1rem' can be simplified to 'margin: 1rem'.\n\nSource: https://www.w3.org/TR/css-box-3/",
		Remediation:         "Simplify repetitive shorthand values.",
		CompliantExample:    "a {\n  margin: 1rem;\n}",
		NoncompliantExample: "a {\n  margin: 1rem 1rem;\n}",
		RemediationEffort:   5,
		Detection:           rule.DetectionAST,
	},
}
