package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func baseSecretRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "aws-access-key-id",
			Name:                "AWS access key ID",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "aws"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded AWS access key IDs.",
			Rationale:           "Hardcoded AWS credentials can be extracted from source code and used by an attacker to impersonate the associated IAM principal, potentially leading to a complete cloud environment compromise.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the hardcoded key. Use IAM roles, environment variables, or a secure secrets manager to provide AWS credentials at runtime.",
			CompliantExample:    "sess, err := session.NewSession()",
			NoncompliantExample: "awsAccessKeyId := \"AKIAIOSFODNN7EXAMPLE\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "github-token",
			Name:                "GitHub token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "github"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded GitHub personal access tokens or OAuth tokens.",
			Rationale:           "Leaked GitHub tokens grant an attacker access to repositories, packages, and potentially administrative controls over the organization, leading to source code theft or supply chain attacks.\n\nSource: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository",
			Remediation:         "Revoke the leaked token immediately and remove it from the code. Use GitHub Apps or environment-injected secrets instead.",
			CompliantExample:    "token := os.Getenv(\"GITHUB_TOKEN\")",
			NoncompliantExample: "token := \"ghp_16C7e42k292cMGXQ7z18GgXv1BwG4V1EXAMPLE\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "gitlab-pat",
			Name:                "GitLab personal access token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "gitlab"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded GitLab personal access tokens.",
			Rationale:           "Leaked GitLab tokens can be used to bypass authentication and gain unauthorized access to repositories, CI/CD pipelines, and infrastructure.\n\nSource: https://docs.gitlab.com/ee/security/token_overview.html",
			Remediation:         "Revoke the token and remove it from the source tree. Supply credentials using CI/CD variables or external secret stores.",
			CompliantExample:    "token := os.Getenv(\"GITLAB_TOKEN\")",
			NoncompliantExample: "pat := \"glpat-EXAMPLETOKEN1234567890\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "slack-token",
			Name:                "Slack token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "slack"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded Slack API tokens.",
			Rationale:           "Leaked Slack tokens can expose internal communications, private channels, and allow attackers to masquerade as employees or bots to launch social engineering attacks.\n\nSource: https://api.slack.com/authentication/best-practices",
			Remediation:         "Revoke the token in the Slack app console and remove it from the code. Inject the token at runtime using an environment variable.",
			CompliantExample:    "api := slack.New(os.Getenv(\"SLACK_BOT_TOKEN\"))",
			NoncompliantExample: "api := slack.New(\"xoxb-EXAMPLE-TOKEN-DO-NOT-USE-123\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "google-api-key",
			Name:                "Google API key",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"credentials", "google"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded Google Cloud or Maps API keys.",
			Rationale:           "Leaked Google API keys can be abused by third parties to consume quota, resulting in significant financial charges or denial of service.\n\nSource: https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key",
			Remediation:         "Restrict the key's usage in the Google Cloud Console (e.g., by referring URL or IP) and move the raw key to a secure configuration store.",
			CompliantExample:    "apiKey := config.GoogleAPIKey",
			NoncompliantExample: "apiKey := \"<REDACTED_GOOGLE_API_KEY>\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "private-key",
			Name:                "Private key block",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"credentials", "cryptography"},
			CWE:                 []string{"CWE-321"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded cryptographic private keys (e.g., RSA, EC, DSA, OpenSSH).",
			Rationale:           "Embedding private keys in source code compromises the fundamental security of any cryptographic protocol relying on them, allowing attackers to decrypt data, forge signatures, or authenticate as the key owner.\n\nSource: https://cwe.mitre.org/data/definitions/321.html",
			Remediation:         "Generate a new key pair. Remove the compromised private key from the source tree and load the new key securely from a keystore or HSM at runtime.",
			CompliantExample:    "keyBytes, err := ioutil.ReadFile(\"/etc/secrets/tls.key\")",
			NoncompliantExample: "var key = `-----BEGIN PRIVATE KEY-----\nMIIEvAIB... (key data) ...\n-----END PRIVATE KEY-----`",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "jwt",
			Name:                "JSON Web Token",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"credentials", "jwt"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects hardcoded JSON Web Tokens (JWTs).",
			Rationale:           "Hardcoded JWTs embedded in code or configuration can be extracted to impersonate users or bypass authorization. Even if expired, they can reveal sensitive claims about the application's internal structure.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html",
			Remediation:         "Remove the JWT. Design the application to obtain tokens dynamically through a secure authentication flow.",
			CompliantExample:    "req.Header.Set(\"Authorization\", \"Bearer \"+session.Token)",
			NoncompliantExample: "const testToken = \"eyJhbGciOiJIUzI1NiIsInR5cCI.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZS.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "generic-secret",
			Name:                "Hardcoded secret",
			Language:            "Secrets",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"credentials"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "Detects high-entropy strings assigned to variables that appear to hold secrets, passwords, or API keys.",
			Rationale:           "Storing generic secrets in plaintext exposes them to anyone with read access to the repository, leading to unauthorized access to downstream systems.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the plaintext secret. Store it in a secure vault or inject it via environment variables.",
			CompliantExample:    "dbPassword := os.Getenv(\"DB_PASSWORD\")",
			NoncompliantExample: "dbPassword := \"V3ryC0mpl3xP@ssw0rd!9876\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		secretRule("aws-secret-access-key", "AWS secret access key", shared.SeverityHigh, "CWE-798", "aws", "Detects a hardcoded AWS secret access key assigned in source.",
			"An AWS secret access key paired with an access key ID grants full programmatic access to the associated IAM principal, so leaking one can hand an attacker the cloud account.", "https://cwe.mitre.org/data/definitions/798.html",
			"sess := session.Must(session.NewSession())", "awsSecretAccessKey := \"<REDACTED_AWS_SECRET_ACCESS_KEY>\""),
		secretRule("gcp-service-account-key", "GCP service account key", shared.SeverityHigh, "CWE-798", "gcp", "Detects a hardcoded GCP service-account JSON key.",
			"A service-account key JSON authenticates as the service account, so committing one lets an attacker impersonate it and reach every resource it can access.", "https://cloud.google.com/iam/docs/best-practices-for-managing-service-account-keys",
			"client, _ := storage.NewClient(ctx) // ADC", "// key.json\n{ \"type\": \"service_account\", \"private_key\": \"<REDACTED>\" }"),
		secretRule("azure-storage-key", "Azure storage account key", shared.SeverityHigh, "CWE-798", "azure", "Detects a hardcoded Azure storage account key in a connection string.",
			"An Azure storage account key grants full read/write control over the account's blobs, files, queues, and tables.", "https://learn.microsoft.com/azure/storage/common/storage-account-keys-manage",
			"conn := os.Getenv(\"AZURE_STORAGE_CONNECTION_STRING\")", "conn := \"<REDACTED_AZURE_CONNECTION_STRING>\""),
		secretRule("github-fine-grained-pat", "GitHub fine-grained token", shared.SeverityHigh, "CWE-798", "github", "Detects a hardcoded GitHub fine-grained personal access token.",
			"A fine-grained PAT grants scoped access to repositories and can be used to read code or push malicious changes if leaked.", "https://docs.github.com/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens",
			"token := os.Getenv(\"GITHUB_TOKEN\")", "token := \"<REDACTED_GITHUB_FINE_GRAINED_PAT>\""),
		secretRule("npm-token", "npm access token", shared.SeverityHigh, "CWE-798", "npm", "Detects a hardcoded npm access token.",
			"An npm token can publish packages to the registry, enabling a supply-chain attack if it is leaked.", "https://docs.npmjs.com/about-access-tokens",
			"//registry.npmjs.org/:_authToken=${NPM_TOKEN}", "//registry.npmjs.org/:_authToken=<REDACTED_NPM_TOKEN>"),
		secretRule("pypi-token", "PyPI upload token", shared.SeverityHigh, "CWE-798", "pypi", "Detects a hardcoded PyPI upload token.",
			"A PyPI token can publish packages, enabling a supply-chain attack against everyone who installs the project.", "https://pypi.org/help/#apitoken",
			"password = ${PYPI_TOKEN}", "password = <REDACTED_PYPI_TOKEN>"),
		secretRule("rubygems-token", "RubyGems API key", shared.SeverityHigh, "CWE-798", "rubygems", "Detects a hardcoded RubyGems API key.",
			"A RubyGems API key can push gems to the registry, enabling a supply-chain attack.", "https://guides.rubygems.org/api-key-scopes/",
			"gem push --key ci", "rubygems_api_key = \"<REDACTED_RUBYGEMS_KEY>\""),
		secretRule("stripe-secret-key", "Stripe secret key", shared.SeverityHigh, "CWE-798", "stripe", "Detects a hardcoded Stripe live secret key.",
			"A Stripe live secret key can move real money: create charges, issue refunds, and read customer/payment data.", "https://stripe.com/docs/keys",
			"stripe.Key = os.Getenv(\"STRIPE_SECRET_KEY\")", "stripe.Key = \"<REDACTED_STRIPE_SECRET_KEY>\""),
		secretRule("twilio-api-key", "Twilio API key SID", shared.SeverityHigh, "CWE-798", "twilio", "Detects a hardcoded Twilio API key SID.",
			"A Twilio API key can send messages and place calls on the account, driving cost and enabling phishing.", "https://www.twilio.com/docs/glossary/what-is-an-api-key",
			"sid := os.Getenv(\"TWILIO_API_KEY\")", "sid := \"<REDACTED_TWILIO_API_KEY_SID>\""),
		secretRule("sendgrid-api-key", "SendGrid API key", shared.SeverityHigh, "CWE-798", "sendgrid", "Detects a hardcoded SendGrid API key.",
			"A SendGrid key can send email as the account, enabling spam and phishing from a trusted domain.", "https://docs.sendgrid.com/ui/account-and-settings/api-keys",
			"key := os.Getenv(\"SENDGRID_API_KEY\")", "key := \"<REDACTED_SENDGRID_API_KEY>\""),
		secretRule("slack-webhook-url", "Slack webhook URL", shared.SeverityMedium, "CWE-798", "slack", "Detects a hardcoded Slack incoming-webhook URL.",
			"A Slack webhook URL lets anyone who has it post messages into the channel, enabling spam or convincing phishing.", "https://api.slack.com/messaging/webhooks",
			"url := os.Getenv(\"SLACK_WEBHOOK_URL\")", "url := \"<REDACTED_SLACK_WEBHOOK_URL>\""),
		secretRule("mailgun-api-key", "Mailgun API key", shared.SeverityHigh, "CWE-798", "mailgun", "Detects a hardcoded Mailgun API key.",
			"A Mailgun key can send email as the account and read logs, enabling spam and data disclosure.", "https://documentation.mailgun.com/en/latest/api-intro.html#authentication",
			"key := os.Getenv(\"MAILGUN_API_KEY\")", "key := \"<REDACTED_MAILGUN_API_KEY>\""),
		secretRule("mailchimp-api-key", "Mailchimp API key", shared.SeverityHigh, "CWE-798", "mailchimp", "Detects a hardcoded Mailchimp API key.",
			"A Mailchimp key can read subscriber lists (PII) and send campaigns from the account.", "https://mailchimp.com/developer/marketing/guides/quick-start/",
			"key := os.Getenv(\"MAILCHIMP_API_KEY\")", "key := \"<REDACTED_MAILCHIMP_API_KEY>\""),
		secretRule("openai-api-key", "OpenAI API key", shared.SeverityHigh, "CWE-798", "openai", "Detects a hardcoded OpenAI API key.",
			"An OpenAI key bills the account per request, so a leaked key can run up large charges.", "https://platform.openai.com/docs/api-reference/authentication",
			"client := openai.NewClient(os.Getenv(\"OPENAI_API_KEY\"))", "client := openai.NewClient(\"<REDACTED_OPENAI_API_KEY>\")"),
		secretRule("anthropic-api-key", "Anthropic API key", shared.SeverityHigh, "CWE-798", "anthropic", "Detects a hardcoded Anthropic API key.",
			"An Anthropic key bills the account per request, so a leaked key can run up large charges.", "https://docs.anthropic.com/en/api/getting-started",
			"key := os.Getenv(\"ANTHROPIC_API_KEY\")", "key := \"<REDACTED_ANTHROPIC_API_KEY>\""),
		secretRule("digitalocean-token", "DigitalOcean personal access token", shared.SeverityHigh, "CWE-798", "digitalocean", "Detects a hardcoded DigitalOcean personal access token.",
			"A DigitalOcean token can create and destroy droplets and other infrastructure, and read account data.", "https://docs.digitalocean.com/reference/api/create-personal-access-token/",
			"token := os.Getenv(\"DIGITALOCEAN_TOKEN\")", "token := \"<REDACTED_DIGITALOCEAN_TOKEN>\""),
		secretRule("shopify-token", "Shopify access token", shared.SeverityHigh, "CWE-798", "shopify", "Detects a hardcoded Shopify access token.",
			"A Shopify token can read orders and customer PII and modify a store, depending on scope.", "https://shopify.dev/docs/apps/auth/oauth/access-token-types",
			"token := os.Getenv(\"SHOPIFY_TOKEN\")", "token := \"<REDACTED_SHOPIFY_ACCESS_TOKEN>\""),
		secretRule("square-token", "Square access token", shared.SeverityHigh, "CWE-798", "square", "Detects a hardcoded Square access token.",
			"A Square access token can process payments and read customer and transaction data.", "https://developer.squareup.com/docs/build-basics/access-tokens",
			"token := os.Getenv(\"SQUARE_ACCESS_TOKEN\")", "token := \"<REDACTED_SQUARE_ACCESS_TOKEN>\""),
		secretRule("telegram-bot-token", "Telegram bot token", shared.SeverityMedium, "CWE-798", "telegram", "Detects a hardcoded Telegram bot token.",
			"A Telegram bot token lets anyone control the bot: read messages it receives and post as it.", "https://core.telegram.org/bots/api#authorizing-your-bot",
			"token := os.Getenv(\"TELEGRAM_BOT_TOKEN\")", "token := \"<REDACTED_TELEGRAM_BOT_TOKEN>\""),
		secretRule("new-relic-key", "New Relic API key", shared.SeverityHigh, "CWE-798", "newrelic", "Detects a hardcoded New Relic API key.",
			"A New Relic key can read telemetry and account configuration and, for some key types, modify alerting.", "https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/",
			"key := os.Getenv(\"NEW_RELIC_API_KEY\")", "key := \"<REDACTED_NEW_RELIC_API_KEY>\""),
		secretRule("dynatrace-token", "Dynatrace token", shared.SeverityHigh, "CWE-798", "dynatrace", "Detects a hardcoded Dynatrace API token.",
			"A Dynatrace token can read monitoring data and, depending on scope, reconfigure the environment.", "https://docs.dynatrace.com/docs/manage/access-control/access-tokens",
			"token := os.Getenv(\"DYNATRACE_TOKEN\")", "token := \"<REDACTED_DYNATRACE_TOKEN>\""),
		secretRule("grafana-token", "Grafana service account token", shared.SeverityHigh, "CWE-798", "grafana", "Detects a hardcoded Grafana service-account token.",
			"A Grafana token can read dashboards and data sources and, depending on role, modify them.", "https://grafana.com/docs/grafana/latest/administration/service-accounts/",
			"token := os.Getenv(\"GRAFANA_TOKEN\")", "token := \"<REDACTED_GRAFANA_TOKEN>\""),
		secretRule("planetscale-token", "PlanetScale token", shared.SeverityHigh, "CWE-798", "planetscale", "Detects a hardcoded PlanetScale password or token.",
			"A PlanetScale password/token grants access to the database branch, exposing application data.", "https://planetscale.com/docs/concepts/connection-strings",
			"pw := os.Getenv(\"PLANETSCALE_PASSWORD\")", "pw := \"<REDACTED_PLANETSCALE_TOKEN>\""),
		secretRule("doppler-token", "Doppler token", shared.SeverityHigh, "CWE-798", "doppler", "Detects a hardcoded Doppler token.",
			"A Doppler token can read a project's secrets, so leaking it can cascade into every downstream credential.", "https://docs.doppler.com/docs/service-tokens",
			"token := os.Getenv(\"DOPPLER_TOKEN\")", "token := \"<REDACTED_DOPPLER_TOKEN>\""),
		secretRule("postman-api-key", "Postman API key", shared.SeverityHigh, "CWE-798", "postman", "Detects a hardcoded Postman API key.",
			"A Postman API key can read collections and environments, which often embed further credentials.", "https://learning.postman.com/docs/developer/postman-api/authentication/",
			"key := os.Getenv(\"POSTMAN_API_KEY\")", "key := \"<REDACTED_POSTMAN_API_KEY>\""),
		secretRule("huggingface-token", "Hugging Face token", shared.SeverityHigh, "CWE-798", "huggingface", "Detects a hardcoded Hugging Face access token.",
			"A Hugging Face token can read private models/datasets and, with write scope, push to them.", "https://huggingface.co/docs/hub/security-tokens",
			"token := os.Getenv(\"HF_TOKEN\")", "token := \"<REDACTED_HUGGINGFACE_TOKEN>\""),
		secretRule("sentry-dsn", "Sentry DSN with secret", shared.SeverityMedium, "CWE-798", "sentry", "Detects a hardcoded Sentry DSN that embeds a secret key.",
			"A DSN embedding a secret key lets an attacker submit or read events for the project.", "https://docs.sentry.io/product/sentry-basics/dsn-explainer/",
			"dsn := os.Getenv(\"SENTRY_DSN\")", "dsn := \"<REDACTED_SENTRY_DSN>\""),
		secretRule("vault-token", "HashiCorp Vault token", shared.SeverityHigh, "CWE-798", "vault", "Detects a hardcoded HashiCorp Vault token.",
			"A Vault token can read secrets the token is entitled to, so leaking it can cascade into many credentials.", "https://developer.hashicorp.com/vault/docs/concepts/tokens",
			"token := os.Getenv(\"VAULT_TOKEN\")", "token := \"<REDACTED_VAULT_TOKEN>\""),
		secretRule("terraform-cloud-token", "Terraform Cloud API token", shared.SeverityHigh, "CWE-798", "terraform", "Detects a hardcoded Terraform Cloud API token.",
			"A Terraform Cloud token can read state (which frequently contains secrets) and trigger runs against real infrastructure.", "https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/api-tokens",
			"token := os.Getenv(\"TFE_TOKEN\")", "token := \"<REDACTED_TF_CLOUD_TOKEN>\""),
		secretRule("datadog-api-key", "Datadog API key", shared.SeverityMedium, "CWE-798", "datadog", "Detects a hardcoded Datadog API key assigned in source.",
			"A Datadog API key can submit and, with an app key, read telemetry and account configuration.", "https://docs.datadoghq.com/account_management/api-app-keys/",
			"key := os.Getenv(\"DATADOG_API_KEY\")", "datadog_api_key = \"<REDACTED_DATADOG_API_KEY>\""),
		secretRule("db-connection-string", "Database connection string with credentials", shared.SeverityHigh, "CWE-798", "database", "Detects a database connection URI with an embedded username and password.",
			"A connection string with inline credentials exposes the database account to anyone who can read the source.", "https://cwe.mitre.org/data/definitions/798.html",
			"dsn := os.Getenv(\"DATABASE_URL\")", "dsn := \"<REDACTED_DATABASE_URL>\""),
		secretRule("age-secret-key", "age secret key", shared.SeverityHigh, "CWE-321", "age", "Detects a hardcoded age encryption secret key.",
			"An age secret key decrypts everything encrypted to its public key, so committing one voids the confidentiality of that data.", "https://github.com/FiloSottile/age",
			"// key from AGE_SECRET_KEY env", "key := \"<REDACTED_AGE_SECRET_KEY>\""),
		secretRule("databricks-token", "Databricks personal access token", shared.SeverityHigh, "CWE-798", "databricks", "Detects a hardcoded Databricks personal access token.",
			"A Databricks token can run jobs and read data in the workspace, exposing analytical data and compute.", "https://docs.databricks.com/dev-tools/auth/pat.html",
			"token := os.Getenv(\"DATABRICKS_TOKEN\")", "token := \"<REDACTED_DATABRICKS_TOKEN>\""),
		secretRule("linear-api-key", "Linear API key", shared.SeverityHigh, "CWE-798", "linear", "Detects a hardcoded Linear API key.",
			"A Linear API key can read and modify issues and project data for the workspace.", "https://developers.linear.app/docs/graphql/working-with-the-graphql-api#personal-api-keys",
			"key := os.Getenv(\"LINEAR_API_KEY\")", "key := \"<REDACTED_LINEAR_API_KEY>\""),
		secretRule("jfrog-token", "JFrog Artifactory token", shared.SeverityHigh, "CWE-798", "jfrog", "Detects a hardcoded JFrog Artifactory access token.",
			"A JFrog token can read and publish artifacts, enabling a supply-chain attack on everything that pulls from the registry.", "https://jfrog.com/help/r/jfrog-platform-administration-documentation/access-tokens",
			"token := os.Getenv(\"ARTIFACTORY_TOKEN\")", "token := \"<REDACTED_JFROG_TOKEN>\""),
		secretRule("dockerhub-pat", "Docker Hub personal access token", shared.SeverityHigh, "CWE-798", "docker", "Detects a hardcoded Docker Hub personal access token.",
			"A Docker Hub PAT can pull and push images to the account's repositories, enabling a supply-chain attack on anything that pulls them.", "https://docs.docker.com/security/for-developers/access-tokens/",
			"token := os.Getenv(\"DOCKERHUB_TOKEN\")", "token := \"<REDACTED_DOCKERHUB_TOKEN>\""),
		secretRule("stripe-restricted-key", "Stripe restricted key", shared.SeverityHigh, "CWE-798", "stripe", "Detects a hardcoded Stripe restricted API key (rk_live/rk_test).",
			"A Stripe restricted key calls the payments API within its granted scopes, exposing customer and payment data.", "https://stripe.com/docs/keys#limit-access",
			"key := os.Getenv(\"STRIPE_RESTRICTED_KEY\")", "key := \"<REDACTED_STRIPE_KEY>\""),
		secretRule("gitlab-pipeline-trigger-token", "GitLab pipeline trigger token", shared.SeverityHigh, "CWE-798", "gitlab", "Detects a hardcoded GitLab pipeline trigger token.",
			"A pipeline trigger token starts pipelines in the project, which can run privileged CI jobs and read CI secrets.", "https://docs.gitlab.com/ee/ci/triggers/",
			"token := os.Getenv(\"CI_TRIGGER_TOKEN\")", "token := \"<REDACTED_GITLAB_TRIGGER_TOKEN>\""),
		secretRule("pulumi-access-token", "Pulumi access token", shared.SeverityHigh, "CWE-798", "pulumi", "Detects a hardcoded Pulumi access token.",
			"A Pulumi access token reads and updates infrastructure stacks and their state, which can hold cloud credentials.", "https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/",
			"token := os.Getenv(\"PULUMI_ACCESS_TOKEN\")", "token := \"<REDACTED_PULUMI_TOKEN>\""),
		secretRule("clojars-deploy-token", "Clojars deploy token", shared.SeverityHigh, "CWE-798", "clojars", "Detects a hardcoded Clojars deploy token.",
			"A Clojars deploy token can publish artifacts to the account's coordinates, enabling a supply-chain attack on Clojure consumers.", "https://github.com/clojars/clojars-web/wiki/Deploy-Tokens",
			"token := os.Getenv(\"CLOJARS_TOKEN\")", "token := \"<REDACTED_CLOJARS_TOKEN>\""),
		secretRule("sentry-auth-token", "Sentry auth token", shared.SeverityHigh, "CWE-798", "sentry", "Detects a hardcoded Sentry auth token.",
			"A Sentry auth token can read and modify projects, issues, and source maps for the organization.", "https://docs.sentry.io/account/auth-tokens/",
			"token := os.Getenv(\"SENTRY_AUTH_TOKEN\")", "token := \"<REDACTED_SENTRY_TOKEN>\""),
		secretRule("readme-api-key", "ReadMe API key", shared.SeverityHigh, "CWE-798", "readme", "Detects a hardcoded ReadMe API key.",
			"A ReadMe API key can read and modify the documentation project.", "https://docs.readme.com/main/reference/intro-to-the-readme-api",
			"key := os.Getenv(\"README_API_KEY\")", "key := \"<REDACTED_README_KEY>\""),
		secretRule("figma-token", "Figma personal access token", shared.SeverityHigh, "CWE-798", "figma", "Detects a hardcoded Figma personal access token.",
			"A Figma PAT can read and modify the account's design files.", "https://www.figma.com/developers/api#access-tokens",
			"token := os.Getenv(\"FIGMA_TOKEN\")", "token := \"<REDACTED_FIGMA_TOKEN>\""),
		secretRule("atlassian-api-token", "Atlassian API token", shared.SeverityHigh, "CWE-798", "atlassian", "Detects a hardcoded Atlassian (Jira/Confluence) API token.",
			"An Atlassian API token authenticates as the user against Jira and Confluence Cloud, exposing issues, pages, and administration.", "https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/",
			"token := os.Getenv(\"ATLASSIAN_API_TOKEN\")", "token := \"<REDACTED_ATLASSIAN_TOKEN>\""),
		secretRule("openshift-token", "OpenShift ServiceAccount token", shared.SeverityHigh, "CWE-798", "openshift", "Detects a hardcoded OpenShift / Kubernetes ServiceAccount OAuth token.",
			"An OpenShift ServiceAccount token authenticates against the cluster API with the account's RBAC, potentially granting broad cluster access.", "https://docs.openshift.com/container-platform/latest/authentication/understanding-authentication.html",
			"token := os.Getenv(\"OC_TOKEN\")", "token := \"<REDACTED_OPENSHIFT_TOKEN>\""),
		secretRule("duffel-api-token", "Duffel API token", shared.SeverityHigh, "CWE-798", "duffel", "Detects a hardcoded Duffel API token.",
			"A Duffel API token can search, book, and pay for flights on the account, a direct financial exposure.", "https://duffel.com/docs/guides/getting-started-with-flights",
			"token := os.Getenv(\"DUFFEL_TOKEN\")", "token := \"<REDACTED_DUFFEL_TOKEN>\""),
		secretRule("frameio-token", "Frame.io developer token", shared.SeverityHigh, "CWE-798", "frameio", "Detects a hardcoded Frame.io developer token.",
			"A Frame.io developer token can read and modify the account's projects, assets, and comments.", "https://developer.frame.io/api/reference/",
			"token := os.Getenv(\"FRAMEIO_TOKEN\")", "token := \"<REDACTED_FRAMEIO_TOKEN>\""),
		secretRule("definednetworking-token", "Defined Networking nebula API key", shared.SeverityHigh, "CWE-798", "definednetworking", "Detects a hardcoded Defined Networking nebula API key.",
			"A Defined Networking API key can enroll, move, and revoke hosts on the account's overlay network.", "https://docs.defined.net/reference/",
			"token := os.Getenv(\"DN_API_KEY\")", "token := \"<REDACTED_DN_KEY>\""),
		secretRule("typeform-token", "Typeform personal access token", shared.SeverityHigh, "CWE-798", "typeform", "Detects a hardcoded Typeform personal access token.",
			"A Typeform personal access token can read the account's forms and their collected responses.", "https://www.typeform.com/developers/get-started/personal-access-token/",
			"token := os.Getenv(\"TYPEFORM_TOKEN\")", "token := \"<REDACTED_TYPEFORM_TOKEN>\""),
		secretRule("prefect-api-key", "Prefect Cloud API key", shared.SeverityHigh, "CWE-798", "prefect", "Detects a hardcoded Prefect Cloud API key.",
			"A Prefect Cloud API key can read and control the account's workspaces, flows, and deployments.", "https://docs.prefect.io/latest/guides/cloud/",
			"key := os.Getenv(\"PREFECT_API_KEY\")", "key := \"<REDACTED_PREFECT_KEY>\""),
		secretRule("contentful-token", "Contentful personal access token", shared.SeverityHigh, "CWE-798", "contentful", "Detects a hardcoded Contentful personal access token.",
			"A Contentful management token can read and modify the account's content spaces and entries.", "https://www.contentful.com/developers/docs/references/authentication/",
			"token := os.Getenv(\"CONTENTFUL_TOKEN\")", "token := \"<REDACTED_CONTENTFUL_TOKEN>\""),
		secretRule("shippo-token", "Shippo API token", shared.SeverityHigh, "CWE-798", "shippo", "Detects a hardcoded Shippo API token.",
			"A Shippo API token can purchase shipping labels and read the account's orders, a direct financial exposure.", "https://docs.goshippo.com/docs/guides_general/authentication/",
			"token := os.Getenv(\"SHIPPO_TOKEN\")", "token := \"<REDACTED_SHIPPO_TOKEN>\""),
		secretRule("onepassword-service-account", "1Password service account token", shared.SeverityCritical, "CWE-798", "onepassword", "Detects a hardcoded 1Password service account token.",
			"A 1Password service account token unlocks the vaults it is granted, exposing every credential they hold.", "https://developer.1password.com/docs/service-accounts/",
			"token := os.Getenv(\"OP_SERVICE_ACCOUNT_TOKEN\")", "token := \"<REDACTED_1PASSWORD_TOKEN>\""),
		secretRule("gitlab-runner-token", "GitLab runner registration token", shared.SeverityHigh, "CWE-798", "gitlab", "Detects a hardcoded GitLab runner registration token.",
			"A GitLab runner registration token can register a rogue runner that executes CI jobs and reads their secrets.", "https://docs.gitlab.com/runner/register/",
			"token := os.Getenv(\"GITLAB_RUNNER_TOKEN\")", "token := \"<REDACTED_RUNNER_TOKEN>\""),
		secretRule("easypost-token", "EasyPost API token", shared.SeverityHigh, "CWE-798", "easypost", "Detects a hardcoded EasyPost API token.",
			"An EasyPost API token can buy shipping labels and read the account's shipments, a direct financial exposure.", "https://docs.easypost.com/docs/authentication",
			"token := os.Getenv(\"EASYPOST_API_KEY\")", "token := \"<REDACTED_EASYPOST_TOKEN>\""),
		secretRule("slack-app-token", "Slack app-level token", shared.SeverityHigh, "CWE-798", "slack", "Detects a hardcoded Slack app-level token.",
			"A Slack app-level token can open Socket Mode connections and act as the app across its workspaces.", "https://api.slack.com/authentication/token-types",
			"token := os.Getenv(\"SLACK_APP_TOKEN\")", "token := \"<REDACTED_SLACK_APP_TOKEN>\""),
		secretRule("intra42-client-secret", "42 (Intra) client secret", shared.SeverityHigh, "CWE-798", "intra42", "Detects a hardcoded 42 (Intra) API client secret.",
			"A 42 API client secret can mint access tokens for the application, reading student and campus data.", "https://api.intra.42.fr/apidoc",
			"secret := os.Getenv(\"INTRA42_SECRET\")", "secret := \"<REDACTED_INTRA42_SECRET>\""),
		secretRule("yandex-api-key", "Yandex API key", shared.SeverityHigh, "CWE-798", "yandex", "Detects a hardcoded Yandex API key.",
			"A Yandex API key authorizes calls to Yandex Cloud and services on the account, a billing and data exposure.", "https://yandex.cloud/en/docs/iam/concepts/authorization/api-key",
			"key := os.Getenv(\"YANDEX_API_KEY\")", "key := \"<REDACTED_YANDEX_KEY>\""),
		secretRule("notion-token", "Notion integration token", shared.SeverityHigh, "CWE-798", "notion", "Detects a hardcoded Notion integration token.",
			"A Notion integration token can read and modify the pages and databases the integration is shared with.", "https://developers.notion.com/docs/authorization",
			"token := os.Getenv(\"NOTION_TOKEN\")", "token := \"<REDACTED_NOTION_TOKEN>\""),
		secretRule("flutterwave-secret-key", "Flutterwave secret key", shared.SeverityHigh, "CWE-798", "flutterwave", "Detects a hardcoded Flutterwave secret key.",
			"A Flutterwave secret key authorizes charges, refunds, and payouts on the merchant account, a direct financial exposure.", "https://developer.flutterwave.com/docs/api-keys",
			"key := os.Getenv(\"FLW_SECRET_KEY\")", "key := \"<REDACTED_FLUTTERWAVE_KEY>\""),
		secretRule("alibaba-access-key-id", "Alibaba Cloud AccessKey ID", shared.SeverityHigh, "CWE-798", "alibaba", "Detects a hardcoded Alibaba Cloud AccessKey ID.",
			"An Alibaba Cloud AccessKey, with its secret, authenticates API calls across the account's cloud resources.", "https://www.alibabacloud.com/help/en/ram/user-guide/create-an-accesskey-pair",
			"id := os.Getenv(\"ALIBABA_CLOUD_ACCESS_KEY_ID\")", "id := \"<REDACTED_ALIBABA_ACCESS_KEY>\""),
		secretRule("adafruit-io-key", "Adafruit IO key", shared.SeverityHigh, "CWE-798", "adafruit", "Detects a hardcoded Adafruit IO key.",
			"An Adafruit IO key reads and writes the account's feeds and dashboards, controlling connected devices.", "https://io.adafruit.com/api/docs/",
			"key := os.Getenv(\"ADAFRUIT_IO_KEY\")", "key := \"<REDACTED_ADAFRUIT_IO_KEY>\""),
		secretRule("sourcegraph-access-token", "Sourcegraph access token", shared.SeverityHigh, "CWE-798", "sourcegraph", "Detects a hardcoded Sourcegraph access token.",
			"A Sourcegraph access token reads the code and search results the token owner can see across connected repositories.", "https://sourcegraph.com/docs/cli/how-tos/creating_an_access_token",
			"token := os.Getenv(\"SRC_ACCESS_TOKEN\")", "token := \"<REDACTED_SOURCEGRAPH_TOKEN>\""),
		secretRule("replicate-api-token", "Replicate API token", shared.SeverityHigh, "CWE-798", "replicate", "Detects a hardcoded Replicate API token.",
			"A Replicate API token runs models and incurs compute billing on the account.", "https://replicate.com/docs/reference/http",
			"token := os.Getenv(\"REPLICATE_API_TOKEN\")", "token := \"<REDACTED_REPLICATE_TOKEN>\""),
		secretRule("airtable-pat", "Airtable personal access token", shared.SeverityHigh, "CWE-798", "airtable", "Detects a hardcoded Airtable personal access token.",
			"An Airtable personal access token reads and writes the bases and records its scopes cover.", "https://airtable.com/developers/web/guides/personal-access-tokens",
			"token := os.Getenv(\"AIRTABLE_TOKEN\")", "token := \"<REDACTED_AIRTABLE_PAT>\""),
		secretRule("sonarqube-token", "SonarQube token", shared.SeverityHigh, "CWE-798", "sonarqube", "Detects a hardcoded SonarQube token.",
			"A SonarQube token authenticates to the server's API, reading projects and analysis results and running scans.", "https://docs.sonarsource.com/sonarqube-server/user-guide/managing-tokens",
			"token := os.Getenv(\"SONAR_TOKEN\")", "token := \"<REDACTED_SONARQUBE_TOKEN>\""),
		secretRule("dropbox-token", "Dropbox access token", shared.SeverityHigh, "CWE-798", "dropbox", "Detects a hardcoded Dropbox access token.",
			"A Dropbox access token reads and writes the files in the account or app folder it is scoped to.", "https://developers.dropbox.com/oauth-guide",
			"token := os.Getenv(\"DROPBOX_TOKEN\")", "token := \"<REDACTED_DROPBOX_TOKEN>\""),
		secretRule("cloudinary-url", "Cloudinary URL credential", shared.SeverityHigh, "CWE-798", "cloudinary", "Detects a hardcoded Cloudinary URL that embeds the API key and secret.",
			"A Cloudinary URL embeds the API key and secret, which manage and delete the account's media assets.", "https://cloudinary.com/documentation/finding_your_credentials",
			"url := os.Getenv(\"CLOUDINARY_URL\")", "url := \"<REDACTED_CLOUDINARY_URL>\""),
		secretRule("discord-webhook-url", "Discord webhook URL", shared.SeverityMedium, "CWE-798", "discord", "Detects a hardcoded Discord webhook URL.",
			"A Discord webhook URL lets anyone post messages into the channel it targets, enabling spam or phishing in that server.", "https://discord.com/developers/docs/resources/webhook",
			"url := os.Getenv(\"DISCORD_WEBHOOK_URL\")", "url := \"<REDACTED_DISCORD_WEBHOOK>\""),
		{
			Key: "putty-private-key", Name: "PuTTY private key", Language: "Secrets", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity}, DefaultSeverity: shared.SeverityCritical, Tags: []string{"credentials", "cryptography"}, CWE: []string{"CWE-321"}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
			Description:         "Detects a hardcoded PuTTY-format private key (.ppk).",
			Rationale:           "A PuTTY private key authenticates to SSH servers, so committing one lets an attacker log in as the key owner.\n\nSource: https://cwe.mitre.org/data/definitions/321.html",
			Remediation:         "Remove the .ppk from the source tree, rotate the key pair, and load keys from an agent or keystore at runtime.",
			CompliantExample:    "// key loaded from ssh-agent",
			NoncompliantExample: "// committed id.ppk file (PuTTY private key)",
			RemediationEffort:   30,
		},
	}
}

// secretRule builds a Secrets catalog entry, which is always a Vulnerability with the Security quality
// and pattern detection; only the metadata and examples vary between detectors.
func secretRule(key, name string, sev shared.Severity, cwe, provider, desc, why, source, compliant, noncompliant string) rule.Rule {
	return rule.Rule{
		Key: rule.Key(key), Name: name, Language: "Secrets", Type: rule.TypeVulnerability, Qualities: []rule.Quality{rule.QualitySecurity},
		DefaultSeverity: sev, Tags: []string{"credentials", provider}, CWE: []string{cwe}, OWASP: []string{"A07:2021"}, Detection: rule.DetectionPattern,
		Description:         desc,
		Rationale:           why + "\n\nSource: " + source,
		Remediation:         "Remove the hardcoded credential, rotate it, and provide it at runtime via an environment variable or a secrets manager.",
		CompliantExample:    compliant,
		NoncompliantExample: noncompliant,
		RemediationEffort:   15,
	}
}
