package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
	"strings"
)

func xmlRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "xml:not-well-formed",
			Name:                "XML document is not well formed",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects XML files that cannot be parsed as a single well-formed document.",
			Rationale:           "XML processors are required to reject documents that violate well-formedness constraints, so malformed configuration can fail at load time or be ignored by downstream tooling.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Fix the XML structure so tags are properly nested, each document has one root element, and markup syntax is valid.",
			CompliantExample:    "<service><name>api</name></service>",
			NoncompliantExample: "<service name=api></service>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:duplicate-attribute",
			Name:                "Duplicate XML attribute",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "well-formedness", "attributes"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML start tag that repeats the same attribute name.",
			Rationale:           "XML well-formedness requires each attribute name to appear at most once on a single start tag; duplicates make the element invalid and can create ambiguous configuration values.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Keep a single value for the attribute and remove the duplicate, or split distinct meanings into differently named attributes.",
			CompliantExample:    "<service name=\"api\" role=\"worker\" />",
			NoncompliantExample: "<service name=\"api\" name=\"worker\" />",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-entity",
			Name:                "External general entity declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "injection", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects general external entity declarations in XML DTD markup.",
			Rationale:           "External general entities allow XML parsers to fetch local files or external resources, opening vectors for XML External Entity (XXE) data disclosure attacks.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "Disable DTD processing or external entity resolution in XML parser configuration, or replace external entity declarations with inline static values.",
			CompliantExample:    "<!DOCTYPE config [\n  <!ENTITY appName \"Synapse\">\n]>\n<config>&appName;</config>",
			NoncompliantExample: "<!DOCTYPE config [\n  <!ENTITY xxe SYSTEM \"file:///etc/passwd\">\n]>\n<config>&xxe;</config>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-dtd",
			Name:                "External DOCTYPE declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "dtd", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects DOCTYPE declarations that reference an external DTD subset via SYSTEM or PUBLIC identifiers.",
			Rationale:           "External DTD subsets enable remote DTD loading, which can lead to Server-Side Request Forgery (SSRF) or out-of-band XXE exploitation.\n\nSource: https://cwe.mitre.org/data/definitions/611.html",
			Remediation:         "Remove external DTD references or configure the XML parser to disallow external DTD loading completely.",
			CompliantExample:    "<!DOCTYPE root [\n  <!ELEMENT root (#PCDATA)>\n]>\n<root>content</root>",
			NoncompliantExample: "<!DOCTYPE root SYSTEM \"https://example.invalid/external.dtd\">\n<root>content</root>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-parameter-entity",
			Name:                "External parameter entity declaration",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xxe", "parameter-entity", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects external parameter entity declarations in XML DTD subsets.",
			Rationale:           "External parameter entities can be used to construct blind or out-of-band XXE exfiltration payloads during DTD evaluation.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "Disable parameter entity resolution and external DTD processing in your XML parser settings.",
			CompliantExample:    "<!DOCTYPE data [\n  <!ENTITY % local \"INCLUDE\">\n]>\n<data>test</data>",
			NoncompliantExample: "<!DOCTYPE data [\n  <!ENTITY % remote SYSTEM \"https://example.invalid/remote.dtd\">\n]>\n<data>test</data>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:xinclude",
			Name:                "XInclude element in XML document",
			Language:            "XML",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"xml", "xinclude", "injection", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects XInclude elements in XML documents.",
			Rationale:           "XInclude processing enables embedding external documents or local file content into XML documents at parse time, creating file inclusion risks.\n\nSource: https://www.w3.org/TR/xinclude/",
			Remediation:         "Disable XInclude processing in XML parser configuration if external document inclusion is not strictly required.",
			CompliantExample:    "<document xmlns=\"http://example.org/ns\">\n  <content>Hello World</content>\n</document>",
			NoncompliantExample: "<document xmlns:xi=\"http://www.w3.org/2001/XInclude\">\n  <xi:include href=\"file:///etc/passwd\" />\n</document>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:entity-expansion",
			Name:                "Dangerous XML entity expansion structure",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "dos", "entity-expansion", "security"},
			CWE:                 []string{"CWE-776"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects dangerous or highly nested internal entity expansion structures.",
			Rationale:           "Excessive entity reference multiplication (Billion Laughs attack) can cause exponential memory consumption and parser Denial of Service.\n\nSource: https://cwe.mitre.org/data/definitions/776.html",
			Remediation:         "Limit or disable internal entity expansion in XML parser options and set entity expansion depth limits.",
			CompliantExample:    "<!DOCTYPE msg [\n  <!ENTITY greeting \"Hello\">\n]>\n<msg>&greeting;</msg>",
			NoncompliantExample: "<!DOCTYPE msg [\n  <!ENTITY a \"lol\">\n  <!ENTITY b \"&a;&a;&a;&a;&a;&a;&a;&a;&a;&a;\">\n  <!ENTITY c \"&b;&b;&b;&b;&b;&b;&b;&b;&b;&b;\">\n  <!ENTITY d \"&c;&c;&c;&c;&c;&c;&c;&c;&c;&c;\">\n]>\n<msg>&d;</msg>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:doctype-present",
			Name:                "XML DOCTYPE declaration present",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "doctype", "security"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "Detects the presence of a DOCTYPE declaration in XML documents.",
			Rationale:           "DOCTYPE declarations enable DTD parsing, which must be reviewed to ensure external entities and DTD loading are hardened against XXE.\n\nSource: https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html",
			Remediation:         "If DTD features are unneeded, remove the DOCTYPE declaration or explicitly disable DTD processing in your parser configuration.",
			CompliantExample:    "<catalog>\n  <item id=\"1\">Book</item>\n</catalog>",
			NoncompliantExample: "<!DOCTYPE catalog [\n  <!ELEMENT catalog (item*)>\n]>\n<catalog/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:external-schema-location",
			Name:                "External XML schema location reference",
			Language:            "XML",
			Type:                rule.TypeSecurityHotspot,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "schema", "ssrf", "security"},
			CWE:                 []string{"CWE-611", "CWE-918"},
			OWASP:               []string{"A05:2021", "A10:2021"},
			Description:         "Detects external schema locations in xsi:schemaLocation or xsi:noNamespaceSchemaLocation attributes.",
			Rationale:           "Parsing XML with external schema locations can trigger automatic HTTP/FTP connections to remote servers, enabling SSRF or schema poisoning.\n\nSource: https://cwe.mitre.org/data/definitions/918.html",
			Remediation:         "Use local relative schema paths or pre-load XML schemas into an offline XML schema cache.",
			CompliantExample:    "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n        xsi:noNamespaceSchemaLocation=\"schemas/config.xsd\">\n</config>",
			NoncompliantExample: "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n        xsi:noNamespaceSchemaLocation=\"https://example.invalid/schemas/config.xsd\">\n</config>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:              "xml:hardcoded-secret",
			Name:             "Hardcoded secret in XML configuration",
			Language:         "XML",
			Type:             rule.TypeSecurityHotspot,
			Qualities:        []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:  shared.SeverityMedium,
			Tags:             []string{"xml", "secrets", "credentials", "security"},
			CWE:              []string{"CWE-798"},
			OWASP:            []string{"A07:2021"},
			Description:      "Detects literal passwords, private keys, or API tokens in XML attributes or element text.",
			Rationale:        "Hardcoded credentials in source control or configuration files expose sensitive access tokens to unauthorized readers.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:      "Store credentials in environment variables or a secret vault and reference them via runtime interpolation (e.g., ${DB_PASSWORD}).",
			CompliantExample: "<database>\n  <password>${DB_PASSWORD}</password>\n</database>",
			NoncompliantExample: "<database>\n  <password>literal-" +
				"credential-value</password>\n</database>",
			RemediationEffort: 15,
			Detection:         rule.DetectionParse,
		},
		{
			Key:                 "xml:mismatched-tag",
			Name:                "Mismatched XML end tag",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML end tag that does not match the currently open element.",
			Rationale:           "W3C XML well-formedness constraints require every start tag to have a strictly matching end tag. Mismatched tags prevent parsing and indicate structural corruption.\n\nSource: https://www.w3.org/TR/xml/#dt-etag",
			Remediation:         "Ensure the end tag exactly matches the name of the corresponding start tag, preserving case.",
			CompliantExample:    "<root><item></item></root>",
			NoncompliantExample: "<root><item></other></root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:unclosed-element",
			Name:                "Unclosed XML element",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML document that ends while one or more elements remain open.",
			Rationale:           "W3C XML well-formedness constraints require every opened element to be closed before the end of the document.\n\nSource: https://www.w3.org/TR/xml/#sec-logical-struct",
			Remediation:         "Add the missing end tag to close the element, or convert it to a self-closing element if it contains no child content.",
			CompliantExample:    "<root><item></item></root>",
			NoncompliantExample: "<root><item>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:multiple-root-elements",
			Name:                "Multiple XML root elements",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "structure"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects more than one top-level document element in an XML document.",
			Rationale:           "The W3C XML document production rule requires exactly one root element per document. Multiple roots violate well-formedness.\n\nSource: https://www.w3.org/TR/xml/#sec-well-formed",
			Remediation:         "Wrap multiple top-level elements inside a single enclosing root element.",
			CompliantExample:    "<wrapper><first/><second/></wrapper>",
			NoncompliantExample: "<first/>\n<second/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:undeclared-prefix",
			Name:                "Undeclared XML namespace prefix",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "namespaces", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an XML element or attribute using a namespace prefix that has not been declared.",
			Rationale:           "Namespaces in XML requires every prefix to be bound to a namespace URI via an xmlns:prefix declaration in the current or parent scope.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Add an xmlns:prefix declaration for the namespace on the element or one of its ancestors.",
			CompliantExample:    "<root xmlns:cfg=\"http://example.com/cfg\">\n  <cfg:item/>\n</root>",
			NoncompliantExample: "<root>\n  <cfg:item/>\n</root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:invalid-character-reference",
			Name:                "Invalid XML character reference",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects malformed or out-of-range character references in XML text or attributes.",
			Rationale:           "W3C XML character reference rules require well-formed hexadecimal or decimal values that map to valid Unicode characters. Surrogates, nulls, and incomplete references are invalid.\n\nSource: https://www.w3.org/TR/xml/#NT-CharRef",
			Remediation:         "Correct the character reference syntax, ensure it terminates with a semicolon, and points to a valid Unicode character scalar value.",
			CompliantExample:    "<root>&#x20;</root>",
			NoncompliantExample: "<root>&#xZZ;</root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:invalid-comment",
			Name:                "Invalid XML comment syntax",
			Language:            "XML",
			Type:                rule.TypeBug,
			Qualities:           []rule.Quality{rule.QualityReliability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "well-formedness", "syntax"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects comments that violate XML comment syntax constraints.",
			Rationale:           "W3C XML comment production forbids the string '--' within a comment body and requires that a comment does not end with '-'.\n\nSource: https://www.w3.org/TR/xml/#sec-comments",
			Remediation:         "Remove internal double-hyphens from the comment body and ensure it does not end with a hyphen before the closing delimiter.",
			CompliantExample:    "<!-- valid comment -->",
			NoncompliantExample: "<!-- invalid -- comment -->",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:schema-missing",
			Name:                "XML document has no schema association",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "schema", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects XML documents that do not specify a DOCTYPE or schema location.",
			Rationale:           "Without a schema association, tooling cannot validate the correctness or intent of the document's structure, reducing maintainability.\n\nSource: https://www.w3.org/TR/xmlschema-1/",
			Remediation:         "Add a schema location (e.g. xsi:schemaLocation or xsi:noNamespaceSchemaLocation) to the root element.",
			CompliantExample:    "<config xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"config.xsd\">\n  <service name=\"api\"/>\n</config>",
			NoncompliantExample: "<config>\n  <service name=\"api\"/>\n</config>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:duplicate-schema-namespace",
			Name:                "Schema location repeats a namespace",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "schema", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects when a namespace is mapped to multiple schema URIs in xsi:schemaLocation.",
			Rationale:           "Mapping a single namespace to multiple schema files creates ambiguity and reduces configuration clarity.\n\nSource: https://www.w3.org/TR/xmlschema-1/",
			Remediation:         "Consolidate schemas so each namespace resolves to a single authoritative location.",
			CompliantExample:    "<root xmlns=\"urn:a\" xmlns:b=\"urn:b\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:a a.xsd urn:b b.xsd\"/>",
			NoncompliantExample: "<root xmlns=\"urn:a\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:a a1.xsd urn:a a2.xsd\"/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:unused-schema-location",
			Name:                "Schema location targets an unused namespace",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "schema", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects schema locations for namespaces that are never used in the document.",
			Rationale:           "Stale schema mappings clutter the root element and can confuse developers.\n\nSource: https://www.w3.org/TR/xmlschema-1/",
			Remediation:         "Remove the unused schema namespace and its corresponding file location.",
			CompliantExample:    "<root xmlns=\"urn:used\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:used used.xsd\"/>",
			NoncompliantExample: "<root xmlns=\"urn:used\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:used used.xsd urn:stale stale.xsd\"/>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:unused-namespace-declaration",
			Name:                "Namespace declaration is never used",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "namespaces", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects a namespace declaration that is never referenced by elements or attributes in its scope.",
			Rationale:           "Unused namespaces bloat the document and obscure the actual dependencies of the XML structure.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Remove the unused namespace declaration (e.g. xmlns:prefix=\"...\").",
			CompliantExample:    "<root xmlns:used=\"urn:used\"><used:child/></root>",
			NoncompliantExample: "<root xmlns:unused=\"urn:unused\"><child/></root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:redundant-namespace-declaration",
			Name:                "Namespace declaration repeats an inherited binding",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "namespaces", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an inner element that declares the same prefix-to-URI binding already inherited from a parent.",
			Rationale:           "Repeating identical namespace bindings unnecessarily inflates document size and complicates maintenance.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Rely on namespace inheritance and remove the redundant declaration from the child element.",
			CompliantExample:    "<root xmlns:cfg=\"urn:config\"><group><cfg:item/></group></root>",
			NoncompliantExample: "<root xmlns:cfg=\"urn:config\"><group xmlns:cfg=\"urn:config\"><cfg:item/></group></root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:namespace-prefix-shadowing",
			Name:                "Namespace prefix is rebound in a nested scope",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "namespaces", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an inner element that re-binds a named prefix to a different namespace URI.",
			Rationale:           "Shadowing prefixes makes it significantly harder to trace which namespace an element belongs to when reading deeply nested XML.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Use a different prefix for the inner scope's namespace instead of shadowing the parent's prefix.",
			CompliantExample:    "<root xmlns:cfg=\"urn:v1\"><group xmlns:cfg2=\"urn:v2\"><cfg2:item/></group></root>",
			NoncompliantExample: "<root xmlns:cfg=\"urn:v1\"><group xmlns:cfg=\"urn:v2\"><cfg:item/></group></root>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:multiple-prefixes-same-namespace",
			Name:                "One namespace uses multiple prefixes",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "namespaces", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects when the same namespace URI is actively used through multiple different prefixes.",
			Rationale:           "Using multiple aliases for the same namespace creates inconsistency and forces developers to keep track of alias mappings.\n\nSource: https://www.w3.org/TR/xml-names/",
			Remediation:         "Consolidate the usages under a single prefix.",
			CompliantExample:    "<root xmlns:a=\"urn:shared\"><a:first/><a:second/></root>",
			NoncompliantExample: "<root xmlns:a=\"urn:shared\" xmlns:b=\"urn:shared\"><a:first/><b:second/></root>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:excessive-nesting-depth",
			Name:                "XML structure is excessively nested",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"xml", "complexity", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects XML structures that are nested deeper than 16 levels.",
			Rationale:           "Excessively deep hierarchy implies overly complex models and is notoriously difficult to process, style, or map to objects. The detection thresholds are Synapse policy thresholds and are not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:         "Flatten the XML hierarchy by using references (ID/IDREF) or restructuring the schema.",
			CompliantExample:    "<root><level1><level2><item/></level2></level1></root>",
			NoncompliantExample: "<root><n><n><n><n><n><n><n><n><n><n><n><n><n><n><n><n><n/></n></n></n></n></n></n></n></n></n></n></n></n></n></n></n></n></root>",
			RemediationEffort:   60,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:too-many-attributes",
			Name:                "XML element has too many attributes",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "complexity", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an element with more than 12 non-namespace attributes.",
			Rationale:           "Elements with a huge number of attributes often cram too much data into a single node instead of structuring it cleanly into child elements. The detection thresholds are Synapse policy thresholds and are not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:         "Group related attributes into nested child elements.",
			CompliantExample:    "<service id=\"1\" name=\"auth\" port=\"80\" />",
			NoncompliantExample: "<service a1=\"v\" a2=\"v\" a3=\"v\" a4=\"v\" a5=\"v\" a6=\"v\" a7=\"v\" a8=\"v\" a9=\"v\" a10=\"v\" a11=\"v\" a12=\"v\" a13=\"v\" />",
			RemediationEffort:   30,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:too-many-child-elements",
			Name:                "XML element contains too many heterogeneous children",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "complexity", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects an element that has too many direct child elements of different names (heterogeneous).",
			Rationale:           "A tag combining more than 25 children across more than 5 distinct namespaces or types is often a 'god object' that has lost structural coherence. The detection thresholds are Synapse policy thresholds and are not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:         "Group related child elements into logical sub-sections.",
			CompliantExample:    "<config><items><item/><item/><item/></items></config>",
			NoncompliantExample: "<root><a/><b/><c/><d/><e/><f/><g/><h/><i/><j/><k/><l/><m/><n/><o/><p/><q/><r/><s/><t/><u/><v/><w/><x/><y/><z/></root>",
			RemediationEffort:   60,
			Detection:           rule.DetectionParse,
		},
		{
			Key:              "xml:oversized-element",
			Name:             "XML element is excessively large",
			Language:         "XML",
			Type:             rule.TypeCodeSmell,
			Qualities:        []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:  shared.SeverityLow,
			Tags:             []string{"xml", "complexity", "maintainability"},
			CWE:              []string{},
			OWASP:            []string{},
			Description:      "Detects an element spanning more than 200 lines with high descendant complexity.",
			Rationale:        "Large structural blocks are difficult to navigate and maintain, similar to excessively long functions in code. The detection thresholds are Synapse policy thresholds and are not prescribed by ISO/IEC 25010.\n\nSource: https://www.iso.org/standard/78176.html",
			Remediation:      "Break down large elements into smaller, separate configuration units or files.",
			CompliantExample: "<config>\n  <service name=\"api\"/>\n</config>",
			NoncompliantExample: "<root>\n" + strings.Repeat("\n", 200) + `
  <a1/><b1/><c1/><d1/><e1/>
<a2/><b2/><c2/><d2/><e2/>
<a3/><b3/><c3/><d3/><e3/>
<a4/><b4/><c4/><d4/><e4/>
<a5/><b5/><c5/><d5/><e5/>
</root>`,
			RemediationEffort: 60,
			Detection:         rule.DetectionParse,
		},
		{
			Key:                 "xml:commented-out-markup",
			Name:                "XML comment contains disabled markup",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityLow,
			Tags:                []string{"xml", "comments", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects comments whose entire body appears to be well-formed, disabled XML elements.",
			Rationale:           "Dead, commented-out configuration is confusing and rots over time. Version control should be relied upon to retain history.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Remove the commented-out elements.",
			CompliantExample:    "<!-- Configure the <service> element before deployment. -->",
			NoncompliantExample: "<root>\n  <!--\n  <service name=\"legacy\">\n    <port>8080</port>\n  </service>\n  -->\n</root>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:redundant-cdata-section",
			Name:                "CDATA section contains no markup-sensitive characters",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "cdata", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects a CDATA block that contains no '<' or '&' characters.",
			Rationale:           "Using CDATA when standard text would suffice without escaping adds visual noise and offers no benefit.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Remove the CDATA wrapper and use plain text.",
			CompliantExample:    "<desc><![CDATA[ x < y && a > b ]]></desc>",
			NoncompliantExample: "<desc><![CDATA[ plain text without special characters ]]></desc>",
			RemediationEffort:   5,
			Detection:           rule.DetectionParse,
		},
		{
			Key:                 "xml:oversized-comment",
			Name:                "XML comment is excessively large",
			Language:            "XML",
			Type:                rule.TypeCodeSmell,
			Qualities:           []rule.Quality{rule.QualityMaintainability},
			DefaultSeverity:     shared.SeverityInfo,
			Tags:                []string{"xml", "comments", "maintainability"},
			CWE:                 []string{},
			OWASP:               []string{},
			Description:         "Detects a single comment block exceeding 1000 bytes or 20 lines.",
			Rationale:           "Huge comments often indicate misplaced documentation or out-of-date manifestos that obscure the actual configuration. The detection thresholds are Synapse policy thresholds and are not prescribed by W3C.\n\nSource: https://www.w3.org/TR/xml/",
			Remediation:         "Move extensive documentation to a README or dedicated documentation file.",
			CompliantExample:    "<!-- Standard brief note -->",
			NoncompliantExample: "<root>\n  <!--\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nToo many lines\n  -->\n</root>",
			RemediationEffort:   15,
			Detection:           rule.DetectionParse,
		},
	}
}
